<?php
$this->headLink()->appendStylesheet('/css/ui/jquery-ui-1.10.3.css');
$this->headScript()->appendFile('/assets/js/search_form.js');
?>
<script type="text/javascript">
    $(document).ready(function(){
        $('a#btnSearch1, a#btnSearch2' ).click(function() {
            $('form[name="searchForm"]').submit();
            return false;
        });
    });
</script>
<div class="title-row-search bg-dessin">
    <div class="container-text">
        <h1 class="white-txt">Recherche par dessin</h1>
    </div>
</div>
<main>
    <div class="inner">
        <div class="grid grid-dark">
            <div class="menu-search">
                <ul>
                    <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'standard'), false, true)?>"  class=" menu-icons icon-search">Recherche standard</a></li>
                    <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'metro'), false, true)?>" class="menu-icons icon-metro">Recherche<br>par  metro</a></li>
                    <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'draw'), false, true)?>" class="active menu-icons icon-dessin">Recherche<br> par dessin</a></li>
                    <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'map'), false, true)?>" class="menu-icons icon-carte">Recherche<br> par carte</a></li>
                </ul>
            </div>
            <form action="<?=$this->form->getAction()?>" name="searchForm" id="form-search-draw" method="POST">
            <div class="search-box">
                <div class="search-left">
                    <div class="search-budget">
                        <label class="name-title-white">Budget</label>
                        <?=$this->form->getElement('min_budget')?>
                        <?=$this->form->getElement('max_budget')?>
                    </div>
                    <div class="search-surface">
                        <label class="name-title-white">Surface</label>
                        <?=$this->form->getElement('min_size')?>
                        <?=$this->form->getElement('max_size')?>
                    </div>
                </div>
                <div class="search-right">
                    <?=$this->form->getElement('is_furnished')?>
                    <?=$this->form->getElement('number_of_rooms1')?>
                    <?=$this->form->getElement('drawn_polygon')?>
                </div>
            </div>
            </form>
        </div>

        <div class="grid grid-dark">
            <div class="title-advanced">
                <h2>Dessiner une zone</h2>
                <p>Cliquez sur la carte pour commencer le tracé.<br>
                    Ajoutez des points en cliquant.<br>
                    Double-clic pour finir le tracé et définir la zone.<br>
					<span class="blue">
						Lorsque vous êtes satisfait, il vous suffit de lancer la recherche.
					</span>
                </p>
            </div>
            <div class="box-carte">
                <?= $this->googleMap(48.857261, 2.346611, array('width' => 1001, 'height' => 651, 'margin' => 0), array('zoom' => 13, 'zoomControl' => 0, 'scaleControl' => 0, 'streetViewControl' => 0, 'panControl' => 0), "initSearchDraw(map)") ?>
                <div class="btn-plus-minus">
                    <a href="" class="btn btn-gray-lite btn-plus"></a>
                    <a href="" class="btn btn-gray-lite btn-minus"></a>
                </div>
                <div class="btn-carte-nav">
                    <a href="#" class="btn btn-blue" id="btnSearch1">Rechercher</a>
                    <a href="#" class="btn btn-dark clear-polygon">Effacer le dessin</a>
                </div>
            </div>
            <div class="box-btn-search">
                <a href="#" class="btn btn-gray clear-polygon">Effacer le dessin</a>
                <a href="" class="btn btn-red btn-sauv">Sauvegarder</a>
                <a href="#" class="btn btn-blue" id="btnSearch2">Rechercher</a>
            </div>
        </div>
        <div class="grid">
            <div class="grid-full example-regions">
                <h2 class="gray txt-line-metro">Choisir parmi nos sélections</h2>
                <p>Sélectionnez l’un des dessins que nous avons tracés pour vous.</p>
                <?php foreach ($this->exampleRegions as $index => $exampleRegion): ?>
                <div class="box-place">
                    <label><?= $exampleRegion['name']?></label>
                    <a href="#" class="btn btn-gray btn-carte<?= $index + 1 ?>" data-region-path="<?= $exampleRegion['path'] ?>"></a>
                </div>
                <?php endforeach ?>
            </div>
        </div>

        <?= $this->partial('_partials/search.phtml', $this->getVars()) ?>
    </div>
</main>
