<?= $this->contentHeader('Search', array(
            0=>array(
                'type'=>'link',
                'title'=>'Standard Search',
                'url'=>'search/standard',
                'class'=>'btnSearch',
            ),
            1=>array(
                'type'=>'link',
                'title'=>'Search by Metro',
                'url'=>'search/metro',
                'class'=>'btnSearch',
            ),
            2=>array(
                'type'=>'link',
                'title'=>'Search by Draw',
                'url'=>'search/draw',
                'class'=>'btnSearch',
            ),
            3=>array(
                'type'=>'link',
                'title'=>'Search by Map',
                'url'=>'search/map',
                'class'=>'btnSearch',
            )
        )) ?>
