<!--<?= $this->form ?>
<?= $this->googleMap(48.857261, 2.346611, array('width' => 800, 'height' => 600), array('zoom' => 8), "var regions = {$this->regionsJson};\ninitSearchMap(map, regions)") ?>
<div>
<? $curDistrictId = Null ?>
<h2>Paris</h2>
<? foreach ($this->allBlockRegions as $region): ?>
    <? if ($curDistrictId != $region->region_district_id): ?>
        <? $curDistrictId = $region->region_district_id ?>
        <h3><?= $region->RegionDistrict->name ?></h3>
    <? endif ?>
    <input type="checkbox" class="region region<?= $region->id ?>" name="region<?= $region->id ?>" value="1" <? if (in_array($region->id, $this->regionsSelectedIds)): ?>checked="checked"<? endif ?> /><label for="region<?= $region->id ?>"><?= $region->name ?></label>
<? endforeach ?>
</div>
-->

<div class="title-container title-bg-search-map">
	<div class="title-container-text inner">
		<h1 class="white-text">Recherche par carte</h1>
	</div>
</div>
<div class="inner">
	<div class="grid grid-dark">
		<div class="menu-search">
			<ul>
				<li><a href=""  class=" menu-icons icon-search">Recherche standard</a></li>
				<li><a href="" class="menu-icons icon-metro">Recherche<br>par  metro</a></li>
				<li><a href="" class=" menu-icons icon-dessin">Recherche<br> par dessin</a></li>
				<li><a href="" class="active menu-icons icon-carte">Recherche<br> par carte</a></li>
			</ul>
		</div>
		<div class="search-box">
			<div class="search-left">
				<div class="search-budget">
					<label class="name-title-white">Budget</label>
					<input type="text" placeholder="Budget min. (en €)"/>
					<input type="text" placeholder="Budget max. (en €)"/>
				</div>
				<div class="search-surface">
					<label class="name-title-white">Surface</label>
					<input type="text" placeholder="Surface min. (en m²)"/>
					<input type="text" placeholder="Surface max. (en m²)"/>
				</div>
			</div>
			<div class="search-right">
				<div class="box-universal">
					<label class="name-title-white">Mobilier</label>
					<form>
						<input type="reset" value="Tous" class="btn-tous"/>
						<input type='radio' id='Choice2' name='Choice'>
						<label for='Choice2' class="btn-input-gray-dark">Meublé</label>

						<input type='radio' id='Choice3' name='Choice'>
						<label for='Choice3' class="btn-input-gray-dark">Vide</label>
					</form>
				</div>
				<div class="box-universal">
					<label class="name-title-white">Nombre de chambres</label>
					<form>
						<input type="reset" value="Tous" class="btn-tous"/>
						<input type='checkbox' id='Choice11' name='Choice'>
						<label for='Choice11' class="btn-input-gray-dark btn-input-number">1</label>

						<input type='checkbox' id='Choice13' name='Choice'>
						<label for='Choice13' class="btn-input-gray-dark btn-input-number">2</label>

						<input type='checkbox' id='Choice14' name='Choice'>
						<label for='Choice14' class="btn-input-gray-dark btn-input-number">3</label>

						<input type='checkbox' id='Choice15' name='Choice'>
						<label for='Choice15' class="btn-input-gray-dark btn-input-number">4</label>

						<input type='checkbox' id='Choice16' name='Choice'>
						<label for='Choice16' class="btn-input-gray-dark btn-input-number">5 et +</label>
					</form>
				</div>
			</div>
		</div>
	</div>

	<div class="grid grid-dark">
		<div class="title-advanced">
			<h2>Sélectionner des quartiers</h2>
			<p>Cliquez sur un arrondissement pour accéder à une carte plus précise.<br>
				Sélectionnez autant de quartiers que vous le souhaitez.<br>
				<span class="blue">
					Lorsque vous êtes satisfait, il vous suffit de lancer la recherche.
				</span>
			</p>
		</div>
		<div class="box-carte carte-black">
			<img src="/./assets/images/search-carte-black.png">
			<div class="box-btn-return">
				<a href="#" class="btn btn-gray-lite">Retour à la carte générale</a>
			</div>
		</div>
		<div class="box-btn-search">
			<a href="" class="btn btn-gray btn-effacer">Effacer mes sélections</a>
			<a href="" class="btn btn-red btn-sauv">Sauvegarder</a>
			<a href="" class="btn btn-blue">Rechercher</a>
		</div>
	</div>
	<div class="grid grid-dark">
		<div class="title-advanced">
			<h2>Sélectionner à partir de la liste</h2>
			<p>Sélectionnez autant de quartiers que vous souhaitez.<br>
				<span class="blue">
					Lorsque vous êtes satisfait, il vous suffit de lancer la recherche.
				</span>
			</p>
		</div>
		<div class="box-search-advanced">
			<div class="box-universal">
				<label class="name-title-black">75 - Paris</label>
				<div class="box-all-input">
					<form>
						<div class="box-input">
							<input type="checkbox" id='Choice1' name='Choice' />
							<label for='Choice1' class="btn-input-grayer">
								1<sup>er</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice2' name='Choice'>
							<label for='Choice2' class="btn-input-gray-lite">Les Halles</label>

							<input type='checkbox' id='Choice3' name='Choice'>
							<label for='Choice3' class="btn-input-gray-lite">Palais Royal</label>

							<input type='checkbox' id='Choice4' name='Choice'>
							<label for='Choice4' class="btn-input-gray-lite">St Germain</label>

							<input type='checkbox' id='Choice5' name='Choice'>
							<label for='Choice5' class="btn-input-gray-lite">Vendôme</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice6' name='Choice' />
							<label for='Choice6' class="btn-input-grayer">
								2<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice7' name='Choice'>
							<label for='Choice7' class="btn-input-gray-lite">Provence</label>

							<input type='checkbox' id='Choice8' name='Choice'>
							<label for='Choice8' class="btn-input-gray-lite">Sentier</label>

							<input type='checkbox' id='Choice9' name='Choice'>
							<label for='Choice9' class="btn-input-gray-lite">Montorgueil</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice10' name='Choice' />
							<label for='Choice10' class="btn-input-grayer">
								3<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice11' name='Choice'>
							<label for='Choice11' class="btn-input-gray-lite">Arts et Métiers</label>

							<input type='checkbox' id='Choice12' name='Choice'>
							<label for='Choice12' class="btn-input-gray-lite">Archives</label>

							<input type='checkbox' id='Choice13' name='Choice'>
							<label for='Choice13' class="btn-input-gray-lite">Enfants Rouge</label>

							<input type='checkbox' id='Choice14' name='Choice'>
							<label for='Choice14' class="btn-input-gray-lite">Saint-Avoye</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice15' name='Choice' />
							<label for='Choice15' class="btn-input-grayer">
								4<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice16' name='Choice'>
							<label for='Choice16' class="btn-input-gray-lite">Provence</label>

							<input type='checkbox' id='Choice17' name='Choice'>
							<label for='Choice17' class="btn-input-gray-lite">Sentier</label>

							<input type='checkbox' id='Choice18' name='Choice'>
							<label for='Choice18' class="btn-input-gray-lite">Montorgueil</label>

							<input type='checkbox' id='Choice19' name='Choice'>
							<label for='Choice19' class="btn-input-gray-lite">Montorgueil</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice20' name='Choice' />
							<label for='Choice20' class="btn-input-grayer">
								5<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice21' name='Choice'>
							<label for='Choice21' class="btn-input-gray-lite">Arts et Métiers</label>

							<input type='checkbox' id='Choice22' name='Choice'>
							<label for='Choice22' class="btn-input-gray-lite">Archives</label>

							<input type='checkbox' id='Choice23' name='Choice'>
							<label for='Choice23' class="btn-input-gray-lite">Enfants Rouge</label>

							<input type='checkbox' id='Choice24' name='Choice'>
							<label for='Choice24' class="btn-input-gray-lite">Saint-Avoye</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice25' name='Choice' />
							<label for='Choice25' class="btn-input-grayer">
								6<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice26' name='Choice'>
							<label for='Choice26' class="btn-input-gray-lite">Provence</label>

							<input type='checkbox' id='Choice27' name='Choice'>
							<label for='Choice27' class="btn-input-gray-lite">Sentier</label>

							<input type='checkbox' id='Choice28' name='Choice'>
							<label for='Choice28' class="btn-input-gray-lite">Montorgueil</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice29' name='Choice' />
							<label for='Choice29' class="btn-input-grayer">
								7<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice30' name='Choice'>
							<label for='Choice30' class="btn-input-gray-lite">Arts et Métiers</label>

							<input type='checkbox' id='Choice31' name='Choice'>
							<label for='Choice31' class="btn-input-gray-lite">Archives</label>

							<input type='checkbox' id='Choice32' name='Choice'>
							<label for='Choice32' class="btn-input-gray-lite">Enfants Rouge</label>

							<input type='checkbox' id='Choice33' name='Choice'>
							<label for='Choice33' class="btn-input-gray-lite">Saint-Avoye</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice34' name='Choice' />
							<label for='Choice34' class="btn-input-grayer">
								8<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice35' name='Choice'>
							<label for='Choice35' class="btn-input-gray-lite">Provence</label>

							<input type='checkbox' id='Choice36' name='Choice'>
							<label for='Choice36' class="btn-input-gray-lite">Sentier</label>

							<input type='checkbox' id='Choice37' name='Choice'>
							<label for='Choice37' class="btn-input-gray-lite">Montorgueil</label>

							<input type='checkbox' id='Choice38' name='Choice'>
							<label for='Choice38' class="btn-input-gray-lite">Montorgueil</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice39' name='Choice' />
							<label for='Choice39' class="btn-input-grayer">
								9<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice40' name='Choice'>
							<label for='Choice40' class="btn-input-gray-lite">Arts et Métiers</label>

							<input type='checkbox' id='Choice41' name='Choice'>
							<label for='Choice41' class="btn-input-gray-lite">Archives</label>

							<input type='checkbox' id='Choice42' name='Choice'>
							<label for='Choice42' class="btn-input-gray-lite">Enfants Rouge</label>

							<input type='checkbox' id='Choice43' name='Choice'>
							<label for='Choice43' class="btn-input-gray-lite">Saint-Avoye</label>

							<input type='checkbox' id='Choice44' name='Choice'>
							<label for='Choice44' class="btn-input-gray-lite">Enfants Rouge</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice45' name='Choice' />
							<label for='Choice45' class="btn-input-grayer">
								10<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice46' name='Choice'>
							<label for='Choice46' class="btn-input-gray-lite">Arts et Métiers</label>

							<input type='checkbox' id='Choice47' name='Choice'>
							<label for='Choice47' class="btn-input-gray-lite">Archives</label>

							<input type='checkbox' id='Choice48' name='Choice'>
							<label for='Choice48' class="btn-input-gray-lite">Enfants Rouge</label>

							<input type='checkbox' id='Choice49' name='Choice'>
							<label for='Choice49' class="btn-input-gray-lite">Saint-Avoye</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice50' name='Choice' />
							<label for='Choice50' class="btn-input-grayer">
								11<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice51' name='Choice'>
							<label for='Choice51' class="btn-input-gray-lite">Provence</label>

							<input type='checkbox' id='Choice52' name='Choice'>
							<label for='Choice52' class="btn-input-gray-lite">Sentier</label>

							<input type='checkbox' id='Choice53' name='Choice'>
							<label for='Choice53' class="btn-input-gray-lite">Montorgueil</label>

							<input type='checkbox' id='Choice54' name='Choice'>
							<label for='Choice54' class="btn-input-gray-lite">Montorgueil</label>

							<input type='checkbox' id='Choice55' name='Choice'>
							<label for='Choice55' class="btn-input-gray-lite">Montorgueil</label>

							<input type='checkbox' id='Choice56' name='Choice'>
							<label for='Choice56' class="btn-input-gray-lite">Sentier</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice57' name='Choice' />
							<label for='Choice57' class="btn-input-grayer">
								12<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice58' name='Choice'>
							<label for='Choice58' class="btn-input-gray-lite">Arts et Métiers</label>

							<input type='checkbox' id='Choice59' name='Choice'>
							<label for='Choice59' class="btn-input-gray-lite">Archives</label>

							<input type='checkbox' id='Choice60' name='Choice'>
							<label for='Choice60' class="btn-input-gray-lite">Enfants Rouge</label>

							<input type='checkbox' id='Choice61' name='Choice'>
							<label for='Choice61' class="btn-input-gray-lite">Saint-Avoye</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice62' name='Choice' />
							<label for='Choice62' class="btn-input-grayer">
								13<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice63' name='Choice'>
							<label for='Choice63' class="btn-input-gray-lite">Provence</label>

							<input type='checkbox' id='Choice64' name='Choice'>
							<label for='Choice64' class="btn-input-gray-lite">Sentier</label>

							<input type='checkbox' id='Choice65' name='Choice'>
							<label for='Choice65' class="btn-input-gray-lite">Montorgueil</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice66' name='Choice' />
							<label for='Choice66' class="btn-input-grayer">
								14<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice67' name='Choice'>
							<label for='Choice67' class="btn-input-gray-lite">Arts et Métiers</label>

							<input type='checkbox' id='Choice68' name='Choice'>
							<label for='Choice68' class="btn-input-gray-lite">Archives</label>

							<input type='checkbox' id='Choice69' name='Choice'>
							<label for='Choice69' class="btn-input-gray-lite">Enfants Rouge</label>

							<input type='checkbox' id='Choice70' name='Choice'>
							<label for='Choice70' class="btn-input-gray-lite">Saint-Avoye</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice71' name='Choice' />
							<label for='Choice71' class="btn-input-grayer">
								15<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice72' name='Choice'>
							<label for='Choice72' class="btn-input-gray-lite">Provence</label>

							<input type='checkbox' id='Choice73' name='Choice'>
							<label for='Choice73' class="btn-input-gray-lite">Sentier</label>

							<input type='checkbox' id='Choice74' name='Choice'>
							<label for='Choice74' class="btn-input-gray-lite">Montorgueil</label>

							<input type='checkbox' id='Choice75' name='Choice'>
							<label for='Choice75' class="btn-input-gray-lite">Montorgueil</label>

							<input type='checkbox' id='Choice76' name='Choice'>
							<label for='Choice76' class="btn-input-gray-lite">Provence</label>

							<input type='checkbox' id='Choice77' name='Choice'>
							<label for='Choice77' class="btn-input-gray-lite">Sentier</label>

							<input type='checkbox' id='Choice78' name='Choice'>
							<label for='Choice78' class="btn-input-gray-lite">Montorgueil</label>

							<input type='checkbox' id='Choice79' name='Choice'>
							<label for='Choice79' class="btn-input-gray-lite">Montorgueil</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice71' name='Choice' />
							<label for='Choice71' class="btn-input-grayer">
								16<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice80' name='Choice'>
							<label for='Choice80' class="btn-input-gray-lite">Arts et Métiers</label>

							<input type='checkbox' id='Choice81' name='Choice'>
							<label for='Choice81' class="btn-input-gray-lite">Archives</label>

							<input type='checkbox' id='Choice82' name='Choice'>
							<label for='Choice82' class="btn-input-gray-lite">Enfants Rouge</label>

							<input type='checkbox' id='Choice83' name='Choice'>
							<label for='Choice83' class="btn-input-gray-lite">Saint-Avoye</label>

							<input type='checkbox' id='Choice84' name='Choice'>
							<label for='Choice84' class="btn-input-gray-lite">Enfants Rouge</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice85' name='Choice' />
							<label for='Choice85' class="btn-input-grayer">
								17<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice86' name='Choice'>
							<label for='Choice86' class="btn-input-gray-lite">Arts et Métiers</label>

							<input type='checkbox' id='Choice87' name='Choice'>
							<label for='Choice87' class="btn-input-gray-lite">Archives</label>

							<input type='checkbox' id='Choice88' name='Choice'>
							<label for='Choice88' class="btn-input-gray-lite">Enfants Rouge</label>

							<input type='checkbox' id='Choice89' name='Choice'>
							<label for='Choice89' class="btn-input-gray-lite">Saint-Avoye</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice90' name='Choice' />
							<label for='Choice90' class="btn-input-grayer">
								18<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice91' name='Choice'>
							<label for='Choice91' class="btn-input-gray-lite">Provence</label>

							<input type='checkbox' id='Choice92' name='Choice'>
							<label for='Choice92' class="btn-input-gray-lite">Sentier</label>

							<input type='checkbox' id='Choice93' name='Choice'>
							<label for='Choice93' class="btn-input-gray-lite">Montorgueil</label>

							<input type='checkbox' id='Choice94' name='Choice'>
							<label for='Choice94' class="btn-input-gray-lite">Montorgueil</label>

							<input type='checkbox' id='Choice95' name='Choice'>
							<label for='Choice95' class="btn-input-gray-lite">Montorgueil</label>

							<input type='checkbox' id='Choice96' name='Choice'>
							<label for='Choice96' class="btn-input-gray-lite">Sentier</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice97' name='Choice' />
							<label for='Choice97' class="btn-input-grayer">
								19<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice98' name='Choice'>
							<label for='Choice98' class="btn-input-gray-lite">Arts et Métiers</label>

							<input type='checkbox' id='Choice99' name='Choice'>
							<label for='Choice99' class="btn-input-gray-lite">Archives</label>

							<input type='checkbox' id='Choice100' name='Choice'>
							<label for='Choice100' class="btn-input-gray-lite">Enfants Rouge</label>

							<input type='checkbox' id='Choice101' name='Choice'>
							<label for='Choice101' class="btn-input-gray-lite">Saint-Avoye</label>
						</div>
						<div class="box-input">
							<input type="checkbox" id='Choice102' name='Choice' />
							<label for='Choice102' class="btn-input-grayer">
								20<sup>e</sup> Arrondissement
							</label><br>

							<input type='checkbox' id='Choice103' name='Choice'>
							<label for='Choice103' class="btn-input-gray-lite">Provence</label>

							<input type='checkbox' id='Choice104' name='Choice'>
							<label for='Choice104' class="btn-input-gray-lite">Sentier</label>

							<input type='checkbox' id='Choice105' name='Choice'>
							<label for='Choice105' class="btn-input-gray-lite">Montorgueil</label>

							<input type='checkbox' id='Choice106' name='Choice'>
							<label for='Choice106' class="btn-input-gray-lite">Provence</label>

							<input type='checkbox' id='Choice107' name='Choice'>
							<label for='Choice107' class="btn-input-gray-lite">Sentier</label>

							<input type='checkbox' id='Choice108' name='Choice'>
							<label for='Choice108' class="btn-input-gray-lite">Montorgueil</label>
						</div>
					</form>
				</div>
			</div>
			<div class="box-universal">
				<label class="name-title-black">93 - Seine-Saint-Denis</label>
				<div class="box-all-input">
					<form>
						<input type='checkbox' id='Choice109' name='Choice'>
						<label for='Choice109' class="btn-input-gray-lite">Provence</label>

						<input type='checkbox' id='Choice110' name='Choice'>
						<label for='Choice110' class="btn-input-gray-lite">Sentier</label>

						<input type='checkbox' id='Choice111' name='Choice'>
						<label for='Choice111' class="btn-input-gray-lite">Montorgueil</label>

						<input type='checkbox' id='Choice112' name='Choice'>
						<label for='Choice112' class="btn-input-gray-lite">Provence</label>

						<input type='checkbox' id='Choice113' name='Choice'>
						<label for='Choice113' class="btn-input-gray-lite">Sentier</label>

						<input type='checkbox' id='Choice114' name='Choice'>
						<label for='Choice114' class="btn-input-gray-lite">Montorgueil</label>

						<input type='checkbox' id='Choice115' name='Choice'>
						<label for='Choice115' class="btn-input-gray-lite">Sentier</label>

						<input type='checkbox' id='Choice116' name='Choice'>
						<label for='Choice116' class="btn-input-gray-lite">Montorgueil</label>
					</form>
				</div>
			</div>
			<div class="box-universal">
				<label class="name-title-black">94 - Val-de-Marne</label>
				<div class="box-all-input">
					<form>
						<input type='checkbox' id='Choice117' name='Choice'>
						<label for='Choice117' class="btn-input-gray-lite">Provence</label>

						<input type='checkbox' id='Choice118' name='Choice'>
						<label for='Choice118' class="btn-input-gray-lite">Sentier</label>

						<input type='checkbox' id='Choice119' name='Choice'>
						<label for='Choice119' class="btn-input-gray-lite">Montorgueil</label>

						<input type='checkbox' id='Choice120' name='Choice'>
						<label for='Choice120' class="btn-input-gray-lite">Provence</label>

						<input type='checkbox' id='Choice121' name='Choice'>
						<label for='Choice121' class="btn-input-gray-lite">Sentier</label>

						<input type='checkbox' id='Choice122' name='Choice'>
						<label for='Choice122' class="btn-input-gray-lite">Montorgueil</label>

						<input type='checkbox' id='Choice123' name='Choice'>
						<label for='Choice123' class="btn-input-gray-lite">Sentier</label>
					</form>
				</div>
			</div>
			<div class="box-universal">
				<label class="name-title-black">92 - Hauts-de-Seine</label>
				<div class="box-all-input">
					<form>
						<input type='checkbox' id='Choice124' name='Choice'>
						<label for='Choice124' class="btn-input-gray-lite">Provence</label>

						<input type='checkbox' id='Choice125' name='Choice'>
						<label for='Choice125' class="btn-input-gray-lite">Sentier</label>

						<input type='checkbox' id='Choice126' name='Choice'>
						<label for='Choice126' class="btn-input-gray-lite">Montorgueil</label>

						<input type='checkbox' id='Choice127' name='Choice'>
						<label for='Choice127' class="btn-input-gray-lite">Provence</label>

						<input type='checkbox' id='Choice128' name='Choice'>
						<label for='Choice128' class="btn-input-gray-lite">Sentier</label>

						<input type='checkbox' id='Choice129' name='Choice'>
						<label for='Choice129' class="btn-input-gray-lite">Montorgueil</label>

						<input type='checkbox' id='Choice130' name='Choice'>
						<label for='Choice130' class="btn-input-gray-lite">Sentier</label>
					</form>
				</div>
			</div>
		</div>

		<div class="box-btn-search">
			<a href="" class="btn btn-gray btn-effacer">Effacer mes sélections</a>
			<a href="" class="btn btn-red btn-sauv">Sauvegarder</a>
			<a href="" class="btn btn-blue">Rechercher</a>
		</div>
	</div>



	<div class="grid">
		<div class="grid-half grid-transparent">
			<div class="grid-inner">
				<h1 class="blue">Decouveres <br> nos outils <br> de recherche</h1>
				<p>Ommi transforme la façon dont vous louez.
					Il rend service aux propriétaires et aux locataires.
					Ommi vous simplifie l’immobilier.
				</p>
				<a href="#" class="btn btn-red btn-annonce">
					<i class="i-group-red icon-metro"></i>
					par métro
				</a>
				<a href="#" class="btn btn-red btn-annonce">
					<i class="i-group-red icon-dessin"></i>
					par dessin
				</a>
				<a href="#" class="btn btn-red btn-annonce">
					<i class="i-group-red icon-carte-red"></i>
					par carte
				</a>
			</div>
		</div>
		<div class="inner-box-carte">
			<img src="/assets/images/carte-metro-small.png">
		</div>
	</div>
	<div class="grid grid-transparent">
		<div class="grid-half">
			<div class="grid-inner h120">
				<h1 class="gray">Compte Ommium</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Ommi, Ommi+ ou Ommium?
						Des comptes adaptés à chacun.
					</div>
					<div class="index-row-six-link">
						<a href="#link">Découvrez nos comptes</a>
					</div>
				</div>
			</div>
		</div>
		<div class="grid-half">
			<div class="grid-inner h120">
				<h1 class="gray">F.A.Q.</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Consultez les questions les plus fréquemment posées.
					</div>
					<div class="index-row-six-link">
						<a href="#link">Consultez les F.A.Q.</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="grid">
		<div class="grid-full">
			<h1 class="gray">Je m'nscris, c'est gratuit
				<a href="#" class="right btn btn-blue w200">Créer un compte</a>
			</h1>
		</div>
	</div>
</div>