<?php
$this->headLink()->appendStylesheet('/css/ui/jquery-ui-1.10.3.css');
$this->headScript()->appendFile('/assets/js/search_form.js');
?>
<script type="text/javascript">
    $(document).ready(function(){
        $('a#btnSearch1').click(function() {
            $('form[name="searchForm"]').submit();
            return false;
        });

        $('a#bottomSearchButton').click(function() {
            $('form[name="searchForm"]').submit();
            return false;
        });

    });
</script>
<div class="title-row-search bg-carte">
    <div class="container-text">
        <h1 class="white-txt">Recherche par carte</h1>
    </div>
</div>
<main>
<div class="inner">
<div class="grid grid-dark">
    <div class="menu-search">
        <ul>
            <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'standard'), false, true)?>"  class=" menu-icons icon-search">Recherche standard</a></li>
            <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'metro'), false, true)?>" class="menu-icons icon-metro">Recherche<br>par  metro</a></li>
            <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'draw'), false, true)?>" class=" menu-icons icon-dessin">Recherche<br> par dessin</a></li>
            <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'map'), false, true)?>" class="active menu-icons icon-carte">Recherche<br> par carte</a></li>
        </ul>
    </div>
    <form action="<?=$this->form->getAction()?>" name="searchForm"  id="form-search-map" method="POST">
    <div class="search-box">
        <div class="search-left">
            <div class="search-budget">
                <label class="name-title-white">Budget</label>
                <?=$this->form->getElement('min_budget')?>
                <?=$this->form->getElement('max_budget')?>
            </div>
            <div class="search-surface">
                <label class="name-title-white">Surface</label>
                <?=$this->form->getElement('min_size')?>
                <?=$this->form->getElement('max_size')?>
            </div>
        </div>
        <div class="search-right">
            <?=$this->form->getElement('is_furnished')?>
            <?=$this->form->getElement('number_of_rooms1')?>
            <?=$this->form->getElement('regions_selected')?>
        </div>
    </div>
    <!--</form>-->
</div>

<div class="grid grid-dark">
    <div class="title-advanced">
        <h2>Sélectionner des quartiers</h2>
        <p>Cliquez sur un arrondissement pour accéder à une carte plus précise.<br>
            Sélectionnez autant de quartiers que vous le souhaitez.<br>
					<span class="blue">
						Lorsque vous êtes satisfait, il vous suffit de lancer la recherche.
					</span>
        </p>
    </div>
    <div class="box-carte carte-black">
        <?= $this->googleMap(48.857261, 2.346611, array('width' => 1003, 'height' => 621, 'margin' => 0), array('zoom' => 8), "var regions = {$this->regionsJson};\ninitSearchMap(map, regions)") ?>
        <div class="box-btn-return">
            <a href="#" class="btn btn-gray-lite btn-return">Retour à la carte générale</a>
        </div>
    </div>
    <div class="box-btn-search">
        <a href="" class="btn btn-gray btn-effacer">Effacer mes sélections</a>
        <a href="" class="btn btn-red btn-sauv">Sauvegarder</a>
        <a href="#" class="btn btn-blue" id="btnSearch1">Rechercher</a>
    </div>
</div>
<div class="grid grid-dark">
<div class="title-advanced">
    <h2>Sélectionner à partir de la liste</h2>
    <p>Sélectionnez autant de quartiers que vous souhaitez.<br>
					<span class="blue">
						Lorsque vous êtes satisfait, il vous suffit de lancer la recherche.
					</span>
    </p>
</div>
<div class="box-search-advanced">
<div class="box-universal">
<label class="name-title-black">75 - Paris</label>
<div class="box-all-input">
<!--<form action="<?=$this->form->getAction()?>" name="searchForm-bottom"  id="form-search-regions" method="POST">-->
    <? $curDistrictId = Null ?>
    <? foreach ($this->allBlockRegions as $region): ?>
        <? if ($curDistrictId != $region->region_district_id): ?>
            <? if ($curDistrictId): ?></div><? endif ?>
            <div class="box-input">
            <input type="checkbox" class="input-pretty" id="district<?= $region->region_district_id ?>" name="RegionDistrict-<?= $region->region_district_id ?>" />
            <label class="btn-input-grayer" for="district<?= $region->region_district_id ?>">
                <?= $region->RegionDistrict->name ?>
            </label><br>
        
            <? $curDistrictId = $region->region_district_id ?>
        <? endif ?>
        
            <input type="checkbox" id="region<?= $region->id ?>" name="region<?= $region->id ?>" class="input-pretty region region<?= $region->id ?>" value="1" <? if (in_array($region->id, $this->regionsSelectedIds)): ?>checked="checked"<? endif ?>>
            <label for="region<?= $region->id ?>" class="btn-input-gray-lite"><?= $region->name ?></label>
    <? endforeach ?>
    
</form>
</div>
</div>
</div>

<div class="box-btn-search">
    <a href="" class="btn btn-gray btn-effacer">Effacer mes sélections</a>
    <a href="" class="btn btn-red btn-sauv">Sauvegarder</a>
    <a href="#" id="bottomSearchButton" class="btn btn-blue">Rechercher</a>
</div>
</div>

<?= $this->partial('_partials/search.phtml', $this->getVars()) ?>
</div>
</main>
