<?php
//$this->headLink()->appendStylesheet('/assets/css/search_form.css');
//$this->headScript()->appendFile('/js/common.js');

$fields = $this->form->getElements();
?>
<div class="title-row-search bg-metro">
    <div class="container-text">
        <h1 class="white-txt">Recherche par métro</h1>
    </div>
</div>
<main>
    <div class="inner">
        <div class="grid grid-dark">
            <div class="menu-search">
                <ul>
                    <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'standard'), false, true)?>"  class=" menu-icons icon-search">Recherche standard</a></li>
                    <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'metro'), false, true)?>" class="active menu-icons icon-metro">Recherche<br>par  metro</a></li>
                    <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'draw'), false, true)?>" class="menu-icons icon-dessin">Recherche<br> par dessin</a></li>
                    <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'map'), false, true)?>" class="menu-icons icon-carte">Recherche<br> par carte</a></li>
                </ul>
            </div>
            <div class="search-box">
                <div class="search-left">
                    <div class="search-budget">
                        <label class="name-title-white">Budget</label>
                        <?=$this->form->getElement('min_budget')?>
                        <?=$this->form->getElement('max_budget')?>
                    </div>
                    <div class="search-surface">
                        <label class="name-title-white">Surface</label>
                        <?=$this->form->getElement('min_size')?>
                        <?=$this->form->getElement('max_size')?>
                    </div>
                </div>
                <div class="search-right">
                    <div class="box-universal">
                        <label class="name-title-white">Mobilier</label>
                        <form>
                            <input type="reset" value="Tous" class="btn-tous"/>
                            <?php
                            $count = 1;
                            $ctrlName = 'is_furnished';
                            foreach($fields[$ctrlName]->getMultiOptions() as $value => $label) {
                                echo '<input type="radio" class="input-pretty" value="'.$value.'" name="'.$ctrlName.'" id ="'.$ctrlName.'_'.$count.'" '.($fields[$ctrlName]->getValue() === $value ? 'checked="checked"' : '').' /> ' .
                                    '<label for="'.$ctrlName.'_'.($count++).'" class="btn-input-gray-dark">'.$label.'</label>';
                            }
                            ?>
                        </form>
                    </div>
                    <div class="box-universal">
                        <label class="name-title-white">Nombre de chambres</label>
                        <form>
                            <input type="reset" value="Tous" class="btn-tous"/>
                            <?php
                            $count = 1;
                            $ctrlName = 'number_of_rooms1';
                            foreach($fields[$ctrlName]->getMultiOptions() as $value => $label) {
                            ?>
                                <input type='checkbox' class="input-pretty" id='Choice<?=$count?>' name='<?=$ctrlName?>' value='<?=$value?>' <?=($fields[$ctrlName]->getValue() === $value ? 'checked="checked"' : '')?>>
                                <label for='Choice<?=($count++)?>' class="btn-input-gray-dark btn-input-number"><?=$label?></label>
                            <?php
                            }
                            ?>
                        </form>
                    </div>
                    <div class="box-universal">
                        <label class="name-title-white">Distance</label>
                        <form>
                            <input type="reset" value="Tous" class="btn-tous"/>
                            <?php
                            $count = 1;
                            $ctrlName = 'distance';
                            foreach($fields[$ctrlName]->getMultiOptions() as $value => $label) {
                                echo '<input type="radio" class="input-pretty" value="'.$value.'" name="'.$ctrlName.'" id ="'.$ctrlName.'_'.$count.'" '.($fields[$ctrlName]->getValue() === $value ? 'checked="checked"' : '').' /> ' .
                                    '<label for="'.$ctrlName.'_'.($count++).'" class="btn-input-gray-dark">'.$label.'</label>';
                            }
                            ?>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <div class="grid grid-dark">
            <div class="title-advanced">
                <h2>Sélectionner une station</h2>
                <p>Cliquez sur la carte et maintenez le clic enfoncé pour vous déplacer,
                    puis sélectionnez une station.<br>
                    Vous aurez la possibilité de changer de station par la suite.
                </p>
            </div>

            <?= $this->metroMap($this->stations) ?>

            <div class="box-btn-search">
                <a href="" class="link-carte">Recentrer la carte</a>
            </div>
        </div>
        <div class="grid">
            <div class="grid-full">
                <h2 class="gray txt-line-metro">Sélectionner une ligne complète</h2>
                <p>Sélectionner la ligne de votre de votre choix, dans la liste ci-dessous.<br>
                    Vous aurez la possibilité de changer de ligne par la suite.
                </p>
                <div class="box-line-metro">
                    <label class="name-title-black">Lignes de métro</label>
                    <img src="/./assets/images/line-metro.png">
                </div>
                <div class="box-line-metro">
                    <label class="name-title-black">Lignes de RER</label>
                    <img src="/./assets/images/btn-line-metro.png">
                </div>
            </div>
        </div>


        <div class="grid">
            <div class="grid-half grid-transparent">
                <div class="grid-inner">
                    <h1 class="blue">Decouveres <br> nos outils <br> de recherche</h1>
                    <p>Ommi transforme la façon dont vous louez.
                        Il rend service aux propriétaires et aux locataires.
                        Ommi vous simplifie l’immobilier.
                    </p>
                    <a href="#" class="btn btn-red btn-annonce">
                        <i class="i-group-red icon-metro"></i>
                        par métro
                    </a>
                    <a href="#" class="btn btn-red btn-annonce">
                        <i class="i-group-red icon-dessin"></i>
                        par dessin
                    </a>
                    <a href="#" class="btn btn-red btn-annonce">
                        <i class="i-group-red icon-carte-red"></i>
                        par carte
                    </a>
                </div>
            </div>
            <div class="inner-box-carte">
                <img src="/assets/images/carte-annonce.png">
            </div>
        </div>
        <div class="grid grid-transparent">
            <div class="grid-half">
                <div class="grid-inner h120">
                    <h1 class="gray">Compte Ommium</h1>
                    <div class="index-row-six cf">
                        <div class="index-row-six-text">
                            Ommi, Ommi+ ou Ommium?
                            Des comptes adaptés à chacun.
                        </div>
                        <div class="index-row-six-link">
                            <a href="#link">Découvrez nos comptes</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="grid-half">
                <div class="grid-inner h120">
                    <h1 class="gray">F.A.Q.</h1>
                    <div class="index-row-six cf">
                        <div class="index-row-six-text">
                            Consultez les questions les plus fréquemment posées.
                        </div>
                        <div class="index-row-six-link">
                            <a href="#link">Consultez les F.A.Q.</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="grid">
            <div class="grid-full">
                <h1 class="gray">Je m'nscris, c'est gratuit
                    <a href="#" class="right btn btn-blue w200">Créer un compte</a>
                </h1>
            </div>
        </div>
    </div>
</main>