<?php
$this->headLink()->appendStylesheet('/css/ui/jquery-ui-1.10.3.css');
$this->headLink()->appendStylesheet('/assets/css/search_form.css');
$this->headScript()->appendFile('/assets/js/search_form.js');
?>
<script type="text/javascript">
    $(document).ready(function() {

        /*$('.olTileImage,.olAlphaImg, .olLayerDiv').click(function(e) {
            e.stopPropagation();
            e.preventDefault();
            
            return false;
        });*/


        $('div.line-lick  div.number').click(function() {
            var line_id = $(this).attr('data-line-id');
            $('form[name="searchForm"]').find('input#metro_line_id').val(line_id);
            $('form[name="searchForm"]').submit();
        });
    });
</script>
<div class="title-row-search bg-metro">
    <div class="container-text">
        <h1 class="white-txt">Recherche par métro</h1>
    </div>
</div>
<main>
    <div class="inner">
        <div class="grid grid-dark">
            <div class="menu-search">
                <ul>
                    <li><a href="<?= $this->url(array('controller' => 'search', 'action' => 'standard'), false, true) ?>"  class=" menu-icons icon-search">Recherche standard</a></li>
                    <li><a href="<?= $this->url(array('controller' => 'search', 'action' => 'metro'), false, true) ?>" class="active menu-icons icon-metro">Recherche<br>par  metro</a></li>
                    <li><a href="<?= $this->url(array('controller' => 'search', 'action' => 'draw'), false, true) ?>" class="menu-icons icon-dessin">Recherche<br> par dessin</a></li>
                    <li><a href="<?= $this->url(array('controller' => 'search', 'action' => 'map'), false, true) ?>" class="menu-icons icon-carte">Recherche<br> par carte</a></li>
                </ul>
            </div>
            <form action="<?= $this->form->getAction() ?>" name="searchForm" id="form-search-metro" method="POST">
                <div class="search-box">
                    <div class="search-left">
                        <div class="search-budget">
                            <label class="name-title-white">Budget</label>
                            <?= $this->form->getElement('min_budget') ?>
                            <?= $this->form->getElement('max_budget') ?>
                        </div>
                        <div class="search-surface">
                            <label class="name-title-white">Surface</label>
                            <?= $this->form->getElement('min_size') ?>
                            <?= $this->form->getElement('max_size') ?>
                        </div>
                    </div>
                    <div class="search-right">
                        <?= $this->form->getElement('is_furnished') ?>
                        <?= $this->form->getElement('number_of_rooms1') ?>
                        <?= $this->form->getElement('distance') ?>

                        <?= $this->form->getElement('metro_station_id') ?>
                        <?= $this->form->getElement('metro_line_id') ?>
                    </div>
                </div>
            </form>
        </div>

        <div class="grid grid-dark">
            <div class="title-advanced">
                <h2>Sélectionner une station</h2>
                <p>Cliquez sur la carte et maintenez le clic enfoncé pour vous déplacer,
                    puis sélectionnez une station.<br>
                    Vous aurez la possibilité de changer de station par la suite.
                </p>
            </div>

            <?= $this->metroMap($this->stations) ?>

            <div class="box-btn-search">
                <a href="" class="link-carte">Recentrer la carte</a>
            </div>
        </div>
        <div class="grid">
            <div class="grid-full">
                <h2 class="gray txt-line-metro">Sélectionner une ligne complète</h2>
                <p>Sélectionner la ligne de votre de votre choix, dans la liste ci-dessous.<br>
                    Vous aurez la possibilité de changer de ligne par la suite.
                </p>
                <div class="box-line-metro">
                    <?php
                    //mDump(array($this->lines[0]->id, $this->lines[0]->name, $this->lines[0]->color));
                    ?>
                    <label class="name-title-black">Lignes de métro</label>
                    <div class="metro_lines_wrapper">
                        <?php
                        $count = 0;
                        ?>
                        <?php foreach ($this->lines as $indx => $rec): ?>
                            <?php
                            $number = intval($rec->name);
                            if ($number == 0)
                                continue;
                            $count++;
                            $str = mb_substr($rec->name, mb_strlen($number));
                            $r = hexdec(substr($rec->color, 0, 2));
                            $g = hexdec(substr($rec->color, 2, 2));
                            $b = hexdec(substr($rec->color, 4, 2));
                            $Y = ($r + $r + $b + $g + $g + $g) / 6;

                            $r = round($r * 0.6);
                            $g = round($g * 0.6);
                            $b = round($b * 0.6);
                            $shadowStr = 'rgba(' . $r . ', ' . $g . ', ' . $b . ', 0.9)';
                            ?>
                            <div class="line-lick metro_line_circle" style="background-color: #<?= $rec->color ?>; color: <?= ($Y <= 128 ? 'white' : 'black') ?> !important; -webkit-box-shadow: 0px 2px 0px <?= $shadowStr ?>; -moz-box-shadow: 0px 2px 0px <?= $shadowStr ?>; box-shadow: 0px 2px 0px <?= $shadowStr ?>;"><?= '<div data-line-id="' . $rec->id . '" class="number ' . ($str != '' ? 'align2' : 'align1') . '">' . $number . '</div>' . ($str != '' ? '<div class="line-str">' . $str . '</div>' : '') ?></div>
                        <?php endforeach; ?>
                        <div class="clear"></div>
                    </div>
                </div>
                <?php if (count($this->lines) - $count > 0): ?>
                    <div class="box-line-metro">
                        <label class="name-title-black">Lignes de RER</label>
                        <?php foreach ($this->lines as $indx => $rec): ?>
                            <?php
                            $number = intval($rec->name);
                            if ($number != 0)
                                continue;
                            $number = mb_strtoupper(mb_substr($rec->name, 0, 1));

                            $r = hexdec(substr($rec->color, 0, 2));
                            $g = hexdec(substr($rec->color, 2, 2));
                            $b = hexdec(substr($rec->color, 4, 2));
                            $Y = ($r + $r + $b + $g + $g + $g) / 6;

                            $r = round($r * 0.6);
                            $g = round($g * 0.6);
                            $b = round($b * 0.6);
                            $shadowStr = 'rgba(' . $r . ', ' . $g . ', ' . $b . ', 0.9)';
                            ?>
                            <div class="line-lick rer_line_circle" style="border-color: #<?= $rec->color ?>; color: #<?= $rec->color ?> !important; -webkit-box-shadow: 0px 2px 0px <?= $shadowStr ?>; -moz-box-shadow: 0px 2px 0px <?= $shadowStr ?>; box-shadow: 0px 2px 0px <?= $shadowStr ?>;"><?= '<div data-line-id="' . $rec->id . '" class="number align1">' . $number . '</div>' ?></div>
                        <?php endforeach; ?>
                        <div class="clear"></div>
                    </div>
                <?php endif; ?>
            </div>
        </div>


        <?= $this->partial('_partials/search.phtml', $this->getVars()) ?>
    </div>
</main>