<?php
$fields = $this->form->getElements();
?>
<script type="text/javascript">
    var initialRadioValues = new Array();
    $(document).ready(function(){
        var arrIndx = 0;
        $('form[name="searchForm"]').find('input[type="radio"]:checked').each(function() {
            initialRadioValues[arrIndx++] = $(this).attr('id');
        });
        $('form[name="searchForm"]').find('input[type="checkbox"]:checked').each(function() {
            initialRadioValues[arrIndx++] = $(this).attr('id');
        });

        $('input.btn-tous').click(function() {
            $(this).parent().find('input[type="radio"]:checked').prop('checked', false);
            $(this).parent().find('input[type="checkbox"]:checked').prop('checked', false);
            for (var i=0; i<initialRadioValues.length; i++) {
                if ($(this).parent().find('input#'+initialRadioValues[i]).length) {
                    $('input#'+initialRadioValues[i]).prop('checked', true);
                }
            }
        });

        $('a#btnSearch1, a#btnSearch2' ).click(function() {
            $('form[name="searchForm"]').submit();
            return false;
        });
    });
</script>
<div class="title-row-search bg-stand">
    <div class="container-text">
        <h1 class="white-txt">Recherche standard</h1>
    </div>
</div>
<main>
<div class="inner">
<form action="<?=$this->form->getAction()?>" name="searchForm" method="POST">
<div class="grid grid-dark">
    <div class="menu-search">
        <ul>
            <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'standard'), false, true)?>"  class="active menu-icons icon-search">Recherche standard</a></li>
            <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'metro'), false, true)?>" class="menu-icons icon-metro">Recherche<br>par  metro</a></li>
            <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'draw'), false, true)?>" class="menu-icons icon-dessin">Recherche<br> par dessin</a></li>
            <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'map'), false, true)?>" class="menu-icons icon-carte">Recherche<br> par carte</a></li>
        </ul>
    </div>
    <div class="search-box">
        <div class="search-left">
            <div class="search-location">
                <label class="name-title-white">Localisation</label>
                <input type="text" placeholder="Où désirez-vous louer? "/>
                <a href="#" class="btn btn-small btn-dark icon-location"></a>
            </div>
            <div class="search-budget">
                <label class="name-title-white">Budget</label>
                <?=$this->form->getElement('min_budget')?>
                <?=$this->form->getElement('max_budget')?>
            </div>
            <div class="search-surface">
                <label class="name-title-white">Surface</label>
                <?=$this->form->getElement('min_size')?>
                <?=$this->form->getElement('max_size')?>
            </div>
        </div>
        <div class="search-right">
            <?=$this->form->getElement('is_furnished')?>
            <?=$this->form->getElement('number_of_rooms1')?>
            <a href="#" class="btn btn-blue" id="btnSearch1">Rechercher</a>
        </div>
    </div>
</div>

<div class="grid grid-dark">
    <div class="title-advanced">
        <h2>Critères Avancés</h2>
    </div>
    <div class="box-search-advanced">
        <?=$this->form->getElement('property_type')?>
        <?=$this->form->getElement('number_of_rooms2')?>
        <?=$this->form->getElement('availability_select')?>
        <?=$this->form->getElement('rent_period')?>
        <?=$this->form->getElement('collocation')?>
        <?=$this->form->getElement('planning')?>
        <?=$this->form->getElement('outbuilding')?>
        <?=$this->form->getElement('exterior')?>
        <?=$this->form->getElement('building')?>
        <?=$this->form->getElement('heating')?>
    </div>
    <div class="box-btn-search">
        <a href="" class="btn btn-red">Sauvegarder ma recherche</a>
        <a href="#" class="btn btn-blue" id="btnSearch2">Rechercher</a>
    </div>
</div>
</form>


<div class="grid">
    <div class="grid-half grid-transparent">
        <div class="grid-inner">
            <h1 class="blue">Decouveres <br> nos outils <br> de recherche</h1>
            <p>Ommi transforme la façon dont vous louez.
                Il rend service aux propriétaires et aux locataires.
                Ommi vous simplifie l’immobilier.
            </p>
            <a href="#" class="btn btn-red btn-annonce">
                <i class="i-group-red icon-metro"></i>
                par métro
            </a>
            <a href="#" class="btn btn-red btn-annonce">
                <i class="i-group-red icon-dessin"></i>
                par dessin
            </a>
            <a href="#" class="btn btn-red btn-annonce">
                <i class="i-group-red icon-carte-red"></i>
                par carte
            </a>
        </div>
    </div>
    <div class="inner-box-carte">
        <img src="/assets/images/carte-annonce.png">
    </div>
</div>
<div class="grid grid-transparent">
    <div class="grid-half">
        <div class="grid-inner h120">
            <h1 class="gray">Compte Ommium</h1>
            <div class="index-row-six cf">
                <div class="index-row-six-text">
                    Ommi, Ommi+ ou Ommium?
                    Des comptes adaptés à chacun.
                </div>
                <div class="index-row-six-link">
                    <a href="#link">Découvrez nos comptes</a>
                </div>
            </div>
        </div>
    </div>
    <div class="grid-half">
        <div class="grid-inner h120">
            <h1 class="gray">F.A.Q.</h1>
            <div class="index-row-six cf">
                <div class="index-row-six-text">
                    Consultez les questions les plus fréquemment posées.
                </div>
                <div class="index-row-six-link">
                    <a href="#link">Consultez les F.A.Q.</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="grid">
    <div class="grid-full">
        <h1 class="gray">Je m'nscris, c'est gratuit
            <a href="#" class="right btn btn-blue w200">Créer un compte</a>
        </h1>
    </div>
</div>
</div>
</main>