<?php
$fields = $this->form->getElements();
?>
<script type="text/javascript">
    var initialRadioValues = new Array();
    $(document).ready(function(){
        var arrIndx = 0;
        $('form[name="searchForm"]').find('input[type="radio"]:checked').each(function() {
            initialRadioValues[arrIndx++] = $(this).attr('id');
        });
        $('form[name="searchForm"]').find('input[type="checkbox"]:checked').each(function() {
            initialRadioValues[arrIndx++] = $(this).attr('id');
        });

        $('input.btn-tous').click(function() {
            $(this).parent().find('input[type="radio"]:checked').prop('checked', false);
            $(this).parent().find('input[type="checkbox"]:checked').prop('checked', false);
            for (var i=0; i<initialRadioValues.length; i++) {
                if ($(this).parent().find('input#'+initialRadioValues[i]).length) {
                    $('input#'+initialRadioValues[i]).prop('checked', true);
                }
            }
        });

        $('a#btnSearch1, a#btnSearch2' ).click(function() {
            $('form[name="searchForm"]').submit();
            return false;
        });
    });
</script>
<div class="title-row-search bg-stand">
    <div class="container-text">
        <h1 class="white-txt">Recherche standard</h1>
    </div>
</div>
<main>
<div class="inner">
<form action="<?=$this->form->getAction()?>" name="searchForm" method="POST">
<div class="grid grid-dark">
    <div class="menu-search">
        <ul>
            <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'standard'), false, true)?>"  class="active menu-icons icon-search">Recherche standard</a></li>
            <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'metro'), false, true)?>" class="menu-icons icon-metro">Recherche<br>par  metro</a></li>
            <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'draw'), false, true)?>" class="menu-icons icon-dessin">Recherche<br> par dessin</a></li>
            <li><a href="<?=$this->url(array('controller' => 'search', 'action' => 'map'), false, true)?>" class="menu-icons icon-carte">Recherche<br> par carte</a></li>
        </ul>
    </div>
    <div class="search-box">
        <div class="search-left">
            <div class="search-location">
                <label class="name-title-white">Localisation</label>
                <input type="text" placeholder="Où désirez-vous louer? "/>
                <a href="#" class="btn btn-small btn-dark icon-location"></a>
            </div>
            <div class="search-budget">
                <label class="name-title-white">Budget</label>
                <?=$this->form->getElement('min_budget')?>
                <?=$this->form->getElement('max_budget')?>
            </div>
            <div class="search-surface">
                <label class="name-title-white">Surface</label>
                <?=$this->form->getElement('min_size')?>
                <?=$this->form->getElement('max_size')?>
            </div>
        </div>
        <div class="search-right">
            <?=$this->form->getElement('is_furnished')?>
            <?=$this->form->getElement('number_of_rooms1')?>
            <a href="#" class="btn btn-blue" id="btnSearch1">Rechercher</a>
        </div>
    </div>
</div>

<div class="grid grid-dark">
    <div class="title-advanced">
        <h2>Critères Avancés</h2>
    </div>
    <div class="box-search-advanced">
        <?=$this->form->getElement('property_type')?>
        <div class="box-universal">
            <label class="name-title-black">Type de bien</label>
            <form>
                <input type="reset" value="Tous" class="btn-tous"/>
                <input type='checkbox' class="input-pretty" id='Choice5' name='Choice'>
                <label for='Choice5' class="btn-input-gray-lite">Appartement</label>

                <input type='checkbox' class="input-pretty" id='Choice7' name='Choice'>
                <label for='Choice7' class="btn-input-gray-lite">Maison</label>

                <input type='checkbox' class="input-pretty" id='Choice8' name='Choice'>
                <label for='Choice8' class="btn-input-gray-lite">Studio</label>

                <input type='checkbox' class="input-pretty" id='Choice9' name='Choice'>
                <label for='Choice9' class="btn-input-gray-lite">Chambre</label>

                <input type='checkbox' class="input-pretty" id='Choice10' name='Choice'>
                <label for='Choice10' class="btn-input-gray-lite">Loft / Atelier</label>
            </form>
        </div>
        <div class="box-universal">
            <label class="name-title-black">Nombre de pièces</label>
            <form>
                <input type="reset" value="Tous" class="btn-tous"/>
                <input type='checkbox' class="input-pretty" id='Choice11' name='Choice'>
                <label for='Choice11' class="btn-input-gray-lite btn-input-number">1</label>

                <input type='checkbox' class="input-pretty" id='Choice12' name='Choice'>
                <label for='Choice12' class="btn-input-gray-lite btn-input-number">2</label>

                <input type='checkbox' class="input-pretty" id='Choice13' name='Choice'>
                <label for='Choice13' class="btn-input-gray-lite btn-input-number">3</label>

                <input type='checkbox' class="input-pretty" id='Choice14' name='Choice'>
                <label for='Choice14' class="btn-input-gray-lite btn-input-number">4</label>

                <input type='checkbox' class="input-pretty" id='Choice15' name='Choice'>
                <label for='Choice15' class="btn-input-gray-lite btn-input-number">5 et +</label>
            </form>
        </div>
        <div class="box-universal">
            <label class="name-title-black">Disponibilité</label>
            <form>
                <input type="reset" value="Tous" class="btn-tous"/>
                <input type='radio' class="input-pretty" id='Choice4' name='Choice'>
                <label for='Choice4' class="btn-input-gray-lite">Immédiatement</label>

            </form>
        </div>
        <div class="box-universal">
            <label class="name-title-black">Durée du bail</label>
            <form>
                <input type="reset" value="Tous" class="btn-tous"/>
                <input type='radio' class="input-pretty" id='Choice5' name='Choice'>
                <label for='Choice5' class="btn-input-gray-lite">Courte durée</label>

                <input type='radio' class="input-pretty" id='Choice6' name='Choice'>
                <label for='Choice6' class="btn-input-gray-lite">Longue durée</label>
            </form>
        </div>
        <div class="box-universal">
            <label class="name-title-black">Colocation acceptée</label>
            <form>
                <input type="reset" value="Tous" class="btn-tous"/>
                <input type='radio' class="input-pretty" id='Choice7' name='Choice'>
                <label for='Choice7' class="btn-input-gray-lite">Oui</label>
            </form>
        </div>
        <div class="box-universal">
            <label class="name-title-black">Aménagement</label>
            <form>
                <input type='checkbox' class="input-pretty" id='Choice16' name='Choice'>
                <label for='Choice16' class="btn-input-gray-lite">Toilettes séparées</label>

                <input type='checkbox' class="input-pretty" id='Choice17' name='Choice'>
                <label for='Choice17' class="btn-input-gray-lite">Parquet</label>

                <input type='checkbox' class="input-pretty" id='Choice18' name='Choice'>
                <label for='Choice18' class="btn-input-gray-lite">Moulures</label>

                <input type='checkbox' class="input-pretty" id='Choice19' name='Choice'>
                <label for='Choice19' class="btn-input-gray-lite">Double vitrage</label><br>

                <input type='checkbox' class="input-pretty" id='Choice20' name='Choice'>
                <label for='Choice20' class="btn-input-gray-lite">Rangements</label>

                <input type='checkbox' class="input-pretty" id='Choice21' name='Choice'>
                <label for='Choice21' class="btn-input-gray-lite">Cheminée</label>

                <input type='checkbox' class="input-pretty" id='Choice22' name='Choice'>
                <label for='Choice22' class="btn-input-gray-lite">
                    Air conditionné
                </label>
                <input type='checkbox' class="input-pretty" id='Choice23' name='Choice'>
                <label for='Choice23' class="btn-input-gray-lite">
                    Rénové
                </label>
            </form>
        </div>
        <div class="box-universal">
            <label class="name-title-black">Dépendances</label>
            <form>
                <input type='checkbox' class="input-pretty" id='Choice24' name='Choice'>
                <label for='Choice24' class="btn-input-gray-lite">Cave</label>

                <input type='checkbox' class="input-pretty" id='Choice25' name='Choice'>
                <label for='Choice25' class="btn-input-gray-lite">Parking</label>

                <input type='checkbox' class="input-pretty" id='Choice26' name='Choice'>
                <label for='Choice26' class="btn-input-gray-lite">Parking fermé / Box</label>
            </form>
        </div>
        <div class="box-universal">
            <label class="name-title-black">Espaces extérieurs</label>
            <form>
                <input type='checkbox' class="input-pretty" id='Choice27' name='Choice'>
                <label for='Choice27' class="btn-input-gray-lite">Jardin</label>

                <input type='checkbox' class="input-pretty" id='Choice28' name='Choice'>
                <label for='Choice28' class="btn-input-gray-lite">Balcon</label>

                <input type='checkbox' class="input-pretty" id='Choice29' name='Choice'>
                <label for='Choice29' class="btn-input-gray-lite">Terrasse</label>

                <input type='checkbox' class="input-pretty" id='Choice30' name='Choice'>
                <label for='Choice30' class="btn-input-gray-lite">Piscine</label>
            </form>
        </div>
        <div class="box-universal">
            <label class="name-title-black">Immeuble</label>
            <form>
                <input type='checkbox' class="input-pretty" id='Choice31' name='Choice'>
                <label for='Choice31' class="btn-input-gray-lite">Ascenceur</label>

                <input type='checkbox' class="input-pretty" id='Choice32' name='Choice'>
                <label for='Choice32' class="btn-input-gray-lite">Gardien</label>

                <input type='checkbox' class="input-pretty" id='Choice33' name='Choice'>
                <label for='Choice33' class="btn-input-gray-lite">Digicode / Interphone</label><br>

                <input type='checkbox' class="input-pretty" id='Choice34' name='Choice'>
                <label for='Choice34' class="btn-input-gray-lite">Ancien</label>

                <input type='checkbox' class="input-pretty" id='Choice35' name='Choice'>
                <label for='Choice35' class="btn-input-gray-lite">Neuf</label>

                <input type='checkbox' class="input-pretty" id='Choice36' name='Choice'>
                <label for='Choice36' class="btn-input-gray-lite">Pierre de Taille</label>
            </form>
        </div>
        <div class="box-universal">
            <label class="name-title-black">Chauffage</label>
            <form>
                <input type='checkbox' class="input-pretty" id='Choice37' name='Choice'>
                <label for='Choice37' class="btn-input-gray-lite">Central / Collectif</label>

                <input type='checkbox' class="input-pretty" id='Choice38' name='Choice'>
                <label for='Choice38' class="btn-input-gray-lite">Individuel</label><br>

                <input type='checkbox' class="input-pretty" id='Choice39' name='Choice'>
                <label for='Choice39' class="btn-input-gray-lite">Au sol</label>

                <input type='checkbox' class="input-pretty" id='Choice40' name='Choice'>
                <label for='Choice40' class="btn-input-gray-lite">Gaz</label>

                <input type='checkbox' class="input-pretty" id='Choice41' name='Choice'>
                <label for='Choice41' class="btn-input-gray-lite">Électrique</label>

                <input type='checkbox' class="input-pretty" id='Choice42' name='Choice'>
                <label for='Choice42' class="btn-input-gray-lite">Autre</label>
            </form>
        </div>
    </div>
    <div class="box-btn-search">
        <a href="" class="btn btn-red">Sauvegarder ma recherche</a>
        <a href="#" class="btn btn-blue" id="btnSearch2">Rechercher</a>
    </div>
</div>
</form>


<div class="grid">
    <div class="grid-half grid-transparent">
        <div class="grid-inner">
            <h1 class="blue">Decouveres <br> nos outils <br> de recherche</h1>
            <p>Ommi transforme la façon dont vous louez.
                Il rend service aux propriétaires et aux locataires.
                Ommi vous simplifie l’immobilier.
            </p>
            <a href="#" class="btn btn-red btn-annonce">
                <i class="i-group-red icon-metro"></i>
                par métro
            </a>
            <a href="#" class="btn btn-red btn-annonce">
                <i class="i-group-red icon-dessin"></i>
                par dessin
            </a>
            <a href="#" class="btn btn-red btn-annonce">
                <i class="i-group-red icon-carte-red"></i>
                par carte
            </a>
        </div>
    </div>
    <div class="inner-box-carte">
        <img src="/assets/images/carte-annonce.png">
    </div>
</div>
<div class="grid grid-transparent">
    <div class="grid-half">
        <div class="grid-inner h120">
            <h1 class="gray">Compte Ommium</h1>
            <div class="index-row-six cf">
                <div class="index-row-six-text">
                    Ommi, Ommi+ ou Ommium?
                    Des comptes adaptés à chacun.
                </div>
                <div class="index-row-six-link">
                    <a href="#link">Découvrez nos comptes</a>
                </div>
            </div>
        </div>
    </div>
    <div class="grid-half">
        <div class="grid-inner h120">
            <h1 class="gray">F.A.Q.</h1>
            <div class="index-row-six cf">
                <div class="index-row-six-text">
                    Consultez les questions les plus fréquemment posées.
                </div>
                <div class="index-row-six-link">
                    <a href="#link">Consultez les F.A.Q.</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="grid">
    <div class="grid-full">
        <h1 class="gray">Je m'nscris, c'est gratuit
            <a href="#" class="right btn btn-blue w200">Créer un compte</a>
        </h1>
    </div>
</div>
</div>
</main>