<header>
    <div class="inner">
        <a href="<?=$this->baseUrl('/'); ?>" class="home-logo">Ommi</a>
        <ul id="header-nav">
            <? if ($this->currUser) : ?>
            <li class="left"><a href="#">Guide du Locataire</a></li>
            <li><a href="<?= $this->url(array('controller' => 'search', 'action' => 'index'), null, true) ?>" class="btn btn-red">Nouvelle recherche</a></li>
            <li><a href="<?= $this->url(array('module' => 'user', 'controller' => 'my-account', 'action' => 'index'), null, true) ?>">Bonjour, <?= $this->currUser->first_name ?> <?= $this->currUser->last_name ?></a></li>
            <li><a href="#">Mes candidatures</a></li>           
            <? else : ?>            
            <li class="left"><a href="#">Comment ça marche ?</a></li>
            <li><a href="<?= $this->url(array('module' => 'user', 'controller' => 'property', 'action' => 'new-add'), null, true) ?>" class="btn btn-red">Publier une annonce</a></li>
            <li class="dropdown">
            	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Aide <i class="caret"></i></a>
            	<ul class="dropdown-menu">
            		<li><a href="">Guide du Locataire</a></li>
            		<li><a href="">Guide du Propriétaire</a></li>
            		<li><a href="">Guide du Professionnel</a></li>
            		<li><a href="">F.A.Q.</a></li>
            	</ul>
            </li>
            <li><a class="open-in-modal" href="<?= $this->url(array('controller' => 'registration'), null, true) ?>">S’inscrire</a></li>
            <li><a class="open-in-modal" href="<?= $this->url(array('controller' => 'login'), null, true) ?>">Se connecter</a></li>            
            <? endif; ?>
        </ul>
    </div>
</header>
<div class="promo-page">
	<div class="inner">
		<div class="promo">
			<div class="logo"></div>
			<div class="text">l’immo<br>repensé</div>
		</div>
		<a href="#" id="promo-video" class="btn btn-small btn-red">Voir la vidéo</a>
		<div id="promo-search" class="grid grid-dark">
			<div class="promo-search-left">
				<h2>Chercher une location</h2>
				<form action="">
					<fieldset class="promo-search-location">
						<label>Localisation</label>
						<input type="text" placeholder="Où désirez-vous louer?">
						<a href="#location" class="btn btn-small btn-dark icon-location"></a>
					</fieldset>
					<fieldset class="promo-search-budget-surface">
						<div>
							<label>Budget maximum</label>
							<input type="text" placeholder="Budget max. (en €)">
						</div>
						<div>
							<label>Surface minimum</label>
							<input type="text" placeholder="Surface min. (en m²)">
						</div>
					</fieldset>
					<fieldset>
						<a href="#" id="add-criteria" class="btn btn-small btn-dark">Plus de critères</a>
					</fieldset>
				</form>
			</div>
			<div class="promo-search-right">
				<div class="promo-search-buttons">
					<a href="#" class="btn btn-blue">Recherche rapide</a>
					<span class="separator">— ou —</span>
					<div class="cf promo-search-buttons-group">
						<div class="btn btn-red icon-metro" onclick="document.location.href = '<?= $this->url(array('controller' => 'search', 'action' => 'metro'), null, true) ?>';">par métro</div>
						<div class="btn btn-red icon-dessin" onclick="document.location.href = '<?= $this->url(array('controller' => 'search', 'action' => 'draw'), null, true) ?>';">par dessin</div>
						<div class="btn btn-red icon-carte-red" onclick="document.location.href = '<?= $this->url(array('controller' => 'search', 'action' => 'map'), null, true) ?>';">par carte</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>