<header>
		<div class="inner">
			<a href="#" class="home-logo">Ommi</a>
			<ul id="header-nav">
				<li class="left"><a href="#">Guide du Locataire</a></li>
				<li><a href="#" class="btn btn-red">Nouvelle recherche</a></li>
				<li><a href="#">Bonjour, Prenom</a></li>
				<li><a href="#">Mes candidatures</a></li>
			</ul>
		</div>
</header>
<!--
<div id="header">
    <h1><?= $this->translate('default_module_header') ?></h1>
    <? if ($this->currUser) : ?>
        <div class="welcome">
            <div class="clear"></div>
            <?= $this->translate('hello') ?>, <?= $this->currUser->getFullName() ?>!
            [<a href="<?= $this->url(array('module' => 'default', 'controller' => 'login', 'action' => 'logout', 'model' => 'user'), null, true) ?>"><?= $this->translate('logout') ?></a>]
            <? if (!$this->currUser->is_premium): ?>
                [<a href="<?= $this->url(array('module' => 'user', 'controller' => 'subscription', 'action' => 'index'), null, true) ?>"><?= $this->translate('upgrade_to_premium') ?></a>]
            <? endif ?>
        </div>
        <div class="clear"></div>
    <? endif ?>
</div>
-->
