<header>
    <div class="inner">
        <a href="<?=$this->baseUrl('/'); ?>" class="home-logo">Ommi</a>

        <ul id="header-nav">
            <li class="left"><a href="#">Comment ça marche ?</a></li>
            <li><a href="#" class="btn btn-red">Publier une annonce</a></li>
            <li><a href="#">Se connecter</a></li>
            <li><a href="#">S’inscrire</a></li>
            <li><a href="#">Aide</a></li>
            <!--
            <li class="left"><a href="#">Guide du Locataire</a></li>
            <li><a href="#" class="btn btn-red">Nouvelle recherche</a></li>
            <li><a href="#">Bonjour, Prenom</a></li>
            <li><a href="#">Mes candidatures</a></li>
            -->
        </ul>
    </div>
</header>
<div class="promo-page">
	<div class="inner">
		<div class="promo">
			<div class="logo"></div>
			<div class="text">l’immo<br>repensé</div>
		</div>
		<!--<div class="grid grid-dark">
			<div class="grid-half grid-transparent">
				<h2>Chercher une location</h2>
				<form action="#">
					<fieldset>
						<label>Localosation</label>
						<input type="text" placeholder="Où désirez-vous louer? ">
					</fieldset>
					<fieldset>
						<label>Budget maximum</label>
						<input type="text" placeholder="Budget max. (en €)">
					</fieldset>
					<fieldset>
						<label>Surface minimum</label>
						<input type="text" placeholder="Surface min. (en m²)">
					</fieldset>
					<a href="#" class="btn btn-dark">Plus de critères</a>
				</form>
			</div>
			<div class="grid-half grid-transparent">
				<a href="#" class="btn btn-blue btn-search">Recherche rapide</a>
			</div>
		</div>-->
	</div>
</div>