<header>
	<div class="inner">
		<a href="<?=$this->baseUrl('/'); ?>" class="logo">Ommi</a>
        <ul id="header-nav">
            <? if ($this->currUser) : ?>
            <li class="left"><a href="#">Guide du Locataire</a></li>
            <li><a href="<?= $this->url(array('controller' => 'search', 'action' => 'index'), null, true) ?>" class="btn btn-red">Nouvelle recherche</a></li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="">Bonjour, <?= $this->currUser->first_name ?> <?= $this->currUser->last_name ?> <i class="caret"></i></a>
                <ul class="dropdown-menu">
                    <li><a href="">Résumé</a></li>
                    <li><a href="">Mon dossier</a></li>
                    <li><a href="">Mes candidatures</a></li>
                    <li><a href="">Mes recherches</a></li>
                    <li><a href="">Mes services</a></li>
                    <li><a href="">Mon compte</a></li>
                    <li><a href="">Mes recherches</a></li>
                    <li><a href="<?= $this->url(array('controller' => 'logout'), null, true) ?>" class="red">Se déconnecter</a></li>
                </ul>
            </li>
            <li><a href="#">Mes candidatures</a></li>           
            <? else : ?>            
            <li class="left"><a href="#">Comment ça marche ?</a></li>
            <li><a href="<?= $this->url(array('module' => 'user', 'controller' => 'property', 'action' => 'new-add'), null, true) ?>" class="btn btn-red">Publier une annonce</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Aide <i class="caret"></i></a>
                <ul class="dropdown-menu">
                    <li><a href="">Guide du Locataire</a></li>
                    <li><a href="">Guide du Propriétaire</a></li>
                    <li><a href="">Guide du Professionnel</a></li>
                    <li><a href="">F.A.Q.</a></li>
                </ul>
            </li>
            <li><a class="open-in-modal" href="<?= $this->url(array('controller' => 'registration'), null, true) ?>">S’inscrire</a></li>
            <li><a class="open-in-modal" href="<?= $this->url(array('controller' => 'login'), null, true) ?>">Se connecter</a></li>
            <? endif; ?>
        </ul>
	</div>
</header>
<!--
<div id="header">
    <h1><?= $this->translate('default_module_header') ?></h1>
    <? if ($this->currUser) : ?>
        <div class="welcome">
            <div class="clear"></div>
            <?= $this->translate('hello') ?>, <?= $this->currUser->getFullName() ?>!
            [<a href="<?= $this->url(array('module' => 'default', 'controller' => 'login', 'action' => 'logout', 'model' => 'user'), null, true) ?>"><?= $this->translate('logout') ?></a>]
            <? if (!$this->currUser->is_premium): ?>
                [<a href="<?= $this->url(array('module' => 'user', 'controller' => 'subscription', 'action' => 'index'), null, true) ?>"><?= $this->translate('upgrade_to_premium') ?></a>]
            <? endif ?>
        </div>
        <div class="clear"></div>
    <? endif ?>
</div>
-->
