<div class="grid">
    <div class="grid-half grid-transparent">
        <div class="grid-inner">
            <h1 class="blue">Decouveres <br> nos outils <br> de recherche</h1>
            <p>Ommi transforme la façon dont vous louez.
                Il rend service aux propriétaires et aux locataires.
                Ommi vous simplifie l’immobilier.
            </p>
            <a href="<?= $this->url(array('controller' => 'search', 'action' => 'metro'), null, true) ?>" class="btn btn-red btn-annonce">
                <i class="i-group-red icon-metro"></i>
                par métro
            </a>
            <a href="<?= $this->url(array('controller' => 'search', 'action' => 'draw'), null, true) ?>" class="btn btn-red btn-annonce">
                <i class="i-group-red icon-dessin"></i>
                par dessin
            </a>
            <a href="<?= $this->url(array('controller' => 'search', 'action' => 'map'), null, true) ?>" class="btn btn-red btn-annonce">
                <i class="i-group-red icon-carte-red"></i>
                par carte
            </a>
        </div>
    </div>
    <div class="inner-box-carte">
        <img src="/assets/images/carte-annonce.png" alt="">
    </div>
</div>
<div class="grid grid-transparent">
    <div class="grid-half">
        <div class="grid-inner h120">
            <h1 class="gray">Compte Ommium</h1>
            <div class="index-row-six cf">
                <div class="index-row-six-text">
                    Ommi, Ommi+ ou Ommium?
                    Des comptes adaptés à chacun.
                </div>
                <div class="index-row-six-link">
                    <a href="#link">Découvrez nos comptes</a>
                </div>
            </div>
        </div>
    </div>
    <div class="grid-half">
        <div class="grid-inner h120">
            <h1 class="gray">F.A.Q.</h1>
            <div class="index-row-six cf">
                <div class="index-row-six-text">
                    Consultez les questions les plus fréquemment posées.
                </div>
                <div class="index-row-six-link">
                    <a href="#link">Consultez les F.A.Q.</a>
                </div>
            </div>
        </div>
    </div>
</div>
<? if (empty($this->isLoggedIn)) : ?>
<div class="grid">
    <div class="grid-full">
        <h1 class="gray">Je m'nscris, c'est gratuit
            <a data-title="<?= $this->translate('sign_up') ?>" href="<?= $this->url(array('controller' => 'registration'), null, true) ?>" class="right btn btn-blue w200 open-in-modal"><?= $this->translate('create_account') ?></a>
        </h1>
    </div>
</div>
<? endif; ?>