<? if ($this->type == 'text') : ?>
<input type="text" class="<?= $this->name ?>" id="filter_<?= $this->name ?>" name="filter[<?= $this->name ?>]" value="<?= $this->value ?>"/>
<? elseif ($this->type == 'range') : ?>
<div class="range-filter">
    <div>
        <label><?= $this->translator->translate('from') ?>:</label> <input type="text" id="filter_<?= $this->name ?>_from" name="filter[<?= $this->name ?>][from]" value="<?= $this->value['from'] ?>"/>
    </div>
    <div>
        <label><?= $this->translator->translate('to') ?>:</label> <input type="text" id="filter_<?= $this->name ?>_to" name="filter[<?= $this->name ?>][to]" value="<?= $this->value['to'] ?>"/>
    </div>
</div>
<? elseif ($this->type == 'select') : ?>
<select class="<?= $this->name ?>" id="filter_<?= $this->name ?>" name="filter[<?= $this->name ?>]">
    <? if (is_array($this->options)) : ?>
       <? foreach ($this->options as $key => $value) : ?>
            <? $selected = ((string)$this->value === (string) $key) ? 'selected="selected"' : ''; ?>
            <option value="<?= $key ?>" <?= $selected ?>><?= $value ?></option>
       <? endforeach; ?>
    <? endif; ?>
</select>
<? else : ?>
&nbsp;
<? endif; ?>