<div class="grid">
    <? if ($this->filtersEnabled || $this->massActionsEnabled) : ?>
    <form id="grid-action-form" method="post" action="">
        <? if ($this->massActionEnabled) : ?>
            <?= $this->massActions ?>
        <? endif; ?>
        <? if ($this->filtersEnabled) : ?>
        <div class="grid-filter-buttons">
            <input type="submit" class="ui-state-default ui-corner-all" value="<?= $this->translate('set_filter') ?>" name="set_filter" />
            <input type="submit" class="ui-state-default ui-corner-all" value="<?= $this->translate('reset_filter') ?>" name="reset_filter" />
        </div>
        <? endif; ?>
    <? endif; ?>
    <table class="grid-table">
        <?= $this->rows ?>
    </table>
    <? if ($this->paginationEnabled) : ?>
        <?= $this->paginationControl($this->paginator,
                'Sliding',
                '_partials/grid/paginator.phtml',
                array(
                    'perPageOptions' => $this->perPageOptions
        )) ?>
    <? endif ?>
    <? if ($this->filtersEnabled || $this->massActionsEnabled) : ?>
    </form>
    <? endif; ?>
</div>