<div class="grid" id="publier">
    <div class="left">
        <div class="progress">
            <h2 class="gray">Étapes</h2>
            <div class="progress-step" id="step-0"></div>
            <span>4 étapes restantes</span>
        </div>
        <div class="menu">
            <a href="#" class="btn btn-gray">1  Infos personnelles</a>
            <a href="#" class="btn btn-gray">2  Garants</a>
            <a href="#" class="btn btn-gray">3  Vérification</a>
            <a href="#" class="btn btn-gray">4  Pièces de dossier</a>
        </div>
    </div>
    <div class="right">
        <div class="progress-content" id="content-step-0">
            <div class="block-grid grid-inset-white">
                <h2 class="gray">Vous cherchez une location ?</br>Seul, en couple ou en colocation ?</h2>
                <p class="black">Texte a validerTexte a validerTexte a validerTexte a</br> validerTexte a validerTexte a validerTexte a</br> validerTexte a validerTexte a validerTexte a valider</p>
            </div>
            <div class="block-grid grid-light-blue">
                <h2>Informations personnelles</h2>
                <p>Définissez les éléments essentiels de votre annonce.</br>Titre, montant du loyer, etc… tels qu’ils apparaissent aux candidats.
                </p>
                <span>1</span>
            </div>
            <div class="block-grid grid-light-blue">
                <h2>Les garants</h2>
                <p>Décrivez les caractéristiques spécifiques de votre bien.</br>Le tout, en quelques clics.</p>
                <span>2</span>
            </div>
            <div class="block-grid grid-light-blue">
                <h2>Vérification</h2>
                <p>Les bonnes photos attirent les bons candidats.</br>Pensez-y.</p>
                <span>3</span>
            </div>
            <div class="block-grid grid-light-blue">
                <h2>Les pièces justificatives</h2>
                <p>Vous préférez louer à un étudiant ? Un salarié ? Un indépendant ?</br>Donnez vos préférences, vos candidats seront triées en conséquence.
                </p>
                <span>4</span>
            </div>
            <div class="progress-buttons">
                <!--<a href="#" class="btn btn-gray btn-arrow-prev left">Commencer</a>-->
                <a href="/user/my-files/infos/" class="btn btn-medium btn-red btn-arrow-next right">Commencer</a>
            </div>
        </div>
    </div>
</div>