<div class="grid" id="publier">
    <div class="left">
        <div class="progress">
            <h2 class="gray">Étapes</h2>
            <div class="progress-step" id="step-50"></div>
            <span>2 étapes restantes</span>
        </div>
        <div class="menu">
            <a href="#" class="btn btn-gray">1  Infos personnelles</a>
            <a href="#" class="btn btn-gray">2  Garants</a>
            <a href="#" class="btn btn-blue progress-menu-active">3  Vérification</a>
            <a href="#" class="btn btn-gray">4  Pièces de dossier</a>
        </div>
    </div>
    <div class="right">
        <div class="progress-content" id="content-step-2">
            <div class="step-title">
                <h1>Vérification du profil</h1>
                <span>OMMI vous propose de faire vérifier votre profil via les réseaux sociaux afin de rassurer le</br>propriétaire sur le sérieux de votre candidature.</span>
                <span class="blue">Soyez rassuré, OMMI ne consulte pas vos comptes et vos relations.</br>Nous respectons votre vie privée est préservée.</span>
            </div>

            <div class="block-grid grid-inset">
                <fieldset>
                    <label>Vérification avec Facebook <em class="blue">(conseillé)</em></label>
                    <a href="#" class="btn btn-red btn-medium btn-facebook-red w270">Me connecter à Facebook</a>
                </fieldset>
                <fieldset>
                    <label>Vérification avec LinkedIn <em class="blue">(conseillé)</em></label>
                    <a href="#" class="btn btn-red btn-medium btn-linkedin-red w270">Me connecter à LinkedIn</a>
                    <p class="description">
                        Les vérifications aident les propriétaires à prendre des décisions sûres concernant les</br>candidats qu'ils vont rencontrer. Cela assure une relation de confiance.
                    </p>
                </fieldset>

            </div>

            <div class="progress-buttons">
                <a href="/user/my-files/garants/" class="btn btn-medium btn-gray btn-arrow-prev left">Étape précédente</a>
                <a href="/user/my-files/documents/" class="btn btn-medium btn-blue btn-arrow-next right">Enregistrer et continuer</a>
            </div>
        </div>
    </div>
</div>