<div class="tab-services tab-sommaire">
    <?= $this->partial('resident-services/_partials/navigation.phtml') ?>
    <div class="box-right box-modeles">
        <h2 class="gray">Modèles de courriers</h2>
        <div class="inner-box">
            <p>
                <span class="blue-dark">Vous cherchez les mots pour le dire ?</span><br>
                Pour vous simplifier la vie, nous mettons à votre disposition nos
                modèles de lettres type. <br> Pas besoin de chercher plus loin :
                Vous n’avez plus qu’à remplir les champs qui vous <br> concernent.
            </p>
            <div class="box-gray">
                <p>Au moment de la signature</p>
                <div class="box-button">
                    <a href="#" class="btn btn-blue">L’état des lieux</a>
                    <a href="#" class="btn btn-red btn-load"></a>
                </div>
                <div class="box-button">
                    <a href="#" class="btn btn-blue">Acte de Cautionnement simple</a>
                    <a href="#" class="btn btn-red btn-load"></a>
                </div>

            </div>
            <div class="box-gray">
                <p>Pendant la location</p>
                <div class="box-button">
                    <a href="#" class="btn btn-blue">Contestation de l'augmentation du loyer</a>
                    <a href="#" class="btn btn-red btn-load"></a>
                </div>
                <div class="box-button">
                    <a href="#" class="btn btn-blue">
                        Demande de remplacement ou reparation de materiel
                    </a>
                    <a href="#" class="btn btn-red btn-load"></a>
                </div>
                <div class="box-button">
                    <a href="#" class="btn btn-blue">
                        Mise en demeure pour non prise en charge de travaux
                    </a>
                    <a href="#" class="btn btn-red btn-load"></a>
                </div>
                <div class="box-button">
                    <a href="#" class="btn btn-blue">Demande du  decompte des charges</a>
                    <a href="#" class="btn btn-red btn-load"></a>
                </div>
            </div>
            <div class="box-gray">
                <p>Fin du bail</p>
                <div class="box-button">
                    <a href="#" class="btn btn-blue">Conge</a>
                    <a href="#" class="btn btn-red btn-load"></a>
                </div>
                <div class="box-button">
                    <a href="#" class="btn btn-blue">
                        Conge pour cause de mutation ou perte d'emploi
                    </a>
                    <a href="#" class="btn btn-red btn-load"></a>
                </div>
                <div class="box-button">
                    <a href="#" class="btn btn-blue big-txt">
                        Demande de justificatifs concernant la retention sur le depot de garantie
                    </a>
                    <a href="#" class="btn btn-red btn-load"></a>
                </div>
                <div class="box-button">
                    <a href="#" class="btn btn-blue">
                        Mise en dementure pour reprise du logement pour cause d'habitation
                    </a>
                    <a href="#" class="btn btn-red btn-load"></a>
                </div>
                <div class="box-button">
                    <a href="#" class="btn btn-blue">
                        Mise en dementure pour visant la restitution du depot de garantie
                    </a>
                    <a href="#" class="btn btn-red btn-load"></a>
                </div>
                <div class="box-button">
                    <a href="#" class="btn btn-blue">
                        Resiliation du condrat d'assurance
                    </a>
                    <a href="#" class="btn btn-red btn-load"></a>
                </div>
            </div>

        </div>
    </div>
</div>