<div class="tab-services tab-sommaire">
    <?= $this->partial('resident-services/_partials/navigation.phtml') ?>
    <div class="box-right box-lieux">
        <h2 class="gray">État des lieux</h2>
        <div class="inner-box">
            <p>
                <span class="blue-dark">OMMI a pensé à tout ! </span><br>
                Pour vous simplifier la vie, nous mettons à votre disposition
                notre modèle d’état des lieux.<br> Pas besoin de chercher plus loin :
                Vous n’avez plus qu’à remplir les champs qui vous<br> concernent.
            </p>
            <div class="box-gray">
                <p>Modèle d’état des lieux à télécharger</p>
                <a href="#" class="btn btn-blue">État des lieux</a>
                <a href="#" class="btn btn-red btn-load"></a>
            </div>

        </div>
    </div>
</div>