<?
    $this->headLink()->headLink(array(
        'rel'   => 'favicon',
		'href'  => '/favicon.ico',
		'type'  => 'image/x-icon'
    ));

    $this->headLink()->appendStylesheet('/css/ui/jquery-ui-1.8.14.css');
    $this->headLink()->appendStylesheet('/css/admin/styles.css');

    $this->headScript()->appendFile('/js/admin/common.js');

    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=' . $this->getEncoding());

    $this->headMeta()->appendHttpEquiv('Content-Language', 'en');

    $sfMenu = $this->sfMenu();

    $ajaxLoader = $this->ajaxLoader();

    $this->confirmation();
?>
<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US" lang="en-US">
<head>
    <?= $this->headMeta() ?>
    <?= $this->headTitle('Admin area')->setSeparator(' - ') ?>
    <?= $this->headScript() ?>
    <?= $this->headLink() ?>
    <?= $this->jQuery() ?>    
</head>
    <body>
        <div id="wrapper">
            <?= $this->partial('_partials/header.phtml', $this->getVars()) ?>
            <? if ($this->isLoggedIn) : ?>
            <div id="header-menu">
                <?= $sfMenu ?>
            </div>
            <? endif ?>
            <div id="content">
                <?= $this->messenger() ?>
                <?= $this->layout()->content ?>
            </div>
            <?= $this->partial('_partials/footer.phtml', $this->getVars()) ?>
            <?= $ajaxLoader ?>
        </div>
    </body>
</html>