<p>
    <?= $this->translate('hello', array($this->first_name . ' ' . $this->last_name)) ?>
</p>
<p>
    <?= $this->restore_password_key ?>
    <a href="<?= $this->serverUrl($this->url(array(
        'module'     => 'admin',
        'controller' => 'forgot-password',
        'action'     => 'reset',
        'key'        => $this->restore_password_key
        ), null, true)) ?>"><?= $this->translate('click_here_to_reset_password') ?></a>
</p>
