<?php

/**
 * Model_Base_Message
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $message_id
 * @property integer $queue_id
 * @property string $handle
 * @property text $body
 * @property string $md5
 * @property decimal $timeout
 * @property integer $created
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Message extends Ext_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('message');
        $this->hasColumn('message_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('queue_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('handle', 'string', 32, array(
             'type' => 'string',
             'unique' => true,
             'length' => '32',
             ));
        $this->hasColumn('body', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('md5', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('timeout', 'decimal', 14, array(
             'type' => 'decimal',
             'scale' => 4,
             'length' => '14',
             ));
        $this->hasColumn('created', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));


        $this->index('message_queueid', array(
             'fields' => 
             array(
              0 => 'queue_id',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}