<?php

/**
 * Model_Base_MetroStation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $metro_line_id
 * @property string $name
 * @property integer $pixel_x
 * @property integer $pixel_y
 * @property integer $sort_position
 * @property Model_MetroLine $MetroLine
 * @property Doctrine_Collection $PropertyXMetroStation
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_MetroStation extends Ext_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('metro_station');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('metro_line_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('pixel_x', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('pixel_y', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('sort_position', 'integer', 1, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_MetroLine as MetroLine', array(
             'local' => 'metro_line_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('Model_PropertyXMetroStation as PropertyXMetroStation', array(
             'local' => 'id',
             'foreign' => 'metro_station_id'));

        $geographical0 = new Doctrine_Template_Geographical(array(
             'latitude' => 
             array(
              'options' => 
              array(
              'scale' => 10,
              ),
             ),
             'longitude' => 
             array(
              'options' => 
              array(
              'scale' => 10,
              ),
             ),
             ));
        $this->actAs($geographical0);
    }
}