<?php

/**
 * Model_Base_MetroLine
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $color
 * @property Doctrine_Collection $MetroStation
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_MetroLine extends Ext_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('metro_line');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('color', 'string', 6, array(
             'type' => 'string',
             'length' => '6',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_MetroStation as MetroStation', array(
             'local' => 'id',
             'foreign' => 'metro_line_id'));
    }
}