<?php

/**
 * Model_Base_PropertyXMetroStation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $metro_station_id
 * @property integer $property_id
 * @property double $distance
 * @property Model_MetroStation $MetroStation
 * @property Model_Property $Property
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_PropertyXMetroStation extends Ext_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('property_x_metro_station');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('metro_station_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('property_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('distance', 'double', 18, array(
             'type' => 'double',
             'length' => '18',
             'scale' => ' 3',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_MetroStation as MetroStation', array(
             'local' => 'metro_station_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Model_Property as Property', array(
             'local' => 'property_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}