<?php

/**
 * Model_Base_Queue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $queue_id
 * @property string $queue_name
 * @property integer $timeout
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Queue extends Ext_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('queue');
        $this->hasColumn('queue_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('queue_name', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('timeout', 'integer', 2, array(
             'type' => 'integer',
             'default' => 30,
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}