<?php

/**
 * Model_Base_RegionBlock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Model_RegionDistrict $RegionDistrict
 * @property Doctrine_Collection $Property
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_RegionBlock extends Model_Region
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_RegionDistrict as RegionDistrict', array(
             'local' => 'region_district_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('Model_Property as Property', array(
             'local' => 'id',
             'foreign' => 'region_block_id'));
    }
}