<?php

/**
 * Model_Base_RegionDistrict
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Model_RegionCity $RegionCity
 * @property Doctrine_Collection $RegionBlock
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_RegionDistrict extends Model_Region
{
    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_RegionCity as RegionCity', array(
             'local' => 'region_city_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('Model_RegionBlock as RegionBlock', array(
             'local' => 'id',
             'foreign' => 'region_district_id'));
    }
}