<?php

/**
 * Model_Base_Search
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property enum $search_type
 * @property boolean $is_temp
 * @property string $name
 * @property text $conditions
 * @property Model_User $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Search extends Ext_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('search');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('search_type', 'enum', 10, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'standart',
              1 => 'map',
              2 => 'metro',
              3 => 'draw',
             ),
             'size' => 10,
             'length' => 10,
             ));
        $this->hasColumn('is_temp', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'size' => 255,
             'length' => 255,
             ));
        $this->hasColumn('conditions', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}