<?php

/**
 * Model_Base_Subject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $subject_name
 * @property Doctrine_Collection $PropertyIssueSubject
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_Subject extends Ext_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('subject');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('subject_name', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Model_PropertyIssueSubject as PropertyIssueSubject', array(
             'local' => 'id',
             'foreign' => 'Subject_id'));
    }
}