<?php

/**
 * Model_Base_UserResidentGarant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_resident_id
 * @property decimal $amount
 * @property enum $type
 * @property string $company_name
 * @property Model_UserResident $UserResident
 * @property Doctrine_Collection $UserResidentDocument
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_UserResidentGarant extends Ext_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user_resident_garant');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('user_resident_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('amount', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => '10',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'family',
              1 => 'friend',
              2 => 'employer',
              3 => 'bank',
              4 => 'organization',
             ),
             ));
        $this->hasColumn('company_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_UserResident as UserResident', array(
             'local' => 'user_resident_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('Model_UserResidentDocument as UserResidentDocument', array(
             'local' => 'id',
             'foreign' => 'user_resident_garant_id'));
    }
}