<?php

/**
 * Model_Base_UserResident
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property enum $rent_type
 * @property enum $resident_type
 * @property string $job_title
 * @property enum $employee_type
 * @property decimal $monthly_income
 * @property decimal $monthly_income_guaranteed
 * @property boolean $is_primary
 * @property Model_User $User
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_UserResident extends Ext_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user_resident');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('rent_type', 'enum', 15, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'only',
              1 => 'in_couple',
              2 => 'in_roommate',
             ),
             'size' => 15,
             'length' => 15,
             ));
        $this->hasColumn('resident_type', 'enum', 15, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'student',
              1 => 'employee',
              2 => 'independent',
              3 => 'other',
             ),
             'size' => 15,
             'length' => 15,
             ));
        $this->hasColumn('job_title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('employee_type', 'enum', 3, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'cdi',
              1 => 'csd',
             ),
             'size' => 3,
             'length' => 3,
             ));
        $this->hasColumn('monthly_income', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => '10',
             ));
        $this->hasColumn('monthly_income_guaranteed', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => '10',
             ));
        $this->hasColumn('is_primary', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_User as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'created_at',
             ),
             'updated' => 
             array(
              'name' => 'updated_at',
             ),
             ));
        $this->actAs($timestampable0);
    }
}