<?php

/**
 * Model_Base_UserResidentDocument
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_resident_id
 * @property integer $user_resident_garant_id
 * @property string $file
 * @property string $original_name
 * @property enum $type
 * @property Model_UserResident $UserResident
 * @property Model_UserResidentGarant $UserResidentGarant
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Model_Base_UserResidentDocument extends Ext_Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user_resident_document');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('user_resident_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('user_resident_garant_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('file', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('original_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'passport',
              1 => 'student_id',
              2 => 'inc_certificate',
              3 => 'payslip',
              4 => 'paycheck1',
              5 => 'paycheck2',
              6 => 'paycheck3',
              7 => 'contract',
              8 => 'tax_notice',
              9 => 'tax_notice_guaranteed',
              10 => 'payslip_guaranteed',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Model_UserResident as UserResident', array(
             'local' => 'user_resident_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('Model_UserResidentGarant as UserResidentGarant', array(
             'local' => 'user_resident_garant_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}