<form method="post" action="">
	<!-- Rent type radio -->
	<?php if (!empty($this->availableTypes)) : ?>
		<?php foreach ($this->availableTypes as $type) :
			$selectedType = (!empty($this->selectedType)) ? $this->selectedType : Model_UserResident::RENT_TYPE_SINGLE;
			$checked = ($type === $selectedType) ? 'checked="checked"' : '';?>
			<label>
				<input type="radio" value="<?= $type;?>" id="rent_type-<?= $type;?>" name="rent_type" <?= $checked;?> />
				<?= $type;?>
			</label>
		<?php endforeach;?>
	<?php endif;?>

	<!-- Rent type roommate count select -->
	<div id="roommate-count-wrapper" style="display:none;">
		<label for="roommate-count">Roommates count:</label>
		<select name="roommate-count" id="roommate-count">
			<?php for ($i = 1; $i < $this->roommateMaxCount; $i++):
				$selected = ($i === $this->count - 1) ? 'selected="selected"' : '';?>
				<option value="<?= $i + 1;?>" <?= $selected;?>><?= $i;?></option>
			<?php endfor;?>
		</select>
	</div>
 </form>

<div id="form-wrapper">
	<?= $this->form ?>
</div>
<?php
	$function = '$(function() {
		var formWrapper = $("#form-wrapper"),
			countSelect = $("#roommate-count"),
			roommateType = "' . Model_UserResident::RENT_TYPE_ROOMMATE . '",
			baseUrlForm = "' . $this->url() . '/type/",
			residentTypeSelects = $("select.resident-type"),
			rentType = $("input[name=rent_type]"),
			updateForm = function(url) {
				$.ajax({
					type: "post",
					url: url
				}).done(function(data) {
					formWrapper.empty().append(data);
					residentTypeSelects = $("select.resident-type");
					residentTypeSelects.trigger("change");
				}).fail(function(data) {
					if( console && console.log ) {
						console.log("Something is wrong");
					}
				});
			};

		/* Residents count select handler for roommate rent type */
		countSelect.on("change", function() {
			var url = baseUrlForm + roommateType + "/count/" + countSelect.val();
			updateForm(url);
		});

		/* Rent type change handler */
		rentType.on("click", function() {
			var type = this.value,
				url = baseUrlForm + type;
            $("#rent_type").val(type);
			if (type == roommateType) {
				url += "/count/" + countSelect.val();
			}
			updateForm(url);
		}).on("change", function() {
			var roommate = $("input[name=rent_type][value=roommate]"),
				container = $("#roommate-count-wrapper");
			if( $(roommate).is(":checked") ) {
				container.show();
			} else {
				container.slideUp();
			}
		});

		/* Resident type change handler */
		formWrapper.on("change", "select.resident-type", function() {
			var root = $(this).closest("dl"),

				employeeType = root.find("input:radio"),
				employeeTypeContainer = employeeType.closest("dd"),
				employeeTypeLabelContainer = employeeTypeContainer.prev(),
				hideElemIfNotEmployee = function() {
					employeeTypeLabelContainer.hide();
					employeeTypeContainer.hide();
				},
				showElemIfEmployee = function() {
					employeeTypeLabelContainer.slideDown();
					employeeTypeContainer.slideDown();
				},

				jobTitle = root.find("input.job-title"),
				jobTitleContainer = jobTitle.closest("dd"),
				jobTitleLabelContainer = jobTitleContainer.prev(),
				hideElemIfStudent = function() {
					jobTitleLabelContainer.hide();
					jobTitleContainer.hide();
				},
				showElemIfNotStudent = function() {
					jobTitleLabelContainer.slideDown();
					jobTitleContainer.slideDown();
				};
			if (this.value === "' . Model_UserResident::TYPE_EMPLOYEE . '") {
				showElemIfEmployee();
				showElemIfNotStudent();
			} else if (this.value === "' . Model_UserResident::TYPE_STUDENT . '") {
				hideElemIfNotEmployee();
				hideElemIfStudent();
			} else {
				hideElemIfNotEmployee();
				showElemIfNotStudent();
			}
		});
		rentType.trigger("change");
		residentTypeSelects.trigger("change");
	});';
	$this->jQuery()->addOnLoad($function);
?>
