<div class="inner">
    <div class="grid">
        <div class="how-it-works">
            <h1 class="blue">Comment </br>ça marche ?</h1>
            <p>Ommi transforme la façon dont vous louez</br>et vous simplifie la location.</p>
            <div>
                <div class="left">
                    <a href="#101" class="red">Regarder la vidéo</a>
                    <a href="#102">Découvrir les avantages</a>
                </div>
                <div class="right">
                    <a class="btn btn-blue open-in-modal" href="<?= $this->url(array('controller' => 'registration'), null, true) ?>">Créer un compte</a>
                </div>
            </div>
        </div>
        <div class="video-play-block">
            <span class="red">Voir la vidéo</span>
            <a href="#" class="play-video"></a>
        </div>
    </div>
    <div class="grid grid-transparent">
        <div class="grid-half">
            <div class="grid-inner h220">
                <h1 class="gray">Vous cherchez</br>une <span class="red">location ?</span></h1>
                <p>Découvrez comment utiliser nos outils de recherches et télécharger votre dossier en ligne. Candidatez aux annonces qui vous intéressent et ne visitez plus que des appartements pour lesquels vous avez de vraies chances. Finies les visites inutiles !</p>
                <a href="#link" class="bottom">Guide du Locataire</a>
            </div>
        </div>
        <div class="grid-half">
            <div class="grid-inner h220">
                <h1 class="gray">Vous êtes</br><span class="red">propriétaire ?</span></h1>
                <p>Découvrez comment publier votre annonce, présélectionner vos candidats sur la base de leurs dossiers avant des les rencontrer, organiser vos visites, gérer vos biens et enfin, profitez des avantages Ommi.</p>
                <a href="#link" class="bottom">Guide du Propriétaire</a>
            </div>
        </div>
    </div>
    <div class="grid">
        <div class="grid-full">
            <h1 class="gray">Quels sont les avantages ?</br><span class="blue">L’immo repensé !</span></h1>
            <div class="advantages-blocks cf">
                <div>
                    <div class="advantage-1"></div>
                    <strong>Des outils de recherche innovants</strong>
                    <p>Dessinez au coin d’une carte. Suivez votre ligne de métro favorite. Choisissez votre quartier préféré. Jamais la recherche n’a été aussi naturelle.</p>
                    <a href="#">En savoir plus</a>
                </div>
                <div>
                    <div class="advantage-2"></div>
                    <strong>Un compte complet totalement gratuit</strong>
                    <p>Sans frais d’agence ni commission, avec Ommi chacun trouve ce qu’il cherche et plus encore. Modèles de bail, lettres types, dépanneurs, tout est là pour vous accompagner.</p>
                    <a href="#">En savoir plus</a>
                </div>
                <div>
                    <div class="advantage-3"></div>
                    <strong>Propriétaires, louez en toute tranquilité</strong>
                    <p>Ne vous faites plus inonder d’emails ni d’appels. Fixez vos critères à l’avance et présélectionnez vos candidats sur dossier avant de les rencontrer. Gérez vos rendez-vous. Ommi s’occupe de tout.</p>
                    <a href="#">En savoir plus</a>
                </div>
                <div>
                    <div class="advantage-4"></div>
                    <strong class="red">Votre dossier de candidature en ligne</strong>
                    <p>Locataires, économisez du temps et de l’énergie. Chargez votre dossier une fois pour toutes et envoyez-le autant de fois que vous le voulez.</p>
                    <a href="#">En savoir plus</a>
                </div>
            </div>
        </div>
    </div>
    <div class="grid">
        <div class="grid-full">
            <h1 class="gray">Je m’inscris, c’est gratuit !<a class="right btn btn-blue w200 open-in-modal" href="<?= $this->url(array('controller' => 'registration'), null, true) ?>">Créer un compte</a></h1>
        </div>
    </div>
    <div class="grid">
        <div class="grid-full">
            <h1 class="gray">Espace <span class="red">Pro</span> C’est par là.<a class="right btn btn-red w200 open-in-modal" href="<?= $this->url(array('controller' => 'registration', 'action' => 'pro'), null, true) ?>">Compte Professionnel</a></h1>
        </div>
    </div>
    <div class="grid grid-transparent">
        <div class="grid-half">
            <div class="grid-inner h120">
                <h1 class="gray">Compte Ommium</h1>
                <div class="index-row-six cf">
                    <div class="index-row-six-text">Ommi, Ommi+ ou Ommium? Des comptes adaptés à chacun.</div>
                    <div class="index-row-six-link"><a href="#100">Découvrez nos comptes</a></div>
                </div>
            </div>
        </div>
        <div class="grid-half">
            <div class="grid-inner h120">
                <h1 class="gray">F.A.Q.</h1>
                <div class="index-row-six cf">
                    <div class="index-row-six-text">Consultez les questions les plus fréquemment posées.</div>
                    <div class="index-row-six-link"><a href="#101">Consultez les F.A.Q.</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="publish-block"></div>
<div class="social-links-block cf">
    <div class="inner">
        <span>Suivez-nous sur les réseaux</span>
        <div class="social-links cf">
            <a href="#" class="social-link sl-tw"></a>
            <a href="#" class="social-link sl-fb"></a>
            <a href="#" class="social-link sl-ig"></a>
            <a href="#" class="social-link sl-gp"></a>
            <a href="#" class="social-link sl-in"></a>
        </div>
    </div>
</div>