<h2><?= $this->translate('home_page') ?></h2>
<p>
    <a href="<?= $this->url(array('controller' => 'login'), null, true) ?>"><?= $this->translate('login') ?></a>
</p>
<p>
    <a href="<?= $this->url(array('controller' => 'registration'), null, true) ?>"><?= $this->translate('registration') ?></a>
</p>
<p>
    <a href="<?= $this->url(array('module' => 'user', 'controller' => 'property', 'action' => 'well-rental'), null, true) ?>"><?= $this->translate('post_my_ad') ?></a>
</p>
