<div id="publier">
    <?= $this->partial('owner-services/_partials/navigation.phtml') ?>
    <div class="right">
        <div class="progress-content">
            <div class="step-title">
                <h1>Modèles de courriers</h1>
                <span class="blue">Vous cherchez les mots pour le dire ? </span>
                <span>Pour vous simplifier la vie, nous mettons à votre disposition nos modèles de lettres type.<br>Pas besoin de chercher plus loin : Vous n’avez plus qu’à remplir les champs qui vous<br>concernent. </span>
            </div>
            <div class="block-grid grid-set-gray">
                <fieldset>
                    <label>Au moment de la signature</label>
                    <div class="block-file">
                        <a id="file" class="btn btn-blue btn-file" href="#">L’état des lieux</a>
                        <a id="file-download" class="btn btn-red btn-download" href="#">&nbsp;</a>
                    </div>
                    <div class="block-file">
                        <a id="file" class="btn btn-blue btn-file" href="#">Souscription par le locataire de l’assurance habitation</a>
                        <a id="file-download" class="btn btn-red btn-download" href="#">&nbsp;</a>
                    </div>
                    <div class="block-file">
                        <a id="file" class="btn btn-blue btn-file" href="#">Acte de Cautionnement simple</a>
                        <a id="file-download" class="btn btn-red btn-download" href="#">&nbsp;</a>
                    </div>
                </fieldset>
            </div>

            <div class="block-grid grid-set-gray">
                <fieldset>
                    <label>Pendant la location</label>
                    <div class="block-file">
                        <a id="file" class="btn btn-blue btn-file" href="#">Révision du loyer</a>
                        <a id="file-download" class="btn btn-red btn-download" href="#">&nbsp;</a>
                    </div>
                    <div class="block-file">
                        <a id="file" class="btn btn-blue btn-file" href="#">Mise en demeure pour cause de trouble de la jouissance</a>
                        <a id="file-download" class="btn btn-red btn-download" href="#">&nbsp;</a>
                    </div>
                    <div class="block-file">
                        <a id="file" class="btn btn-blue btn-file" href="#">Mise en demeure pour cause de non paiement du loyer</a>
                        <a id="file-download" class="btn btn-red btn-download" href="#">&nbsp;</a>
                    </div>
                    <div class="block-file">
                        <a id="file" class="btn btn-blue btn-file" href="#">Réparation à la charge du locataire</a>
                        <a id="file-download" class="btn btn-red btn-download" href="#">&nbsp;</a>
                    </div>
                </fieldset>
            </div>

            <div class="block-grid grid-set-gray">
                <fieldset>
                    <label>Fin du bail</label>
                    <div class="block-file">
                        <a id="file" class="btn btn-blue btn-file" href="#">Augmentation du loyer à la suite du renouvellement du bail</a>
                        <a id="file-download" class="btn btn-red btn-download" href="#">&nbsp;</a>
                    </div>
                    <div class="block-file">
                        <a id="file" class="btn btn-blue btn-file" href="#">Mise en congé pour vente du bien en location</a>
                        <a id="file-download" class="btn btn-red btn-download" href="#">&nbsp;</a>
                    </div>
                    <div class="block-file">
                        <a id="file" class="btn btn-blue btn-file" href="#">Rétention sur le dépôt de garantie pour cause de dégradations</a>
                        <a id="file-download" class="btn btn-red btn-download" href="#">&nbsp;</a>
                    </div>
                    <div class="block-file">
                        <a id="file" class="btn btn-blue btn-file" href="#">Mise en demeure pour reprise du logement pour cause d’habitation</a>
                        <a id="file-download" class="btn btn-red btn-download" href="#">&nbsp;</a>
                    </div>
                </fieldset>
            </div>

        </div>
    </div>		
</div>