<div id="publier">
    <?= $this->partial('owner-services/_partials/navigation.phtml') ?>
    <div class="right">
        <div class="progress-content">
            <div class="step-title">
                <h1>Modèles de contrats</h1>
                <span class="blue">OMMI a pensé à tout !</span>
                <span>Pour vous simplifier la vie, nous mettons à votre disposition nos modèles de contrat. Pas<br>besoin de chercher plus loin : Vous n’avez plus qu’à remplir les champs qui vous<br>concernent.</span>
            </div>
            <div class="block-grid grid-set-gray">
                <fieldset>
                    <label>Modèles de contrat à télécharger</label>
                    <div class="block-file">
                        <a id="file" class="btn btn-blue btn-file" href="#">Contrat de bail - Meublé</a>
                        <a id="file-download" class="btn btn-red btn-download" href="#">&nbsp;</a>
                        <span>Pour vos logements meublés.</span>
                    </div>
                    <div class="block-file">
                        <a id="file" class="btn btn-blue btn-file" href="#">Contrat de bail - Vide</a>
                        <a id="file-download" class="btn btn-red btn-download" href="#">&nbsp;</a>
                        <span>Pour vos logements vides.</span>
                    </div>
                </fieldset>
            </div>

            <div class="block-grid grid-set-gray">
                <fieldset>
                    <label>Modèles de contrat à télécharger</label>
                    <div class="block-file">
                        <a id="file" class="btn btn-blue btn-file" href="#">État des lieux</a>
                        <a id="file-download" class="btn btn-red btn-download" href="#">&nbsp;</a>
                    </div>
                </fieldset>
            </div>

        </div>
    </div>
</div>