<?
    $this->headLink()->headLink(array(
        'rel'   => 'favicon',
		'href'  => '/favicon.ico',
		'type'  => 'image/x-icon'
    ));

    $this->headLink()->appendStylesheet('/assets/css/style.css');
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=' . $this->getEncoding());
    $this->headScript()->appendFile('/js/common.js');
    $this->headScript()->appendFile('/js/jquery.form.js');
    $this->headScript()->appendFile('/assets/js/jquery.the-modal.js');
    $this->headMeta()->appendHttpEquiv('Content-Language', 'en')
?>
<?= $this->doctype() ?>
<html>
<head>
    <meta charset="UTF-8">
    <?= $this->headMeta() ?>
    <?= $this->headTitle('Frontend')->setSeparator(' - ') ?>
    <?= $this->headLink() ?>    
    <?= $this->jQuery() ?>
    <?= $this->headScript() ?>
</head>
    <body <?php echo (!empty($this->homeHeader) ? 'class="home"' : ''); ?>>
        <div id="modal" style="display: none;">
            <div class="modal-title-container">
                <div class="modal-title">Demo title</div>
                <div class="modal-close"></div>
            </div>
            <div class="modal-content-container"></div>
        </div>
        <?= $this->partial('_partials/header' . (!empty($this->homeHeader) ? '-home' : '') . '.phtml', $this->getVars()) ?>
        <main>
            <?= $this->messenger() ?>
            <?= $this->layout()->content ?>
        </main>
        <?= $this->partial('_partials/footer.phtml', $this->getVars()) ?>        
    </body>
</html>