<?
    $this->headLink()->headLink(array(
        'rel'   => 'favicon',
		'href'  => '/favicon.ico',
		'type'  => 'image/x-icon'
    ));

    //$this->headLink()->appendStylesheet('/css/styles.css');
    $this->headLink()->appendStylesheet('/assets/css/style.css');
    $this->headLink()->appendStylesheet('/css/ui/jquery-ui-1.10.3.css');
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=' . $this->getEncoding());

    $this->headMeta()->appendHttpEquiv('Content-Language', 'en')
?>
<?= $this->doctype() ?>
<html>
<head>
    <meta charset="UTF-8">
    <?= $this->headMeta() ?>
    <?= $this->headTitle('Frontend')->setSeparator(' - ') ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
</head>
    <body>
        <?= $this->partial('_partials/header' . (!empty($this->homeHeader) ? '-home' : '') . '.phtml', $this->getVars()) ?>
        <main>
            <div class="inner">
                <div class="grid">
                    <div class="grid-full">
                        1
                    </div>
                </div>
                <div class="grid grid-transparent">
                    <div class="grid-half">
                        <div class="grid-inner h220">
                            <h1 class="gray">Vous cherchez</br>une <span class="red">location ?</span></h1>
                            <p>Découvrez comment utiliser nos outils de recherches et télécharger votre dossier en ligne. Candidatez aux annonces qui vous intéressent et ne visitez plus que des appartements pour lesquels vous avez de vraies chances. Finies les visites inutiles !</p>
                            <a href="#link" class="bottom">Guide du Locataire</a>
                        </div>
                    </div>
                    <div class="grid-half">
                        <div class="grid-inner h220">
                            <h1 class="gray">Vous êtes</br><span class="red">propriétaire ?</span></h1>
                            <p>Découvrez comment publier votre annonce, présélectionner vos candidats sur la base de leurs dossiers avant des les rencontrer, organiser vos visites, gérer vos biens et enfin, profitez des avantages Ommi.</p>
                            <a href="#link" class="bottom">Guide du Propriétaire</a>
                        </div>
                    </div>
                </div>
                <div class="grid">
                    <div class="grid-full">
                        <h1 class="gray">Quels sont les avantages ?</br><span class="blue">L’immo repensé !</span></h1>
                    </div>
                </div>
                <div class="grid">
                    <div class="grid-full">
                        5
                    </div>
                </div>
                <div class="grid"><div class="grid-full">
                    6
                </div></div>
                <div class="grid grid-transparent">
                    <div class="grid-half">7</div>
                    <div class="grid-half">8</div>
                </div>
                <div id="content">
                    <?= $this->messenger() ?>
                    <?= $this->layout()->content ?>
                </div>
                <?= $this->partial('_partials/footer.phtml', $this->getVars()) ?>
                <div id="ajax-loader">
                    <div class="loading-message"><?= $this->translate('loading') ?></div>
                </div>
            </div>
        </main>
        <?= $this->getPluginLoader('helper')->isLoaded('JQuery') ? $this->jQuery() : '' ?>
    </body>
</html>