<?
    $this->headLink()->headLink(array(
        'rel'   => 'favicon',
		'href'  => '/favicon.ico',
		'type'  => 'image/x-icon'
    ));

    //$this->headLink()->appendStylesheet('/css/styles.css');
    $this->headLink()->appendStylesheet('/assets/css/style.css');
    $this->headLink()->appendStylesheet('/css/ui/jquery-ui-1.10.3.css');
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=' . $this->getEncoding());

    $this->headScript()->appendFile('/js/jquery.form.js');
    $this->headScript()->appendFile('/js/common.js');
    $this->headMeta()->appendHttpEquiv('Content-Language', 'en')
?>
<?= $this->doctype() ?>
<html>
<head>
    <meta charset="UTF-8">
    <?= $this->headMeta() ?>
    <?= $this->headTitle('Frontend')->setSeparator(' - ') ?>
    <?= $this->headLink() ?>    
    <?= $this->jQuery() ?>
    <?= $this->headScript() ?>
</head>
    <body>
        <?= $this->partial('_partials/header' . (!empty($this->homeHeader) ? '-home' : '') . '.phtml', $this->getVars()) ?>
        <main>
            <?= $this->messenger() ?>
            <?= $this->layout()->content ?>
            <div id="ajax-loader">
                <div class="loading-message"><?= $this->translate('loading') ?></div>
             </div>
        </main>
        <?= $this->partial('_partials/footer.phtml', $this->getVars()) ?>        
        <div id="modal-dialog">
            <div id="modal-dialog-content"></div>
        </div>
    </body>
</html>