
<!-- POPUP BASE HTML don't copy this code! -->
<div class="themodal-overlay">
	<div id="modal" style="width: 535px">
		<div class="modal-title-container">
			<div class="modal-title">Ajouter à mes favoris</div>
			<div class="modal-close"></div>
		</div>
	 	<div class="modal-content-container">
<!-- POPUP BASE HTML END -->


			<div class="favoris-popup-html">
				<p>OMMI memorise pour vous les annonces qui vous interessent.<br>
				Retrouves vos annonces favorites dans vorte espace <br>
				"Mes Recherches"</p>
				<p class="blue">Ce message n'apparaitra plus a l'avenir</p>
				<a href="#" class="btn btn-blue">Fermer</a>
			</div>


<!-- POPUP BASE HTML don't copy this code! -->
		</div>
	</div>
</div>
<!-- POPUP BASE HTML END -->
