
<!-- POPUP BASE HTML don't copy this code! -->
<div class="themodal-overlay">
	<div id="modal">
		<div class="modal-title-container">
			<div class="modal-title">Candidater</div>
			<div class="modal-close"></div>
		</div>
	 	<div class="modal-content-container">
<!-- POPUP BASE HTML END -->


			<div class="carte-popup1-html">
				<p>Vous candidatez Tres bon choix!<br>
					<span class="blue">Vauillez selectionner l'une des dates de visite proposees<br>
					par le proprietare.</span>
				</p>
				<div class="box-choice-btn">
					<ul>
						<li><a href="#">Mercredi 23 juillet 2013</a></li>
						<li><a href="#">Jeudi 24 juillet 2013</a></li>
						<li><a href="#">Lundi 28 juillet 2013</a></li>
					</ul>
				</div>
				<a href="#" class="black btn-annuler">Annuler</a>
			</div>


<!-- POPUP BASE HTML don't copy this code! -->
		</div>
	</div>
</div>
<!-- POPUP BASE HTML END -->
