<div class="title-row">
	<div class="container-text">
		<h1 class="white-txt">Details de l'annonce</h1>
		<a href="#" class="btn btn-gray"><i class="i-group-white icon-share-alt"></i>Retour aux resultats</a>
		<a href="#" class="btn btn-red"><i class="i-group-white icon-heart"></i>Ajouter aux favoris</a>
		<a href="#" class="btn btn-blue"><i class="i-group-white icon-thumbs-up"></i>Partager</a>
		<a href="#" class="btn btn-gray"><i class="i-group-white icon-chevron-left"></i>Precedente</a>
		<a href="#" class="btn btn-gray">Suivante<i class="i-group-white icon-chevron-right"></i></a>
	</div>
</div>
<main>
	<div class="inner">
		<div class="grid">
			<div class="box-text box-appart">
				<h2 class="black-txt">Joli appartement refait a neuf</h2>
				<p class="txt-bold">Appartement
					<span class="slash">|</span>
					39 m<sup>2</sup>
					<span class="slash">|</span>
					2 pieces
				</p>
				<p class="date-txt">Mise en  ligne : 22/07/2013
					<a href="#" class="btn btn-red small-btn">
						<i class="icon-urgent"></i>
						Urgent
					</a>
				</p>
			</div>
			<div class="box-text box-price">
				<div class="loyer">Loyer mensuel</div>
				<div class="price">980 €</div>
				<a href="#" class="btn btn-blue small-btn">
					<i class="i-group-white icon-pro"></i>
					Pro
				</a>
			</div>
			<div class="box-text box-button">
				<a href="#" class="btn btn-blue big-btn"><i class="i-group-white icon-check"></i>Candidater</a>
			</div>
		</div>
		<div class="grid">
			<div class="menu-annonce">
				<ul>
					<li><a href="">Description<i class="i-group-white icon-list"></i></a></li>
					<li><a href="">Photos<i class="i-group-white icon-photo"></i></a></li>
					<li><a href="">Carte<i class="i-group-white icon-carte"></i></a></li>
					<li><a href="" class="active">Visites<i class="i-group-gray icon-calendar"></i></a></li>
				</ul>
				<a href="#" class="btn btn-gray btn-left-flag"><i class="i-group-white icon-flag"></i></a>
			</div>
			<div class="tab-annonce">
				<h2 class="black-txt">Calendrier</h2>
				<p>
					<span class="gray"> Le propriétaire a défini des dates de visites
						pour ce bien (en bleu sur le calendrier).
					</span><br>
					En candidatant, vous serez invité à sélectionner une de ces dates.<br>
					<span class="blue"> Assurez-vous d’être disponible.</span>
				</p>
				<div class="block-calendar">
					<div class="calendar">
						<div class="name-month">
							<h2>
								<a href="#" class="btn btn-gray btn-cal-prev">
									<i class="i-group-gray icon-prev"></i>
								</a>
								Juillet
							</h2>
						</div>
						<div class="inner-cell cell-month">
							<div class="cell">Lun</div>
							<div class="cell">Mar</div>
							<div class="cell">Mer</div>
							<div class="cell">Jeu</div>
							<div class="cell">Ven</div>
							<div class="cell">Sa</div>
							<div class="cell">Dim</div>
						</div>
						<div class="inner-cell">
							<div class="cell cell-gray">1</div>
							<div class="cell cell-gray">2</div>
							<div class="cell cell-gray">3</div>
							<div class="cell cell-gray">4</div>
							<div class="cell cell-gray">5</div>
							<div class="cell cell-gray">6</div>
							<div class="cell cell-gray">7</div>
						</div>
						<div class="inner-cell">
							<div class="cell cell-gray">8</div>
							<div class="cell cell-gray">9</div>
							<div class="cell cell-gray">10</div>
							<div class="cell cell-gray">11</div>
							<div class="cell cell-black">12</div>
							<div class="cell">13</div>
							<div class="cell">14</div>
						</div>
						<div class="inner-cell">
							<div class="cell">15</div>
							<div class="cell">16</div>
							<div class="cell">17</div>
							<div class="cell">18</div>
							<div class="cell">19</div>
							<div class="cell">20</div>
							<div class="cell">21</div>
						</div>
						<div class="inner-cell">
							<div class="cell">22</div>
							<div class="cell cell-blue">23</div>
							<div class="cell cell-blue">24</div>
							<div class="cell">25</div>
							<div class="cell cell-blue">26</div>
							<div class="cell">27</div>
							<div class="cell">28</div>
						</div>
						<div class="inner-cell cell-bottom">
							<div class="cell">29</div>
							<div class="cell">30</div>
							<div class="cell">31</div>
							<div class="cell cell-next-month">1</div>
							<div class="cell cell-next-month">2</div>
							<div class="cell cell-next-month">3</div>
							<div class="cell cell-next-month">4</div>
						</div>
					</div>
					<div class="calendar">
						<div class="name-month">
							<h2>Août
								<a href="#" class="btn btn-gray name-month-next">
									<i class="i-group-gray icon-next"></i>
								</a>
							</h2>
						</div>
						<div class="inner-cell cell-month">
							<div class="cell">Lun</div>
							<div class="cell">Mar</div>
							<div class="cell">Mer</div>
							<div class="cell">Jeu</div>
							<div class="cell">Ven</div>
							<div class="cell">Sa</div>
							<div class="cell">Dim</div>
						</div>
						<div class="inner-cell">
							<div class="cell cell-next-month">29</div>
							<div class="cell cell-next-month">30</div>
							<div class="cell cell-next-month">31</div>
							<div class="cell">1</div>
							<div class="cell">2</div>
							<div class="cell">3</div>
							<div class="cell">4</div>
						</div>
						<div class="inner-cell">
							<div class="cell">5</div>
							<div class="cell">3</div>
							<div class="cell">7</div>
							<div class="cell">8</div>
							<div class="cell">9</div>
							<div class="cell">10</div>
							<div class="cell">11</div>
						</div>
						<div class="inner-cell">
							<div class="cell">12</div>
							<div class="cell">13</div>
							<div class="cell">14</div>
							<div class="cell">15</div>
							<div class="cell">16</div>
							<div class="cell">17</div>
							<div class="cell">18</div>
						</div>
						<div class="inner-cell">
							<div class="cell">19</div>
							<div class="cell">20</div>
							<div class="cell">21</div>
							<div class="cell">22</div>
							<div class="cell">23</div>
							<div class="cell">24</div>
							<div class="cell">25</div>
						</div>
						<div class="inner-cell cell-bottom">
							<div class="cell">26</div>
							<div class="cell">27</div>
							<div class="cell">28</div>
							<div class="cell">29</div>
							<div class="cell">30</div>
							<div class="cell">31</div>
							<div class="cell cell-next-month">1</div>
						</div>
					</div>
				</div>
				<h2 class="black-txt">Visites</h2>
				<div class="block-btn-visites">
					<a href="#" class="btn btn-gray btn-blue-lite w220">Mardi 23 juillet 2013</a>
					<a href="#" class="btn btn-gray btn-blue-lite w220">Mercredi 24 juillet 2013</a>
					<a href="#" class="btn btn-gray btn-blue-lite w220">Vendredi 26 juillet 2013</a>
				</div>
				<div class="block-photo">
					<div class="btn-nav-group">
						<a href="#" class="btn btn-red w220">
							<i class="i-group-white icon-heart"></i>
							Ajouter aux favoris
						</a>
						<a href="#" class="btn btn-blue w220">
							<i class="i-group-white icon-thumbs-up"></i>
							Partager
						</a>
					</div>
				</div>
			</div>
		</div>
		<div class="grid grid-transparent">
			<div class="main-container-box">
				<div class="container-box">
					<div class="grid grid-block-big">
						<div class="triangle-left"></div>
						<div class="triangle-left triangle-second"></div>
						<h2 class="black-txt">Annonces similaires</h2>
						<p>Nous vous proposons ici d’autres annonces susceptibles de vous intéresser</p>
					</div>
				</div>
				<div class="container-box">
					<div class="grid grid-block">
						<div class="box-text info-box">
							<img src="/./assets/images/img-gallery-01.png" class="img-ad">
							<h3 class="title-ad">Appartement calme à Père-Lachaise</h3>
							<div>Appartement <span class="slash">|</span> Meublé<br>
								Paris 11e (75011)<br>
								Disponibilité : immédiate<br>
								Métro : Père-Lachaise
							</div>
						</div>
						<div class="box-text price-box">
							<p class="price-small">1200 €</p>
							<p>54 m²</p>
							<p>2 pièces</p>
						</div>
					</div>
					<div class="grid grid-block">
						<div class="box-text info-box">
							<img src="/./assets/images/img-gallery-02.png" class="img-ad">
							<h3 class="title-ad">Appartement entièrement rénové</h3>
							<div>Appartement <span class="slash">|</span> Meublé<br>
								Paris 11e (75011)<br>
								Disponibilité : 12/09/2013<br>
								Métro : Nation
							</div>
						</div>
						<div class="box-text price-box">
							<p class="price-small">1250 €</p>
							<p>54 m²</p>
							<p>2 pièces</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="grid">
			<div class="grid-half grid-transparent">
				<div class="grid-inner">
					<h1 class="blue">Decouveres <br> nos outils <br> de recherche</h1>
					<p>Ommi transforme la façon dont vous louez.
						Il rend service aux propriétaires et aux locataires.
						Ommi vous simplifie l’immobilier.
					</p>
					<a href="#" class="btn btn-red btn-annonce">
						<i class="i-group-red icon-metro"></i>
						par métro
					</a>
					<a href="#" class="btn btn-red btn-annonce">
						<i class="i-group-red icon-dessin"></i>
						par dessin
					</a>
					<a href="#" class="btn btn-red btn-annonce">
						<i class="i-group-red icon-carte-red"></i>
						par carte
					</a>
				</div>
			</div>
		</div>
		<div class="grid grid-transparent">
			<div class="grid-half">
				<div class="grid-inner h120">
					<h1 class="gray">Compte Ommium</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Ommi, Ommi+ ou Ommium?
							Des comptes adaptés à chacun.
						</div>
						<div class="index-row-six-link">
							<a href="#link">Découvrez nos comptes</a>
						</div>
					</div>
				</div>
			</div>
			<div class="grid-half">
				<div class="grid-inner h120">
					<h1 class="gray">F.A.Q.</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Consultez les questions les plus fréquemment posées.
						</div>
						<div class="index-row-six-link">
							<a href="#link">Consultez les F.A.Q.</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="grid">
			<div class="grid-full">
				<h1 class="gray">Je m'nscris, c'est gratuit
					<a href="#" class="right btn btn-blue w200">Créer un compte</a>
				</h1>
			</div>
		</div>
	</div>
</main>