
<!-- POPUP BASE HTML don't copy this code! -->
<div class="themodal-overlay">
	<div id="modal" style="width: 535px">
		<div class="modal-title-container">
			<div class="modal-title">Candidater</div>
			<div class="modal-close"></div>
		</div>
	 	<div class="modal-content-container">
<!-- POPUP BASE HTML END -->


			<div class="carte-popup1-html">
				<p>
					Vous candidatez Tres bon choix!<br>
					<span class="blue">Vauillez selectionner l'une des dates de visite proposees<br>
					par le proprietare.</span>
				</p>
				<div class="box-choice-btn">
					<ul>
						<li><a href="#" class="active-btn">Mercredi 23 juillet 2013</a></li>
						<li><a href="#">Jeudi 24 juillet 2013</a></li>
						<li><a href="#">Lundi 28 juillet 2013</a></li>
					</ul>
				</div>
				<div class="details-block" style="display: block">
					<p>
						A vous d'indiquer au proprietaire une plage horaire de visite qui vous
						arrange. Pensez large. Si vous etes choisi, le proprietaire vous
						donnera un horaire de visite precis correspondant a vos choix.<br>
						<span class="blue">Vauillez selectionner un horaire minimum et maximum.</span>
					</p>

					<div class="box-select">
						<div class="inner-box-select">
							<label>Horaire minimum</label>
							<div class="select-performed">
								<select name="field" class="pretty">
									<option value="1">08:00</option>
									<option value="2">07:00</option>
									<option value="3">06:00</option>
									<option value="4">05:00</option>
									<option value="5">04:00</option>
								</select>
							</div>
						</div>
						<span>a</span>
						<div class="inner-box-select">
							<label>Horaire maximum</label>
							<div class="select-performed">
								<select name="field" class="pretty">
									<option value="1">08:00</option>
									<option value="2">07:00</option>
									<option value="3">06:00</option>
									<option value="4">05:00</option>
									<option value="5">04:00</option>
								</select>
							</div>
						</div>
					</div>
					<p>Vorte dossier va etre transmis au proprietaire qui va etudier votre
						candidature. Si vous etes selectionne vous recevrez l'adresse
						exacte sur vorte tableau de bord.
					</p>
					<a href="#" class="btn btn-blue">Envoyer mon dossier</a>
					<p class="gray">
						En cliquant "Envoyer mon dossier" vous acceptez que vorte dossier
						de candidature dans tous ses elements soir transmis au proprietaire.
					</p>
				</div>

				<a href="#" class="black btn-annuler">Annuler</a>
			</div>


<!-- POPUP BASE HTML don't copy this code! -->
		</div>
	</div>
</div>
<!-- POPUP BASE HTML END -->


<!---->
<!--<script>-->
<!---->
<!---->
<!---->
<!--	$( function() {-->
<!--		$('.box-choice-btn a').on('click', function(e) {-->
<!--			e.preventDefault();-->
<!--			$(".carte-popup1-html .details-block").slideDown();-->
<!--		});-->
<!---->
<!--	})-->
<!---->
<!--</script>-->