<div class="title-row">
	<div class="conteiner-text">
		<h1 class="white">Details de l'annonce</h1>
		<a href="#" class="btn btn-gray">Retour aux resultats</a>
		<a href="#" class="btn btn-red">Ajouter aux favoris</a>
		<a href="#" class="btn btn-blue">Partager</a>
		<a href="#" class="btn btn-gray">Precedente</a>
		<a href="#" class="btn btn-gray">Suivante</a>
	</div>
</div>
<main>
	<div class="inner">
		<div class="grid">
			<div class="box-text">
				<h2 class="black-txt">Joli appartement refait a neuf</h2>
				<p>Appartement <span class="slash">|</span>39 m2<span class="slash">|</span> 2 pieces</p>
				<p>Mise en  ligne : 22/07/2013
					<a href="#" class="btn btn-red">Urgent</a>
				</p>
			</div>
			<div class="box-text">
				<div class="loyer">Loyer mensuel</div>
				<div class="price">980 </div>
				<a href="#" class="btn btn-blue">Pro</a>
			</div>
			<div class="box-text">
				<a href="#" class="btn btn-blue">Candidater</a>
			</div>
		</div>
	</div>
</main>