<div class="title-row">
	<div class="conteiner-text">
		<h1 class="white-txt">Details de l'annonce</h1>
		<a href="#" class="btn btn-gray">Retour aux resultats</a>
		<a href="#" class="btn btn-red">Ajouter aux favoris</a>
		<a href="#" class="btn btn-blue">Partager</a>
		<a href="#" class="btn btn-gray">Precedente</a>
		<a href="#" class="btn btn-gray">Suivante</a>
	</div>
</div>
<main>
	<div class="inner">
		<div class="grid">
			<div class="box-text box-appart">
				<h2 class="black-txt">Joli appartement refait a neuf</h2>
				<p class="txt-bold">Appartement
					<span class="slash">|</span>
					39 m<sup>2</sup>
					<span class="slash">|</span>
					2 pieces
				</p>
				<p class="date-txt">Mise en  ligne : 22/07/2013
					<a href="#" class="btn btn-red small-btn">Urgent</a>
				</p>
			</div>
			<div class="box-text box-price">
				<div class="loyer">Loyer mensuel</div>
				<div class="price">980 €</div>
				<a href="#" class="btn btn-blue small-btn">Pro</a>
			</div>
			<div class="box-text box-button">
				<a href="#" class="btn btn-blue big-btn">Candidater</a>
			</div>
		</div>
		<div class="grid">Hello</div>
		<div class="main-conteiner-box">
			<div class="conteiner-box">
				<div class="grid grid-block-big">Hello</div>
			</div>
			<div class="conteiner-box">
				<div class="grid grid-block">Hello</div>
				<div class="grid grid-block">Hello</div>
			</div>
		</div>
		<div class="grid">
			<div class="grid-half grid-transparent">
				<div class="grid-inner h220">
					<h1 class="blue">Decouveres <br> nos outils <br> de recherche</h1>
					<p>Ommi transforme la façon dont vous louez.
						Il rend service aux propriétaires et aux locataires.
						Ommi vous simplifie l’immobilier.
					</p>
					<a href="#" class="btn btn-red"> par métro</a>
					<a href="#" class="btn btn-red">par dessin</a>
					<a href="#" class="btn btn-red">par carte</a>
				</div>
			</div>
		</div>
		<div class="grid grid-transparent">
			<div class="grid-half">
				<h1 class="gray">Compte Ommium</h1>
				<div class="inner-box">
					<p>
						Ommi, Ommi+ ou Ommium?
						Des comptes adaptés à chacun.
					</p>
				</div>
				<div class="inner-box">
					<a href="#link">Découvrez nos comptes</a>
				</div>
			</div>
			<div class="grid-half">
				<h1 class="gray">F.A.Q.</h1>
				<div class="inner-box">
					<p>
						Consultez les questions les plus fréquemment posées.
					</p>
				</div>
				<div class="inner-box">
					<a href="#link">Consultez les F.A.Q.</a>
				</div>
			</div>
		</div>
		<div class="grid">
			<div class="grid-full">
				<h1 class="gray">Je m'nscris, c'est gratuit
					<a href="#" class="right btn btn-blue w200">Créer un compte</a>
				</h1>
			</div>
		</div>
	</div>
</main>