<div class="title-row">
	<div class="container-text">
		<h1 class="white-txt">Details de l'annonce</h1>
		<a href="#" class="btn btn-gray">Retour aux resultats</a>
		<a href="#" class="btn btn-red">Ajouter aux favoris</a>
		<a href="#" class="btn btn-blue">Partager</a>
		<a href="#" class="btn btn-gray">Precedente</a>
		<a href="#" class="btn btn-gray">Suivante</a>
	</div>
</div>
<main>
	<div class="inner">
		<div class="grid">
			<div class="box-text box-appart">
				<h2 class="black-txt">Joli appartement refait a neuf</h2>
				<p class="txt-bold">Appartement
					<span class="slash">|</span>
					39 m<sup>2</sup>
					<span class="slash">|</span>
					2 pieces
				</p>
				<p class="date-txt">Mise en  ligne : 22/07/2013
					<a href="#" class="btn btn-red small-btn">Urgent</a>
				</p>
			</div>
			<div class="box-text box-price">
				<div class="loyer">Loyer mensuel</div>
				<div class="price">980 €</div>
				<a href="#" class="btn btn-blue small-btn">Pro</a>
			</div>
			<div class="box-text box-button">
				<a href="#" class="btn btn-blue big-btn">Candidater</a>
			</div>
		</div>
		<div class="grid">
			<div class="menu-annonce">
				<ul>
					<li><a href="" class="active">Description</a></li>
					<li><a href="">Photos</a></li>
					<li><a href="">Carte</a></li>
					<li><a href="">Visites</a></li>
				</ul>
			</div>
			<div class="inset-discription">
				<h2 class="black-txt">Description</h2>
				<div class="table-discription">
					<div class="cellsblock">
						<div class="cellleft">
							<p>Localisation</p>
						</div>
						<div class="cellright">
							<p>75011 - Paris 11e</p>
						</div>
					</div>
					<div class="cellsblock">
						<div class="cellleft">
							<p>Loyer (charges comprises)</p>
						</div>
						<div class="cellright">
							<p>980 € </p>
						</div>
					</div>
					<div class="cellsblock">
						<div class="cellleft">
							<p>Charges</p>
						</div>
						<div class="cellright">
							<p>50 € </p>
						</div>
					</div>
					<div class="cellsblock">
						<div class="cellleft">
							<p>Durée du bail</p>
						</div>
						<div class="cellright">
							<p>Longue durée</p>
						</div>
					</div>
				</div>
				<div class="block-photo">
					<p>hello</p>
					<a href="#" class="btn btn-red">Ajouter aux favoris</a>
					<a href="#" class="btn btn-blue">Partager</a>
				</div>
			</div>
		</div>
		<div class="grid grid-transparent">
			<div class="main-container-box">
				<div class="container-box">
					<div class="grid grid-block-big">
						<div class="triangle-left"></div>
						<h2 class="black-txt">Annonces similaires</h2>
						<p>Nous vous proposons ici d’autres annonces susceptibles de vous intéresser</p>
					</div>
				</div>
				<div class="container-box">
					<div class="grid grid-block">
						<div class="box-text">
	<!--						<img src=""></>-->
							<h3 class="title-ad">Appartement calme à Père-Lachaise</h3>
							<div>Appartement <span class="slash">|</span> Meublé<br>
								Paris 11e (75011)<br>
								Disponibilité : immédiate<br>
								Métro : Père-Lachaise
							</div>
						</div>
						<div class="box-text">
							<p class="price-small">1200 €</p>
							<p>54 m²</p>
							<p>2 pièces</p>
						</div>
					</div>
					<div class="grid grid-block">
					<div class="box-text">
	<!--						<img src=""></>-->
						<h3 class="title-ad">Appartement entièrement rénové</h3>
						<div>Appartement <span class="slash">|</span> Meublé<br>
							Paris 11e (75011)<br>
							Disponibilité : 12/09/2013<br>
							Métro : Nation
						</div>
					</div>
					<div class="box-text">
						<p class="price-small">1200 €</p>
						<p>54 m²</p>
						<p>2 pièces</p>
					</div>
					</div>
				</div>
			</div>
		</div>
		<div class="grid">
			<div class="grid-half grid-transparent">
				<div class="grid-inner">
					<h1 class="blue">Decouveres <br> nos outils <br> de recherche</h1>
					<p>Ommi transforme la façon dont vous louez.
						Il rend service aux propriétaires et aux locataires.
						Ommi vous simplifie l’immobilier.
					</p>
					<a href="#" class="btn btn-red"> par métro</a>
					<a href="#" class="btn btn-red">par dessin</a>
					<a href="#" class="btn btn-red">par carte</a>
				</div>
			</div>
		</div>
		<div class="grid grid-transparent">
			<div class="grid-half">
				<div class="grid-inner">
					<h1 class="gray">Compte Ommium</h1>
					<div class="inner-box">
						<div class="txt-box">
							<p>
								Ommi, Ommi+ ou Ommium?
								Des comptes adaptés à chacun.
							</p>
						</div>
						<div class="txt-box">
							<a href="#link">Découvrez nos comptes</a>
						</div>
					</div>
				</div>
			</div>
			<div class="grid-half">
				<div class="grid-inner">
					<h1 class="gray">F.A.Q.</h1>
					<div class="inner-box">
						<div class="txt-box">
							<p>
								Consultez les questions les plus fréquemment posées.
							</p>
						</div>
						<div class="txt-box">
							<a href="#link">Consultez les F.A.Q.</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="grid">
			<div class="grid-full">
				<h1 class="gray">Je m'nscris, c'est gratuit
					<a href="#" class="right btn btn-blue w200">Créer un compte</a>
				</h1>
			</div>
		</div>
	</div>
</main>