<div class="title-row-tabl">
	<div class="container-text">
		<h1 class="white-txt">Tableau de bord</h1>
	</div>
</div>
<main>
	<div class="inner">
		<div class="grid">
			<div class="menu-annonce menu-tabl">
				<ul>
					<li><a href="">Résumé</a></li>
					<li><a href="">Mon dossier</a></li>
					<li><a href="">Mes recherches</a></li>
					<li><a href="">Mes candidatures</a></li>
					<li><a href="" class="active">Mes services</a></li>
					<li><a href="">Mon compte</a></li>
				</ul>
			</div>
			<div class="tab-services tab-lieux">
				<div class="box-nav-button">
					<a class="btn btn-gray" href="#">Sommaire</a>
					<a class="btn btn-gray icon-affairs active-blue" href="#">
						<i class="icon-right"></i>
						État des lieux
					</a>
					<a class="btn btn-gray icon-mail" href="#">Modèles de courrier</a>
					<a class="btn btn-red icon-repair" href="#">Professionnels</a>
				</div>
				<div class="box-right box-lieux">
					<h2 class="gray">État des lieux</h2>
					<div class="inner-box">
						<p>
							<span class="blue-dark">OMMI a pensé à tout ! </span><br>
							Pour vous simplifier la vie, nous mettons à votre disposition
							notre modèle d’état des lieux.<br> Pas besoin de chercher plus loin :
							Vous n’avez plus qu’à remplir les champs qui vous<br> concernent.
						</p>
						<div class="box-gray">
							<p>Modèle d’état des lieux à télécharger</p>
							<a class="btn btn-blue" href="#">État des lieux</a>
							<a class="btn btn-red btn-load" href="#"></a>
						</div>

					</div>
				</div>



			</div>

		</div>


		<div class="grid">
			<div class="grid-full grid-full-other">
				<div class="grid-inner">
					<h1 class="gray"><span class="blue"> Pourquoi faire certifier</span><br>
						mon dossier par OMMI ?
					</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Partez avec un avantage décisif !<br>
							En faisant certifier votre candidature, rassurez les propriétaires et sortez du lot.
						</div>
						<div class="index-row-six-btn">
							<a href="#" class="right btn btn-blue w200">Certifier ma candidature</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="grid grid-transparent">
			<div class="grid-half grid-half-other">
				<div class="grid-inner">
					<h1 class="gray">Presse de trouver<br> un logement ?</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Découvrez nos comptes sur-mesure et<br>
							choisissez celui qui vous convient le mieux.<br>
							Donnez-vous les moyens de trouver vite.
						</div>
						<div class="index-row-six-link">
							<a href="#">Comples OMMI</a>
						</div>
					</div>
				</div>
			</div>

			<div class="grid-half grid-half-other">
				<div class="grid-inner">
					<h1 class="gray">Au secours !<br> Un depanneur ?</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Pas de panique! Profitez du réseau Ommi<br>
							de dépanneurs de confiance à prix d’ami !
							Programmez en ligne vos rendez-vous.
						</div>
						<div class="index-row-six-link">
							<a href="#">Dépannage</a>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
</main>