<div class="title-row-tabl">
	<div class="container-text box-text-tabl">
		<h1 class="white-txt">Tableau de bord</h1>
	</div>
</div>
	<div class="inner">
		<div class="grid">
			<div class="menu-annonce menu-tabl">
				<ul>
					<li><a href="">Résumé</a></li>
					<li><a href="">Mon dossier</a></li>
					<li><a href="">Mes recherches</a></li>
					<li><a href="">Mes candidatures</a></li>
					<li><a href="" class="active">Mes services</a></li>
					<li><a href="">Mon compte</a></li>
				</ul>
			</div>
			<div class="tab-services tab-professionnels">
				<div class="box-nav-button">
					<a class="btn btn-gray" href="#">Sommaire</a>
					<a class="btn btn-gray icon-affairs" href="#">État des lieux</a>
					<a class="btn btn-gray icon-mail" href="#">Modèles de courrier</a>
					<a class="btn btn-red icon-repair active-red" href="#">
						<i class="icon-right"></i>
						Professionnels
					</a>
				</div>
				<div class="box-right box-professionnels">
					<h2 class="gray">Professionnels</h2>
					<div class="inner-box">
						<p>
							<span class="blue-dark">On peut vous rendre service?</span><br>
							Besoin d’idées ? D’un coup de peinture ? Des travaux à faire ? <br>
							Qu’il arrive un sinistre chez vous ou si vous voulez simplement
							remettre à neuf votre bien, <br> ne cherchez pas plus loin. OMMI travaille
							en collaboration avec des entrepreneurs, <br>des dépanneurs et des
							décorateurs d’intérieur de talent et de confiance.
						</p>
						<div class="box-gray">
							<p>Téléphone <span class="blue-dark italic">(conseillé)</span></p>
							<input type="text"/>
							<p class="blue-dark">
								Soyez rassuré, ces informations ne seront utilisées qu’aux fins<br>
								d’organiser votre rendez-vous avec le professionnel.
							</p>
						</div>
						<div class="box-gray box-reformed">
							<div class="inner-menu-prof">
								<ul>
									<li><a href="#" class="active-tab">Dépanneur</a></li>
									<li><a href="#">Décorateur</a></li>
									<li><a href="#">Entrepreneur</a></li>
								</ul>
							</div>
							<div class="inner-content">
								<p class="gray">
									Une fuite ? Une casse ? Une panne ?<br>
									Pas de panique, les dépanneurs OMMI sont là pour vous aider.
								</p>
								<p>Spécialité <span class="red italic">(obligatoire)</span></p>
								<p>
								<select name="field" class="pretty">
									<option value="">Selectionner une specialite</option>
									<option value="2">Plomberie</option>
									<option value="3">Plomberie</option>
									<option value="4">Plomberie</option>
									<option value="5">Plomberie</option>
								</select>
								</p>

								<p>Calendrier</p>
								<div class="block-calendar">
									<div class="calendar">
										<div class="name-month-calend">
											<h2>
												<a href="#" class="btn btn-gray btn-gray-lite btn-cal-prev">
													<i class="i-group-gray icon-prev"></i>
												</a>
												Juillet
											</h2>
										</div>
										<div class="inner-cell cell-month">
											<div class="cell">Lun</div>
											<div class="cell">Mar</div>
											<div class="cell">Mer</div>
											<div class="cell">Jeu</div>
											<div class="cell">Ven</div>
											<div class="cell">Sa</div>
											<div class="cell">Dim</div>
										</div>
										<div class="inner-cell">
											<div class="cell cell-gray">1</div>
											<div class="cell cell-gray">2</div>
											<div class="cell cell-gray">3</div>
											<div class="cell cell-gray">4</div>
											<div class="cell cell-gray">5</div>
											<div class="cell cell-gray">6</div>
											<div class="cell cell-gray">7</div>
										</div>
										<div class="inner-cell">
											<div class="cell cell-gray">8</div>
											<div class="cell cell-gray">9</div>
											<div class="cell cell-gray">10</div>
											<div class="cell cell-gray">11</div>
											<div class="cell cell-black">12</div>
											<div class="cell">13</div>
											<div class="cell">14</div>
										</div>
										<div class="inner-cell">
											<div class="cell">15</div>
											<div class="cell">16</div>
											<div class="cell">17</div>
											<div class="cell">18</div>
											<div class="cell">19</div>
											<div class="cell">20</div>
											<div class="cell">21</div>
										</div>
										<div class="inner-cell">
											<div class="cell">22</div>
											<div class="cell">23</div>
											<div class="cell">24</div>
											<div class="cell">25</div>
											<div class="cell">26</div>
											<div class="cell">27</div>
											<div class="cell">28</div>
										</div>
										<div class="inner-cell cell-bottom">
											<div class="cell">29</div>
											<div class="cell">30</div>
											<div class="cell">31</div>
											<div class="cell cell-next-month">1</div>
											<div class="cell cell-next-month">2</div>
											<div class="cell cell-next-month">3</div>
											<div class="cell cell-next-month">4</div>
										</div>
									</div>
									<div class="calendar">
										<div class="name-month-calend">
											<h2>Août
												<a href="#" class="btn btn-gray btn-gray-lite name-month-next">
													<i class="i-group-gray icon-next"></i>
												</a>
											</h2>
										</div>
										<div class="inner-cell cell-month">
											<div class="cell">Lun</div>
											<div class="cell">Mar</div>
											<div class="cell">Mer</div>
											<div class="cell">Jeu</div>
											<div class="cell">Ven</div>
											<div class="cell">Sa</div>
											<div class="cell">Dim</div>
										</div>
										<div class="inner-cell">
											<div class="cell cell-next-month">29</div>
											<div class="cell cell-next-month">30</div>
											<div class="cell cell-next-month">31</div>
											<div class="cell">1</div>
											<div class="cell">2</div>
											<div class="cell">3</div>
											<div class="cell">4</div>
										</div>
										<div class="inner-cell">
											<div class="cell">5</div>
											<div class="cell">3</div>
											<div class="cell">7</div>
											<div class="cell">8</div>
											<div class="cell">9</div>
											<div class="cell">10</div>
											<div class="cell">11</div>
										</div>
										<div class="inner-cell">
											<div class="cell">12</div>
											<div class="cell">13</div>
											<div class="cell">14</div>
											<div class="cell">15</div>
											<div class="cell">16</div>
											<div class="cell">17</div>
											<div class="cell">18</div>
										</div>
										<div class="inner-cell">
											<div class="cell">19</div>
											<div class="cell">20</div>
											<div class="cell">21</div>
											<div class="cell">22</div>
											<div class="cell">23</div>
											<div class="cell">24</div>
											<div class="cell">25</div>
										</div>
										<div class="inner-cell cell-bottom">
											<div class="cell">26</div>
											<div class="cell">27</div>
											<div class="cell">28</div>
											<div class="cell">29</div>
											<div class="cell">30</div>
											<div class="cell">31</div>
											<div class="cell cell-next-month">1</div>
										</div>
									</div>
								</div>
								<p>Rendez-vous<span class="red italic"> (obligatoire)</span></p>
								<div class="grid">
									<div class="inner-vous date">
										<p>Date</p>
										<input type="text" class="js-select-date"/>
										<a class="btn btn-grayer-lite gray" href="#">
											Selectionner une date
										</a><br>

										<!-- START JQ CALENDAR -->
										<div class="ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all" style="display: none;">
											<div class="ui-datepicker-header ui-widget-header ui-helper-clearfix ui-corner-all">
												<a class="ui-datepicker-prev ui-corner-all" data-handler="prev" data-event="click" title="Prev">
													<span class="ui-icon ui-icon-circle-triangle-w"></span>
												</a>
												<a class="ui-datepicker-next ui-corner-all" data-handler="next" data-event="click" title="Next">
													<span class="ui-icon ui-icon-circle-triangle-e"></span>
												</a>
												<div class="ui-datepicker-title">
													<span class="ui-datepicker-month">October</span>
													<span class="ui-datepicker-year">2013</span>
												</div>
											</div>
											<table class="ui-datepicker-calendar">
												<thead>
												<tr>
													<th class="ui-datepicker-week-end">
														<span title="Sunday">Su</span>
													</th>
													<th>
														<span title="Monday">Mo</span>
													</th>
													<th>
														<span title="Tuesday">Tu</span>
													</th>
													<th>
														<span title="Wednesday">We</span>
													</th>
													<th>
														<span title="Thursday">Th</span>
													</th>
													<th>
														<span title="Friday">Fr</span>
													</th>
													<th class="ui-datepicker-week-end">
														<span title="Saturday">Sa</span>
													</th>
												</tr>
												</thead>
												<tbody>
												<tr>
													<td class=" ui-datepicker-week-end ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled"> </td>
													<td class=" ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled"> </td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">1</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">2</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">3</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">4</a>
													</td>
													<td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">5</a>
													</td>
												</tr>
												<tr>
													<td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">6</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">7</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">8</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">9</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">10</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">11</a>
													</td>
													<td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">12</a>
													</td>
												</tr>
												<tr>
													<td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">13</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">14</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">15</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">16</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">17</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">18</a>
													</td>
													<td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">19</a>
													</td>
												</tr>
												<tr>
													<td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">20</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">21</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">22</a>
													</td>
													<td class=" ui-datepicker-days-cell-over  ui-datepicker-today" data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default ui-state-highlight" href="#">23</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">24</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">25</a>
													</td>
													<td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">26</a>
													</td>
												</tr>
												<tr>
													<td class=" ui-datepicker-week-end " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">27</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">28</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">29</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">30</a>
													</td>
													<td class=" " data-handler="selectDay" data-event="click" data-month="9" data-year="2013">
														<a class="ui-state-default" href="#">31</a>
													</td>
													<td class=" ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled"> </td>
													<td class=" ui-datepicker-week-end ui-datepicker-other-month ui-datepicker-unselectable ui-state-disabled"> </td>
												</tr>
												</tbody>
											</table>
										</div>
										<!-- END JQ CALENDAR -->

										<span class="blue-dark">
											Sélectionnez une date et un horaire puis un
											professionnel du réseau OMMI vous contactera au plus vite.
										</span>
									</div>
									<div class="inner-vous horaire">
										<p>Horaire</p>
										<div class="time-box">
											<span>Entre</span>
											<div class="select-performed">
												<select name="field" class="pretty">
													<option value="1">08:00</option>
													<option value="2">07:00</option>
													<option value="3">06:00</option>
													<option value="4">05:00</option>
													<option value="5">04:00</option>
												</select>
											</div>
											<div class="select-performed">
												<span class="center">et</span>
													<select name="field" class="pretty">
														<option value="1">20:00</option>
														<option value="2">21:00</option>
														<option value="3">22:00</option>
														<option value="4">23:00</option>
														<option value="5">24:00</option>
													</select>
											</div>
										</div>
										<a class="btn btn-red btn-prend" href="#">Prendre le rendez-vous</a>
									</div>
								</div>
								<a class="btn btn-blue btn-depan" href="#">Dépannage en urgence !</a>
							</div>

						</div>

					</div>
				</div>



			</div>

		</div>


		<div class="grid">
			<div class="grid-full grid-full-other">
				<div class="grid-inner">
					<h1 class="gray"><span class="blue"> Pourquoi faire certifier</span><br>
						mon dossier par OMMI ?
					</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Partez avec un avantage décisif !<br>
							En faisant certifier votre candidature, rassurez les propriétaires et sortez du lot.
						</div>
						<div class="index-row-six-btn">
							<a href="#" class="right btn btn-blue w200">Certifier ma candidature</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="grid grid-transparent">
			<div class="grid-half grid-half-other">
				<div class="grid-inner">
					<h1 class="gray">Presse de trouver<br> un logement ?</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Découvrez nos comptes sur-mesure et<br>
							choisissez celui qui vous convient le mieux.<br>
							Donnez-vous les moyens de trouver vite.
						</div>
						<div class="index-row-six-link">
							<a href="#">Comples OMMI</a>
						</div>
					</div>
				</div>
			</div>

			<div class="grid-half grid-half-other">
				<div class="grid-inner">
					<h1 class="gray">Au secours !<br> Un depanneur ?</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Pas de panique! Profitez du réseau Ommi<br>
							de dépanneurs de confiance à prix d’ami !
							Programmez en ligne vos rendez-vous.
						</div>
						<div class="index-row-six-link">
							<a href="#">Dépannage</a>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>

<script type="text/javascript">
	$(function(){
		$(".js-select-date").datepicker({nextText: '', prevText: ''});
	});
</script>