<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Tableau de bord</h1>
	</div>
</div>
<div class="inner">
	<div class="grid">
		<div class="page-tab-nav">
			<ul>
				<li><a href="">Résumé</a></li>
				<li><a href="">Mes annonces</a></li>
				<li><a href="">Mes candidats</a></li>
				<li><a href="">Mes services</a></li>
				<li><a href="" class="active">Mon compte</a></li>
			</ul>
		</div>
		<div id="compte" class="compte-01">
			<div class="left">
				<div class="menu">
					<a href="#" class="btn btn-blue progress-menu-active">Sommaire</a>
					<a href="#" class="btn btn-gray">Mes parametres</a>
					<a href="#" class="btn btn-gray">Mon compte</a>
					<a href="#" class="btn btn-gray">Bulletins d'information</a>
				</div>
			</div>
			<div class="right">
				<div class="progress-content">
					<div class="block-grid grid-inset-white">
						<h2><span class="red">Mes paramètres :</span> <span class="gray">Notifications</span></h2>
						<ul>
							<p>Vous recevez actuellement :</p>
							<li>Candidatures acceptées : Quotidien</li>
							<li>Alertes : Hebdomadaire</li>
							<li>Rendez-vous : 1 jour avant, 5 heures avant</li>
						</ul>
						<a href="#" class="btn btn-red w200">Mes paramètres</a>
					</div>
					<div class="block-grid grid-inset-white">
						<h2><span class="blue">Mon compte :</span> <span class="gray">Profil et sécurité</span></h2>
						<p>
							<span>Prénom Nom</span></br>
							<span>monadresse@mail.com</span></br>
							<span>numéro de telephone</span>
						</p>
						<a href="#" class="btn btn-blue w200">Modifier mon compte</a>
					</div>
					<div class="block-grid grid-inset-white">
						<h2><span class="blue">Bulletin d’informations :</span></br><span class="gray">Restons en contact !</span></h2>
						<ul>
							<p>Vous êtes inscrit à :</p>
							<li>La newsletter <strong>Ommi</strong></li>
						</ul>
						<a href="#" class="btn btn-blue w200">Mes abonnements</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="grid">
		<div class="grid-full grid-full-other">
			<div class="grid-inner">
				<h1 class="gray"><span class="blue"> Pourquoi faire certifier</span><br>
					mon dossier par OMMI ?
				</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Partez avec un avantage décisif ! </br>En faisant certifier votre candidature, rassurez les propriétaires et sortez du lot. 
					</div>
					<div class="index-row-six-btn">
						<a href="#" class="right btn btn-blue w200">Certifier ma candidature</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="grid grid-transparent">
		<div class="grid-half grid-half-other">
			<div class="grid-inner">
				<h1 class="gray">Presse de trouver<br> un logement ?</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Découvrez nos comptes sur-mesure et<br>
						choisissez celui qui vous convient le mieux.<br>
						Donnez-vous les moyens de trouver vite.
					</div>
					<div class="index-row-six-link">
						<a href="#">Comples OMMI</a>
					</div>
				</div>
			</div>
		</div>

		<div class="grid-half grid-half-other">
			<div class="grid-inner">
				<h1 class="gray">Au secours !<br> Un depanneur ?</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Pas de panique! Profitez du réseau Ommi<br>
						de dépanneurs de confiance à prix d’ami !
						Programmez en ligne vos rendez-vous.
					</div>
					<div class="index-row-six-link">
						<a href="#">Dépannage</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>