<div class="title-row-tabl">
	<div class="container-text">
		<h1 class="white-txt">Tableau de bord</h1>
	</div>
</div>
<div class="inner">
<div class="grid">
	<div class="menu-annonce menu-tabl">
		<ul>
			<li><a href="">Résumé</a></li>
			<li><a href="" class="active">Mon dossier</a></li>
			<li><a href="">Mes recherches</a></li>
			<li><a href="">Mes candidatures</a></li>
			<li><a href="">Mes services</a></li>
			<li><a href="">Mon compte</a></li>
		</ul>
	</div>
	<div class="tab-file">
		<div class="box-title">
			<div class="title-txt">
				<h2 class="black-txt">Dossier de candidature</h2>
				<span class="bold-txt">Candidat + 2 Colocataire</span>
			</div>
			<div class="btn-group">
				<a class="btn btn-gray" href="#">Modifier</a>
				<a class="btn btn-blue" href="#">Profil Ommi+</a>
				<a class="btn btn-red" href="#">Profil Ommium</a>
			</div>
		</div>
		<div class="box-info-universal">
			<div class="inner-menu-file">
				<ul>
					<li><a href="" class="active">Candidat</a></li>
					<li><a href="">Colocataire 1</a></li>
					<li><a href="">Colocataire 2</a></li>
				</ul>
			</div>
			<div class="inner-bg-black">
				<h2 class="white-text txt-small">Profil</h2>
				<div class="box-info-universal">
					<h2 class="black-text">Prénom Nomdefamille</h2>
					<div class="inner-box">
						<p>Profil : <span class="bold-txt">Salarié</span></p>
						<p>Revenus : <span class="bold-txt">1400 €/mois</span></p>
						<div class="garant">
							<p>Garant 1 : <span class="bold-txt">Famille - 1200 €/mois</span></p>
							<p>Garant 2 : <span class="bold-txt">Famille - 3000 €/mois</span></p>
						</div>
					</div>
					<div class="inner-box">
						<p>Profession : <span class="bold-txt">Ingénieur</span></p>
						<p>Contrat: <span class="bold-txt">CDI</span></p>
					</div>
					<div class="inner-box box-size">
						<p>Compte vérifié sur :</p>
						<a class="btn small-btn btn-gray-small blue-dark btn-fb" href="#">
							x amis
							<i class="icon-chek"></i>
						</a>
						<a class="btn small-btn btn-gray-small blue-dark btn-in" href="#">
							x relations
							<i class="icon-chek"></i>
						</a>
					</div>
				</div>
				<h2 class="white-text txt-small">Pièces justificatives</h2>
				<p class="white-text">
					Sélectionnez un document pour le consulter.<br>
					Certaines pièces justificatives peuvent contenir plusieurs pages.
				</p>
				<div class="inner-box-btn">
					<label class="bold-txt">Candidat</label>
					<a class="btn btn-blue" href="#">Pièce d’identité</a>
					<a class="btn btn-blue" href="#">Avis d’imposition</a>
					<a class="btn btn-blue" href="#">Curriculum Vitae</a>
				</div>
				<div class="inner-box-btn">
					<label class="bold-txt">Garant 1</label>
					<a class="btn btn-blue" href="#">Avis d’imposition</a>
					<a class="btn btn-blue" href="#">Taxe foncière</a>
				</div>
				<div class="inner-box-btn">
					<label class="bold-txt">Garant 2</label>
					<a class="btn btn-blue" href="#">Fiche de paye 1</a>
					<a class="btn btn-blue" href="#">Fiche de paye 2</a>
				</div>
			</div>

		</div>



	</div>

</div>


<div class="grid">
	<div class="grid-full grid-full-other">
		<div class="grid-inner">
			<h1 class="gray"><span class="blue"> Pourquoi faire certifier</span><br>
				mon dossier par OMMI ?
			</h1>
			<div class="index-row-six cf">
				<div class="index-row-six-text">
					Partez avec un avantage décisif !<br>
					En faisant certifier votre candidature, rassurez les propriétaires et sortez du lot.
				</div>
				<div class="index-row-six-btn">
					<a href="#" class="right btn btn-blue w200">Certifier ma candidature</a>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="grid grid-transparent">
	<div class="grid-half grid-half-other">
		<div class="grid-inner">
			<h1 class="gray">Presse de trouver<br> un logement ?</h1>
			<div class="index-row-six cf">
				<div class="index-row-six-text">
					Découvrez nos comptes sur-mesure et<br>
					choisissez celui qui vous convient le mieux.<br>
					Donnez-vous les moyens de trouver vite.
				</div>
				<div class="index-row-six-link">
					<a href="#">Comples OMMI</a>
				</div>
			</div>
		</div>
	</div>

	<div class="grid-half grid-half-other">
		<div class="grid-inner">
			<h1 class="gray">Au secours !<br> Un depanneur ?</h1>
			<div class="index-row-six cf">
				<div class="index-row-six-text">
					Pas de panique! Profitez du réseau Ommi<br>
					de dépanneurs de confiance à prix d’ami !
					Programmez en ligne vos rendez-vous.
				</div>
				<div class="index-row-six-link">
					<a href="#">Dépannage</a>
				</div>
			</div>
		</div>
	</div>
</div>

</div>