<div class="title-row-tabl">
	<div class="container-text">
		<h1 class="white-txt">Tableau de bord</h1>
	</div>
</div>
<div class="inner">
<div class="grid">
<div class="menu-annonce menu-tabl">
	<ul>
		<li><a href="">Résumé</a></li>
		<li><a href="">Mon dossier</a></li>
		<li><a href="">Mes recherches</a></li>
		<li><a href="" class="active">Mes candidatures</a></li>
		<li><a href="">Mes services</a></li>
		<li><a href="">Mon compte</a></li>
	</ul>
</div>
<div class="tab-candidature">
<div class="title-box">
	<div class="inner-text">
		<p>Retrouvez ici vos candidatures, leurs avancements et les visites programmées</p>
		<input type="text" class="txt-gray" placeholder="Vous avez déposé 11 candidatures"/>
		<input type="text" class="txt-red" placeholder="4 candidatures acceptées"/>
		<input type="text" class="txt-blue" placeholder="5 candidatures refusées"/>
	</div>
	<a class="btn btn-gray" href="#">Effacer mes candidatures refusées</a>
</div>
<div class="box-inner inner-right">
	<h2 class="black-txt txt-small">Mes candidatures <span class="blue">(0)</span></h2>
	<div class="box-info-univ-black">
		<div class="grid grid-block">
			<div class="box-vous">
				<h3 class="blue">Vous n’avez actuellement aucune candidature</h3>
				<p>
					Lorsque votre dossier est complet, lancez une recherche et candidatez aux annonces qui
					vous conviennent. Retrouvez dans cet espace vos candidatures et leur avancement.
				</p>
				<a class="btn btn-blue" href="#">Mon dossier de candidature</a>
				<a class="btn btn-red" href="#">Nouvelle recherche</a>
			</div>
		</div>
	</div>

</div>
<div class="box-inner inner-left">
	<h2 class="black-txt txt-small">État de la candidature</h2>
	<div class="box-info-univ-black"></div>
</div>
<a class="btn btn-red w200" href="#">J’ai trouvé mon logement</a>
</div>

</div>


<div class="grid">
	<div class="grid-full grid-full-other">
		<div class="grid-inner">
			<h1 class="gray"><span class="blue"> Pourquoi faire certifier</span><br>
				mon dossier par OMMI ?
			</h1>
			<div class="index-row-six cf">
				<div class="index-row-six-text">
					Partez avec un avantage décisif !<br>
					En faisant certifier votre candidature, rassurez les propriétaires et sortez du lot.
				</div>
				<div class="index-row-six-btn">
					<a href="#" class="right btn btn-blue w200">Certifier ma candidature</a>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="grid grid-transparent">
	<div class="grid-half grid-half-other">
		<div class="grid-inner">
			<h1 class="gray">Presse de trouver<br> un logement ?</h1>
			<div class="index-row-six cf">
				<div class="index-row-six-text">
					Découvrez nos comptes sur-mesure et<br>
					choisissez celui qui vous convient le mieux.<br>
					Donnez-vous les moyens de trouver vite.
				</div>
				<div class="index-row-six-link">
					<a href="#">Comples OMMI</a>
				</div>
			</div>
		</div>
	</div>

	<div class="grid-half grid-half-other">
		<div class="grid-inner">
			<h1 class="gray">Au secours !<br> Un depanneur ?</h1>
			<div class="index-row-six cf">
				<div class="index-row-six-text">
					Pas de panique! Profitez du réseau Ommi<br>
					de dépanneurs de confiance à prix d’ami !
					Programmez en ligne vos rendez-vous.
				</div>
				<div class="index-row-six-link">
					<a href="#">Dépannage</a>
				</div>
			</div>
		</div>
	</div>
</div>

</div>

