<div class="title-row-tabl">
	<div class="container-text">
		<h1 class="white-txt">Tableau de bord</h1>
	</div>
</div>
<main>
<div class="inner">
<div class="grid grid-dark">
<div class="menu-annonce menu-tabl">
	<ul>
		<li><a href="" class="active">Résumé</a></li>
		<li><a href="">Mon dossier</a></li>
		<li><a href="">Mes recherches</a></li>
		<li><a href="">Mes candidatures</a></li>
		<li><a href="">Mes services</a></li>
		<li><a href="">Mon compte</a></li>
	</ul>
</div>
<div class="tab-resume">
<div class="inner-transparent inner-left">
	<h2 class="black-txt txt-small">Profil</h2>
	<div class="box-info-universal bg-circle">
		<h2 class="black-txt">Prénom Nom</h2>
		<span class="blue">monadresse@mail.com</span><br>
		<span class="red">profil basique</span>
		<p>
			0 recherches<br>
			0 candidatures<br>
			0 candidatures acceptées
		</p>
		<a href="#" class="btn btn-gray">Compléter mon profil</a>
	</div>
	<h2 class="black-txt txt-small">Calendrier</h2>
	<div class="box-info-universal">
		<div class="calendar">
			<div class="name-month-calend">
				<h2>
					<a href="#" class="btn btn-gray-lite btn-cal-prev"></a>
					Juillet
					<a href="#" class="btn btn-gray-lite name-month-next"></a>
				</h2>
			</div>
			<div class="inner-cell cell-month">
				<div class="cell">Lun</div>
				<div class="cell">Mar</div>
				<div class="cell">Mer</div>
				<div class="cell">Jeu</div>
				<div class="cell">Ven</div>
				<div class="cell">Sa</div>
				<div class="cell">Dim</div>
			</div>
			<div class="inner-cell">
				<div class="cell cell-gray">1</div>
				<div class="cell cell-gray">2</div>
				<div class="cell cell-gray">3</div>
				<div class="cell cell-gray">4</div>
				<div class="cell cell-gray">5</div>
				<div class="cell cell-gray">6</div>
				<div class="cell cell-gray">7</div>
			</div>
			<div class="inner-cell">
				<div class="cell cell-gray">8</div>
				<div class="cell cell-gray">9</div>
				<div class="cell cell-gray">10</div>
				<div class="cell cell-gray">11</div>
				<div class="cell cell-black">12</div>
				<div class="cell">13</div>
				<div class="cell">14</div>
			</div>
			<div class="inner-cell">
				<div class="cell">15</div>
				<div class="cell">16</div>
				<div class="cell cell-blue">17</div>
				<div class="cell">18</div>
				<div class="cell">19</div>
				<div class="cell">20</div>
				<div class="cell">21</div>
			</div>
			<div class="inner-cell">
				<div class="cell">22</div>
				<div class="cell cell-blue">23</div>
				<div class="cell cell-blue">24</div>
				<div class="cell">25</div>
				<div class="cell cell-blue">26</div>
				<div class="cell">27</div>
				<div class="cell">28</div>
			</div>
			<div class="inner-cell cell-bottom">
				<div class="cell">29</div>
				<div class="cell">30</div>
				<div class="cell">31</div>
				<div class="cell cell-next-month">1</div>
				<div class="cell cell-next-month">2</div>
				<div class="cell cell-next-month">3</div>
				<div class="cell cell-next-month">4</div>
			</div>
		</div>
		<div class="color-calendar">
			<img src="/./assets/images/date-visit.png">
			<span class="black">Visite</span>
			<img src="/./assets/images/date-free.png">
			<span class="black">Depannage</span>
		</div>
		<a href="#" class="btn btn-blue btn-voir">Voir  mes candidatures</a>
	</div>
</div>
<div class="inner-transparent inner-right">
	<h2 class="black-txt txt-small">Alertes</h2>
	<div class="box-info-universal">
		<div class="alert-gray w500">
			<a href="#" class="close-gray"></a>
			<div class="text-box">
				Vorte candidature pour l'annonce
				<span class="bold-txt">[*.Titre de l'annonce.*]</span> n'a pas ete retenue.
			</div>
			<a href="#" class="black link-btn">Voir</a>
		</div>
		<div class="alert-blue w500">
			<a href="#" class="close-blue"></a>
			<div class="text-box">
				Connaissez-vous les avantages<br>du Compte OMMIUM ?
			</div>
			<a href="#" class="blue link-btn">Voir</a>
		</div>
		<div class="alert-red w500">
			<a href="#" class="close-red"></a>
			<div class="text-box">
				Afin de pouvoir candidater,<br>pensez à compléter votre profil !
			</div>
			<a href="#" class="red link-btn">Voir</a>
		</div>
	</div>
	<h2 class="black-txt txt-small">Mes candidatures récentes</h2>
	<div class="box-info-univ-black">
		<p class="txt-description">Vous n’avez actuellment déposé aucune candidature.<br>
			Complétez votre dossier de candidature, sélectionnez une annonce<br>
			et candidatez en quelques clics.
		</p>

		<a href="#" class="btn btn-blue btn-search">Effectuer une recherches</a>
		<a href="#" class="btn btn-red btn-compl">Completer mon dossier</a>
	</div>
	<h2 class="black-txt txt-small">Mes recherches récentes</h2>
	<div class="box-info-univ-black">
		<p class="txt-description">Vous n’avez actuellment déposé aucune candidature.<br>
			Effectuez une recherche et sauvegardez la facilement.<br>
			Vous pourrez la consulter et la modifier à tout moment.
		</p>
		<a href="#" class="btn btn-blue btn-search">Effectuer une recherches</a>
	</div>
</div>


</div>
<div class="box-btn-nav-resume">
	<a href="#" class="btn btn-red">Profil Ommium</a>
	<a href="#" class="btn btn-blue">Dossier de candidature</a>
	<a href="#" class="btn btn-gray icon-book">Guide du Locataire</a>
	<a href="#" class="btn btn-gray icon-hand">J’ai trouvé mon appart !</a>
</div>
</div>


<div class="grid">
	<div class="grid-full grid-full-other">
		<div class="grid-inner">
			<h1 class="gray"><span class="blue"> Pourquoi faire certifier</span><br>
				mon dossier par OMMI ?
			</h1>
			<div class="index-row-six cf">
				<div class="index-row-six-text">
					Partez avec un avantage décisif !<br>
					En faisant certifier votre candidature, rassurez les propriétaires et sortez du lot.
				</div>
				<div class="index-row-six-btn">
					<a href="#" class="right btn btn-blue w200">Certifier ma candidature</a>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="grid grid-transparent">
	<div class="grid-half grid-half-other">
		<div class="grid-inner">
			<h1 class="gray">Presse de trouver<br> un logement ?</h1>
			<div class="index-row-six cf">
				<div class="index-row-six-text">
					Découvrez nos comptes sur-mesure et<br>
					choisissez celui qui vous convient le mieux.<br>
					Donnez-vous les moyens de trouver vite.
				</div>
				<div class="index-row-six-link">
					<a href="#">Comples OMMI</a>
				</div>
			</div>
		</div>
	</div>

	<div class="grid-half grid-half-other">
		<div class="grid-inner">
			<h1 class="gray">Au secours !<br> Un depanneur ?</h1>
			<div class="index-row-six cf">
				<div class="index-row-six-text">
					Pas de panique! Profitez du réseau Ommi<br>
					de dépanneurs de confiance à prix d’ami !
					Programmez en ligne vos rendez-vous.
				</div>
				<div class="index-row-six-link">
					<a href="#">Dépannage</a>
				</div>
			</div>
		</div>
	</div>
</div>

</div>
</main>