<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Publier une annonce</h1>
	</div>
</div>
<div class="inner">
	<div class="grid" id="publier">
		<div class="left">
			<div class="progress">
				<h2 class="gray">Étapes</h2>
				<div class="progress-step" id="step-75"></div>
				<span>1 étapes restantes</span>
			</div>
			<div class="menu">
				<a href="#" class="btn btn-gray">1  Infos personnelles</a>
				<a href="#" class="btn btn-gray">2  Garants</a>
				<a href="#" class="btn btn-gray">3  Vérification</a>
				<a href="#" class="btn btn-blue progress-menu-active">4  Pièces de dossier</a>
			</div>
		</div>
		<div class="right">
			<div class="progress-content" id="content-step-2">
				<div class="step-title">
					<h1>Pièces de dossier</h1>
					<span class="blue" style="float: left;">Pour candidater sur OMMI, vous devez fournir des pièces justificatives. Seuls les</br>propriétaires auprès desquels vous candidaterez pourront les consulter sur le site.</span>
					<a href="#" class="red" style="float: right;">Aide?</a>
				</div>
				
				<div class="block-grid grid-dark">
					<h3>Moi</h3>
					<h5>Vous avez indiqué que vous êtes <span class="blue">salarié : 2000€ /mois</span></h5>
					
					<div class="block-grid grid-inset" id="accept-block">
						<fieldset>
							<label>Pièce d’identité <em class="red">(obligatoire)</em></label>
							<div class="uploaded-files-dossier">
								<div class="uploaded-file">
									<div class="uploaded-file-info">
										<span class="uploaded-file-info-title">Fichier actuel :</span>
										<span class="uploaded-file-info-filename">FileName.format</span>
									</div>
									<div class="uploaded-file-controlls">
										<a href="#" class="btn btn-medium btn-gray btn-refresh">Modifier</a>
										<a href="#" class="btn btn-medium btn-red btn-delete">Supprimer</a>
									</div>
								</div>
								<a href="#" class="black">Ajouter une page à ce document</a>
							</div>
						</fieldset>
						<p class="gray">Carte d’identité, Passeport ou Titre de séjour.</p>
					</div>

					<div class="block-grid grid-inset" id="accept-block">
						<fieldset>
							<label>Avis d’imposition <em class="red">(obligatoire)</em></label>
							<div class="uploaded-files-dossier">
								<div class="uploaded-file">
									<div class="uploaded-file-info">
										<span class="uploaded-file-info-title">Fichier actuel :</span>
										<span class="uploaded-file-info-filename">FileName.format</span>
									</div>
									<div class="uploaded-file-controlls">
										<a href="#" class="btn btn-medium btn-gray btn-refresh">Modifier</a>
										<a href="#" class="btn btn-medium btn-red btn-delete">Supprimer</a>
									</div>
								</div>
								<div class="uploaded-file">
									<div class="uploaded-file-info">
										<span class="uploaded-file-info-title">Fichier actuel :</span>
										<span class="uploaded-file-info-filename">FileName.format</span>
									</div>
									<div class="uploaded-file-controlls">
										<a href="#" class="btn btn-medium btn-gray btn-refresh">Modifier</a>
										<a href="#" class="btn btn-medium btn-red btn-delete">Supprimer</a>
									</div>
								</div>
								<a href="#" class="black">Ajouter une page à ce document</a>
							</div>
						</fieldset>
					</div>

					<div class="block-grid grid-inset">
						<fieldset>
							<label>Curriculum Vitae <em class="blue">(conseillé)</em></label>
							<div class="upload-files-dossier">
								<a href="" class="btn btn-red" id="upload-file-btn">Sélectionner un fichier</br>sur mon ordinateur</a>
								<span class="separator">ou</span>
								<div class="upload-area">Glisser et déposer un fichier ici</br>pour le télécharger</div>
							</div>
						</fieldset>
					</div>

					<h4>Garant 1</h4>
					<h5 class="blue">Famille : 1900€ /mois</h5>

					<div class="block-grid grid-inset" id="accept-block">
						<fieldset>
							<label>Justificatif de revenu <em class="red">(obligatoire)</em></label>
							<div>
								<input type="checkbox" class="input-pretty" id="demo1" name="demo1" checked>
								<label for="demo1" class="btn-input-lite">Bulletins de salaire</label>
								<input type="checkbox" class="input-pretty" id="demo2" name="demo2">
								<label for="demo2" class="btn-input-lite">Avis d'imposition</label>
							</div>
						</fieldset>
					</div>

					<div class="block-grid grid-inset" id="accept-block">
						<fieldset>
							<label>Bulletin de salaire 1 <em class="red">(obligatoire)</em></label>
							<div class="uploaded-files-dossier">
								<div class="uploaded-file">
									<div class="uploaded-file-info">
										<span class="uploaded-file-info-title">Fichier actuel :</span>
										<span class="uploaded-file-info-filename">FileName.format</span>
									</div>
									<div class="uploaded-file-controlls">
										<a href="#" class="btn btn-medium btn-gray btn-refresh">Modifier</a>
										<a href="#" class="btn btn-medium btn-red btn-delete">Supprimer</a>
									</div>
								</div>
								<a href="#" class="black">Ajouter une page à ce document</a>
							</div>
						</fieldset>
					</div>

					<div class="block-grid grid-inset">
						<fieldset>
							<label>Bulletin de salaire 2 <em class="red">(obligatoire)</em></label>
							<div class="upload-files-dossier">
								<a href="" class="btn btn-red" id="upload-file-btn">Sélectionner un fichier</br>sur mon ordinateur</a>
								<span class="separator">ou</span>
								<div class="upload-area">Glisser et déposer un fichier ici</br>pour le télécharger</div>
							</div>
						</fieldset>
					</div>

					<div class="block-grid grid-inset">
						<fieldset>
							<label>Bulletin de salaire 3 <em class="blue">(conseillé)</em></label>
							<div class="upload-files-dossier">
								<a href="" class="btn btn-red" id="upload-file-btn">Sélectionner un fichier</br>sur mon ordinateur</a>
								<span class="separator">ou</span>
								<div class="upload-area">Glisser et déposer un fichier ici</br>pour le télécharger</div>
							</div>
						</fieldset>
					</div>

					<h4>Garant 2</h4>
					<h5 class="blue">Employeur</h5>

					<div class="block-grid grid-inset">
						<fieldset>
							<label>Justificatif <em class="red">(obligatoire)</em></label>
							<div class="upload-files-dossier">
								<a href="" class="btn btn-red" id="upload-file-btn">Sélectionner un fichier</br>sur mon ordinateur</a>
								<span class="separator">ou</span>
								<div class="upload-area">Glisser et déposer un fichier ici</br>pour le télécharger</div>
							</div>
						</fieldset>
					</div>

					<a href="#" class="btn btn-medium btn-gray btn-plus">Ajouter un document</a>
				</div>

				<div class="block-grid grid-dark">
					<h3>Colocotaire 1</h3>
					<h5>Vous avez indiqué que cette personne est <span class="blue">salariée : 2500€ /mois</span></h5>
					
					<div class="block-grid grid-inset">
						<fieldset>
							<label>Pièce d’identité <em class="red">(obligatoire)</em></label>
							<div class="upload-files-dossier">
								<a href="" class="btn btn-red" id="upload-file-btn">Sélectionner un fichier</br>sur mon ordinateur</a>
								<span class="separator">ou</span>
								<div class="upload-area">Glisser et déposer un fichier ici</br>pour le télécharger</div>
							</div>
						</fieldset>
						<p class="gray">Carte d’identité, Passeport ou Titre de séjour.</p>
					</div>

					<div class="block-grid grid-inset">
						<fieldset>
							<label>Contrat de travail</label>
							<div class="upload-files-dossier">
								<a href="" class="btn btn-red" id="upload-file-btn">Sélectionner un fichier</br>sur mon ordinateur</a>
								<span class="separator">ou</span>
								<div class="upload-area">Glisser et déposer un fichier ici</br>pour le télécharger</div>
							</div>
						</fieldset>
					</div>

					<div class="block-grid grid-inset">
						<fieldset>
							<label>Curriculum Vitae <em class="blue">(conseillé)</em></label>
							<div class="upload-files-dossier">
								<a href="" class="btn btn-red" id="upload-file-btn">Sélectionner un fichier</br>sur mon ordinateur</a>
								<span class="separator">ou</span>
								<div class="upload-area">Glisser et déposer un fichier ici</br>pour le télécharger</div>
							</div>
						</fieldset>
					</div>

					<div class="block-grid grid-inset">
						<fieldset>
							<label>Justificatif de revenu <em class="red">(obligatoire)</em></label>
							<div>
								<input type="checkbox" class="input-pretty" id="demo1" name="demo1">
								<label for="demo1" class="btn-input-lite">Bulletins de salaire</label>
								<input type="checkbox" class="input-pretty" id="demo2" name="demo2">
								<label for="demo2" class="btn-input-lite">Avis d'imposition</label>
							</div>
						</fieldset>
					</div>

					<h4>Garant 1</h4>
					<h5 class="blue">Famille : 1900€ /mois</h5>

					<div class="block-grid grid-inset" id="accept-block">
						<fieldset>
							<label>Justificatif de revenu <em class="red">(obligatoire)</em></label>
							<div>
								<input type="checkbox" class="input-pretty" id="demo1" name="demo1" checked>
								<label for="demo1" class="btn-input-lite">Bulletins de salaire</label>
								<input type="checkbox" class="input-pretty" id="demo2" name="demo2">
								<label for="demo2" class="btn-input-lite">Avis d'imposition</label>
							</div>
						</fieldset>
					</div>

					<div class="block-grid grid-inset" id="accept-block">
						<fieldset>
							<label>Bulletin de salaire 1 <em class="red">(obligatoire)</em></label>
							<div class="uploaded-files-dossier">
								<div class="uploaded-file">
									<div class="uploaded-file-info">
										<span class="uploaded-file-info-title">Fichier actuel :</span>
										<span class="uploaded-file-info-filename">FileName.format</span>
									</div>
									<div class="uploaded-file-controlls">
										<a href="#" class="btn btn-medium btn-gray btn-refresh">Modifier</a>
										<a href="#" class="btn btn-medium btn-red btn-delete">Supprimer</a>
									</div>
								</div>
								<a href="#" class="black">Ajouter une page à ce document</a>
							</div>
						</fieldset>
					</div>

					<div class="block-grid grid-inset" id="accept-block">
						<fieldset>
							<label>Bulletin de salaire 2 <em class="red">(obligatoire)</em></label>
							<div class="uploaded-files-dossier">
								<div class="uploaded-file">
									<div class="uploaded-file-info">
										<span class="uploaded-file-info-title">Fichier actuel :</span>
										<span class="uploaded-file-info-filename">FileName.format</span>
									</div>
									<div class="uploaded-file-controlls">
										<a href="#" class="btn btn-medium btn-gray btn-refresh">Modifier</a>
										<a href="#" class="btn btn-medium btn-red btn-delete">Supprimer</a>
									</div>
								</div>
								<a href="#" class="black">Ajouter une page à ce document</a>
							</div>
						</fieldset>
					</div>

					<div class="block-grid grid-inset">
						<fieldset>
							<label>Bulletin de salaire 3 <em class="blue">(conseillé)</em></label>
							<div class="upload-files-dossier">
								<a href="" class="btn btn-red" id="upload-file-btn">Sélectionner un fichier</br>sur mon ordinateur</a>
								<span class="separator">ou</span>
								<div class="upload-area">Glisser et déposer un fichier ici</br>pour le télécharger</div>
							</div>
						</fieldset>
					</div>

					<h4>Document supplémentaire	</h4>

					<div class="block-grid grid-inset" id="accept-block">
						<fieldset>
							<label>Titre du document</label>
							<input type="text" style="width: 400px;">
						</fieldset>
						<fieldset>
							<div class="uploaded-files-dossier">
								<div class="uploaded-file">
									<div class="uploaded-file-info">
										<span class="uploaded-file-info-title">Fichier actuel :</span>
										<span class="uploaded-file-info-filename">FileName.format</span>
									</div>
									<div class="uploaded-file-controlls">
										<a href="#" class="btn btn-medium btn-gray btn-refresh">Modifier</a>
										<a href="#" class="btn btn-medium btn-red btn-delete">Supprimer</a>
									</div>
								</div>
								<a href="#" class="black">Ajouter une page à ce document</a>
							</div>
						</fieldset>
					</div>

					<a href="#" class="btn btn-medium btn-gray btn-plus">Ajouter un document</a>

				</div>

				<div class="block-grid grid-dark">
					<h3>Colocotaire 1</h3>
					<h5>Vous avez indiqué que cette personne est <span class="blue">salariée : 2500€ /mois</span></h5>
					
					<div class="block-grid grid-inset">
						<fieldset>
							<label>Pièce d’identité <em class="red">(obligatoire)</em></label>
							<div class="upload-files-dossier">
								<a href="" class="btn btn-red" id="upload-file-btn">Sélectionner un fichier</br>sur mon ordinateur</a>
								<span class="separator">ou</span>
								<div class="upload-area">Glisser et déposer un fichier ici</br>pour le télécharger</div>
							</div>
						</fieldset>
						<p class="gray">Carte d’identité, Passeport ou Titre de séjour.</p>
					</div>

					<div class="block-grid grid-inset">
						<fieldset>
							<label>Curriculum Vitae <em class="blue">(conseillé)</em></label>
							<div class="upload-files-dossier">
								<a href="" class="btn btn-red" id="upload-file-btn">Sélectionner un fichier</br>sur mon ordinateur</a>
								<span class="separator">ou</span>
								<div class="upload-area">Glisser et déposer un fichier ici</br>pour le télécharger</div>
							</div>
						</fieldset>
					</div>

					<h4>Garant 1</h4>
					<h5 class="blue">Famille : 3000€ /mois</h5>

					<div class="block-grid grid-inset">
						<fieldset>
							<label>Justificatif de revenu <em class="red">(obligatoire)</em></label>
							<div>
								<input type="checkbox" class="input-pretty" id="demo1" name="demo1">
								<label for="demo1" class="btn-input-lite">Bulletins de salaire</label>
								<input type="checkbox" class="input-pretty" id="demo2" name="demo2">
								<label for="demo2" class="btn-input-lite">Avis d'imposition</label>
							</div>
						</fieldset>
					</div>

					<a href="#" class="btn btn-medium btn-gray btn-plus">Ajouter un document</a>
					
				</div>

				<div class="progress-buttons">
					<a href="#" class="btn btn-medium btn-gray btn-arrow-prev left">Étape précédente</a>
					<a href="#" class="btn btn-medium btn-blue btn-arrow-next right">Enregistrer et continuer</a>
				</div>
			</div>
		</div>
	</div>
</div>