<div class="title-row-tabl">
	<div class="container-text box-text-tabl">
		<h1 class="white-txt">Tableau de bord</h1>
	</div>
</div>
	<div class="inner">
		<div class="grid">
			<div class="menu-annonce menu-tabl">
				<ul>
					<li><a href="">Résumé</a></li>
					<li><a href="">Mon dossier</a></li>
					<li><a href="" class="active">Mes recherches</a></li>
					<li><a href="">Mes candidatures</a></li>
					<li><a href="">Mes services</a></li>
					<li><a href="">Mon compte</a></li>
				</ul>
			</div>
			<div class="tab-search">
				<h2 class="black-txt txt-small">Mes recherches</h2>
				<div class="box-info-univ-black">
					<div class="grid grid-block">
						<div class="box-text info-box">
							<h3 class="item-title">Appartement 2 pièces Paris centre 1200max</h3>
							<span class="blue-dark">Recherche standard</span>
							<div class="box-input-item">
								<input type="checkbox" class="input-pretty" id="Choice1" name="Choice"/>
								<label for="Choice1" class="btn-input-gray-lite">Localisation</label>

								<input type="checkbox" class="input-pretty" id="Choice2" name="Choice"/>
								<label for="Choice2" class="btn-input-gray-lite">Budget</label>

								<input type="checkbox" class="input-pretty" id="Choice3" name="Choice"/>
								<label for="Choice3" class="btn-input-gray-lite">Surface</label>

								<input type="checkbox" class="input-pretty" id="Choice4" name="Choice"/>
								<label for="Choice4" class="btn-input-gray-lite">Type de bien</label>

								<input type="checkbox" class="input-pretty" id="Choice5" name="Choice"/>
								<label for="Choice5" class="btn-input-gray-lite">Pieces</label>
							</div>
							<a class="black" href="#">Modifier la recherche</a>
						</div>
						<div class="box-text box-center">
							<p class="gray">Annonces trouvees</p>
							<p>27</p>
							<p class="gray">Nouvelles annonces</p>
							<p>3</p>
							<a class="btn btn-blue" href="#">Voir les resultats</a>
						</div>
						<div class="box-text box-right">
							<p class="gray">Budget maximum</p>
							<p>1200 €</p>
							<p class="gray">Surface minimum</p>
							<p class="size-bottom">38 m²</p>
							<a class="red" href="#">Supprimer</a>
						</div>
					</div>
					<div class="grid grid-block">
						<div class="box-text info-box">
							<h3 class="item-title">Appart 2 pièces Paris 1100€ Vide</h3>
							<span class="blue-dark">Recherche carte</span>
							<div class="box-input-item">
								<input type="checkbox" class="input-pretty" id="Choice6" name="Choice"/>
								<label for="Choice6" class="btn-input-gray-lite">Localisation</label>

								<input type="checkbox" class="input-pretty" id="Choice7" name="Choice"/>
								<label for="Choice7" class="btn-input-gray-lite">Budget</label>

								<input type="checkbox" class="input-pretty" id="Choice8" name="Choice"/>
								<label for="Choice8" class="btn-input-gray-lite">Type de bien</label>

								<input type="checkbox" class="input-pretty" id="Choice9" name="Choice"/>
								<label for="Choice9" class="btn-input-gray-lite">Ameumblement</label>

								<input type="checkbox" class="input-pretty" id="Choice10" name="Choice"/>
								<label for="Choice10" class="btn-input-gray-lite">Pieces</label>

								<input type="checkbox" class="input-pretty" id="Choice11" name="Choice"/>
								<label for="Choice11" class="btn-input-gray-lite">Dependances</label>
							</div>
							<a class="black" href="#">Modifier la recherche</a>
						</div>
						<div class="box-text box-center">
							<p class="gray">Annonces trouvees</p>
							<p>19</p>
							<p class="gray">Nouvelles annonces</p>
							<p>5</p>
							<a class="btn btn-blue" href="#">Voir les resultats</a>
						</div>
						<div class="box-text box-right">
							<p class="gray">Budget maximum</p>
							<p>1100 €</p>
							<p class="gray">Surface minimum</p>
							<p class="size-bottom">- m²</p>
							<a class="red" href="#">Supprimer</a>
						</div>
					</div>
					<div class="grid grid-block">
						<div class="box-text info-box">
							<h3 class="item-title">Recherche 12/07/2013</h3>
							<span class="blue-dark">Recherche metro</span>
							<div class="box-input-item">
								<input type="checkbox" class="input-pretty" id="Choice12" name="Choice"/>
								<label for="Choice12" class="btn-input-gray-lite">Localisation</label>

								<input type="checkbox" class="input-pretty" id="Choice13" name="Choice"/>
								<label for="Choice13" class="btn-input-gray-lite">Budget</label>

								<input type="checkbox" class="input-pretty" id="Choice14" name="Choice"/>
								<label for="Choice14" class="btn-input-gray-lite">Type de bien</label>
							</div>
							<a class="black" href="#">Modifier la recherche</a>
						</div>
						<div class="box-text box-center">
							<p class="gray">Annonces trouvees</p>
							<p>91</p>
							<p class="gray">Nouvelles annonces</p>
							<p>17</p>
							<a class="btn btn-blue" href="#">Voir les resultats</a>
						</div>
						<div class="box-text box-right">
							<p class="gray">Budget maximum</p>
							<p>1000 €</p>
							<p class="gray">Surface minimum</p>
							<p class="size-bottom">- m²</p>
							<a class="red" href="#">Supprimer</a>
						</div>
					</div>
				</div>
				<a class="btn btn-red w200" href="#">Nouvelle rechercher</a>
				<h2 class="black-txt txt-small">Mes favoris</h2>
				<div class="box-info-univ-black">
					<div class="grid grid-block">
						<div class="box-text info-box box-size">
							<img src="/./assets/images/img-gallery-13.png" class="item-img">
							<h3 class="item-title">Appartement calme à Père-Lachaise</h3>
							<div>Appartement <span class="slash">|</span> Meublé<br>
								Paris 11e (75011)<br>
								2e étage avec ascenseur<br>
								Disponibilité : immédiate
							</div>
						</div>
						<div class="box-text price-box">
							<p class="price-small">1200 €</p>
							<p>44 m²</p>
							<p>2 pièces</p>
						</div>
						<div class="box-text box-link">
							<div class="box-btn-voir">
								<a class="btn btn-blue" href="#">Voir l'annonce</a><br>
							</div>
							<a class="red" href="#">Supprimer</a>
						</div>
					</div>
					<div class="grid grid-block">
						<div class="box-text info-box box-size">
							<img src="/./assets/images/img-gallery-15.png" class="item-img">
							<h3 class="item-title">Joli appartement proche Bastille</h3>
							<div>Appartement <span class="slash">|</span> Vide<br>
								Paris 12e (75012)<br>
								4e étage avec ascenseur<br>
								Disponibilité : 12/07/2013
							</div>
						</div>
						<div class="box-text price-box">
							<p class="price-small">970 €</p>
							<p>32 m²</p>
							<p>2 pièces</p>
						</div>
						<div class="box-text box-link">
							<div class="box-btn-voir">
								<a class="btn btn-blue" href="#">Voir l'annonce</a><br>
							</div>
							<a class="red" href="#">Supprimer</a>
						</div>
					</div>
				</div>
			</div>

		</div>


		<div class="grid">
			<div class="grid-full grid-full-other">
				<div class="grid-inner">
					<h1 class="gray"><span class="blue"> Pourquoi faire certifier</span><br>
						mon dossier par OMMI ?
					</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Partez avec un avantage décisif !<br>
							En faisant certifier votre candidature, rassurez les propriétaires et sortez du lot.
						</div>
						<div class="index-row-six-btn">
							<a href="#" class="right btn btn-blue w200">Certifier ma candidature</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="grid grid-transparent">
			<div class="grid-half grid-half-other">
				<div class="grid-inner">
					<h1 class="gray">Presse de trouver<br> un logement ?</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Découvrez nos comptes sur-mesure et<br>
							choisissez celui qui vous convient le mieux.<br>
							Donnez-vous les moyens de trouver vite.
						</div>
						<div class="index-row-six-link">
							<a href="#">Comples OMMI</a>
						</div>
					</div>
				</div>
			</div>

			<div class="grid-half grid-half-other">
				<div class="grid-inner">
					<h1 class="gray">Au secours !<br> Un depanneur ?</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Pas de panique! Profitez du réseau Ommi<br>
							de dépanneurs de confiance à prix d’ami !
							Programmez en ligne vos rendez-vous.
						</div>
						<div class="index-row-six-link">
							<a href="#">Dépannage</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>