<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Publier une annonce</h1>
	</div>
</div>
<div class="inner">
	<div class="grid" id="publier">
		<div class="left">
			<div class="progress">
				<h2 class="gray">Étapes</h2>
				<div class="progress-step" id="step-25"></div>
				<span>3 étapes restantes</span>
			</div>
			<div class="menu">
				<a href="#" class="btn btn-gray">1  Infos personnelles</a>
				<a href="#" class="btn btn-blue progress-menu-active">2  Garants</a>
				<a href="#" class="btn btn-gray">3  Vérification</a>
				<a href="#" class="btn btn-gray">4  Pièces de dossier</a>
			</div>
		</div>
		<div class="right">
			<div class="progress-content" id="content-step-2">
				<div class="step-title">
					<h1>Garants</h1>
					<span class="blue">Les garants ne sont pas obligatoires mais ils sont fortement conseillés.</span>
				</div>
				
				<div class="block-grid grid-dark">
					<h3 class="white">Moi</h3>
					<h4>Garant 1</h4>
					<div class="block-grid grid-inset" id="accept-block">
						<fieldset>
							<label>Garant <em class="red">(obligatoire)</em></label>
							<input type="radio" class="input-pretty" id="demo1" name="demo1" value="demo1" checked>
							<label for="demo1" class="btn-input-lite">Oui</label>
							<input type="radio" class="input-pretty" id="demo2" name="demo1" value="demo2">
							<label for="demo2" class="btn-input-lite">Non</label>
						</fieldset>
					</div>

					<div class="block-grid grid-inset" id="accept-block">
						<fieldset>
							<label>Lien avec le garant <em class="red">(obligatoire)</em></label>
							<div>
								<input type="checkbox" class="input-pretty" id="demo1" name="demo1" checked>
								<label for="demo1" class="btn-input-lite">Famille</label>
								<input type="checkbox" class="input-pretty" id="demo2" name="demo2">
								<label for="demo2" class="btn-input-lite">Ami(e)</label>
								<input type="checkbox" class="input-pretty" id="demo3" name="demo3">
								<label for="demo3" class="btn-input-lite">Employeur</label>
								<input type="checkbox" class="input-pretty" id="demo4" name="demo4">
								<label for="demo4" class="btn-input-lite">Banque</label>
							</div>
							<div>
								<input type="checkbox" class="input-pretty" id="demo5" name="demo5">
								<label for="demo5" class="btn-input-lite">Organisme</label>
							</div>
						</fieldset>
					</div>

					<div class="block-grid grid-inset" id="accept-block">
						<fieldset>
							<label>Revenu brut mensuel du garant <em class="red">(obligatoire)</em></label>
							<input type="text" value="1450" class="input-money">
						</fieldset>
					</div>

					<h4>Garant 2</h4>

					<div class="block-grid grid-inset" id="accept-block">
						<fieldset>
							<label>Lien avec le garant <em class="red">(obligatoire)</em></label>
							<div>
								<input type="checkbox" class="input-pretty" id="demo1" name="demo1">
								<label for="demo1" class="btn-input-lite">Famille</label>
								<input type="checkbox" class="input-pretty" id="demo2" name="demo2">
								<label for="demo2" class="btn-input-lite">Ami(e)</label>
								<input type="checkbox" class="input-pretty" id="demo3" name="demo3">
								<label for="demo3" class="btn-input-lite">Employeur</label>
								<input type="checkbox" class="input-pretty" id="demo4" name="demo4">
								<label for="demo4" class="btn-input-lite">Banque</label>
							</div>
							<div>
								<input type="checkbox" class="input-pretty" id="demo5" name="demo5" checked>
								<label for="demo5" class="btn-input-lite">Organisme</label>
							</div>
						</fieldset>
					</div>

					<div class="block-grid grid-inset" id="accept-block">
						<fieldset>
							<label>Nom de l'organisme <em class="red">(obligatoire)</em></label>
							<input type="text" style="width: 400px;" value="Aidologement">
						</fieldset>
					</div>


					<a href="#" class="btn btn-medium btn-gray btn-plus">Ajouter un garant</a>
				</div>

				<div class="block-grid grid-dark">
					<h3 class="white">Colocataire 1</h3>
					<h4>Garant 1</h4>

					<div class="block-grid grid-inset">
						<fieldset>
							<label>Garant <em class="red">(obligatoire)</em></label>
							<input type="radio" class="input-pretty" id="demo1" name="demo1" value="demo1">
							<label for="demo1" class="btn-input-lite">Oui</label>
							<input type="radio" class="input-pretty" id="demo2" name="demo1" value="demo2">
							<label for="demo2" class="btn-input-lite">Non</label>
						</fieldset>
					</div>

					<a href="#" class="btn btn-gray btn-plus">Ajouter un garant</a>
				</div>

				<div class="block-grid grid-dark">
					<h3 class="white">Colocataire 2</h3>
					<h4>Garant 1</h4>

					<div class="block-grid grid-inset">
						<fieldset>
							<label>Garant <em class="red">(obligatoire)</em></label>
							<input type="radio" class="input-pretty" id="demo1" name="demo1" value="demo1">
							<label for="demo1" class="btn-input-lite">Oui</label>
							<input type="radio" class="input-pretty" id="demo2" name="demo1" value="demo2">
							<label for="demo2" class="btn-input-lite">Non</label>
						</fieldset>
					</div>

					<a href="#" class="btn btn-medium btn-gray btn-plus">Ajouter un garant</a>
				</div>

				<div class="block-grid grid-dark">
					<h3 class="white">Colocataire 3</h3>
					<h4>Garant 1</h4>

					<div class="block-grid grid-inset">
						<fieldset>
							<label>Garant <em class="red">(obligatoire)</em></label>
							<input type="radio" class="input-pretty" id="demo1" name="demo1" value="demo1">
							<label for="demo1" class="btn-input-lite">Oui</label>
							<input type="radio" class="input-pretty" id="demo2" name="demo1" value="demo2">
							<label for="demo2" class="btn-input-lite">Non</label>
						</fieldset>
					</div>

					<a href="#" class="btn btn-medium btn-gray btn-plus">Ajouter un garant</a>
				</div>

				<div class="progress-buttons">
					<a href="#" class="btn btn-medium btn-gray btn-arrow-prev left">Étape précédente</a>
					<a href="#" class="btn btn-medium btn-blue btn-arrow-next right">Enregistrer et continuer</a>
				</div>
			</div>
		</div>
	</div>
</div>