<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Publier une annonce</h1>
	</div>
</div>
<div class="inner">
	<div class="grid" id="publier">
		<div class="left">
			<div class="progress">
				<h2 class="gray">Étapes</h2>
				<div class="progress-step" id="step-100"></div>
				<span>Votre annonce est</br>prête à être publiée</span>
			</div>
			<div class="menu">
				<a href="#" class="btn btn-gray">1  Infos personnelles</a>
				<a href="#" class="btn btn-gray">2  Garants</a>
				<a href="#" class="btn btn-gray">3  Vérification</a>
				<a href="#" class="btn btn-gray">4  Pièces de dossier</a>
				<a href="#" class="btn btn-red">Comptes OMMI</a>
			</div>
		</div>
		<div class="right">
			<div class="progress-content" id="content-step-0">
				<div class="block-grid grid-light-blue accept">
					<h2>Bravo ! Vous avez complété</br>votre dossier.</h2>
					<p>Vous pouvez désormais candidater aux annonces qui vous intéressent. </br>En quelques clics, organisez des visites et trouvez votre logement. </br>La concurrence est rude? Distinguez vous: </br>Vous pouvez mettre votre dossier en avant grâce aux options Ommi+ et Ommium.</p>
				</div>
				<div class="block-grid grid-inset-white">
					<h2 class="red">Profil avancé OMMI+</h2>
					<p class="black">Vous recherchez dans l’urgence ? Le compte <strong>OMMI+</strong> vous</br>permet, par catégorie, de relever votre annonce dans la pile</br>des candidatures que reçoit le propriétaire. Elle bénéficiera</br>ainsi d’un logo urgent et sortira du lot, pour vous faire trouver</br>plus rapidement votre logement.</p>
					<div class="block-price">
						<span>9,90 €</span>
						<a href="#" class="btn btn-medium btn-red w230 btn-plus-round">Souscrire à Ommi+</a>
					</div>
				</div>

				<div class="block-grid grid-inset-white">
					<h2 class="red">Profil certifié OMMIUM</h2>
					<p class="black">Tout est une question de garanties. Parce qu’à candidature</br>égale, le propriétaire choisira toujours le dossier qui offre le</br>plus de sûretés, <strong>OMMI</strong> vous propose le compte <strong>OMMIUM</strong> qui</br>certifie la qualité de votre dossier. Et comme la parole a un</br>prix, un dossier <strong>OMMIUM</strong> vous place en première position</br>par catégorie !</p>
					<div class="block-price">
						<span>19,90 €</span>
						<a href="#" class="btn btn-medium btn-red w230 btn-check-round">Souscrire à Ommium</a>
					</div>
				</div>

				<div class="progress-buttons">
					<a href="#" class="btn btn-medium btn-blue btn-search right">Publier mon annonce</a>
				</div>
			</div>
		</div>
	</div>
</div>