<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Tableau de bord</h1>
	</div>
</div>
<div class="inner">
	<div class="grid">
		<div class="page-tab-nav">
			<ul>
				<li><a href="">Résumé</a></li>
				<li><a href="">Mes annonces</a></li>
				<li><a href="">Mes candidats</a></li>
				<li><a href="">Mes services</a></li>
				<li><a href="" class="active">Mon compte</a></li>
			</ul>
		</div>
		<div id="compte" class="compte-01">
			<div class="left">
				<div class="menu">
					<a href="#" class="btn btn-gray">Sommaire</a>
					<a href="#" class="btn btn-gray">Mes parametres</a>
					<a href="#" class="btn btn-blue progress-menu-active">Mon compte</a>
					<a href="#" class="btn btn-gray">Bulletins d'information</a>
				</div>
			</div>
			<div class="right">
				<div class="progress-content">
					<div class="step-title">
						<h1>Mon profil</h1>
					</div>
					<div class="block-grid grid-inset">
						<fieldset>
							<label>Civilité</label>
							<div>
								<input type="checkbox" class="input-pretty" id="demo7" name="demo7" value="demo7">
								<label for="demo7" class="btn-input-lite">Mademoiselle</label>
								<input type="checkbox" class="input-pretty" id="demo8" name="demo8" value="demo8">
								<label for="demo8" class="btn-input-lite">Madame</label>
								<input type="checkbox" class="input-pretty" id="demo9" name="demo9" value="demo9">
								<label for="demo9" class="btn-input-lite">Monsieur</label>
							</div>
						</fieldset>
						<fieldset>
							<label>Prénom <em class="red">(obligatoire)</em></label>
							<input type="text" placeholder="Prénom actuel" style="width: 350px;">
						</fieldset>
						<fieldset>
							<label>Nom <em class="red">(obligatoire)</em></label>
							<input type="text" placeholder="Nom actuel" style="width: 350px;">
						</fieldset>
						<fieldset>
							<label>Adresse</label>
							<input type="text" placeholder="Numéro et voie" style="width: 350px;">
						</fieldset>
						<fieldset>
							<div class="left" style="width: 140px;">
								<label>Code postal</label>
								<input type="text" placeholder="Code postal" style="width: 100px;">
							</div>
							<div class="left">
								<label>Ville</label>
								<input type="text" placeholder="Ville" style="width: 210px;">
							</div>
						</fieldset>
						<fieldset>
							<label>Téléphone <em class="blue">(conseillé)</em></label>
							<input type="text" placeholder="Numéro de téléphone" style="width: 350px;">
						</fieldset>
					</div>
					<div class="step-title" style="margin-top: 40px;">
						<h1>Mon adresse email</h1>
						<span>Votre adresse email actuelle est : <span class="blue">monadresse@mail.com</span></span>
						<span>Vous pouvez la changer ci-dessous.</span>
					</div>
					<div class="block-grid grid-inset">
						<fieldset>
							<label>Nouvelle adresse email</label>
							<input type="text" placeholder="Nouvelle adresse email" style="width: 350px;">
							<span style="width: 250px;color: #b3b3b3;position: absolute;right: 20px;">Un mail de confirmation vous</br>sera envoyé afin de valider votre</br>nouvelle adresse.</span>
						</fieldset>
						<fieldset>
							<label>Mot de passe <em class="red">(obligatoire)</em></label>
							<input type="text" placeholder="Nom actuel" style="width: 350px;">
						</fieldset>
					</div>
					<div class="step-title" style="margin-top: 40px;">
						<h1>Mon mot de passe</h1>
						<span>Vous pouvez changer votre mot de passe ci-dessous.</span>
					</div>
					<div class="block-grid grid-inset">
						<fieldset>
							<label>Mot de passe actuel</label>
							<input type="password" placeholder="••••••••" style="width: 350px;">
							<span style="width: 250px;color: #b3b3b3;position: absolute;right: 20px;">Votre mot de passe doit contenir</br>au moins 8 caractères.</span>
						</fieldset>
						<fieldset>
							<label>Nouveau mot de passe</label>
							<input type="password" placeholder="••••••••" style="width: 350px;">
						</fieldset>
						<fieldset>
							<label>Confirmer le nouveau mot de passe</label>
							<input type="password" placeholder="••••••••" style="width: 350px;">
						</fieldset>
					</div>
					<div class="step-title" style="margin-top: 40px;">
						<h1>Supprimer</h1>
					</div>
					<div class="block-grid grid-inset">
						<a href="#" class="black">Supprimer mon compte Ommi</a>
					</div>
					<div class="progress-buttons">
						<a href="#" class="btn btn-red right">Enregistrer les modifications</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="grid">
		<div class="grid-full grid-full-other">
			<div class="grid-inner">
				<h1 class="gray"><span class="blue"> Pourquoi faire certifier</span><br>
					mon dossier par OMMI ?
				</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Partez avec un avantage décisif ! </br>En faisant certifier votre candidature, rassurez les propriétaires et sortez du lot. 
					</div>
					<div class="index-row-six-btn">
						<a href="#" class="right btn btn-blue w200">Certifier ma candidature</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="grid grid-transparent">
		<div class="grid-half grid-half-other">
			<div class="grid-inner">
				<h1 class="gray">Presse de trouver<br> un logement ?</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Découvrez nos comptes sur-mesure et<br>
						choisissez celui qui vous convient le mieux.<br>
						Donnez-vous les moyens de trouver vite.
					</div>
					<div class="index-row-six-link">
						<a href="#">Comples OMMI</a>
					</div>
				</div>
			</div>
		</div>

		<div class="grid-half grid-half-other">
			<div class="grid-inner">
				<h1 class="gray">Au secours !<br> Un depanneur ?</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Pas de panique! Profitez du réseau Ommi<br>
						de dépanneurs de confiance à prix d’ami !
						Programmez en ligne vos rendez-vous.
					</div>
					<div class="index-row-six-link">
						<a href="#">Dépannage</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>