<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Publier une annonce</h1>
	</div>
</div>
<div class="inner">
	<div class="grid" id="publier">
		<div class="left">
			<div class="progress">
				<h2 class="gray">Étapes</h2>
				<div class="progress-step" id="step-0"></div>
				<span>4 étapes restantes</span>
			</div>
			<div class="menu">
				<a href="#" class="btn btn-blue  progress-menu-active">1  Infos personnelles</a>
				<a href="#" class="btn btn-gray">2  Garants</a>
				<a href="#" class="btn btn-gray">3  Vérification</a>
				<a href="#" class="btn btn-gray">4  Pièces de dossier</a>
			</div>
		</div>
		<div class="right">
			<div class="progress-content" id="content-step-2">
				<div class="step-title">
					<h1>Informations personnelles</h1>
				</div>
				<div class="block-grid grid-inset">
					<fieldset>
						<label>Téléphone <em class="red">(conseillé)</em></label>
						<div>
							<input type="text" style="width: 300px;" class="input-phone">
						</div>
					</fieldset>
					<div style="margin-top: 10px;">
						<span class="gray">Votre numéro de téléphone est important pour organiser vos visites.</span></br>
						<span class="blue">Soyez rassuré, il n’est envoyé qu’aux candidats que vous acceptez.</span>
					</div>
				</div>
				<div class="step-title">
					<span class="blue">Les informations suivantes sont essentielles et donc obligatoires.</span>
					<span>Si il y a plusieurs personnes rattachés à ce dossier, pensez à compléter chaque profil.</span>
				</div>

				<div class="block-grid grid-inset">
					<fieldset>
						<label>Vous souhaitez candidater <em class="red">(obligatoire)</em></label>
							<input type="checkbox" class="input-pretty" id="demo1" name="demo1" value="demo1">
							<label for="demo1" class="btn-input-lite">Seul</label>
							<input type="checkbox" class="input-pretty" id="demo2" name="demo2" value="demo2">
							<label for="demo2" class="btn-input-lite">En couple</label>
							<input type="checkbox" class="input-pretty" id="demo3" name="demo3" value="demo3">
							<label for="demo3" class="btn-input-lite">En colocation</label>
					</fieldset>
				</div>

				<div class="block-grid grid-dark">
					<h3 class="white">Moi</h3>
					<div class="block-grid grid-inset">
						<fieldset>
							<label>Profil <em class="red">(obligatoire)</em></label>
								<input type="checkbox" class="input-pretty" id="demo1" name="demo1" value="demo1">
								<label for="demo1" class="btn-input-lite">Etudiant</label>
								<input type="checkbox" class="input-pretty" id="demo2" name="demo2" value="demo2">
								<label for="demo2" class="btn-input-lite">Salarie</label>
								<input type="checkbox" class="input-pretty" id="demo3" name="demo3" value="demo3">
								<label for="demo3" class="btn-input-lite">Independant</label>
								<input type="checkbox" class="input-pretty" id="demo3" name="demo3" value="demo3">
								<label for="demo3" class="btn-input-lite">Autre</label>
						</fieldset>
					</div>
				</div>

				<div class="progress-buttons">
					<a href="#" class="btn btn-medium btn-gray btn-arrow-prev left">Étape précédente</a>
					<a href="#" class="btn btn-medium btn-blue btn-arrow-next right">Enregistrer et continuer</a>
				</div>
			</div>
		</div>
	</div>
</div>