<div class="title-row-tabl">
	<div class="container-text box-text-tabl">
		<h1 class="white-txt">Tableau de bord</h1>
	</div>
</div>

<div class="inner">
<div class="grid">
<div class="menu-annonce menu-tabl">
	<ul>
		<li><a href="">Résumé</a></li>
		<li><a href="">Mon dossier</a></li>
		<li><a href="">Mes recherches</a></li>
		<li><a href="">Mes candidatures</a></li>
		<li><a href="" class="active">Mes services</a></li>
		<li><a href="">Mon compte</a></li>
	</ul>
</div>
<div class="tab-services tab-sommaire">
	<div class="box-nav-button">
		<a class="btn btn-gray active-blue" href="#">
			<i class="icon-right"></i>
			Sommaire
		</a>
		<a class="btn btn-gray icon-affairs" href="#">État des lieux</a>
		<a class="btn btn-gray icon-mail" href="#">Modèles de courrier</a>
		<a class="btn btn-red icon-repair" href="#">Professionnels</a>
	</div>
	<div class="box-right box-sommaire">
		<h2 class="gray">Sommaire</h2>
		<div class="inner-box">
			<div class="box-info-universal">
				<h2 class="gray">On peut vous rendre service ?</h2>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						<span class="blue">Pas de panique!</span> Profitez du réseau OMMI, des
						professionnels de confiance à prix d’ami ! Programmez en
						ligne vos rendez-vous et laissez-vous guider. Vous-êtes
						prévenus par mail et sur votre calendrier.
					</div>
					<div class="index-row-six-btn">
						<a class="btn btn-red" href="#">Professionnels</a>
					</div>
				</div>
			</div>
			<div class="box-info-universal">
				<h2 class="gray">Comment faire un état des lieux ?</h2>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						<span class="blue">Ça fait un bail et vous avez oublié? </span> OMMI met à votre
						disposition des exemples d’états des lieux et des conseils pour vous simplifier
						la location.
					</div>
					<div class="index-row-six-btn">
						<a class="btn btn-blue icon-pencil" href="#">Etats des lieux</a>
					</div>
				</div>
			</div>
			<div class="box-info-universal">
				<h2 class="gray">Comment rédiger un courrier ?</h2>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						<span class="blue">Les mots vous manquent pour le dire? </span> Retrouvez de
						nombreux modèles de lettres type pour gérer votre location en toute quiétude.
						Révision du loyer, Mise en Demeure, etc.
						Ils sont tous ici sur OMMI.
					</div>
					<div class="index-row-six-btn">
						<a class="btn btn-blue icon-mail" href="#">Modèles de courrier</a>
					</div>
				</div>
			</div>
		</div>
	</div>



</div>

</div>


<div class="grid">
	<div class="grid-full grid-full-other">
		<div class="grid-inner">
			<h1 class="gray"><span class="blue"> Pourquoi faire certifier</span><br>
				mon dossier par OMMI ?
			</h1>
			<div class="index-row-six cf">
				<div class="index-row-six-text">
					Partez avec un avantage décisif !<br>
					En faisant certifier votre candidature, rassurez les propriétaires et sortez du lot.
				</div>
				<div class="index-row-six-btn">
					<a href="#" class="right btn btn-blue w200">Certifier ma candidature</a>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="grid grid-transparent">
	<div class="grid-half grid-half-other">
		<div class="grid-inner">
			<h1 class="gray">Presse de trouver<br> un logement ?</h1>
			<div class="index-row-six cf">
				<div class="index-row-six-text">
					Découvrez nos comptes sur-mesure et<br>
					choisissez celui qui vous convient le mieux.<br>
					Donnez-vous les moyens de trouver vite.
				</div>
				<div class="index-row-six-link">
					<a href="#">Comples OMMI</a>
				</div>
			</div>
		</div>
	</div>

	<div class="grid-half grid-half-other">
		<div class="grid-inner">
			<h1 class="gray">Au secours !<br> Un depanneur ?</h1>
			<div class="index-row-six cf">
				<div class="index-row-six-text">
					Pas de panique! Profitez du réseau Ommi<br>
					de dépanneurs de confiance à prix d’ami !
					Programmez en ligne vos rendez-vous.
				</div>
				<div class="index-row-six-link">
					<a href="#">Dépannage</a>
				</div>
			</div>
		</div>
	</div>
</div>

</div>

