<div class="title-row">
	<div class="container-text">
		<h1 class="white-txt">Tableau de bord</h1>
	</div>
</div>
<main>
	<div class="inner">


		<div class="grid grid-dark">
			<div class="menu-annonce">
				<ul>
					<li><a href="" class="active">Résumé</a></li>
					<li><a href="">Mon dossier</a></li>
					<li><a href="">Mes recherches</a></li>
					<li><a href="">Mes candidatures</a></li>
					<li><a href="">Mes services</a></li>
					<li><a href="">Mon compte</a></li>
				</ul>
			</div>
			<div class="tab-resume">
				<div class="inner-transparent inner-left">
					<h2 class="black-txt">Profil</h2>
					<div class="box-info-universal">
						<h2 class="black-txt">Prénom Nom</h2>
						<span class="blue">monadresse@mail.com</span><br>
						<span class="red">profil Ommi+</span>
						<p>
							2 recherches<br>
							45 candidatures<br>
							10 candidatures acceptées
						</p>
						<a href="#" class="btn btn-gray">Compléter mon profil</a>
					</div>
					<h2 class="black-txt">Calendrier</h2>
					<div class="box-info-universal">
							<div class="calendar">
								<div class="name-month-calend">
									<h2>
										<a href="#" class="btn btn-gray-lite btn-cal-prev">
											<i class="i-group-gray icon-prev"></i>
										</a>
										Juillet
										<a href="#" class="btn btn-gray-lite name-month-next">
											<i class="i-group-gray icon-next"></i>
										</a>
									</h2>
								</div>
								<div class="inner-cell cell-month">
									<div class="cell">Lun</div>
									<div class="cell">Mar</div>
									<div class="cell">Mer</div>
									<div class="cell">Jeu</div>
									<div class="cell">Ven</div>
									<div class="cell">Sa</div>
									<div class="cell">Dim</div>
								</div>
								<div class="inner-cell">
									<div class="cell cell-gray">1</div>
									<div class="cell cell-gray">2</div>
									<div class="cell cell-gray">3</div>
									<div class="cell cell-gray">4</div>
									<div class="cell cell-gray">5</div>
									<div class="cell cell-gray">6</div>
									<div class="cell cell-gray">7</div>
								</div>
								<div class="inner-cell">
									<div class="cell cell-gray">8</div>
									<div class="cell cell-gray">9</div>
									<div class="cell cell-gray">10</div>
									<div class="cell cell-gray">11</div>
									<div class="cell cell-black">12</div>
									<div class="cell">13</div>
									<div class="cell">14</div>
								</div>
								<div class="inner-cell">
									<div class="cell">15</div>
									<div class="cell">16</div>
									<div class="cell cell-blue">17</div>
									<div class="cell">18</div>
									<div class="cell">19</div>
									<div class="cell">20</div>
									<div class="cell">21</div>
								</div>
								<div class="inner-cell">
									<div class="cell">22</div>
									<div class="cell cell-blue">23</div>
									<div class="cell cell-blue">24</div>
									<div class="cell">25</div>
									<div class="cell cell-blue">26</div>
									<div class="cell">27</div>
									<div class="cell">28</div>
								</div>
								<div class="inner-cell cell-bottom">
									<div class="cell">29</div>
									<div class="cell">30</div>
									<div class="cell">31</div>
									<div class="cell cell-next-month">1</div>
									<div class="cell cell-next-month">2</div>
									<div class="cell cell-next-month">3</div>
									<div class="cell cell-next-month">4</div>
								</div>
							</div>
						<div class="color-calendar">
							<img src="/./assets/images/date-visit.png">
							<span class="black">Visite</span>
							<img src="/./assets/images/date-free.png">
							<span class="black">Depannage</span>
						</div>
						<a href="#" class="btn btn-blue btn-voir">Voir  mes candidatures</a>
					</div>
				</div>
				<div class="inner-transparent inner-right">
					<h2 class="black-txt">Alertes</h2>
					<div class="box-info-universal">
						<div class="alert-gray w500">
							<a href="#" class="close-gray"></a>
							Vorte candidature pour l'annonce
							<span>[*.Titre de<br>l'annonce.*]</span> n'a pas ete retenue.
							<a href="#" class="gray">Voir</a>
						</div>
						<div class="alert-blue w500">
							<a href="#" class="close-blue"></a>
							Vorte candidature pour l'annonce [*.Titre de<br> l'annonce.*] n'a pas ete retenue.
						</div>
						<div class="alert-red w500">
							<a href="#" class="close-red"></a>
							Vorte candidature pour l'annonce [*.Titre de<br> l'annonce.*] n'a pas ete retenue.
						</div>
					</div>
				</div>


			</div>
			<div class="box-btn-nav-resume">
				<a href="#" class="btn btn-red">Profil Ommium</a>
				<a href="#" class="btn btn-blue">Dossier de candidature</a>
				<a href="#" class="btn btn-gray icon-book">Guide du Locataire</a>
				<a href="#" class="btn btn-gray icon-hand">J’ai trouvé mon appart !</a>
			</div>
		</div>

		<div class="grid grid-transparent">
			<div class="main-container-box">
				<div class="container-box">
					<div class="grid grid-block-big">
						<div class="triangle-left"></div>
						<div class="triangle-left triangle-second"></div>
						<h2 class="black-txt">Annonces similaires</h2>
						<p>Nous vous proposons ici d’autres annonces susceptibles de vous intéresser</p>
					</div>
				</div>
				<div class="container-box">
					<div class="grid grid-block">
						<div class="box-text info-box">
							<img src="/./assets/images/img-gallery-01.png" class="img-ad">
							<h3 class="title-ad">Appartement calme à Père-Lachaise</h3>
							<div>Appartement <span class="slash">|</span> Meublé<br>
								Paris 11e (75011)<br>
								Disponibilité : immédiate<br>
								Métro : Père-Lachaise
							</div>
						</div>
						<div class="box-text price-box">
							<p class="price-small">1200 €</p>
							<p>54 m²</p>
							<p>2 pièces</p>
						</div>
					</div>
					<div class="grid grid-block">
						<div class="box-text info-box">
							<img src="/./assets/images/img-gallery-02.png" class="img-ad">
							<h3 class="title-ad">Appartement entièrement rénové</h3>
							<div>Appartement <span class="slash">|</span> Meublé<br>
								Paris 11e (75011)<br>
								Disponibilité : 12/09/2013<br>
								Métro : Nation
							</div>
						</div>
						<div class="box-text price-box">
							<p class="price-small">1250 €</p>
							<p>54 m²</p>
							<p>2 pièces</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="grid">
			<div class="grid-full grid-full-other">
				<div class="grid-inner">
					<h1 class="gray"><span class="blue"> Pourquoi faire certifier</span><br>
						mon dossier par OMMI ?
					</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Partez avec un avantage décisif !<br>
							En faisant certifier votre candidature, rassurez les propriétaires et sortez du lot.
						</div>
						<div class="index-row-six-btn">
							<a href="#" class="right btn btn-blue w200">Certifier ma candidature</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="grid grid-transparent">
			<div class="grid-half grid-half-other">
				<div class="grid-inner">
					<h1 class="gray">Presse de trouver<br> un logement ?</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Découvrez nos comptes sur-mesure et<br>
							choisissez celui qui vous convient le mieux.<br>
							Donnez-vous les moyens de trouver vite.
						</div>
						<div class="index-row-six-link">
							<a href="#">Comples OMMI</a>
						</div>
					</div>
				</div>
			</div>

			<div class="grid-half grid-half-other">
				<div class="grid-inner">
					<h1 class="gray">Au secours !<br> Un depanneur ?</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Pas de panique! Profitez du réseau Ommi<br>
							de dépanneurs de confiance à prix d’ami !
							Programmez en ligne vos rendez-vous.
						</div>
						<div class="index-row-six-link">
							<a href="#">Dépannage</a>
						</div>
					</div>
				</div>
			</div>
		</div>

	</div>
</main>