<div class="title-row-metro">
	<div class="line-name">
		<img src="/./assets/images/line5.png">
		<p>
			Ligne 1
			<span>La Défense / Château de Vincennes</span>
		</p>
	</div>
	<div class="yellow-line-metro">
		<div class="main-name">
			<p>Nation</p>
		</div>
		<div class="name-line">
			<span class="line1">Gare de Lyon</span>
			<span class="line2">Reuilly - Diderot</span>
			<span class="line3">Porte de Vincennes</span>
			<span class="line4">Saint-Mandé</span>
		</div>
		<img src="/./assets/images/line-metro-yellow.png">
		<div class="line-number">
			<img src="/./assets/images/line1.png">
			<img src="/./assets/images/line2.png">
			<img src="/./assets/images/line3.png">
			<img src="/./assets/images/line4.png">
		</div>
	</div>
	<div class="container-text">
		<h1 class="white-txt">Résultats de ma recherche</h1>
		<p  class="txt-annonce">36 annonces trouvées</p>
		<a href="#" class="btn btn-gray">
			<i class="i-group-white icon-share-alt"></i>
			Modifier ma recherche
		</a>
		<a href="#" class="btn btn-gray">Nouvelle recherche</a>
		<a href="#" class="btn btn-red"><i class="icon-sauv"></i>Sauvegarder ma recherche</a>
		<a href="#" class="btn btn-blue"><i class="icon-bell-blue"></i>Créer une alerte</a>
	</div>
</div>
<main>
<div class="inner">


<div class="grid grid-transparent">
<div class="main-container-box">
<div class="container-box">
	<div class="grid grid-blue grid-block-search">
		<h2 class="name-txt">Ma recherche</h2>
		<span>Retrouvez ici les filtres <br>de votre recherche. </span>
		<div class="box-btn-choice">
			<a href="#" class="btn btn-gray btn-blue-dark btn-choice">
				Localisation
			</a>
			<a href="#" class="btn btn-gray btn-blue-dark btn-choice">
				Budget
			</a>
			<a href="#" class="btn btn-gray btn-blue-dark btn-choice">
				Surface
			</a>
			<a href="#" class="btn btn-gray btn-blue-dark btn-choice">
				Type de bien
			</a>
			<a href="#" class="btn btn-gray btn-blue-dark btn-choice">
				Mobilier
			</a>
		</div>
	</div>

	<div class="grid grid-dark grid-block-search">
		<h2 class="name-txt2">Affiner ma recherche</h2>
	</div>
	<div class="grid grid-dark grid-block-search">
		<div class="title-name">
			<span>Localisation</span>
			<a href="#" class="btn-up">
				<img src="/./assets/images/btn-up.png">
			</a>
		</div>
		<div class="box-btn-choice">
			<a href="#" class="btn btn-gray btn-blue-dark btn-choice">
				75011 - Paris 11e
			</a>
			<a href="#" class="btn btn-gray btn-blue-dark btn-choice">
				75011 - Paris 12e
			</a>
			<a href="#" class="btn btn-gray btn-blue-dark btn-choice">
				75010 - Château d’Eau
			</a>
			<input type="text" placeholder="Ajouter un lieu"/>
		</div>
	</div>
	<div class="grid grid-dark grid-block-search">
		<div class="title-name">
			<span>Budget</span>
			<a href="#" class="btn-up">
				<img src="/./assets/images/btn-up.png">
			</a>
		</div>
		<div class="box-price-btn">
			<a href="#" class="btn-input-gray-dark">200 €</a>
			<a href="#" class="btn-input-gray-dark">1500 €</a>
		</div>
	</div>
	<div class="grid grid-dark grid-block-search">
		<div class="title-name">
			<span>Surface</span>
			<a href="#" class="btn-up">
				<img src="/./assets/images/btn-up.png">
			</a>
		</div>

	</div>
	<div class="grid grid-dark grid-block-search">
		<div class="title-name">
			<span>Mobilier</span>
			<a href="#" class="btn-up">
				<img src="/./assets/images/btn-up.png">
			</a>
		</div>
		<form>
			<input type="reset" value="Tous" class="btn-tous-dark"/><br>
			<input type='radio' class="input-pretty" id='Choice1' name='Choice'>
			<label for='Choice1' class="btn-input-daker">Meublé</label>

			<input type='radio' class="input-pretty" id='Choice2' name='Choice'>
			<label for='Choice2' class="btn-input-daker">Vide</label>
		</form>
	</div>
	<div class="grid grid-dark grid-block-search">
		<div class="title-name">
			<span>Mobilier</span>
			<a href="#" class="btn-up">
				<img src="/./assets/images/btn-up.png">
			</a>
		</div>
		<form>
			<input type="reset" value="Tous" class="btn-tous-dark"/><br>
			<input type='checkbox' class="input-pretty" id='Choice1' name='Choice'>
			<label for='Choice1' class="btn-input-daker">Appartement</label>

			<input type='checkbox' class="input-pretty" id='Choice2' name='Choice'>
			<label for='Choice2' class="btn-input-daker">Maison</label>

			<input type='checkbox' class="input-pretty" id='Choice3' name='Choice'>
			<label for='Choice3' class="btn-input-daker">Studette</label>

			<input type='checkbox' class="input-pretty" id='Choice4' name='Choice'>
			<label for='Choice4' class="btn-input-daker">Loft / Atelier</label>

			<input type='checkbox' class="input-pretty" id='Choice5' name='Choice'>
			<label for='Choice5' class="btn-input-daker">Autre</label>
		</form>
	</div>
	<div class="grid grid-dark grid-block-search">
		<div class="title-name">
			<span>Disponibilité</span>
			<a href="#" class="btn-up">
				<img src="/./assets/images/btn-up.png">
			</a>
		</div>
		<form>
			<input type='radio' class="input-pretty" id='Choice3' name='Choice'>
			<label for='Choice3' class="btn-input-daker">Immédiatement</label><br>
			<span>ou à partir de</span>
			<div class="box-calend-search">
				<input type="text" placeholder="Date souhaitée"/>
				<a href="#" class="btn btn-small btn-dark">
					<i class="icon-calend"></i>
				</a>
			</div>
		</form>
	</div>
	<div class="grid grid-dark grid-block-search">
		<div class="title-name">
			<span>Durée du bail</span>
			<a href="#" class="btn-down">
				<img src="/./assets/images/btn-down.png">
			</a>
		</div>
	</div>
	<div class="grid grid-dark grid-block-search">
		<div class="title-name">
			<span>Aménagement</span>
			<a href="#" class="btn-down">
				<img src="/./assets/images/btn-down.png">
			</a>
		</div>
	</div>
	<div class="grid grid-dark grid-block-search">
		<div class="title-name">
			<span>Dépendances</span>
			<a href="#" class="btn-down">
				<img src="/./assets/images/btn-down.png">
			</a>
		</div>
	</div>
	<div class="grid grid-dark grid-block-search">
		<div class="title-name">
			<span>Immeuble</span>
			<a href="#" class="btn-down">
				<img src="/./assets/images/btn-down.png">
			</a>
		</div>
	</div>
	<div class="grid grid-dark grid-block-search">
		<div class="title-name">
			<span>Chauffage</span>
			<a href="#" class="btn-up">
				<img src="/./assets/images/btn-up.png">
			</a>
		</div>
		<form>
			<input type='checkbox' class="input-pretty" id='Choice6' name='Choice'>
			<label for='Choice6' class="btn-input-daker">Central / Collectif</label>

			<input type='checkbox' class="input-pretty" id='Choice7' name='Choice'>
			<label for='Choice7' class="btn-input-daker">Individuel</label>

			<input type='checkbox' class="input-pretty" id='Choice8' name='Choice'>
			<label for='Choice8' class="btn-input-daker">Au sol</label>

			<input type='checkbox' class="input-pretty" id='Choice9' name='Choice'>
			<label for='Choice9' class="btn-input-daker">Gaz</label>

			<input type='checkbox' class="input-pretty" id='Choice10' name='Choice'>
			<label for='Choice10' class="btn-input-daker">Électrique</label>

			<input type='checkbox' class="input-pretty" id='Choice11' name='Choice'>
			<label for='Choice11' class="btn-input-daker">Autre</label>
		</form>
	</div>
</div>
<div class="container-box">
<div class="grid grid-dark grid-block">
	<h2>Trier les résultats (36)</h2>
	<div class="box-btn-date">
		<span>Trier par</span>
		<a href="#" class="btn btn-dark btn-date">Date de publication</a>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-11.png" class="img-ad">
		<h3 class="title-ad">Joli appartement refait à neuf </h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			Paris 11e (75011)<br>
			<a href="#" class="btn btn-red-small small-btn">
				<i class="icon-urgent"></i>
				Urgent
			</a>
			Métro : Rue des Boulets, Nation<br>
			<a href="#">Voir sur une carte</a>
		</div>
	</div>
	<div class="box-text price-box bg-red">
		<p class="price-small">980 €</p>
		<p>39 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-13.png" class="img-ad">
		<h3 class="title-ad">Appartement calme à Père-Lachaise</h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			Paris 11e (75011)<br>
			Métro : Père-Lachaise
		</div>
		<a href="#">Voir sur une carte</a>
	</div>
	<div class="box-text price-box">
		<p class="price-small">1200 €</p>
		<p>54 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-12.png" class="img-ad">
		<h3 class="title-ad">Appartement entièrement rénové</h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			Paris 12e (75012)<br>
			<a href="#" class="btn btn-red-small small-btn">
				<i class="icon-urgent"></i>
				Urgent
			</a>
			Métro : Nation
		</div>
		<a href="#">Voir sur une carte</a>
	</div>
	<div class="box-text price-box bg-red">
		<p class="price-small">1250 €</p>
		<p>54 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-16.png" class="img-ad">
		<h3 class="title-ad">Appartement 2 pièces Haussmannien</h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			<div class="inner-box-right">
				<span class="txt-price">Honoraires : 1300 €</span>
				<a href="#" class="btn btn-gray btn-blue-dark small-btn">
					<i class="i-group-white icon-pro"></i>
					Pro
				</a>
			</div>
			Paris 10e (75010)<br>
			Métro : Château d’Eau
		</div>
		<a href="#">Voir sur une carte</a>
	</div>
	<div class="box-text price-box">
		<p class="price-small">1310 €</p>
		<p>47 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-14.png" class="img-ad">
		<h3 class="title-ad">Appartement XIIe - parfait étudiant</h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			Paris 12e (75012)<br>
			Métro : Daumesnil
		</div>
		<a href="#">Voir sur une carte</a>
	</div>
	<div class="box-text price-box">
		<p class="price-small">900 €</p>
		<p>30 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-15.png" class="img-ad">
		<h3 class="title-ad">Charmant 2 pièces lumineux et calme</h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			Paris 11e (75011)<br>
			Métro : Richard-Lenoir
		</div>
		<a href="#">Voir sur une carte</a>
	</div>
	<div class="box-text price-box">
		<p class="price-small">1280 €</p>
		<p>40 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-13.png" class="img-ad">
		<h3 class="title-ad">Appartement calme à Père-Lachaise</h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			<div class="inner-box-right">
				<span class="txt-price">Honoraires : 1200 €</span>
				<a href="#" class="btn btn-gray btn-blue-dark small-btn">
					<i class="i-group-white icon-pro"></i>
					Pro
				</a>
			</div>
			Paris 11e (75011)<br>
			Métro : Père-Lachaise
		</div>
		<a href="#">Voir sur une carte</a>
	</div>
	<div class="box-text price-box">
		<p class="price-small">1200 €</p>
		<p>54 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-12.png" class="img-ad">
		<h3 class="title-ad">Appartement entièrement rénové</h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			Paris 12e (75012)<br>
			Métro : Nation
		</div>
		<a href="#">Voir sur une carte</a>
	</div>
	<div class="box-text price-box">
		<p class="price-small">1250 €</p>
		<p>54 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-16.png" class="img-ad">
		<h3 class="title-ad">Appartement 2 pièces Haussmannien</h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			Paris 10e (75010)<br>
			Métro : Château d’Eau
		</div>
		<a href="#">Voir sur une carte</a>
	</div>
	<div class="box-text price-box">
		<p class="price-small">1310 €</p>
		<p>47 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-14.png" class="img-ad">
		<h3 class="title-ad">Appartement XIIe - parfait étudiant</h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			<div class="inner-box-right">
				<span class="txt-price">Honoraires : 800 €</span>
				<a href="#" class="btn btn-gray btn-blue-dark small-btn">
					<i class="i-group-white icon-pro"></i>
					Pro
				</a>
				<a href="#" class="btn btn-red-small small-btn">
					<i class="icon-urgent"></i>
					Urgent
				</a>
			</div>
			Paris 12e (75012)<br>

			Métro : Daumesnil
		</div>
		<a href="#">Voir sur une carte</a>
	</div>
	<div class="box-text price-box bg-red">
		<p class="price-small">900 €</p>
		<p>30 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-15.png" class="img-ad">
		<h3 class="title-ad">Charmant 2 pièces lumineux et calme</h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			Paris 11e (75011)<br>
			Métro : Richard-Lenoir
		</div>
		<a href="#">Voir sur une carte</a>
	</div>
	<div class="box-text price-box">
		<p class="price-small">1280 €</p>
		<p>40 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-13.png" class="img-ad">
		<h3 class="title-ad">Charmant 2 pièces lumineux et calme</h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			Paris 11e (75011)<br>
			Métro : Richard-Lenoir
		</div>
		<a href="#">Voir sur une carte</a>
	</div>
	<div class="box-text price-box">
		<p class="price-small">1280 €</p>
		<p>54 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-12.png" class="img-ad">
		<h3 class="title-ad">Appartement calme à Père-Lachaise</h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			Paris 11e (75011)<br>
			Métro : Père-Lachaise
		</div>
		<a href="#">Voir sur une carte</a>
	</div>
	<div class="box-text price-box">
		<p class="price-small">1200 €</p>
		<p>54 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-16.png" class="img-ad">
		<h3 class="title-ad">Appartement XIIe - parfait étudiant</h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			Paris 12e (75012)<br>
			Métro : Daumesnil
		</div>
		<a href="#">Voir sur une carte</a>
	</div>
	<div class="box-text price-box">
		<p class="price-small">900 €</p>
		<p>30 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-14.png" class="img-ad">
		<h3 class="title-ad">Appartement entièrement rénové</h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			Paris 12e (75012)<br>
			Métro : Nation
		</div>
		<a href="#">Voir sur une carte</a>
	</div>
	<div class="box-text price-box">
		<p class="price-small">1250 €</p>
		<p>54 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-block">
	<div class="box-text info-box">
		<img src="/./assets/images/img-gallery-15.png" class="img-ad">
		<h3 class="title-ad">Appartement 2 pièces Haussmannien</h3>
		<div>Appartement <span class="slash">|</span> Meublé<br>
			Paris 10e (75010)<br>
			Métro : Château d’Eau
		</div>
		<a href="#">Voir sur une carte</a>
	</div>
	<div class="box-text price-box">
		<p class="price-small">1310 €</p>
		<p>47 m²</p>
		<p>2 pièces</p>
	</div>
</div>
<div class="grid grid-dark grid-block">
	<p class="page-number">1 - 16 sur 36 annonces</p>
	<div class="box-btn-page">
		<a href="#" class="btn btn-dark btn-page active-page">1</a>
		<a href="#" class="btn btn-dark btn-page">2</a>
		<a href="#" class="btn btn-dark btn-page">3</a>
		<a href="#" class="btn btn-dark btn-page">
			<i class="icon-right"></i>
		</a>
	</div>
</div>
</div>
</div>
</div>

</div>
</main>