<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Tableau de bord</h1>
	</div>
</div>
<div class="inner">
	<div class="grid grid-dark-gray">
		<div class="page-tab-nav">
			<ul>
				<li><a href="" class="active">Résumé</a></li>
				<li><a href="">Mes annonces</a></li>
				<li><a href="">Mes candidats</a></li>
				<li><a href="">Mon compte</a></li>
			</ul>
		</div>
		<div class="page-tab-content">
			<div class="page-tab-content-left">
				
			</div>
			<div class="page-tab-content-right">
				
			</div>
		</div>
		<div class="page-tab-bottom">
			<a href="#" class="btn btn-red">Dépannage</a>
			<a href="#" class="btn btn-blue">Publier une annonce</a>
			<a href="#" class="btn btn-gray icon-book">Guide du Professionnel</a>
		</div>
	</div>

	<div class="grid">
		<div class="grid-full grid-full-other">
			<div class="grid-inner">
				<h1 class="gray"><span class="blue"> Pourquoi faire certifier</span><br>
					mon dossier par OMMI ?
				</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						OMMI s’engage, pour tous les candidats qui le souhaitent, à vérifier la cohérence</br>des dossiers de candidature et les certifie. Fini les mauvaises surprises !
					</div>
					<div class="index-row-six-btn">
						<a href="#" class="right btn btn-blue w200">Certifier ma candidature</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="grid grid-transparent">
		<div class="grid-half grid-half-other">
			<div class="grid-inner">
				<h1 class="gray">Presse de trouver<br> un logement ?</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Découvrez nos comptes sur-mesure et<br>
						choisissez celui qui vous convient le mieux.<br>
						Donnez-vous les moyens de trouver vite.
					</div>
					<div class="index-row-six-link">
						<a href="#">Comples OMMI</a>
					</div>
				</div>
			</div>
		</div>

		<div class="grid-half grid-half-other">
			<div class="grid-inner">
				<h1 class="gray">Au secours !<br> Un depanneur ?</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Pas de panique! Profitez du réseau Ommi<br>
						de dépanneurs de confiance à prix d’ami !
						Programmez en ligne vos rendez-vous.
					</div>
					<div class="index-row-six-link">
						<a href="#">Dépannage</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>