<div class="title-row-tabl">
	<div class="container-text">
		<h1 class="white-txt">Tableau de bord</h1>
	</div>
</div>
<div class="inner">
	<div class="grid grid-dark">
		<div class="menu-annonce menu-tabl">
			<ul>
				<li><a href="" class="active">Résumé</a></li>
				<li><a href="">Mon dossier</a></li>
				<li><a href="">Mes recherches</a></li>
				<li><a href="">Mes candidatures</a></li>
				<li><a href="">Mes services</a></li>
				<li><a href="">Mon compte</a></li>
			</ul>
		</div>
		<div class="tab-resume">
			<div class="inner-transparent inner-left">
				<h2 class="black-txt txt-small">Profil</h2>
				<div class="box-info-universal bg-circle">
					<h2 class="black-txt">Prénom Nom</h2>
					<span class="blue">monadresse@mail.com</span><br>
					<span class="red">profil Ommi+</span>
					<p>
						2 recherches<br>
						45 candidatures<br>
						10 candidatures acceptées
					</p>
					<a href="#" class="btn btn-gray">Compléter mon profil</a>
				</div>
				<h2 class="black-txt txt-small">Calendrier</h2>
				<div class="box-info-universal">
						<div class="calendar">
							<div class="name-month-calend">
								<h2>
									<a href="#" class="btn btn-gray-lite btn-cal-prev"></a>
									Juillet
									<a href="#" class="btn btn-gray-lite name-month-next"></a>
								</h2>
							</div>
							<div class="inner-cell cell-month">
								<div class="cell">Lun</div>
								<div class="cell">Mar</div>
								<div class="cell">Mer</div>
								<div class="cell">Jeu</div>
								<div class="cell">Ven</div>
								<div class="cell">Sa</div>
								<div class="cell">Dim</div>
							</div>
							<div class="inner-cell">
								<div class="cell cell-gray">1</div>
								<div class="cell cell-gray">2</div>
								<div class="cell cell-gray">3</div>
								<div class="cell cell-gray">4</div>
								<div class="cell cell-gray">5</div>
								<div class="cell cell-gray">6</div>
								<div class="cell cell-gray">7</div>
							</div>
							<div class="inner-cell">
								<div class="cell cell-gray">8</div>
								<div class="cell cell-gray">9</div>
								<div class="cell cell-gray">10</div>
								<div class="cell cell-gray">11</div>
								<div class="cell cell-black">12</div>
								<div class="cell">13</div>
								<div class="cell">14</div>
							</div>
							<div class="inner-cell">
								<div class="cell">15</div>
								<div class="cell">16</div>
								<div class="cell cell-blue">17</div>
								<div class="cell">18</div>
								<div class="cell">19</div>
								<div class="cell">20</div>
								<div class="cell">21</div>
							</div>
							<div class="inner-cell">
								<div class="cell">22</div>
								<div class="cell cell-blue">23</div>
								<div class="cell cell-blue">24</div>
								<div class="cell">25</div>
								<div class="cell cell-blue">26</div>
								<div class="cell">27</div>
								<div class="cell">28</div>
							</div>
							<div class="inner-cell cell-bottom">
								<div class="cell">29</div>
								<div class="cell">30</div>
								<div class="cell">31</div>
								<div class="cell cell-next-month">1</div>
								<div class="cell cell-next-month">2</div>
								<div class="cell cell-next-month">3</div>
								<div class="cell cell-next-month">4</div>
							</div>
						</div>
					<div class="color-calendar">
						<img src="/./assets/images/date-visit.png">
						<span class="black">Visite</span>
						<img src="/./assets/images/date-free.png">
						<span class="black">Depannage</span>
					</div>
					<a href="#" class="btn btn-blue btn-voir">Voir  mes candidatures</a>
				</div>
			</div>
			<div class="inner-transparent inner-right">
				<h2 class="black-txt txt-small">Alertes</h2>
				<div class="box-info-universal">
					<div class="alert-gray w500">
						<a href="#" class="close-gray"></a>
						<div class="text-box">
							Vorte candidature pour l'annonce
							<span class="bold-txt">[*.Titre de l'annonce.*]</span> n'a pas ete retenue.
						</div>
						<a href="#" class="black link-btn">Voir</a>
					</div>
					<div class="alert-blue w500">
						<a href="#" class="close-blue"></a>
						<div class="text-box">
							Connaissez-vous les avantages<br>du Compte OMMIUM ?
						</div>
						<a href="#" class="blue link-btn">Voir</a>
					</div>
					<div class="alert-red w500">
						<a href="#" class="close-red"></a>
						<div class="text-box">
							Rappel : Vous avez une visite programmee<br>
							le <span class="bold-txt">(jour mois)</span>
							a <span class="bold-txt">(heure)</span>
							pour l'annonce <span class="bold-txt"><br>[*Titre de l'annonce.*]</span>
						</div>
						<a href="#" class="red link-btn">Voir</a>
					</div>
				</div>
				<h2 class="black-txt txt-small">Mes candidatures récentes</h2>
				<div class="box-info-univ-black">
					<div class="grid grid-inner-item">
						<div class="box-text info-box">
							<img src="/./assets/images/img-gallery-13.png" class="item-img">
							<h3 class="item-title">Appartement calme à Père-Lachaise</h3>
							<div class="item-address">
								Paris 11e (75011)

							</div>
							<a class="btn small-btn btn-gray-small btn-item black" href="#">Non lue</a>
							<a href="#" class="black link-add">Voir l'annonce</a>
						</div>
						<div class="box-text price-box">
							<p class="price-small">1100 €</p>
							<p>47 m²</p>
							<p>2 pièces</p>
						</div>
					</div>
					<div class="grid grid-inner-item">
						<div class="box-text info-box">
							<img src="/./assets/images/img-gallery-12.png" class="item-img">
							<h3 class="item-title">Appartement entièrement rénové</h3>
							<div class="item-address">
								Bagnolet (93120)
							</div>
							<a class="btn small-btn btn-gray-small btn-item red" href="#">Refusee</a>
							<a href="#" class="black">Voir l'annonce</a>
						</div>
						<div class="box-text price-box">
							<p class="price-small">970 €</p>
							<p>39 m²</p>
							<p>2 pièces</p>
						</div>
					</div>
					<div class="grid grid-inner-item">
						<div class="box-text info-box">
							<img src="/./assets/images/img-gallery-12.png" class="item-img">
							<h3 class="item-title">Charmant meublé 2 pièces</h3>
							<div class="item-address">
								Paris 20e (75020)
							</div>
							<a class="btn small-btn btn-gray-small btn-item blue" href="#">Acceptee</a>
							<a href="#" class="black">Voir l'annonce</a>
						</div>
						<div class="box-text price-box">
							<p class="price-small">1030 €</p>
							<p>34 m²</p>
							<p>2 pièces</p>
						</div>
					</div>
					<a href="#" class="btn btn-blue btn-candid">Voir mes candidatures</a>
				</div>
				<h2 class="black-txt txt-small">Mes recherches récentes</h2>
				<div class="box-info-univ-black">
					<div class="grid grid-inner-item">
						<div class="box-text info-box">
							<h3 class="item-title">Appartement 2 pièces Paris centre 1200max</h3>
							<div>
								<input type="checkbox" class="input-pretty" id="Choice1" name="Choice"/>
								<label for="Choice1" class="btn-input-gray-lite">Localisation</label>

								<input type="checkbox" class="input-pretty" id="Choice2" name="Choice"/>
								<label for="Choice2" class="btn-input-gray-lite">Budget</label>

								<input type="checkbox" class="input-pretty" id="Choice3" name="Choice"/>
								<label for="Choice3" class="btn-input-gray-lite">Surface</label><br>

								<input type="checkbox" class="input-pretty" id="Choice4" name="Choice"/>
								<label for="Choice4" class="btn-input-gray-lite">Type de bien</label>

								<input type="checkbox" class="input-pretty" id="Choice5" name="Choice"/>
								<label for="Choice5" class="btn-input-gray-lite">Mobilier</label>
							</div>
							<div class="box-links-add">
								<a class="blue" href="#">Voir la recherche</a>
								<a class="black" href="#">Modifier la recherche</a>
							</div>
						</div>
						<div class="box-text price-box box-annonce">
							<p>22 annonces trouvees</p>
							<p>4 nouvelles annonces</p>
							<a class="red" href="#">Supprimer</a>
						</div>
					</div>
					<div class="grid grid-inner-item">
						<div class="box-text info-box">
							<h3 class="item-title">Appart 1100 max 2 pièces 30m2</h3>
							<div>
								<input type="checkbox" class="input-pretty" id="Choice6" name="Choice"/>
								<label for="Choice6" class="btn-input-gray-lite">Localisation</label>

								<input type="checkbox" class="input-pretty" id="Choice7" name="Choice"/>
								<label for="Choice7" class="btn-input-gray-lite">Budget</label>

								<input type="checkbox" class="input-pretty" id="Choice8" name="Choice"/>
								<label for="Choice8" class="btn-input-gray-lite">Surface</label><br>

								<input type="checkbox" class="input-pretty" id="Choice9" name="Choice"/>
								<label for="Choice9" class="btn-input-gray-lite">Type de bien</label>

								<input type="checkbox" class="input-pretty" id="Choice10" name="Choice"/>
								<label for="Choice10" class="btn-input-gray-lite">Mobilier</label>
							</div>
							<div class="box-links-add">
								<a class="blue" href="#">Voir la recherche</a>
								<a class="black" href="#">Modifier la recherche</a>
							</div>

						</div>
						<div class="box-text price-box box-annonce">
							<p>19 annonces trouvees</p>
							<p>6 nouvelles annonces</p>
							<a class="red" href="#">Supprimer</a>
						</div>
					</div>

					<a href="#" class="btn btn-blue btn-search">Voir mes recherches</a>
				</div>
			</div>


		</div>
		<div class="box-btn-nav-resume">
			<a href="#" class="btn btn-red">Profil Ommium</a>
			<a href="#" class="btn btn-blue">Dossier de candidature</a>
			<a href="#" class="btn btn-gray icon-book">Guide du Locataire</a>
			<a href="#" class="btn btn-gray icon-hand">J’ai trouvé mon appart !</a>
		</div>
	</div>


	<div class="grid">
		<div class="grid-full grid-full-other">
			<div class="grid-inner">
				<h1 class="gray"><span class="blue"> Pourquoi faire certifier</span><br>
					mon dossier par OMMI ?
				</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Partez avec un avantage décisif !<br>
						En faisant certifier votre candidature, rassurez les propriétaires et sortez du lot.
					</div>
					<div class="index-row-six-btn">
						<a href="#" class="right btn btn-blue w200">Certifier ma candidature</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="grid grid-transparent">
		<div class="grid-half grid-half-other">
			<div class="grid-inner">
				<h1 class="gray">Presse de trouver<br> un logement ?</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Découvrez nos comptes sur-mesure et<br>
						choisissez celui qui vous convient le mieux.<br>
						Donnez-vous les moyens de trouver vite.
					</div>
					<div class="index-row-six-link">
						<a href="#">Comples OMMI</a>
					</div>
				</div>
			</div>
		</div>

		<div class="grid-half grid-half-other">
			<div class="grid-inner">
				<h1 class="gray">Au secours !<br> Un depanneur ?</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Pas de panique! Profitez du réseau Ommi<br>
						de dépanneurs de confiance à prix d’ami !
						Programmez en ligne vos rendez-vous.
					</div>
					<div class="index-row-six-link">
						<a href="#">Dépannage</a>
					</div>
				</div>
			</div>
		</div>
	</div>

</div>