<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Publier une annonce</h1>
	</div>
</div>
<div class="inner">
	<div class="grid" id="publier">
		<div class="left">
			<div class="progress">
				<h2 class="gray">Étapes</h2>
				<div class="progress-step" id="step-0"></div>
				<span>5 étapes restantes</span>
			</div>
			<div class="menu">
				<a href="#" class="btn btn-gray">1  Location</a>
				<a href="#" class="btn btn-gray">2  Description</a>
				<a href="#" class="btn btn-gray">3  Photos</a>
				<a href="#" class="btn btn-gray">4  Profil recherché</a>
				<a href="#" class="btn btn-gray">5  Dates de visite</a>
			</div>
		</div>
		<div class="right">
			<div class="progress-content" id="content-step-0">
				<div class="block-grid grid-light-blue">
					<h2>La location</h2>
					<p>Définissez les éléments essentiels de votre annonce.</br>Titre, montant du loyer, etc… tels qu’ils appaent aux candidats.</p>
					<span>1</span>
				</div>
				<div class="block-grid grid-light-blue">
					<h2>Décrire le bien</h2>
					<p>Décrivez les caractéristiques spécifiques de votre bien.</br>Le tout, en quelques clics.</p>
					<span>2</span>
				</div>
				<div class="block-grid grid-light-blue">
					<h2>Ajouter des photos</h2>
					<p>Les bonnes photos attirent les bons candidats.</br>Pensez-y.</p>
					<span>3</span>
				</div>
				<div class="block-grid grid-light-blue">
					<h2>Profil recherché</h2>
					<p>Vous préférez louer à un étudiant ? Un salarié ? Un indépendant ?</br>Donnez vos préférences, vos candi</p>
					<span>4</span>
				</div>
				<div class="block-grid grid-light-blue">
					<h2>Définir des visites</h2>
					<p>Sélectionnez les dates de visite qui vous conviennent.</br>Les candidats postuleront pour l’une d’entre</p>
					<span>5</span>
				</div>
				<div class="progress-buttons">
					<!--<a href="#" class="btn btn-gray btn-arrow-prev left">Commencer</a>-->
					<a href="#" class="btn btn-red btn-arrow-next right">Commencer</a>
				</div>
			</div>
		</div>
	</div>
</div>