<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Tableau de bord</h1>
	</div>
</div>
<div class="inner">
	<div class="grid">
		<div class="page-tab-nav">
			<ul>
				<li><a href="">Résumé</a></li>
				<li><a href="">Mes annonces</a></li>
				<li><a href="">Mes candidats</a></li>
				<li><a href="" class="active">Mes services</a></li>
				<li><a href="">Mon compte</a></li>
			</ul>
		</div>
		<div id="publier">
			<div class="left">
				<div class="menu">
					<a href="#" class="btn btn-gray">Sommaire</a>
					<a href="#" class="btn btn-gray btn-energy">Diagnostic énergétique</a>
					<a href="#" class="btn btn-gray btn-mail">Modèles de courrier</a>
					<a href="#" class="btn btn-gray btn-file">Modèles de contrats</a>
					<a href="#" class="btn btn-blue btn-edit progress-menu-active">État des lieux</a>
					<a href="#" class="btn btn-red btn-pro">Professionnels</a>
				</div>
			</div>
			<div class="right">
				<div class="progress-content">
					<div class="step-title">
						<h1>Modèles de contrats</h1>
						<span class="blue">OMMI a pensé à tout !</span>
						<span>Pour vous simplifier la vie, nous mettons à votre disposition nos modèles de contrat. Pas</br>besoin de chercher plus loin : Vous n’avez plus qu’à remplir les champs qui vous</br>concernent.</span>
					</div>
					<div class="block-grid grid-set-gray">
						<fieldset>
							<label>Modèles de contrat à télécharger</label>
							<div class="block-file">
								<a href="#" class="btn btn-blue btn-file" id="file">Contrat de bail - Meublé</a>
								<a href="#" class="btn btn-red btn-download" id="file-download">&nbsp;</a>
								<span>Pour vos logements meublés.</span>
							</div>
							<div class="block-file">
								<a href="#" class="btn btn-blue btn-file" id="file">Contrat de bail - Vide</a>
								<a href="#" class="btn btn-red btn-download" id="file-download">&nbsp;</a>
								<span>Pour vos logements vides.</span>
							</div>
						</fieldset>
					</div>

					<div class="block-grid grid-set-gray">
						<fieldset>
							<label>Modèles de contrat à télécharger</label>
							<div class="block-file">
								<a href="#" class="btn btn-blue btn-file" id="file">État des lieux</a>
								<a href="#" class="btn btn-red btn-download" id="file-download">&nbsp;</a>
							</div>
						</fieldset>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>