<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Tableau de bord</h1>
	</div>
</div>
<div class="inner">
	<div class="grid">
		<div class="page-tab-nav">
			<ul>
				<li><a href="">Résumé</a></li>
				<li><a href="">Mes annonces</a></li>
				<li><a href="">Mes candidats</a></li>
				<li><a href="">Mes services</a></li>
				<li><a href="" class="active">Mon compte</a></li>
			</ul>
		</div>
		<div id="compte" class="compte-01">
			<div class="left">
				<div class="menu">
					<a href="#" class="btn btn-gray">Sommaire</a>
					<a href="#" class="btn btn-blue progress-menu-active">Mes parametres</a>
					<a href="#" class="btn btn-gray">Mon compte</a>
					<a href="#" class="btn btn-gray">Bulletins d'information</a>
				</div>
			</div>
			<div class="right">
				<div class="progress-content">
					<div class="step-title">
						<h1>Notifications des candidatures</h1>
						<span>Ommi vous avertit par email lorsque vous recevez de nouvelles candidatures.</span>
						<span class="blue">Vous pouvez régler la fréquence de ces notifications.</span>
					</div>
					<div class="block-grid grid-inset">
						<fieldset>
							<label>Résumé des nouvelles candidatures</label>
							<div>
								<input type="checkbox" class="input-pretty" id="demo7" name="demo7" value="demo7" checked>
								<label for="demo7" class="btn-input-lite">Chaque jour</label>
								<input type="checkbox" class="input-pretty" id="demo8" name="demo8" value="demo8">
								<label for="demo8" class="btn-input-lite">Un jour sur deux</label>
								<input type="checkbox" class="input-pretty" id="demo9" name="demo9" value="demo9">
								<label for="demo9" class="btn-input-lite">Une fois par semaine</label>
								<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
								<label for="demo10" class="btn-input-lite">Jamais</label>
							</div>
						</fieldset>
					</div>
					<div class="step-title" style="margin-top: 40px;">
						<h1>Notifications des alertes</h1>
						<span>
							Ommi vous accompagne et veille à que vous trouviez un locataire, c'est pourquoi</br>Ommi vous avertit par email lorsque vous devez prendre connaissance d'un</br>évènement important ou lorsque de nouveaux candidats correspondent à vos</br>critères. <span class="blue">Vous pouvez régler la fréquence de ces notifications.</span>
						</span>
					</div>
					<div class="block-grid grid-inset">
						<fieldset>
							<label>Résumé des alertes importantes</label>
							<div>
								<input type="checkbox" class="input-pretty" id="demo7" name="demo7" value="demo7">
								<label for="demo7" class="btn-input-lite">Chaque jour</label>
								<input type="checkbox" class="input-pretty" id="demo8" name="demo8" value="demo8">
								<label for="demo8" class="btn-input-lite">Un jour sur deux</label>
								<input type="checkbox" class="input-pretty" id="demo9" name="demo9" value="demo9" checked>
								<label for="demo9" class="btn-input-lite">Une fois par semaine</label>
								<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
								<label for="demo10" class="btn-input-lite">Jamais</label>
							</div>
						</fieldset>
					</div>
					<div class="step-title" style="margin-top: 40px;">
						<h1>Notifications des alertes et rendez-vous</h1>
						<span>Ommi peut vous rappeler à l’avance vos visites et vos rendez-vous.</span>
						<span class="blue">Vous pouvez régler ces notifications et sélectionner plusieurs choix.</span>
					</div>
					<div class="block-grid grid-inset">
						<fieldset>
							<label>Rappel des visites et rendez-vous</label>
							<div>
								<input type="checkbox" class="input-pretty" id="demo7" name="demo7" value="demo7" checked>
								<label for="demo7" class="btn-input-lite">5 heures avant</label>
								<input type="checkbox" class="input-pretty" id="demo8" name="demo8" value="demo8" checked>
								<label for="demo8" class="btn-input-lite">1 jour avant</label>
								<input type="checkbox" class="input-pretty" id="demo9" name="demo9" value="demo9">
								<label for="demo9" class="btn-input-lite">1 semaine avant</label>
							</div>
						</fieldset>
					</div>
					<div class="progress-buttons">
						<a href="#" class="btn btn-red right">Enregistrer les modifications</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="grid">
		<div class="grid-full grid-full-other">
			<div class="grid-inner">
				<h1 class="gray"><span class="blue"> Pourquoi faire certifier</span><br>
					mon dossier par OMMI ?
				</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						OMMI s’engage, pour tous les candidats qui le souhaitent, à vérifier la cohérence</br>des dossiers de candidature et les certifie. Fini les mauvaises surprises !
					</div>
					<div class="index-row-six-btn">
						<a href="#" class="right btn btn-blue w200">Certifier ma candidature</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="grid grid-transparent">
		<div class="grid-half grid-half-other">
			<div class="grid-inner">
				<h1 class="gray">Presse de trouver<br> un logement ?</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Découvrez nos comptes sur-mesure et<br>
						choisissez celui qui vous convient le mieux.<br>
						Donnez-vous les moyens de trouver vite.
					</div>
					<div class="index-row-six-link">
						<a href="#">Comples OMMI</a>
					</div>
				</div>
			</div>
		</div>

		<div class="grid-half grid-half-other">
			<div class="grid-inner">
				<h1 class="gray">Au secours !<br> Un depanneur ?</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Pas de panique! Profitez du réseau Ommi<br>
						de dépanneurs de confiance à prix d’ami !
						Programmez en ligne vos rendez-vous.
					</div>
					<div class="index-row-six-link">
						<a href="#">Dépannage</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>