<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Publier une annonce</h1>
	</div>
</div>
<div class="inner">
	<div class="grid" id="publier">
		<div class="left">
			<div class="progress">
				<h2 class="gray">Étapes</h2>
				<div class="progress-step" id="step-2"></div>
				<span>3 étapes restantes</span>
			</div>
			<div class="menu">
				<a href="#" class="btn btn-gray">1  Location</a>
				<a href="#" class="btn btn-gray">2  Description</a>
				<a href="#" class="btn btn-blue  progress-menu-active">3  Photos</a>
				<a href="#" class="btn btn-gray">4  Profil recherché</a>
				<a href="#" class="btn btn-gray">5  Dates de visite</a>
			</div>
		</div>
		<div class="right">
			<div class="progress-content" id="content-step-2">
				<div class="step-title">
					<h1>Photos de l’annonce</h1>
				</div>
				<div class="block-grid grid-inset">
					<fieldset>
						<label>Téléchargement des photos <em class="red">(obligatoire)</em></label>
						<div class="upload-photos">
							<a href="" class="btn btn-red" id="upload-btn">Sélectionner une photo</br>sur mon ordinateur</a>
							<span class="separator">ou</span>
							<div class="upload-area">Glisser et déposer une photo</br>ici pour la télécharger</div>
						</div>
					</fieldset>
					<div class="left" style="margin-top: 10px;">
						<span class="blue">Les photos sont importantes sur OMMI.</span></br>
						<span class="gray">Elles aident les bons candidats à se faire une meilleure idée de votre bien.</br>Ne les chargez qu’une seule fois : </br>pour votre confort, OMMI les garde en mémoire pour de prochaines locations.</span>
					</div>
				</div>

				<div class="block-grid grid-inset">
					<fieldset>
						<label>Choisir la photo principale de l’annonce</label>
						<div class="uploaded-photos">
							<div class="uploaded-photo">
								<input type="checkbox" name="photo1" id="photo1">
								<label for="photo1">
									<img src="/assets/images/none.png">
									<span>1</span>
								</label>
							</div>
							<div class="uploaded-photo">
								<input type="checkbox" name="photo2" id="photo2">
								<label for="photo2">
									<img src="/assets/images/none.png">
									<span>2</span>
								</label>
							</div>
						</div>
					</fieldset>
				</div>

				<div class="progress-buttons">
					<a href="#" class="btn btn-medium btn-gray btn-arrow-prev left">Étape précédente</a>
					<a href="#" class="btn btn-medium btn-blue btn-arrow-next right">Enregistrer et continuer</a>
				</div>
			</div>
		</div>
	</div>
</div>