<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Publier une annonce</h1>
	</div>
</div>
<div class="inner">
	<div class="grid" id="publier">
		<div class="left">
			<div class="progress">
				<h2 class="gray">Étapes</h2>
				<div class="progress-step" id="step-0"></div>
				<span>5 étapes restantes</span>
			</div>
			<div class="menu">
				<a href="#" class="btn btn-blue progress-menu-active">1  Location</a>
				<a href="#" class="btn btn-gray">2  Description</a>
				<a href="#" class="btn btn-gray">3  Photos</a>
				<a href="#" class="btn btn-gray">4  Profil recherché</a>
				<a href="#" class="btn btn-gray">5  Dates de visite</a>
			</div>
		</div>
		<div class="right">
			<div class="progress-content" id="content-step-1">
				<div class="step-title">
					<h1>Location</h1>
				</div>
				<div class="block-grid grid-inset">
					<fieldset>
						<label>Titre de l’annonce <em class="red">(obligatoire)</em></label>
						<input type="text" class="w300">
						<span class="helper">36 caractères restants</span>
						<p class="description">Titre de votre annonce tel qu’il va être vu par tous.</br>Décrivez le plus fidèlement possible ce que vous offrez.</p>
					</fieldset>
				</div>
				<div class="block-grid grid-inset">
					<div class="left">
						<fieldset>
							<label>Montant du loyer hors charges <em class="red">(obligatoire)</em></label>
							<input type="text" placeholder="Montant en euros" class="input-money">
							<p class="description">Indiquez les montants du loyer demandé et des charges.</br>Ceux-ci pourront être modifiés à tout moment.</p>
						</fieldset>
					</div>
					<div class="left">
						<fieldset>
							<label>Montant des charges <em class="red">(obligatoire)</em></label>
							<input type="text" placeholder="Montant en euros" class="input-money">
						</fieldset>
					</div>
				</div>
				<div class="block-grid grid-inset">
					<fieldset>
						<label>Mobilier <em class="red">(obligatoire)</em></label>
						<input type="checkbox" class="input-pretty" id="demo1" name="demo1" value="demo1">
						<label for="demo1" class="btn-input-lite">Meuble</label>
						<input type="checkbox" class="input-pretty" id="demo2" name="demo2" value="demo2">
						<label for="demo2" class="btn-input-lite">Vide</label>
					</fieldset>
				</div>
				<div class="block-grid grid-inset">
					<fieldset>
						<label>Durée du bail <em class="red">(obligatoire)</em></label>
						<select name="" id=""></select>
					</fieldset>
				</div>
				<div class="block-grid grid-inset">
					<fieldset>
						<input type="checkbox" class="input-pretty" id="demo3" name="demo3" value="demo3">
						<label for="demo3" class="btn-input-lite">1 mois</label>
						<input type="checkbox" class="input-pretty" id="demo4" name="demo4" value="demo4">
						<label for="demo4" class="btn-input-lite">2 mois</label>
					</fieldset>
				</div>
				<div class="block-grid grid-inset">
					<fieldset>
						<label>Dépôt de garantie <em class="red">(obligatoire)</em></label>
						<input type="radio" class="input-pretty" id="demo5" name="demo5" value="demo5">
						<label for="demo5" class="btn-input-lite">Immédiate</label>
						<span class="separator">ou à partir de</span>
						<input type="text" placeholder="Sélectionner une date" class="input-date">
					</fieldset>
				</div>
				<div class="progress-buttons">
					<a href="#" class="btn btn-blue btn-medium btn-arrow-next right">Enregistrer et continuer</a>
				</div>
			</div>
		</div>
	</div>
</div>