<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Tableau de bord</h1>
	</div>
</div>
<div class="inner">
	<div class="grid">
		<div class="page-tab-nav">
			<ul>
				<li><a href="">Résumé</a></li>
				<li><a href="">Mes annonces</a></li>
				<li><a href="">Mes candidats</a></li>
				<li><a href="">Mes services</a></li>
				<li><a href="" class="active">Mon compte</a></li>
			</ul>
		</div>
		<div id="publier">
			<div class="left">
				<div class="menu">
					<a href="#" class="btn btn-blue progress-menu-active">Sommaire</a>
					<a href="#" class="btn btn-gray btn-gears">Mes paramètres</a>
					<a href="#" class="btn btn-gray btn-lock">Mon compte</a>
					<a href="#" class="btn btn-gray btn-disk">Bulletins d’information</a>
				</div>
			</div>
			<div class="right">
				<div class="progress-content">
					<div class="step-title">
						<h1>Sommaire</h1>
					</div>
					<div class="block-grid grid-inset-white block-service">
						<h2 class="gray"><span class="red">Mes paramètres :</span> Notifications</h2>
						<p class="black">
							<span>Vous recevez actuellement :</span></br>
							<span>• Nouvelles candidatures : Quotidien</span></br>
							<span>• Alertes : Hebdomadaire</span></br>
							<span>• Rendez-vous : 1 jour avant, 5 heures avant</span>
						</p>
						<div class="block-btn">
							<a href="#" class="btn btn-medium btn-red btn-gears">Mes paramètres</a>
						</div>
					</div>

					<div class="block-grid grid-inset-white block-service">
						<h2 class="gray"><span class="blue">Mon compte :</span> Profil et sécurité</h2>
						<p class="black">
							<span>Prénom Nom</span></br>
							<span>monadresse@mail.com</span></br>
							<span>numéro de telephone</span>
						</p>
						<div class="block-btn">
							<a href="#" class="btn btn-medium btn-blue btn-lock">Modifier mon compte</a>
						</div>
					</div>

					<div class="block-grid grid-inset-white block-service">
						<h2 class="gray"><span class="blue">Bulletin d’informations :</span></br>Restons en contact !</h2>
						<p class="black">
							<span>Vous êtes inscrit à :</span></br>
							<span>• La newsletter <strong>Ommi</strong></span></br>
						</p>
						<div class="block-btn">
							<a href="#" class="btn btn-medium btn-blue btn-disk">Mes abonnements</a>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>