<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Publier une annonce</h1>
	</div>
</div>
<div class="inner">
	<div class="grid" id="publier">
		<div class="left">
			<div class="progress">
				<h2 class="gray">Étapes</h2>
				<div class="progress-step" id="step-4"></div>
				<span>1 étapes restantes</span>
			</div>
			<div class="menu">
				<a href="#" class="btn btn-gray">1  Location</a>
				<a href="#" class="btn btn-gray">2  Description</a>
				<a href="#" class="btn btn-gray">3  Photos</a>
				<a href="#" class="btn btn-gray">4  Profil recherché</a>
				<a href="#" class="btn btn-blue  progress-menu-active">5  Dates de visite</a>
			</div>
		</div>
		<div class="right">
			<div class="progress-content" id="content-step-2">
				<div class="step-title">
					<h1>Dates de visite</h1>
				</div>
				<div class="block-grid grid-inset">
					<fieldset>
						<label>Téléphone <em class="blue">(conseillé)</em></label>
						<div>
							<input type="text" style="width: 300px;">
						</div>
					</fieldset>
					<div style="margin-top: 10px;">
						<span class="gray">Votre numéro de téléphone est important pour organiser vos visites.</span></br>
						<span class="blue">Soyez rassuré, il n’est envoyé qu’aux candidats que vous acceptez.</span>
					</div>
				</div>

				<div class="block-grid grid-inset">
					<fieldset>
						<label>Calendier</label>
						<div>тут календарь</div>
					</fieldset>
					<div style="margin-top: 10px;">
						<span class="gray">Choisissez vos dates de visites à l’avance.</br>Vous conviendrez de l’horaire avec vos candidats, ultérieurement.</span></br>
						<span class="red">Vous devez définir au moins une date de visite.</span>
					</div>
				</div>

				<div class="block-grid grid-inset">
					<fieldset>
						<label>Dates de visite <em class="red">(obligatoire)</em></label>
						<div class="block-grid grid-gray">
							<div class="left" style="width: 260px;">
								<fieldset>
									<label>Date</label>
									<div class="labels-group">
										<input type="radio" class="input-pretty" value="date" name="availability_select" id="availability_select_date">
										<label for="availability_select_date" class="btn-input-gray-lite">Sélectionner une date</label>
										<label for="availability_select_date" class="btn-input-gray-lite label-date icon-calendar-gray"></label>
									</div>
								</fieldset>
							</div>
							<div class="left">
								<ul style="list-style: none; color: #198E9C; margin: 23px 0 0 0; padding: 0;">
									<li>1.Vous fixez le jour.</li>
									<li>2.Vos candidats vous proposeront une plage horaire.</li>
									<li>3.Vous choisirez l’heure du rendez vous.</li>
								</ul>
							</div>
						</div>
					</fieldset>
					<div style="margin-top: 10px;">
						<span class="gray">Passée la dernière date de visite, votre annonce ne sera plus visible.</span></br>
						<span class="red">Pensez à en prévoir suffisamment.</span>
					</div>
				</div>

				<div class="progress-buttons">
					<a href="#" class="btn btn-gray btn-arrow-prev left">Étape précédente</a>
					<a href="#" class="btn btn-blue btn-arrow-next right">Enregistrer et continuer</a>
				</div>
			</div>
		</div>
	</div>
</div>