<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Publier une annonce</h1>
	</div>
</div>
<div class="inner">
	<div class="grid" id="publier">
		<div class="left">
			<div class="progress">
				<h2 class="gray">Étapes</h2>
				<div class="progress-step" id="step-4"></div>
				<span>1 étapes restantes</span>
			</div>
			<div class="menu">
				<a href="#" class="btn btn-gray">1  Location</a>
				<a href="#" class="btn btn-gray">2  Description</a>
				<a href="#" class="btn btn-gray">3  Photos</a>
				<a href="#" class="btn btn-gray">4  Profil recherché</a>
				<a href="#" class="btn btn-blue  progress-menu-active">5  Dates de visite</a>
			</div>
		</div>
		<div class="right">
			<div class="progress-content" id="content-step-2">
				<div class="step-title">
					<h1>Dates de visite</h1>
				</div>
				<div class="block-grid grid-inset">
					<fieldset>
						<label>Téléphone <em class="blue">(conseillé)</em></label>
						<div>
							<input type="text" style="width: 300px;" class="input-phone">
						</div>
					</fieldset>
					<div style="margin-top: 10px;">
						<span class="gray">Votre numéro de téléphone est important pour organiser vos visites.</span></br>
						<span class="blue">Soyez rassuré, il n’est envoyé qu’aux candidats que vous acceptez.</span>
					</div>
				</div>

				<div class="block-grid grid-inset">
					<fieldset>
						<label>Calendier</label>
						<div class="content-tab-inner">
							<div class="block-calendar">
								<div class="calendar">
									<div class="name-month-calend">
										<h2>
											<a href="#" class="btn btn-gray btn-gray-lite btn-cal-prev">
												<i class="i-group-gray icon-prev"></i>
											</a>
											Juillet
										</h2>
									</div>
									<div class="inner-cell cell-month">
										<div class="cell">Lun</div>
										<div class="cell">Mar</div>
										<div class="cell">Mer</div>
										<div class="cell">Jeu</div>
										<div class="cell">Ven</div>
										<div class="cell">Sa</div>
										<div class="cell">Dim</div>
									</div>
									<div class="inner-cell">
										<div class="cell cell-gray">1</div>
										<div class="cell cell-gray">2</div>
										<div class="cell cell-gray">3</div>
										<div class="cell cell-gray">4</div>
										<div class="cell cell-gray">5</div>
										<div class="cell cell-gray">6</div>
										<div class="cell cell-gray">7</div>
									</div>
									<div class="inner-cell">
										<div class="cell cell-gray">8</div>
										<div class="cell cell-gray">9</div>
										<div class="cell cell-gray">10</div>
										<div class="cell cell-gray">11</div>
										<div class="cell cell-black">12</div>
										<div class="cell">13</div>
										<div class="cell">14</div>
									</div>
									<div class="inner-cell">
										<div class="cell">15</div>
										<div class="cell">16</div>
										<div class="cell">17</div>
										<div class="cell">18</div>
										<div class="cell">19</div>
										<div class="cell">20</div>
										<div class="cell">21</div>
									</div>
									<div class="inner-cell">
										<div class="cell">22</div>
										<div class="cell cell-blue">23</div>
										<div class="cell">24</div>
										<div class="cell">25</div>
										<div class="cell">26</div>
										<div class="cell">27</div>
										<div class="cell">28</div>
									</div>
									<div class="inner-cell cell-bottom">
										<div class="cell">29</div>
										<div class="cell">30</div>
										<div class="cell">31</div>
										<div class="cell cell-next-month">1</div>
										<div class="cell cell-next-month">2</div>
										<div class="cell cell-next-month">3</div>
										<div class="cell cell-next-month">4</div>
									</div>
								</div>
								<div class="calendar">
									<div class="name-month-calend">
										<h2>Août
											<a href="#" class="btn btn-gray btn-gray-lite name-month-next">
												<i class="i-group-gray icon-next"></i>
											</a>
										</h2>
									</div>
									<div class="inner-cell cell-month">
										<div class="cell">Lun</div>
										<div class="cell">Mar</div>
										<div class="cell">Mer</div>
										<div class="cell">Jeu</div>
										<div class="cell">Ven</div>
										<div class="cell">Sa</div>
										<div class="cell">Dim</div>
									</div>
									<div class="inner-cell">
										<div class="cell cell-next-month">29</div>
										<div class="cell cell-next-month">30</div>
										<div class="cell cell-next-month">31</div>
										<div class="cell">1</div>
										<div class="cell">2</div>
										<div class="cell">3</div>
										<div class="cell">4</div>
									</div>
									<div class="inner-cell">
										<div class="cell">5</div>
										<div class="cell">3</div>
										<div class="cell">7</div>
										<div class="cell">8</div>
										<div class="cell">9</div>
										<div class="cell">10</div>
										<div class="cell">11</div>
									</div>
									<div class="inner-cell">
										<div class="cell">12</div>
										<div class="cell">13</div>
										<div class="cell">14</div>
										<div class="cell">15</div>
										<div class="cell">16</div>
										<div class="cell">17</div>
										<div class="cell">18</div>
									</div>
									<div class="inner-cell">
										<div class="cell">19</div>
										<div class="cell">20</div>
										<div class="cell">21</div>
										<div class="cell">22</div>
										<div class="cell">23</div>
										<div class="cell">24</div>
										<div class="cell">25</div>
									</div>
									<div class="inner-cell cell-bottom">
										<div class="cell">26</div>
										<div class="cell">27</div>
										<div class="cell">28</div>
										<div class="cell">29</div>
										<div class="cell">30</div>
										<div class="cell">31</div>
										<div class="cell cell-next-month">1</div>
									</div>
								</div>
							</div>
						</div>
					</fieldset>
					<div style="margin-top: 10px;">
						<span class="gray">Choisissez vos dates de visites à l’avance.</br>Vous conviendrez de l’horaire avec vos candidats, ultérieurement.</span></br>
						<span class="red">Vous devez définir au moins une date de visite.</span>
					</div>
				</div>

				<div class="block-grid grid-inset">
					<fieldset>
						<label>Dates de visite <em class="red">(obligatoire)</em></label>
						<div class="block-grid grid-grayv" id="accept-block">
							<div class="left" style="width: 260px;">
								<fieldset>
									<label>Date</label>
									<div class="labels-group">
										<input type="radio" class="input-pretty" value="date" name="availability_select" id="availability_select_date">
										<label for="availability_select_date" class="btn-input-gray-lite">Sélectionner une date</label>
										<label for="availability_select_date" class="btn-input-gray-lite label-date icon-calendar-gray"></label>
									</div>
								</fieldset>
							</div>
							<div class="right">
								<fieldset>
									<label>&nbsp;</label>
									<a href="#" class="btn btn-medium btn-gray btn-delete">Supprimer</a>
								</fieldset>
							</div>
						</div>

						<div class="block-grid grid-gray">
							<div class="left" style="width: 260px;">
								<fieldset>
									<label>Date</label>
									<div class="labels-group">
										<input type="radio" class="input-pretty" value="date" name="availability_select" id="availability_select_date">
										<label for="availability_select_date" class="btn-input-gray-lite">Sélectionner une date</label>
										<label for="availability_select_date" class="btn-input-gray-lite label-date icon-calendar-gray"></label>
									</div>
								</fieldset>
							</div>
							<div class="left">
								<ul style="list-style: none; color: #198E9C; margin: 23px 0 0 0; padding: 0;">
									<li>1.Vous fixez le jour.</li>
									<li>2.Vos candidats vous proposeront une plage horaire.</li>
									<li>3.Vous choisirez l’heure du rendez vous.</li>
								</ul>
							</div>
						</div>
					</fieldset>
					<div style="margin-top: 10px;">
						<span class="gray">Passée la dernière date de visite, votre annonce ne sera plus visible.</span></br>
						<span class="red">Pensez à en prévoir suffisamment.</span>
					</div>
				</div>

				<div class="progress-buttons">
					<a href="#" class="btn btn-medium btn-gray btn-arrow-prev left">Étape précédente</a>
					<a href="#" class="btn btn-medium btn-blue btn-arrow-next right">Enregistrer et continuer</a>
				</div>
			</div>
		</div>
	</div>
</div>