<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Tableau de bord</h1>
	</div>
</div>
<div class="inner">
	<div class="grid">
		<div class="page-tab-nav">
			<ul>
				<li><a href="">Résumé</a></li>
				<li><a href="">Mes annonces</a></li>
				<li><a href="" class="active">Mes candidats</a></li>
				<li><a href="">Mes services</a></li>
				<li><a href="">Mon compte</a></li>
			</ul>
		</div>
		<div id="candidats">
			<div class="candidats-block first-block">
				<h3>Mes annonces</h3>
				<div class="candidats-content">
					<div class="c_annonce_block active">
						<div class="c_annonce_block_info">
							<div class="c_annonce_block_info_photo">
								<img src="//place-hold.it/70x70">
							</div>
							<div class="c_annonce_block_info_titles">
								<span class="c_annonce_block_info_title">Joli studio proche …</span>
								<span class="c_annonce_block_info_views">(75018)</span>
								<span class="c_annonce_block_info_price">700 €</span>
							</div>
						</div>

						<div class="c_annonce_block_meta">
							<span>87 candidats</span>
							<span>9 candidats sélectionnés</span>
						</div>
					</div>
				</div>
			</div>
			<div class="candidats-block second-block">
				<h3>Candidats <span class="blue">(87)</span></h3>
				<div class="candidats-content">
					
					<div class="c_candidate">
						<span>Candidats en attente</span>
						<div class="c_candidate_block active">
							<span class="c_candidate_block_title">Tous les candidats</br>en attente</span>
							<span class="c_candidate_block_candidats">87 candidats</span>
						</div>
					</div>

					<div class="c_candidate">
						<span>Mes sélections</span>
						<div class="c_candidate_block inactive">
							<span class="c_candidate_block_title">Tous les candidats</br>en attente</span>
							<span class="c_candidate_block_candidats">87 candidats</span>
						</div>
					</div>

					<div class="c_candidate">
						<span>Mes visites</span>
						<div class="c_candidate_block inactive">
							<span class="c_candidate_block_title">Visite du 02/07/2013</span>
							<span class="c_candidate_block_candidats">87 candidats</span>
						</div>
						<div class="c_candidate_block inactive">
							<span class="c_candidate_block_title">Visite du 03/07/2013</span>
							<span class="c_candidate_block_candidats">87 candidats</span>
						</div>
					</div>

				</div>
			</div>
			<div class="candidats-block third-block">
				<h3>En attente <span class="blue">(78)</span></h3>
				<div class="candidats-content">
					<div class="attente-list">

						<div class="attente-block">
							<h3 style="font-size: 23px; color: #34A6B3; margin: 0; font-weight: 400;" class="blue">Vous n’avez actuellement aucun candidat</h3>
							<span style="display: block; margin-bottom: 10px;">Dés qu’un utilisateur candidate à votre annonce, il apparaît ici.</br>
Vous pourrez alors consulter son dossier.</br>
Puis le sélectionner ou le refuser pour la visite demandée.</span>
							<a href="#" class="btn btn-red btn-magic" style="width: 100%;">Augmenter la visibilité de mon annonce</a>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>