<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Publier une annonce</h1>
	</div>
</div>
<div class="inner">
	<div class="grid" id="publier">
		<div class="left">
			<div class="progress">
				<h2 class="gray">Étapes</h2>
				<div class="progress-step" id="step-3"></div>
				<span>2 étapes restantes</span>
			</div>
			<div class="menu">
				<a href="#" class="btn btn-gray">1  Location</a>
				<a href="#" class="btn btn-gray">2  Description</a>
				<a href="#" class="btn btn-gray">3  Photos</a>
				<a href="#" class="btn btn-blue  progress-menu-active">4  Profil recherché</a>
				<a href="#" class="btn btn-gray">5  Dates de visite</a>
			</div>
		</div>
		<div class="right">
			<div class="progress-content" id="content-step-2">
				<div class="step-title">
					<h1>Profil recherché</h1>
					<span>Quel profil recherchez-vous?</span>
				</div>
				<div class="block-grid grid-inset">
					<fieldset>
						<label>Profil recherché</label>
						<div>
							<input type="checkbox" class="input-pretty" id="demo7" name="demo7" value="demo7">
							<label for="demo7" class="btn-input-lite">Etudiants</label>
							<input type="checkbox" class="input-pretty" id="demo8" name="demo8" value="demo8">
							<label for="demo8" class="btn-input-lite">Salaries</label>
							<input type="checkbox" class="input-pretty" id="demo9" name="demo9" value="demo9">
							<label for="demo9" class="btn-input-lite">Independants</label>
						</div>
						<div>
							<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
							<label for="demo10" class="btn-input-lite">Aucune preference</label>
						</div>
						
					</fieldset>
					<div style="margin-top: 10px;">
						<span class="blue">Indiquez nous votre préférence quant au profil que vous recherchez.</span></br>
						<span class="gray">En fonction de celle-ci et de la solidité du dossier, OMMI classe les</br>candidatures que vous recevrez sur une échelle de 1 à 5 afin de vous aider</br>à faire votre choix.</span>
					</div>
				</div>

				<div class="block-grid grid-inset" style="margin-top: 50px;">
					<fieldset>
						<label>Colocation acceptée</label>
						<input type="radio" class="input-pretty" id="demo1" name="demo1" value="demo1">
						<label for="demo1" class="btn-input-lite">Oui</label>
						<input type="radio" class="input-pretty" id="demo2" name="demo1" value="demo2">
						<label for="demo2" class="btn-input-lite">Non</label>
					</fieldset>
				</div>

				<div class="progress-buttons">
					<a href="#" class="btn btn-gray btn-arrow-prev left">Étape précédente</a>
					<a href="#" class="btn btn-blue btn-arrow-next right">Enregistrer et continuer</a>
				</div>
			</div>
		</div>
	</div>
</div>