<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Publier une annonce</h1>
	</div>
</div>
<div class="inner">
	<div class="grid" id="publier">
		<div class="left">
			<div class="progress">
				<h2 class="gray">Étapes</h2>
				<div class="progress-step" id="step-1"></div>
				<span>4 étapes restantes</span>
			</div>
			<div class="menu">
				<a href="#" class="btn btn-gray">1  Location</a>
				<a href="#" class="btn btn-blue  progress-menu-active">2  Description</a>
				<a href="#" class="btn btn-gray">3  Photos</a>
				<a href="#" class="btn btn-gray">4  Profil recherché</a>
				<a href="#" class="btn btn-gray">5  Dates de visite</a>
			</div>
		</div>
		<div class="right">
			<div class="progress-content" id="content-step-2">
				<div class="step-title">
					<h1>Description du bien</h1>
					<span class="blue">Les informations suivantes sont essentielles et donc obligatoires.</span>
					<span>Elles renseignent sur les caract</span>
				</div>
				<div class="block-grid grid-inset">
					<fieldset>
						<label>Adresse <em class="red">(obligatoire)</em></label>
						<input type="text" style="width: 500px;">
					</fieldset>
					<div class="left" style="width: 250px;">
						<fieldset>
							<label>Code Postal <em class="red">(obligatoire)</em></label>
							<input type="text">
						</fieldset>
					</div>
					<div class="left">
						<fieldset>
							<label>Ville</label>
							<input type="text" style="width: 250px;">
						</fieldset>
					</div>
					<div class="left" style="margin-top: 10px;">
						<span class="blue">L’adresse est essentielle pour localiser votre bien. Cette information est privée.</span></br>
						<span class="gray">Votre adresse ne sera connue que des candidats que vous sélectionnerez pour les visites.</span>
					</div>
				</div>
				<div class="block-grid grid-inset">
					<fieldset>
						<label>Surface <em class="red">(obligatoire)</em></label>
						<input type="text" placeholder="">
					</fieldset>
				</div>
				<div class="block-grid grid-inset">
					<fieldset>
						<label>Type de bien <em class="red">(obligatoire)</em></label>
						<div>
							<input type="checkbox" class="input-pretty" id="demo1" name="demo1" value="demo1">
							<label for="demo1" class="btn-input-lite">Appartement</label>
							<input type="checkbox" class="input-pretty" id="demo2" name="demo2" value="demo2">
							<label for="demo2" class="btn-input-lite">Maison</label>
							<input type="checkbox" class="input-pretty" id="demo3" name="demo3" value="demo3">
							<label for="demo3" class="btn-input-lite">Loft / Atelier</label>
						</div>
						<div>
							<input type="checkbox" class="input-pretty" id="demo4" name="demo4" value="demo4">
							<label for="demo4" class="btn-input-lite">Studette</label>
							<input type="checkbox" class="input-pretty" id="demo5" name="demo5" value="demo5">
							<label for="demo5" class="btn-input-lite">Colocation</label>
							<input type="checkbox" class="input-pretty" id="demo6" name="demo6" value="demo6">
							<label for="demo6" class="btn-input-lite">Autre</label>
						</div>
					</fieldset>
				</div>
				<div class="block-grid grid-inset">
					<fieldset>
						<label>Nombre de pièces <em class="red">(obligatoire)</em></label>
						<input type="checkbox" class="input-pretty" id="demo7" name="demo7" value="demo7">
						<label for="demo7" class="btn-input-lite">1</label>
						<input type="checkbox" class="input-pretty" id="demo8" name="demo8" value="demo8">
						<label for="demo8" class="btn-input-lite">2</label>
						<input type="checkbox" class="input-pretty" id="demo9" name="demo9" value="demo9">
						<label for="demo9" class="btn-input-lite">3</label>
						<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
						<label for="demo10" class="btn-input-lite">4</label>
						<input type="checkbox" class="input-pretty" id="demo11" name="demo11" value="demo11">
						<label for="demo11" class="btn-input-lite">5</label>
						<input type="checkbox" class="input-pretty" id="demo12" name="demo12" value="demo12">
						<label for="demo12" class="btn-input-lite">6</label>
						<input type="checkbox" class="input-pretty" id="demo13" name="demo13" value="demo13">
						<label for="demo13" class="btn-input-lite">7 et +</label>
					</fieldset>
				</div>
				<div class="block-grid grid-inset">
					<fieldset>
						<label>Nombre de chambres <em class="red">(obligatoire)</em></label>
						<input type="checkbox" class="input-pretty" id="demo7" name="demo7" value="demo7">
						<label for="demo7" class="btn-input-lite">1</label>
						<input type="checkbox" class="input-pretty" id="demo8" name="demo8" value="demo8">
						<label for="demo8" class="btn-input-lite">2</label>
						<input type="checkbox" class="input-pretty" id="demo9" name="demo9" value="demo9">
						<label for="demo9" class="btn-input-lite">3</label>
						<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
						<label for="demo10" class="btn-input-lite">4 et +</label>
					</fieldset>
				</div>
				<div class="block-grid grid-inset">
					<div class="left half">
						<fieldset>
							<label>Étage <em class="red">(obligatoire)</em></label>
							<select name="" id=""></select>
						</fieldset>
					</div>
					<div class="left half">
						<fieldset>
							<label>Ascenseur <em class="red">(obligatoire)</em></label>
							<input type="checkbox" class="input-pretty" id="demo3" name="demo3" value="demo3">
							<label for="demo3" class="btn-input-lite">1 mois</label>
							<input type="checkbox" class="input-pretty" id="demo4" name="demo4" value="demo4">
							<label for="demo4" class="btn-input-lite">2 mois</label>
						</fieldset>
					</div>
				</div>
				<div class="block-grid grid-inset">
					<div class="left half">
						<fieldset>
							<label>Classe Énergie <em class="red">(obligatoire)</em></label>
							<select name="" id=""></select>
						</fieldset>
					</div>
					<div class="left half">
						<fieldset>
							<label>GES <em class="red">(obligatoire)</em></label>
							<select name="" id=""></select>
						</fieldset>
					</div>
					<div class="left" style="margin-top: 10px;">
						<span class="gray">La classe énergie et le GES sont déterminés suite à l’intervention d’un professionnel certifié. N’indiquez pas de classe au hasard car votre responsabilité pourrait être engagée. </br>Ommi met à votre disposition un professionnel certifié. </span></br>
						<span class="blue">Rendez-vous dans l’onglet Mes Services.</span>
					</div>
				</div>
				
				<div class="step-title" style="margin-top:40px;">
					<h1>Détails supplémentaires</h1>
					<span class="blue">Les informations suivantes sont optionnelles.</span>
					<span>Elles renseignent les candidats sur les spécificités de votre bien.</span>
				</div>

				<div class="block-grid grid-inset">
					<fieldset>
						<label>Aménagement</label>
						<input type="checkbox" class="input-pretty" id="demo7" name="demo7" value="demo7">
						<label for="demo7" class="btn-input-lite">Toilettes separees</label>
						<input type="checkbox" class="input-pretty" id="demo8" name="demo8" value="demo8">
						<label for="demo8" class="btn-input-lite">Parquet</label>
						<input type="checkbox" class="input-pretty" id="demo9" name="demo9" value="demo9">
						<label for="demo9" class="btn-input-lite">Moulure</label>
						<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
						<label for="demo10" class="btn-input-lite">Double vitrage</label>
						<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
						<label for="demo10" class="btn-input-lite">Rangements</label>
						<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
						<label for="demo10" class="btn-input-lite">Cheminee</label>
						<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
						<label for="demo10" class="btn-input-lite">Air conditionne</label>
					</fieldset>
				</div>

				<div class="block-grid grid-inset">
					<fieldset>
						<label>Dépendances</label>
						<input type="checkbox" class="input-pretty" id="demo7" name="demo7" value="demo7">
						<label for="demo7" class="btn-input-lite">Grenier</label>
						<input type="checkbox" class="input-pretty" id="demo8" name="demo8" value="demo8">
						<label for="demo8" class="btn-input-lite">Cave</label>
						<input type="checkbox" class="input-pretty" id="demo9" name="demo9" value="demo9">
						<label for="demo9" class="btn-input-lite">Parking</label>
						<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
						<label for="demo10" class="btn-input-lite">Parking ferme / Box</label>
						<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
						<label for="demo10" class="btn-input-lite">Piscine</label>
					</fieldset>
				</div>

				<div class="block-grid grid-inset">
					<fieldset>
						<label>Espaces extérieurs</label>
						<input type="checkbox" class="input-pretty" id="demo7" name="demo7" value="demo7">
						<label for="demo7" class="btn-input-lite">Balcon</label>
						<input type="checkbox" class="input-pretty" id="demo8" name="demo8" value="demo8">
						<label for="demo8" class="btn-input-lite">Terrasse</label>
						<input type="checkbox" class="input-pretty" id="demo9" name="demo9" value="demo9">
						<label for="demo9" class="btn-input-lite">Jardin</label>
						<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
						<label for="demo10" class="btn-input-lite">Cour</label>
					</fieldset>
				</div>

				<div class="block-grid grid-inset">
					<fieldset>
						<label>Immeuble</label>
						<input type="checkbox" class="input-pretty" id="demo7" name="demo7" value="demo7">
						<label for="demo7" class="btn-input-lite">Gardien</label>
						<input type="checkbox" class="input-pretty" id="demo8" name="demo8" value="demo8">
						<label for="demo8" class="btn-input-lite">Digicode / Interphone</label>
						<input type="checkbox" class="input-pretty" id="demo9" name="demo9" value="demo9">
						<label for="demo9" class="btn-input-lite">Pierre de taille</label>
						<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
						<label for="demo10" class="btn-input-lite">Ancien</label>
						<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
						<label for="demo10" class="btn-input-lite">Renove</label>
						<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
						<label for="demo10" class="btn-input-lite">Neuf</label>
					</fieldset>
				</div>		

				<div class="block-grid grid-inset">
					<fieldset>
						<label>Nombre de Salles de bains</label>
						<input type="checkbox" class="input-pretty" id="demo7" name="demo7" value="demo7">
						<label for="demo7" class="btn-input-lite">1</label>
						<input type="checkbox" class="input-pretty" id="demo8" name="demo8" value="demo8">
						<label for="demo8" class="btn-input-lite">2</label>
						<input type="checkbox" class="input-pretty" id="demo9" name="demo9" value="demo9">
						<label for="demo9" class="btn-input-lite">3</label>
						<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
						<label for="demo10" class="btn-input-lite">4 et +</label>
					</fieldset>
				</div>

				<div class="block-grid grid-inset">
					<fieldset>
						<label>Type de chauffage</label>
						<input type="checkbox" class="input-pretty" id="demo7" name="demo7" value="demo7">
						<label for="demo7" class="btn-input-lite">Individuel</label>
						<input type="checkbox" class="input-pretty" id="demo8" name="demo8" value="demo8">
						<label for="demo8" class="btn-input-lite">Central / Collectif</label>
						<input type="checkbox" class="input-pretty" id="demo9" name="demo9" value="demo9">
						<label for="demo9" class="btn-input-lite">Au sol</label>
						<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
						<label for="demo10" class="btn-input-lite">Gaz</label>
						<input type="checkbox" class="input-pretty" id="demo9" name="demo9" value="demo9">
						<label for="demo9" class="btn-input-lite">Electrique</label>
						<input type="checkbox" class="input-pretty" id="demo10" name="demo10" value="demo10">
						<label for="demo10" class="btn-input-lite">Autre</label>
					</fieldset>
				</div>

				<div class="progress-buttons">
					<a href="#" class="btn btn-gray btn-arrow-prev left">Étape précédente</a>
					<a href="#" class="btn btn-blue btn-arrow-next right">Enregistrer et continuer</a>
				</div>
			</div>
		</div>
	</div>
</div>