<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Tableau de bord</h1>
	</div>
</div>
<div class="inner">
	<div class="grid grid-dark-gray">
		<div class="page-tab-nav">
			<ul>
				<li><a href="">Résumé</a></li>
				<li><a href="" class="active">Mes annonces</a></li>
				<li><a href="">Mes candidats</a></li>
				<li><a href="">Mes services</a></li>
				<li><a href="">Mon compte</a></li>
			</ul>
		</div>
		<div id="annonces" class="page-tab-content">

			<h3>Annonces actives</h3>
			<div class="annonce-blocks">
				<div class="annonce-block grid-gray">
					<div class="annonce-block-photo">
						<img src="//place-hold.it/120x120">
					</div>
					<div class="annonce-block-information">
						<h4>Appartement calme à Père-Lachaise</h4>
						<div class="information-more">
							<div class="information-left">
								<span>Appartement<span class="slash">|</span>Meublé</span>
								<span>Paris 11e (75011)</span>
								<span>45 m²</span>
								<span>2e étage avec ascenceur</span>
							</div>
							<div class="information-right">
								<span>disponibilité : immédiate</span>
								<span>Cave<span class="slash">|</span>Balcon</span>
								<span>&nbsp;</span>
								<span class="blue">3 dates de visites</span>
							</div>
							
						</div>
						<div class="information-links">
							<a href="#" class="blue">Ajouter une date</a>
							<a href="#" class="red">Modifier l’annonce</a>
							<a href="#" class="black">Voir l’annonce</a>
						</div>
					</div>
					<div class="annonce-block-controlls">
						<div class="controlls-stats">
							<span>Vue 87 fois</span>
							<span>19 candidats</span>
							<span>2 candidats sélectionnés</span>
							<a href="#" class="btn btn-red">Mettre en valeur</a>
						</div>
						<div class="controlls-price">
							<span class="price">
								1200 €
							</span>
							<a href="#" class="btn btn-dark">
								J’ai trouvé </br>mon locataire
							</a>
						</div>
					</div>
				</div>

				<div class="annonce-block grid-gray">
					<div class="annonce-block-photo">
						<img src="//place-hold.it/120x120">
					</div>
					<div class="annonce-block-information">
						<h4>Appartement calme à Père-Lachaise</h4>
						<div class="information-more">
							<div class="information-left">
								<span>Appartement<span class="slash">|</span>Meublé</span>
								<span>Paris 11e (75011)</span>
								<span>45 m²</span>
								<span>2e étage avec ascenceur</span>
							</div>
							<div class="information-right">
								<span>disponibilité : immédiate</span>
								<span>Cave<span class="slash">|</span>Balcon</span>
								<span>&nbsp;</span>
								<span class="blue">3 dates de visites</span>
							</div>
							
						</div>
						<div class="information-links">
							<a href="#" class="blue">Ajouter une date</a>
							<a href="#" class="red">Modifier l’annonce</a>
							<a href="#" class="black">Voir l’annonce</a>
						</div>
					</div>
					<div class="annonce-block-controlls">
						<div class="controlls-stats">
							<span>Vue 87 fois</span>
							<span>19 candidats</span>
							<span>2 candidats sélectionnés</span>
							<a href="#" class="btn btn-red">Mettre en valeur</a>
						</div>
						<div class="controlls-price">
							<span class="price">
								1200 €
							</span>
							<a href="#" class="btn btn-dark">
								J’ai trouvé </br>mon locataire
							</a>
						</div>
					</div>
				</div>
			</div>


			<!-- Неактивные блоки -->
			<h3 style="margin-top: 20px;">Annonces inactives</h3>
			<div class="annonce-blocks inactive-blocks">
				<div class="annonce-block grid-gray">
					<div class="annonce-block-photo">
						<img src="//place-hold.it/120x120">
					</div>
					<div class="annonce-block-information">
						<h4>Appartement calme à Père-Lachaise</h4>
						<div class="information-more">
							<div class="information-left">
								<span>Appartement<span class="slash">|</span>Meublé</span>
								<span>Paris 11e (75011)</span>
								<span>45 m²</span>
								<span>2e étage avec ascenceur</span>
							</div>
							<div class="information-right">
								<span>disponibilité : immédiate</span>
								<span>Cave<span class="slash">|</span>Balcon</span>
								<span>&nbsp;</span>
								<span class="blue">3 dates de visites</span>
							</div>
							
						</div>
						<div class="information-links">
							<a href="#" class="blue">Ajouter une date</a>
							<a href="#" class="red">Modifier l’annonce</a>
							<a href="#" class="black">Voir l’annonce</a>
						</div>
					</div>
					<div class="annonce-block-controlls">
						<div class="controlls-stats">
							<span>Vue 87 fois</span>
							<span>19 candidats</span>
							<span>2 candidats sélectionnés</span>
							<a href="#" class="btn btn-red">Mettre en valeur</a>
						</div>
						<div class="controlls-price">
							<span class="price">
								1200 €
							</span>
							<a href="#" class="btn btn-dark">
								J’ai trouvé </br>mon locataire
							</a>
						</div>
					</div>
				</div>

			</div>
		</div>
		<div class="page-tab-bottom">
			<a href="#" class="btn btn-red">Dépannage</a>
			<a href="#" class="btn btn-blue">Publier une nouvelle annonce</a>
		</div>
	</div>
</div>