<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Tableau de bord</h1>
	</div>
</div>
<div class="inner">
	<div class="grid">
		<div class="page-tab-nav">
			<ul>
				<li><a href="">Résumé</a></li>
				<li><a href="">Mes annonces</a></li>
				<li><a href="">Mes candidats</a></li>
				<li><a href="" class="active">Mes services</a></li>
				<li><a href="">Mon compte</a></li>
			</ul>
		</div>
		<div id="publier">
			<div class="left">
				<div class="menu">
					<a href="#" class="btn btn-gray">Sommaire</a>
					<a href="#" class="btn btn-gray btn-energy">Diagnostic énergétique</a>
					<a href="#" class="btn btn-gray btn-mail">Modèles de courrier</a>
					<a href="#" class="btn btn-gray btn-file">Modèles de contrats</a>
					<a href="#" class="btn btn-gray btn-edit">État des lieux</a>
					<a href="#" class="btn btn-red btn-pro progress-menu-active">Professionnels</a>
				</div>
			</div>
			<div class="right">
				<div class="progress-content">
					<div class="step-title">
						<h1>Professionnels</h1>
						<span class="blue">On peut vous rendre service?</span>
						<span>Besoin d’idées ? D’un coup de peinture ? Des travaux à faire ?</br>Qu’il arrive un sinistre chez vous ou si vous voulez simplement remettre à neuf votre bien,</br>ne cherchez pas plus loin. <strong>OMMI</strong> travaille en collaboration avec des entrepreneurs, </br>des dépanneurs et des décorateurs d’intérieur de talent et de confiance.</span>
					</div>
					<div class="block-grid grid-inset">
						<fieldset>
							<label>Téléphone <em class="blue">(conseillé)</em></label>
							<input type="text" style="width: 300px;" class="input-phone">
							<p class="description blue">Soyez rassuré, ces informations ne seront utilisées qu’aux fins</br>d’organiser votre rendez-vous avec le professionnel.</p>
						</fieldset>
					</div>

					<div class="block-grid grid-set-gray">
						<div class="content-tab-nav">
							<ul>
								<li><a href="">Dépanneur</a></li>
								<li><a href="" class="active">Décorateur</a></li>
								<li><a href="">Diagnostiqueur</a></li>
								<li><a href="">Entrepreneur</a></li>
							</ul>
						</div>
						<div class="content-tab-inner">
							<p class="description">
								Comme les chats, votre appartement a plusieurs vies.Celle qui vient se trouve peut être ici. Consultez les décorateurs d’intérieur <strong>OMMI</strong>.
							</p>

							<fieldset>
								<label>Calendrier</label>

								<div class="block-calendar">
									<div class="calendar">
										<div class="name-month-calend">
											<h2>
												<a href="#" class="btn btn-gray btn-gray-lite btn-cal-prev">
													<i class="i-group-gray icon-prev"></i>
												</a>
												Juillet
											</h2>
										</div>
										<div class="inner-cell cell-month">
											<div class="cell">Lun</div>
											<div class="cell">Mar</div>
											<div class="cell">Mer</div>
											<div class="cell">Jeu</div>
											<div class="cell">Ven</div>
											<div class="cell">Sa</div>
											<div class="cell">Dim</div>
										</div>
										<div class="inner-cell">
											<div class="cell cell-gray">1</div>
											<div class="cell cell-gray">2</div>
											<div class="cell cell-gray">3</div>
											<div class="cell cell-gray">4</div>
											<div class="cell cell-gray">5</div>
											<div class="cell cell-gray">6</div>
											<div class="cell cell-gray">7</div>
										</div>
										<div class="inner-cell">
											<div class="cell cell-gray">8</div>
											<div class="cell cell-gray">9</div>
											<div class="cell cell-gray">10</div>
											<div class="cell cell-gray">11</div>
											<div class="cell cell-black">12</div>
											<div class="cell">13</div>
											<div class="cell">14</div>
										</div>
										<div class="inner-cell">
											<div class="cell">15</div>
											<div class="cell">16</div>
											<div class="cell">17</div>
											<div class="cell">18</div>
											<div class="cell">19</div>
											<div class="cell">20</div>
											<div class="cell">21</div>
										</div>
										<div class="inner-cell">
											<div class="cell">22</div>
											<div class="cell">23</div>
											<div class="cell">24</div>
											<div class="cell">25</div>
											<div class="cell">26</div>
											<div class="cell">27</div>
											<div class="cell">28</div>
										</div>
										<div class="inner-cell cell-bottom">
											<div class="cell">29</div>
											<div class="cell cell-blue">30</div>
											<div class="cell">31</div>
											<div class="cell cell-next-month">1</div>
											<div class="cell cell-next-month">2</div>
											<div class="cell cell-next-month">3</div>
											<div class="cell cell-next-month">4</div>
										</div>
									</div>
									<div class="calendar">
										<div class="name-month-calend">
											<h2>Août
												<a href="#" class="btn btn-gray btn-gray-lite name-month-next">
													<i class="i-group-gray icon-next"></i>
												</a>
											</h2>
										</div>
										<div class="inner-cell cell-month">
											<div class="cell">Lun</div>
											<div class="cell">Mar</div>
											<div class="cell">Mer</div>
											<div class="cell">Jeu</div>
											<div class="cell">Ven</div>
											<div class="cell">Sa</div>
											<div class="cell">Dim</div>
										</div>
										<div class="inner-cell">
											<div class="cell cell-next-month">29</div>
											<div class="cell cell-next-month">30</div>
											<div class="cell cell-next-month">31</div>
											<div class="cell">1</div>
											<div class="cell">2</div>
											<div class="cell">3</div>
											<div class="cell">4</div>
										</div>
										<div class="inner-cell">
											<div class="cell">5</div>
											<div class="cell">3</div>
											<div class="cell">7</div>
											<div class="cell">8</div>
											<div class="cell">9</div>
											<div class="cell">10</div>
											<div class="cell">11</div>
										</div>
										<div class="inner-cell">
											<div class="cell">12</div>
											<div class="cell">13</div>
											<div class="cell">14</div>
											<div class="cell">15</div>
											<div class="cell">16</div>
											<div class="cell">17</div>
											<div class="cell">18</div>
										</div>
										<div class="inner-cell">
											<div class="cell">19</div>
											<div class="cell">20</div>
											<div class="cell">21</div>
											<div class="cell">22</div>
											<div class="cell">23</div>
											<div class="cell">24</div>
											<div class="cell">25</div>
										</div>
										<div class="inner-cell cell-bottom">
											<div class="cell">26</div>
											<div class="cell">27</div>
											<div class="cell">28</div>
											<div class="cell">29</div>
											<div class="cell">30</div>
											<div class="cell">31</div>
											<div class="cell cell-next-month">1</div>
										</div>
									</div>
								</div>

							</fieldset>

							<fieldset>
								<label>Dates de visite <em class="red">(obligatoire)</em></label>
								<div class="block-grid grid-gray select-dates">
									<fieldset id="date-fieldset">
										<label>Date</label>
										<input type="text">
										<p class="description blue">
											Sélectionnez une date et un horaire puis un</br>professionnel du réseau OMMI vous</br>contactera au plus vite.
										</p>
									</fieldset>

									<fieldset id="time-fieldset">
										<label>Horaire</label>
										<div>
											<span>Entre</span>
											<select name="" id=""></select>
											<span>et</span>
											<select name="" id=""></select>
										</div>
									</fieldset>
									<div class="block-btn">
										<a href="#" class="btn btn-medium btn-red btn-time-red">Prendre lerendez-vous</a>
									</div>
								</div>
							</fieldset>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>