<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Tableau de bord</h1>
	</div>
</div>
<div class="inner">
	<div class="grid">
		<div class="page-tab-nav">
			<ul>
				<li><a href="">Résumé</a></li>
				<li><a href="">Mes annonces</a></li>
				<li><a href="">Mes candidats</a></li>
				<li><a href="">Mes services</a></li>
				<li><a href="" class="active">Mon compte</a></li>
			</ul>
		</div>
		<div id="compte" class="compte-01">
			<div class="left">
				<div class="menu">
					<a href="#" class="btn btn-gray">Sommaire</a>
					<a href="#" class="btn btn-gray">Mes parametres</a>
					<a href="#" class="btn btn-gray">Mon compte</a>
					<a href="#" class="btn btn-blue progress-menu-active">Bulletins d'information</a>
				</div>
			</div>
			<div class="right">
				<div class="progress-content">
					<div class="step-title">
						<h1>Newsletter Ommi</h1>
						<span>Ommi a d’excellentes nouvelles à vous apporter.</br>Inscrivez-vous pour recevoir notre bulletin d’information.</span>
					</div>
					<div class="block-grid grid-inset">
						<fieldset>
							<label>Inscription au bulletin d’information</label>
							<div>
								<input type="radio" class="input-pretty" id="demo7" name="demo7" value="demo7">
								<label for="demo7" class="btn-input-lite">Oui, je souhaite m'inscrire</label>
								<input type="radio" class="input-pretty" id="demo8" name="demo8" value="demo8" checked>
								<label for="demo8" class="btn-input-lite">Non merci</label>
							</div>
						</fieldset>
					</div>
					<div class="step-title" style="margin-top: 40px;">
						<h1>Offres partenaires</h1>
						<span>
							Nos partenaires ont souvent des offres exceptionnelles pour vous.</br>Inscrivez pour recevoir les offres de nos partenaires.
						</span>
					</div>
					<div class="block-grid grid-inset">
						<fieldset>
							<label>Inscription aux offres des partenaires</label>
							<div>
								<input type="radio" class="input-pretty" id="demo7" name="demo7" value="demo7">
								<label for="demo7" class="btn-input-lite">Oui, je souhaite m'inscrire</label>
								<input type="radio" class="input-pretty" id="demo5" name="demo5" value="demo5" checked>
								<label for="demo5" class="btn-input-lite">Non merci</label>
							</div>
						</fieldset>
					</div>
					<div class="progress-buttons">
						<a href="#" class="btn btn-red right">Enregistrer les modifications</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="grid">
		<div class="grid-full grid-full-other">
			<div class="grid-inner">
				<h1 class="gray"><span class="blue"> Pourquoi faire certifier</span><br>
					mon dossier par OMMI ?
				</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						OMMI s’engage, pour tous les candidats qui le souhaitent, à vérifier la cohérence</br>des dossiers de candidature et les certifie. Fini les mauvaises surprises !
					</div>
					<div class="index-row-six-btn">
						<a href="#" class="right btn btn-blue w200">Certifier ma candidature</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="grid grid-transparent">
		<div class="grid-half grid-half-other">
			<div class="grid-inner">
				<h1 class="gray">Presse de trouver<br> un logement ?</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Découvrez nos comptes sur-mesure et<br>
						choisissez celui qui vous convient le mieux.<br>
						Donnez-vous les moyens de trouver vite.
					</div>
					<div class="index-row-six-link">
						<a href="#">Comples OMMI</a>
					</div>
				</div>
			</div>
		</div>

		<div class="grid-half grid-half-other">
			<div class="grid-inner">
				<h1 class="gray">Au secours !<br> Un depanneur ?</h1>
				<div class="index-row-six cf">
					<div class="index-row-six-text">
						Pas de panique! Profitez du réseau Ommi<br>
						de dépanneurs de confiance à prix d’ami !
						Programmez en ligne vos rendez-vous.
					</div>
					<div class="index-row-six-link">
						<a href="#">Dépannage</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>