<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Publier une annonce</h1>
	</div>
</div>
<div class="inner">
	<div class="grid" id="publier">
		<div class="left">
			<div class="progress">
				<h2 class="gray">Étapes</h2>
				<div class="progress-step" id="step-100"></div>
				<span>Votre annonce est</br>prête à être publiée</span>
			</div>
			<div class="menu">
				<a href="#" class="btn btn-gray">1  Location</a>
				<a href="#" class="btn btn-gray">2  Description</a>
				<a href="#" class="btn btn-gray">3  Photos</a>
				<a href="#" class="btn btn-gray">4  Profil recherché</a>
				<a href="#" class="btn btn-gray">5  Dates de visite</a>
				<a href="#" class="btn btn-red">Mettre en valeur</a>
			</div>
		</div>
		<div class="right">
			<div class="progress-content" id="content-step-0">
				<div class="block-grid grid-light-blue block-service accept">
					<h2>Bravo ! Votre annonce est prête.</h2>
					<p>Il ne vous reste plus qu’à la publier pour commencer à recevoir des candidatures.</br>Louez bien et vite avec <strong>Ommi</strong> : Distinguez votre annonce des autres en la</br>mettant en avant ou en lui ajoutant un logo urgent.</p>
				</div>

				<div class="block-grid grid-light-blue block-service accept">
					<h2>Mettre en avant mon annonce</h2>
					<p>Vous êtes pressé de louer? <strong>Ommi</strong> propose à votre annonce</br>de se démarquer des autres. Ajoutez lui un logo urgent et</br>faites la remonter en tête de liste une fois par jour pendant</br>une semaine.</p>
				</div>

				<div class="block-grid grid-inset-white block-service">
					<h2 class="red">Apparaître sur la page d’accueil</h2>
					<p class="black">Faites gagner de la visibilité à votre annonce en ajoutant le</br>logo urgent.</br></br></br></p>
					<div class="block-price">
						<span>5 €</span>
						<p>pour une semaine</p>
						<a href="#" class="btn btn-medium btn-red w230 btn-speed">Ajouter logo urgent</a>
					</div>
				</div>

				<div class="progress-buttons">
					<a href="#" class="btn btn-medium btn-blue btn-good right">Publier mon annonce</a>
				</div>
			</div>
		</div>
	</div>
</div>