<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Tableau de bord</h1>
	</div>
</div>
<div class="inner">
	<div class="grid">
		<div class="page-tab-nav">
			<ul>
				<li><a href="">Résumé</a></li>
				<li><a href="">Mes annonces</a></li>
				<li><a href="">Mes candidats</a></li>
				<li><a href="">Mes services</a></li>
				<li><a href="" class="active">Mon compte</a></li>
			</ul>
		</div>
		<div id="publier">
			<div class="left">
				<div class="menu">
					<a href="#" class="btn btn-gray">Sommaire</a>
					<a href="#" class="btn btn-gray btn-gears">Mes paramètres</a>
					<a href="#" class="btn btn-gray btn-lock">Mon compte</a>
					<a href="#" class="btn btn-blue btn-disk progress-menu-active">Bulletins d’information</a>
				</div>
			</div>
			<div class="right">
				<div class="progress-content">
					<div class="step-title">
						<h1>Newsletter Ommi</h1>
						<span>Ommi a d’excellentes nouvelles à vous apporter.</br>Inscrivez-vous pour recevoir notre bulletin d’information.</span>
					</div>
					<div class="block-grid grid-inset">
						<fieldset>
							<label>Inscription au bulletin d’information</label>
							<div>
								<input type="radio" class="input-pretty" id="demo7" name="demo7" value="demo7">
								<label for="demo7" class="btn-input-lite">Oui, je souhaite m'inscrire</label>
								<input type="radio" class="input-pretty" id="demo8" name="demo8" value="demo8" checked>
								<label for="demo8" class="btn-input-lite">Non merci</label>
							</div>
						</fieldset>
					</div>
					<div class="step-title" style="margin-top: 40px;">
						<h1>Offres partenaires</h1>
						<span>
							Nos partenaires ont souvent des offres exceptionnelles pour vous.</br>Inscrivez pour recevoir les offres de nos partenaires.
						</span>
					</div>
					<div class="block-grid grid-inset">
						<fieldset>
							<label>Inscription aux offres des partenaires</label>
							<div>
								<input type="radio" class="input-pretty" id="demo7" name="demo7" value="demo7">
								<label for="demo7" class="btn-input-lite">Oui, je souhaite m'inscrire</label>
								<input type="radio" class="input-pretty" id="demo5" name="demo5" value="demo5" checked>
								<label for="demo5" class="btn-input-lite">Non merci</label>
							</div>
						</fieldset>
					</div>
					<div class="progress-buttons">
						<a href="#" class="btn btn-medium btn-red right">Enregistrer les modifications</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>