<div class="title-container">
	<div class="title-container-text inner">
		<h1 class="white-text">Tableau de bord</h1>
	</div>
</div>
<div class="inner">
	<div class="grid">
		<div class="page-tab-nav">
			<ul>
				<li><a href="">Résumé</a></li>
				<li><a href="">Mes annonces</a></li>
				<li><a href="">Mes candidats</a></li>
				<li><a href="" class="active">Mes services</a></li>
				<li><a href="">Mon compte</a></li>
			</ul>
		</div>
		<div id="publier">
			<div class="left">
				<div class="menu">
					<a href="#" class="btn btn-gray">Sommaire</a>
					<a href="#" class="btn btn-gray btn-energy">Diagnostic énergétique</a>
					<a href="#" class="btn btn-blue btn-mail progress-menu-active">Modèles de courrier</a>
					<a href="#" class="btn btn-gray btn-file">Modèles de contrats</a>
					<a href="#" class="btn btn-gray btn-edit">État des lieux</a>
					<a href="#" class="btn btn-red btn-pro">Professionnels</a>
				</div>
			</div>
			<div class="right">
				<div class="progress-content">
					<div class="step-title">
						<h1>Modèles de courriers</h1>
						<span class="blue">Vous cherchez les mots pour le dire ? </span>
						<span>Pour vous simplifier la vie, nous mettons à votre disposition nos modèles de lettres type.</br>Pas besoin de chercher plus loin : Vous n’avez plus qu’à remplir les champs qui vous</br>concernent. </span>
					</div>
					<div class="block-grid grid-set-gray">
						<fieldset>
							<label>Au moment de la signature</label>
							<div class="block-file">
								<a href="#" class="btn btn-blue btn-file" id="file">L’état des lieux</a>
								<a href="#" class="btn btn-red btn-download" id="file-download">&nbsp;</a>
							</div>
							<div class="block-file">
								<a href="#" class="btn btn-blue btn-file" id="file">Souscription par le locataire de l’assurance habitation</a>
								<a href="#" class="btn btn-red btn-download" id="file-download">&nbsp;</a>
							</div>
							<div class="block-file">
								<a href="#" class="btn btn-blue btn-file" id="file">Acte de Cautionnement simple</a>
								<a href="#" class="btn btn-red btn-download" id="file-download">&nbsp;</a>
							</div>
						</fieldset>
					</div>

					<div class="block-grid grid-set-gray">
						<fieldset>
							<label>Pendant la location</label>
							<div class="block-file">
								<a href="#" class="btn btn-blue btn-file" id="file">Révision du loyer</a>
								<a href="#" class="btn btn-red btn-download" id="file-download">&nbsp;</a>
							</div>
							<div class="block-file">
								<a href="#" class="btn btn-blue btn-file" id="file">Mise en demeure pour cause de trouble de la jouissance</a>
								<a href="#" class="btn btn-red btn-download" id="file-download">&nbsp;</a>
							</div>
							<div class="block-file">
								<a href="#" class="btn btn-blue btn-file" id="file">Mise en demeure pour cause de non paiement du loyer</a>
								<a href="#" class="btn btn-red btn-download" id="file-download">&nbsp;</a>
							</div>
							<div class="block-file">
								<a href="#" class="btn btn-blue btn-file" id="file">Réparation à la charge du locataire</a>
								<a href="#" class="btn btn-red btn-download" id="file-download">&nbsp;</a>
							</div>
						</fieldset>
					</div>

					<div class="block-grid grid-set-gray">
						<fieldset>
							<label>Fin du bail</label>
							<div class="block-file">
								<a href="#" class="btn btn-blue btn-file" id="file">Augmentation du loyer à la suite du renouvellement du bail</a>
								<a href="#" class="btn btn-red btn-download" id="file-download">&nbsp;</a>
							</div>
							<div class="block-file">
								<a href="#" class="btn btn-blue btn-file" id="file">Mise en congé pour vente du bien en location</a>
								<a href="#" class="btn btn-red btn-download" id="file-download">&nbsp;</a>
							</div>
							<div class="block-file">
								<a href="#" class="btn btn-blue btn-file" id="file">Rétention sur le dépôt de garantie pour cause de dégradations</a>
								<a href="#" class="btn btn-red btn-download" id="file-download">&nbsp;</a>
							</div>
							<div class="block-file">
								<a href="#" class="btn btn-blue btn-file" id="file">Mise en demeure pour reprise du logement pour cause d’habitation</a>
								<a href="#" class="btn btn-red btn-download" id="file-download">&nbsp;</a>
							</div>
						</fieldset>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>