<div class="title-row-search bg-dessin">
	<div class="container-text">
		<h1 class="white-txt">Recherche par dessin</h1>
	</div>
</div>
<main>
	<div class="inner">
		<div class="grid grid-dark">
			<div class="menu-search">
				<ul>
					<li><a href=""  class=" menu-icons icon-search">Recherche standard</a></li>
					<li><a href="" class="menu-icons icon-metro">Recherche<br>par  metro</a></li>
					<li><a href="" class="active menu-icons icon-dessin">Recherche<br> par dessin</a></li>
					<li><a href="" class="menu-icons icon-carte">Recherche<br> par carte</a></li>
				</ul>
			</div>
			<div class="search-box">
				<div class="search-left">
					<div class="search-budget">
						<label class="name-title-white">Budget</label>
						<input type="text" placeholder="Budget min. (en €)"/>
						<input type="text" placeholder="Budget max. (en €)"/>
					</div>
					<div class="search-surface">
						<label class="name-title-white">Surface</label>
						<input type="text" placeholder="Surface min. (en m²)"/>
						<input type="text" placeholder="Surface max. (en m²)"/>
					</div>
				</div>
				<div class="search-right">
					<div class="box-universal">
						<label class="name-title-white">Mobilier</label>
						<form>
							<input type="reset" value="Tous" class="btn-tous"/>
							<input type='radio' class="input-pretty" id='Choice2' name='Choice'>
							<label for='Choice2' class="btn-input-gray-dark">Meublé</label>

							<input type='radio' class="input-pretty" id='Choice3' name='Choice'>
							<label for='Choice3' class="btn-input-gray-dark">Vide</label>
						</form>
					</div>
					<div class="box-universal">
						<label class="name-title-white">Nombre de chambres</label>
						<form>
							<input type="reset" value="Tous" class="btn-tous"/>
							<input type='checkbox' class="input-pretty" id='Choice11' name='Choice'>
							<label for='Choice11' class="btn-input-gray-dark btn-input-number">1</label>

							<input type='checkbox' class="input-pretty" id='Choice13' name='Choice'>
							<label for='Choice13' class="btn-input-gray-dark btn-input-number">2</label>

							<input type='checkbox' class="input-pretty" id='Choice14' name='Choice'>
							<label for='Choice14' class="btn-input-gray-dark btn-input-number">3</label>

							<input type='checkbox' class="input-pretty" id='Choice15' name='Choice'>
							<label for='Choice15' class="btn-input-gray-dark btn-input-number">4</label>

							<input type='checkbox' class="input-pretty" id='Choice16' name='Choice'>
							<label for='Choice16' class="btn-input-gray-dark btn-input-number">5 et +</label>
						</form>
					</div>
				</div>
			</div>
		</div>

		<div class="grid grid-dark">
			<div class="title-advanced">
				<h2>Dessiner une zone</h2>
				<p>Cliquez sur la carte pour commencer le tracé.<br>
					Ajoutez des points en cliquant.<br>
					Double-clic pour finir le tracé et définir la zone.<br>
					<span class="blue">
						Lorsque vous êtes satisfait, il vous suffit de lancer la recherche.
					</span>
				</p>
			</div>
			<div class="box-carte">
				<img src="/./assets/images/dessin-carte.png">
				<div class="btn-plus-minus">
					<a href="" class="btn btn-gray-lite btn-plus"></a>
					<a href="" class="btn btn-gray-lite btn-minus"></a>
				</div>
				<div class="btn-carte-nav">
					<a href="" class="btn btn-blue">Rechercher</a>
					<a href="" class="btn btn-dark">Effacer le dessin</a>
				</div>
			</div>
			<div class="box-btn-search">
				<a href="" class="btn btn-gray">Effacer le dessin</a>
				<a href="" class="btn btn-red btn-sauv">Sauvegarder</a>
				<a href="" class="btn btn-blue">Rechercher</a>
			</div>
		</div>
		<div class="grid">
			<div class="grid-full">
				<h2 class="gray txt-line-metro">Choisir parmi nos sélections</h2>
				<p>Sélectionnez l’un des dessins que nous avons tracés pour vous.</p>
				<div class="box-place">
					<label>Le Marais</label>
					<a href="#" class="btn btn-gray btn-carte1"></a>
				</div>
				<div class="box-place">
					<label>Barbès</label>
					<a href="#" class="btn btn-gray btn-carte2"></a>
				</div>
				<div class="box-place">
					<label>Paris Ouest</label>
					<a href="#" class="btn btn-gray btn-carte3"></a>
				</div>
				<div class="box-place">
					<label>Les Ambassades</label>
					<a href="#" class="btn btn-gray btn-carte4"></a>
				</div>
				<div class="box-place">
					<label>Paris Est</label>
					<a href="#" class="btn btn-gray btn-carte5"></a>
				</div>
				<div class="box-place">
					<label>Rive Gauche</label>
					<a href="#" class="btn btn-gray btn-carte6"></a>
				</div>
				<div class="box-place">
					<label>Périphérique Est</label>
					<a href="#" class="btn btn-gray btn-carte7"></a>
				</div>
				<div class="box-place">
					<label>Rive Droite</label>
					<a href="#" class="btn btn-gray btn-carte8"></a>
				</div>
			</div>
		</div>


		<div class="grid">
			<div class="grid-half grid-transparent">
				<div class="grid-inner">
					<h1 class="blue">Decouveres <br> nos outils <br> de recherche</h1>
					<p>Ommi transforme la façon dont vous louez.
						Il rend service aux propriétaires et aux locataires.
						Ommi vous simplifie l’immobilier.
					</p>
					<a href="#" class="btn btn-red btn-annonce">
						<i class="i-group-red icon-metro"></i>
						par métro
					</a>
					<a href="#" class="btn btn-red btn-annonce">
						<i class="i-group-red icon-dessin"></i>
						par dessin
					</a>
					<a href="#" class="btn btn-red btn-annonce">
						<i class="i-group-red icon-carte-red"></i>
						par carte
					</a>
				</div>
			</div>
			<div class="inner-box-carte">
				<img src="/assets/images/carte-metro-small.png">
			</div>
		</div>
		<div class="grid grid-transparent">
			<div class="grid-half">
				<div class="grid-inner h120">
					<h1 class="gray">Compte Ommium</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Ommi, Ommi+ ou Ommium?
							Des comptes adaptés à chacun.
						</div>
						<div class="index-row-six-link">
							<a href="#link">Découvrez nos comptes</a>
						</div>
					</div>
				</div>
			</div>
			<div class="grid-half">
				<div class="grid-inner h120">
					<h1 class="gray">F.A.Q.</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Consultez les questions les plus fréquemment posées.
						</div>
						<div class="index-row-six-link">
							<a href="#link">Consultez les F.A.Q.</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="grid">
			<div class="grid-full">
				<h1 class="gray">Je m'nscris, c'est gratuit
					<a href="#" class="right btn btn-blue w200">Créer un compte</a>
				</h1>
			</div>
		</div>
	</div>
</main>