<div class="title-row-search-stand">
	<div class="container-text">
		<h1 class="white-txt">Recherche standard</h1>
	</div>
</div>
<main>
	<div class="inner">
		<div class="grid grid-dark">
			<div class="menu-search">
				<ul>
					<li><a href=""  class="active menu-icons icon-search">Recherche standard</a></li>
					<li><a href="" class="menu-icons icon-metro">Recherche<br>par  metro</a></li>
					<li><a href="" class="menu-icons icon-dessin">Recherche<br> par dessin</a></li>
					<li><a href="" class="menu-icons icon-carte">Recherche<br> par carte</a></li>
				</ul>
			</div>
			<div class="search-box">
				<div class="search-left">
					<div class="search-location">
						<label class="name-title-white">Localisation</label>
						<input type="text" placeholder="Où désirez-vous louer? "/>
						<a href="#" class="btn btn-small btn-dark icon-location"></a>
					</div>
					<div class="search-budget">
						<label class="name-title-white">Budget</label>
						<input type="text" placeholder="Budget min. (en €)"/>
						<input type="text" placeholder="Budget max. (en €)"/>
					</div>
					<div class="search-surface">
						<label class="name-title-white">Surface</label>
						<input type="text" placeholder="Surface min. (en m²)"/>
						<input type="text" placeholder="Surface max. (en m²)"/>
					</div>
				</div>
				<div class="search-right">
					<div class="box-universal">
						<label class="name-title-white">Mobilier</label>
						<form>
							<input type="reset" value="Tous" class="btn-tous"/>
							<input type='radio' id='Choice2' name='Choice'>
							<label for='Choice2' class="btn-input-gray-dark">Meublé</label>

							<input type='radio' id='Choice3' name='Choice'>
							<label for='Choice3' class="btn-input-gray-dark">Vide</label>
						</form>
					</div>
					<div class="box-universal">
						<label class="name-title-white">Nombre de chambres</label>
						<form>
							<input type="reset" value="Tous" class="btn-tous"/>
							<input type='checkbox' id='Choice11' name='Choice'>
							<label for='Choice11' class="btn-input-gray-dark btn-input-number">1</label>

							<input type='checkbox' id='Choice13' name='Choice'>
							<label for='Choice13' class="btn-input-gray-dark btn-input-number">2</label>

							<input type='checkbox' id='Choice14' name='Choice'>
							<label for='Choice14' class="btn-input-gray-dark btn-input-number">3</label>

							<input type='checkbox' id='Choice15' name='Choice'>
							<label for='Choice15' class="btn-input-gray-dark btn-input-number">4</label>

							<input type='checkbox' id='Choice16' name='Choice'>
							<label for='Choice16' class="btn-input-gray-dark btn-input-number">5 et +</label>
						</form>
					</div>
					<a href="#" class="btn btn-blue">Rechercher</a>
				</div>
			</div>
		</div>

		<div class="grid grid-dark">
			<h2>Critères Avancés</h2>
			<div class="box-search-results">
				<div class="box-universal">
					<label class="name-title-black">Type de bien</label>
					<form>
						<input type="reset" value="Tous" class="btn-tous"/>
						<input type='checkbox' id='Choice5' name='Choice'>
						<label for='Choice5' class="btn-input-gray-lite">Appartement</label>

						<input type='checkbox' id='Choice7' name='Choice'>
						<label for='Choice7' class="btn-input-gray-lite">Maison</label>

						<input type='checkbox' id='Choice8' name='Choice'>
						<label for='Choice8' class="btn-input-gray-lite">Studio</label>

						<input type='checkbox' id='Choice9' name='Choice'>
						<label for='Choice9' class="btn-input-gray-lite">Chambre</label>

						<input type='checkbox' id='Choice10' name='Choice'>
						<label for='Choice10' class="btn-input-gray-lite">Loft / Atelier</label>
					</form>
				</div>
				<div class="box-universal">
					<label class="name-title-black">Nombre de pièces</label>
					<form>
						<input type="reset" value="Tous" class="btn-tous"/>
						<input type='checkbox' id='Choice11' name='Choice'>
						<label for='Choice11' class="btn-input-gray-lite btn-input-number">1</label>

						<input type='checkbox' id='Choice12' name='Choice'>
						<label for='Choice12' class="btn-input-gray-lite btn-input-number">2</label>

						<input type='checkbox' id='Choice13' name='Choice'>
						<label for='Choice13' class="btn-input-gray-lite btn-input-number">3</label>

						<input type='checkbox' id='Choice14' name='Choice'>
						<label for='Choice14' class="btn-input-gray-lite btn-input-number">4</label>

						<input type='checkbox' id='Choice15' name='Choice'>
						<label for='Choice15' class="btn-input-gray-lite btn-input-number">5 et +</label>
					</form>
				</div>
			</div>
			<div class="box-btn-search">
				<a href="" class="btn btn-red">Sauvegarder ma recherche</a>
				<a href="" class="btn btn-blue">Rechercher</a>
			</div>
		</div>


		<div class="grid">
			<div class="grid-half grid-transparent">
				<div class="grid-inner">
					<h1 class="blue">Decouveres <br> nos outils <br> de recherche</h1>
					<p>Ommi transforme la façon dont vous louez.
						Il rend service aux propriétaires et aux locataires.
						Ommi vous simplifie l’immobilier.
					</p>
					<a href="#" class="btn btn-red btn-annonce">
						<i class="i-group-red icon-metro"></i>
						par métro
					</a>
					<a href="#" class="btn btn-red btn-annonce">
						<i class="i-group-red icon-dessin"></i>
						par dessin
					</a>
					<a href="#" class="btn btn-red btn-annonce">
						<i class="i-group-red icon-carte-red"></i>
						par carte
					</a>
				</div>
			</div>
		</div>
		<div class="grid grid-transparent">
			<div class="grid-half">
				<div class="grid-inner h120">
					<h1 class="gray">Compte Ommium</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Ommi, Ommi+ ou Ommium?
							Des comptes adaptés à chacun.
						</div>
						<div class="index-row-six-link">
							<a href="#link">Découvrez nos comptes</a>
						</div>
					</div>
				</div>
			</div>
			<div class="grid-half">
				<div class="grid-inner h120">
					<h1 class="gray">F.A.Q.</h1>
					<div class="index-row-six cf">
						<div class="index-row-six-text">
							Consultez les questions les plus fréquemment posées.
						</div>
						<div class="index-row-six-link">
							<a href="#link">Consultez les F.A.Q.</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="grid">
			<div class="grid-full">
				<h1 class="gray">Je m'nscris, c'est gratuit
					<a href="#" class="right btn btn-blue w200">Créer un compte</a>
				</h1>
			</div>
		</div>
	</div>
</main>