<? if (!$this->isAjax) : ?>
    <div class="inner">
<? endif; ?>  
<div id="page-registration">
	<h2><?= $this->translate('registration') ?></h2>
	<div class="registration-top">
		<span>Sélectionnez votre situation, </br><strong>Ommi</strong> vous apporte une aide adaptée à vos besoins</span>
		<div class="registration-top-buttons">
			<a class="btn btn-red open-in-modal" href="<?= $this->url(array('controller' => 'registration', 'action' => 'base', 'type' => Model_User::RESIDENT), null, true) ?>">Je cherche une location</a><span class="sep">ou</span><a class="btn btn-gray open-in-modal" href="<?= $this->url(array('controller' => 'registration', 'action' => 'base', 'type' => Model_User::OWNER), null, true) ?>">Je suis propriétaire</a>
		</div>
	</div>
	<div class="registration-type">
		<a href="#" class="btn btn-blue">S’inscrire par email</a>
		<a href="<?= $this->url(array('module' => 'default', 'controller' => 'login', 'action' => 'facebook'), null, true) ?>" class="btn btn-gray btn-fb">S’inscrire avec Facebook</a>
		<p>En cliquant sur « S’inscrire avec Facebook », vous confirmez que vous</br> acceptez les <a href="#">Conditions générales.</a></p>
	</div>
	<div class="registration-bottom">
		<a href="#bottom-link1" class="red">Je suis un professionnel</a>
		<p>Vous avez déjà un compte? <a class="open-in-modal" href="<?= $this->url(array('controller' => 'login', 'action' => 'index'), null, true) ?>">Connectez-vous</a></p>
	</div>
</div>

<? if (!$this->isAjax) : ?>
    </div>
<? endif; ?> 