Use <a href="<?= $this->url(array('module' => 'default', 'controller' => 'login', 'action' => 'facebook'), null, true) ?>">Facebook</a> account
<?= $this->form ?>
<p>By clicking "Create Account", you confirm that you accept the
<a href="#">Terms and Conditions</a> and <a href="#">Privacy Policy</a>.</p>
<? if ($this->isAjax) : ?>
    <script type="text/javascript">
        $(function() {
            var target = $('#modal-dialog');
            var options = {
                target: target
            };
            $('#registration-pro-form').ajaxForm(options);            
        });
    </script>
<? endif; ?>