<div class="tab-resume">
    <div class="inner-transparent inner-left">
        <?= $this->partial('_partials/my-profile.phtml', $this->getVars()); ?>
        <?= $this->partial('_partials/my-calendar.phtml', $this->getVars()); ?>
    </div>
    <div class="inner-transparent inner-right <?=$this->currUser->type?>" id="annonces">
        <?= $this->partial('_partials/my-alerts.phtml', $this->getVars()); ?>

        <? if ($this->currUser->type == Model_User::OWNER && count($this->candidatesCount) > 0) : ?>
            <h2 class="black-txt txt-small">Mes candidats</h2>
            <div class="box-info-universal my-candidates">
            <?php $isFirst = true; ?>
            <?php foreach($this->candidatesCount as $indx => $rec): ?>
                <div class="single-candidate">
                    <?php if (!$isFirst): ?>
                    <div class="separator"></div>
                    <?php endif; ?>
                    <h4><?= $this->escape($rec['title']) ?></h4>

                    <div class="counts-info">
                        <span><?=$rec['all']?> candidats</span>
                        <?php if ($rec['selected'] > 0): ?>
                        <span><?=$rec['selected']?> candidats selectionnes</span>
                        <?php endif; ?>
                        <?php if ($rec['new'] > 0): ?>
                        <span class="red"><?=$rec['new']?> nouveaux candidats</span>
                        <?php endif; ?>
                    </div>

                    <a class="btn btn-blue btn-candidates" href="<?=$this->url(array('module' => 'user', 'controller' => 'candidates', 'action' => 'index', 'property_id' => $indx), null, true)?>">Voir mes candidatss</a>
                    <div class="clear"></div>

                    <?php $isFirst = false; ?>
                </div>
            <?php endforeach; ?>
            </div>
        <? endif; ?>

        <? if ($this->currUser->type == Model_User::OWNER && count($this->activeProperties)) : ?>
            <h3>Mes annonces</h3>
            <div class="annonce-blocks">
                <? foreach ($this->activeProperties as $property) : ?>
                    <div class="annonce-block grid-gray">
                        <div class="annonce-block-photo">
                            <?= $this->imageResize(100, 100, $property->main_photo) ?>
                        </div>
                        <div class="annonce-block-information">
                            <h4><?= $this->escape($property->title) ?></h4>
                            <div class="information-more">
                                <div class="information-left">
                                    <span class="address"><?= $this->escape($property->address) ?> (<?= $property->postcode ?>)</span>
                                    <span>Vue <?= $property->views ?> fois</span>
                                </div>
                                <div class="information-right">
                                    <span><?= $property->getApplicationsCount() ?> candidats</span>
                                    <span><?= $property->getAcceptedAppsCount() ?> candidats sélectionnés</span>
                                </div>
                            </div>
                            <div class="information-links">
                                <a class="blue" href="#">Ajouter une date</a>
                                <a class="red" href="<?= $this->url(array('module' => 'user', 'controller' => 'property', 'action' => 'location', 'item' => $property->id), null, false) ?>">Modifier l’annonce</a>
                                <a class="black" href="#">Voir</a>
                            </div>
                        </div>
                        <div class="annonce-block-controlls">
                            <div class="controlls-price" style="border-left: 3px dotted #E5E5E5;">
                                <span class="price">
                                    <?= $property->amount_of_charges ?> €
                                </span>
                                <a class="btn btn-dark" href="#">
                                    J’ai trouvé <br />mon locataire
                                </a>
                            </div>
                        </div>
                    </div>
                <? endforeach; ?>

                <? foreach ($this->inActiveProperties as $property) : ?>
                    <div class="annonce-block grid-gray inactive">
                        <div class="annonce-block-photo">
                            <?= $this->imageResize(100, 100, $property->main_photo) ?>
                        </div>
                        <div class="annonce-block-information">
                            <h4><?= $this->escape($property->title) ?></h4>
                            <div class="information-more">
                                <div class="information-left">
                                    <span class="address"><?= $this->escape($property->address) ?> (<?= $property->postcode ?>)</span>
                                    <span>Vue <?= $property->views ?> fois</span>
                                </div>
                                <div class="information-right">
                                    <span><?= $property->getApplicationsCount() ?> candidats</span>
                                    <span><?= $property->getAcceptedAppsCount() ?> candidats sélectionnés</span>
                                </div>
                            </div>
                            <div class="information-links">
                                <a class="blue" href="#">Ajouter une date</a>
                                <a class="red" href="<?= $this->url(array('module' => 'user', 'controller' => 'property', 'action' => 'location', 'item' => $property->id), null, false) ?>">Modifier l’annonce</a>
                                <a class="black" href="#">Voir</a>
                            </div>
                        </div>
                        <div class="annonce-block-controlls">
                            <div class="controlls-price" style="border-left: 3px dotted #E5E5E5;">
                                <span class="price">
                                    <?= $property->amount_of_charges ?> €
                                </span>
                                <a class="btn btn-dark" href="#">
                                    J’ai trouvé <br />mon locataire
                                </a>
                            </div>
                        </div>
                    </div>
                <? endforeach; ?>

                <a class="btn btn-blue btn-voir" href="<?=$this->url(array('module' => 'user', 'controller' => 'properties', 'action' => 'index'), null, true)?>">Voir mes annonces</a>
                <div class="clear"></div>
            </div>

        <? endif; ?>


        <? if ($this->applications->count()) : ?>
        <h2 class="black-txt txt-small">Mes candidatures récentes</h2>
        <div class="box-info-univ-black">
            <? foreach ($this->applications as $application) : ?>
            <div class="grid grid-inner-item">
                <div class="box-text info-box">
                    <?= $this->imageResize(100, 100, $application->Property->main_photo, array('class' => 'item-img')) ?>
                    <h3 class="item-title"><?= $this->escape($application->Property->title) ?></h3>
                    <div class="item-address">
                        <?= $this->escape($application->Property->address) ?> (<?= $application->Property->postcode ?>)
                    </div>
                    <? if ($application->isAccepted()) : ?>
                        <a class="btn small-btn btn-gray-small btn-item blue" href="#">Acceptee</a>
                    <? elseif ($application->isDeclined()) : ?>
                        <a class="btn small-btn btn-gray-small btn-item red" href="#">Refusee</a>
                    <? elseif ($application->isRead()) : ?>
                        <a class="btn small-btn btn-gray-small btn-item black" href="#">Lue</a>
                    <? else : ?>
                        <a class="btn small-btn btn-gray-small btn-item black" href="#">Non lue</a>
                    <? endif ?>
                    <a href="<?= $this->url(array('module' => 'default', 'controller' => 'property', 'action' => 'detail', 'item' => $application->property_id), null, false) ?>" class="black link-add">Voir l'annonce</a>
                </div>
                <div class="box-text price-box">
                    <p class="price-small"><?= $application->rate ?> €</p>
                    <p><?= $application->Property->size ?> m²</p>
                    <p><?= $application->Property->number_of_rooms1 ?> pièces</p>
                </div>
            </div>
            <? endforeach; ?>
            <a href="<?= $this->url(array('module' => 'user', 'controller' => 'candidatures', 'action' => 'index'), null, false) ?>" class="btn btn-blue btn-candid">Voir mes candidatures</a>
        </div>
        <? endif; ?>

        <? if ($this->searches->count()) : ?>
        <h2 class="black-txt txt-small">Mes recherches récentes</h2>
        <div class="box-info-univ-black">
            <? foreach ($this->searches as $searchKey => $search) : ?>
            <div class="grid grid-inner-item">
                <div class="box-text info-box">
                    <h3 class="item-title"><?= substr($tmpStr = $this->escape($search->name), 0, 50).(strlen($tmpStr) > 50 ? '...' : '') ?></h3>
                    <div class="box-input-item-">
                        <? foreach ($search->getSearchFields() as $key => $field) : ?>
                        <input type="checkbox" class="input-pretty" id="condition-<?= $searchKey ?>-<?= $key ?>" name="<?= $field ?>"/>
                        <label for="condition-<?= $searchKey ?>-<?= $key ?>" class="btn-input-gray-lite"><?= $this->translate($field) ?></label>
                        <? endforeach; ?>
                    </div>       
                    <div class="box-links-add">
						<?php
						$urlSearch = $this->url(array('module' => 'default', 'controller' => 'search', 'action' => 'results', 'search_id' => $search->id), null, false);
						$urlUpdate = $this->url(array('module' => 'default', 'controller' => 'search', 'action' => 'updatesearch', 'search_id' => $search->id), null, false);
						?>
                        <a class="blue" href="<?= $urlSearch ?>">Voir la recherche</a>
                        <a class="black" href="<?= $urlUpdate; ?>">Modifier la recherche</a>
                    </div>
                </div>
                <div class="box-text price-box box-annonce">
                    <p><?= $search->found_items ?> annonces trouvees</p>
                    <p>4 nouvelles annonces</p>
                    <a class="red delete-search" href="<?= $this->url(array('module' => 'user', 'controller' => 'searches', 'action' => 'delete', 'id' => $search->id), null, false) ?>">Supprimer</a>
                </div>
            </div>
            <? endforeach; ?>
            <a href="<?= $this->url(array('module' => 'user', 'controller' => 'searches', 'action' => 'index'), null, false) ?>" class="btn btn-blue btn-search">Voir mes recherches</a>
        </div>
        <? endif; ?>
    </div>
</div>
<script type="text/javascript">
    
    $('.delete-search').click(function (event) {
        if (!confirm('<?= $this->translate('are_you_sure_want_to_delete_search') ?>')) {
            event.preventDefault();
        }
    })
    
</script>