<div class="grid">
    <div class="grid-full grid-full-other">
        <div class="grid-inner">
            <h1 class="gray"><span class="blue"> Pourquoi faire certifier</span><br>
                mon dossier par OMMI ?
            </h1>
            <div class="index-row-six cf">
                <div class="index-row-six-text">
                    Partez avec un avantage décisif !<br>
                    En faisant certifier votre candidature, rassurez les propriétaires et sortez du lot.
                </div>
                <div class="index-row-six-btn">
                    <a href="#" class="right btn btn-blue w200">Certifier ma candidature</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="grid grid-transparent">
    <div class="grid-half grid-half-other">
        <div class="grid-inner">
            <h1 class="gray">Presse de trouver<br> un logement ?</h1>
            <div class="index-row-six cf">
                <div class="index-row-six-text">
                    Découvrez nos comptes sur-mesure et<br>
                    choisissez celui qui vous convient le mieux.<br>
                    Donnez-vous les moyens de trouver vite.
                </div>
                <div class="index-row-six-link">
                    <a href="#">Comples OMMI</a>
                </div>
            </div>
        </div>
    </div>

    <div class="grid-half grid-half-other">
        <div class="grid-inner">
            <h1 class="gray">Au secours !<br> Un depanneur ?</h1>
            <div class="index-row-six cf">
                <div class="index-row-six-text">
                    Pas de panique! Profitez du réseau Ommi<br>
                    de dépanneurs de confiance à prix d’ami !
                    Programmez en ligne vos rendez-vous.
                </div>
                <div class="index-row-six-link">
                    <a href="#">Dépannage</a>
                </div>
            </div>
        </div>
    </div>
</div>