<?php

$tabs['resident'] = array(
    'index'             => 'Résumé',
    'documents'         => 'Mon dossier',
    'searches'          => 'Mes recherches', 
    'candidatures'      => 'Mes candidatures',
    'resident-services' => 'Mes services',
    'my-account'        => 'Mon compte'
);
$tabs['owner'] = array(
    'index'             => 'Résumé',
    'properties'        => 'Mes annonces',
    'candidates'        => 'Mes candidats', 
    'owner-services'    => 'Mes services',    
    'my-account'        => 'Mon compte'
);

$tabs = $tabs[$this->currUser->type];

$currController = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$currAction = Zend_Controller_Front::getInstance()->getRequest()->getActionName();

?>
<? if ($currController != 'candidates' || $currAction != 'view'): ?>
<div class="grid">
    <div class="page-tab-nav">
        <ul>
            <? foreach ($tabs as $controller => $label) : ?>
            <li><a href="<?= $this->url(array('module' => 'user', 'controller' => $controller, 'action' => 'index'), null, false) ?>" <?= $currController == $controller ? 'class="active"' : '' ?>><?= $this->translate($label) ?></a></li>
            <? endforeach; ?>
        </ul>
    </div>
    <?= $this->dashboardContent ?>
    <? if ($currController == 'index') : ?>
    <div class="box-btn-nav-resume">
        <a class="btn btn-red" href="#">Profil Ommium</a>
        <a class="btn btn-blue" href="#">Dossier de candidature</a>
        <a class="btn btn-gray icon-book" href="#">Guide du Locataire</a>
        <a class="btn btn-gray icon-hand" href="#">J’ai trouvé mon appart !</a>
    </div>             
    <? endif ?>
</div>
<? else: ?>
    <?= $this->dashboardContent ?>
<? endif; ?>