<footer>
    <div class="inner">
        <div class="nav-blocks">
            <div class="block">
                <h3>Découvrir</h3>
                <ul>
                    <li><a href="#">Voir la vidéo</a></li>
                    <li><a href="#">Comment ça marche?</a></li>
                    <li><a href="#">Ommi, Ommi+ et Ommium</a></li>
                    <li><a href="#">Mentions légales</a></li>
                    <li><a href="#">C.G.U.</a></li>
                </ul>
            </div>
            <div class="block">
                <h3>Aide</h3>
                <ul>
                    <li><a href="#">Guide du Propriétaire</a></li>
                    <li><a href="#">Guide du Locataire</a></li>
                    <li><a href="#">Guide du Professionnel</a></li>
                    <li><a href="#">F.A.Q.</a></li>
                </ul>
            </div>
            <div class="block">
                <h3>Contact</h3>
                <ul>
                    <li><a href="#">Qui sommes-nous?</a></li>
                    <li><a href="#">L’entreprise</a></li>
                    <li><a href="#">Les réseaux sociaux</a></li>
                    <li><a href="#">Nous contacter</a></li>
                </ul>
            </div>
        </div>
        <div class="nav-buttons">
            <a href="/user/property/new-add" class="btn btn-red">Publier une annonce</a>
            <a class="btn btn-blue open-in-modal" href="/registration">Créer un compte</a>
            <a class="btn btn-gray open-in-modal" href="/registration/pro">Compte Professionnel</a>
        </div>
        <div class="cf"></div>
        <div class="fb-likes-block">
            <span><strong>Ommi</strong> sur Facebook <a href="#" class="btn btn-gray btn-fb-like">J’aime</a> 318,903 personnes aiment <strong>Ommi</strong></span>
        </div>
    </div>
    <div class="copyright">
        Tous droits réservés - Ommi SAS
    </div>
</footer> 