<header>
    <div class="inner">
        <a href="/" class="logo">Ommi</a>
        <ul id="header-nav">
            <li class="left"><a href="#">Guide du Locataire</a></li>
            <li><a href="/search" class="btn btn-red">Nouvelle recherche</a></li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="">Bonjour, <?= $this->currUser->getFullName() ?> <i class="caret"></i></a>
                <ul class="dropdown-menu">
                    <li><a href="">Résumé</a></li>
                    <li><a href="">Mon dossier</a></li>
                    <li><a href="">Mes candidatures</a></li>
                    <li><a href="">Mes recherches</a></li>
                    <li><a href="">Me services</a></li>
                    <li><a href="">Mon compte</a></li>
                    <li><a href="">Mes recherches</a></li>
                    <li><a href="/logout" class="red">Se déconnecter</a></li>
                </ul>
            </li>
            <li><a href="#">Mes candidatures</a></li>           
        </ul>
    </div>
</header>
