<h2 class="black-txt txt-small">Calendrier</h2>
<div class="box-info-universal">
    <div class="calendar">
        <div class="name-month-calend">
            <h2>
                <a href="#" class="btn btn-gray-lite btn-cal-prev"></a>
                Juillet
                <a href="#" class="btn btn-gray-lite name-month-next"></a>
            </h2>
        </div>
        <div class="inner-cell cell-month">
            <div class="cell">Lun</div>
            <div class="cell">Mar</div>
            <div class="cell">Mer</div>
            <div class="cell">Jeu</div>
            <div class="cell">Ven</div>
            <div class="cell">Sa</div>
            <div class="cell">Dim</div>
        </div>
        <div class="inner-cell">
            <div class="cell cell-gray">1</div>
            <div class="cell cell-gray">2</div>
            <div class="cell cell-gray">3</div>
            <div class="cell cell-gray">4</div>
            <div class="cell cell-gray">5</div>
            <div class="cell cell-gray">6</div>
            <div class="cell cell-gray">7</div>
        </div>
        <div class="inner-cell">
            <div class="cell cell-gray">8</div>
            <div class="cell cell-gray">9</div>
            <div class="cell cell-gray">10</div>
            <div class="cell cell-gray">11</div>
            <div class="cell cell-black">12</div>
            <div class="cell">13</div>
            <div class="cell">14</div>
        </div>
        <div class="inner-cell">
            <div class="cell">15</div>
            <div class="cell">16</div>
            <div class="cell cell-blue">17</div>
            <div class="cell">18</div>
            <div class="cell">19</div>
            <div class="cell">20</div>
            <div class="cell">21</div>
        </div>
        <div class="inner-cell">
            <div class="cell">22</div>
            <div class="cell cell-blue">23</div>
            <div class="cell cell-blue">24</div>
            <div class="cell">25</div>
            <div class="cell cell-blue">26</div>
            <div class="cell">27</div>
            <div class="cell">28</div>
        </div>
        <div class="inner-cell cell-bottom">
            <div class="cell">29</div>
            <div class="cell">30</div>
            <div class="cell">31</div>
            <div class="cell cell-next-month">1</div>
            <div class="cell cell-next-month">2</div>
            <div class="cell cell-next-month">3</div>
            <div class="cell cell-next-month">4</div>
        </div>
    </div>
    <div class="color-calendar">
        <img src="/./assets/images/date-visit.png">
        <span class="black">Visite</span>
        <img src="/./assets/images/date-free.png">
        <span class="black">Depannage</span>
    </div>
    <a href="<?= $this->url(array('module' => 'user', 'controller' => 'candidatures', 'action' => 'index'), null, false) ?>" class="btn btn-blue btn-voir">Voir  mes candidatures</a>
</div>