<?php
$this->headLink()->appendStylesheet('/assets/css/property_form.css');
?>

<h2 class="black-txt txt-small">Calendrier</h2>
<div class="box-info-universal">
    <div class="calendar one-month-calendar">
        <div id="one-month-calendar"></div>
    </div>
    <div class="color-calendar">
        <img src="/./assets/images/date-visit.png">
        <span class="black">Visite</span>
        <img src="/./assets/images/date-free.png">
        <span class="black">Depannage</span>
    </div>
    <a href="<?= $this->url(array('module' => 'user', 'controller' => 'candidatures', 'action' => 'index'), null, false) ?>" class="btn btn-blue btn-voir">Voir  mes candidatures</a>
</div>

<script type="text/javascript">
    var datesList = new Array(<?=json_encode($this->visitDates)?>);

    $('#one-month-calendar').datepicker(
        {
            numberOfMonths: 1,
            showButtonPanel: false,

            monthNames: ['Janvier','Février','Mars','Avril','Mai','Juin',
                'Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
            monthNamesShort: ['Jan','Fév','Mar','Avr','Mai','Jun',
                'Jul','Aoû','Sep','Oct','Nov','Déc'],
            dayNames: ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'],
            dayNamesShort: ['Dim','Lun','Mar','Mer','Jeu','Ven','Sam'],
            dayNamesMin: ['Dim','Lun','Mar','Mer','Jeu','Ven','Sa'],

            firstDay: 1,
            prevText: '', prevStatus: 'Voir le mois précédent',
            prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: 'Voir l\'année précédent',
            nextText: '', nextStatus: 'Voir le mois suivant',
            nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: 'Voir l\'année suivant',
            currentText: 'Courant', currentStatus: 'Voir le mois courant',
            todayText: 'Aujourd\'hui', todayStatus: 'Voir aujourd\'hui',
            clearText: 'Effacer', clearStatus: 'Effacer la date sélectionnée',
            closeText: 'Fermer', closeStatus: 'Fermer sans modifier',
            yearStatus: 'Voir une autre année', monthStatus: 'Voir un autre mois',
            weekText: 'Sm', weekStatus: 'Semaine de l\'année',
            dayStatus: '\'Choisir\' le DD d MM',
            defaultStatus: 'Choisir la date',
            isRTL: false,

            dateFormat: 'dd/mm/yy',

            beforeShowDay: function(date) {
                var res = new Array(
                    true,
                    '',
                    ''
                );

                var curDate = new Date();
                curDate = curDate.getFullYear()+'-'+
                    ((curDate.getMonth()+1) <= 9 ? '0'+(curDate.getMonth()+1) : (curDate.getMonth()+1))+'-'+
                    (curDate.getDate() <= 9 ? '0'+curDate.getDate() : curDate.getDate());

                var checkedDate = date.getFullYear()+'-'+
                    ((date.getMonth()+1) <= 9 ? '0'+(date.getMonth()+1) : (date.getMonth()+1))+'-'+
                    (date.getDate() <= 9 ? '0'+date.getDate() : date.getDate());

                if (checkedDate < curDate) {
                    res[0] = false;
                    res[1] = 'td-selected';
                }

                for (var i=0; i<datesList[0].length; i++) {
                    if (datesList[0][i].year == date.getFullYear() &&
                        datesList[0][i].month == (date.getMonth()+1) &&
                        datesList[0][i].day == date.getDate()) {

                        if (res[0] != false) {
                            if (datesList[0][i].declined == 0) {
                                res[1] = 'td-selected-new';
                            } else {
                                res[1] = 'td-selected-declined';
                            }
                        }
                    }
                }

                if (checkedDate == curDate && res[1] != 'td-selected-new') {
                    res[1] = 'td-selected-cur';
                }

                res[0] = false;

                return res;
            }

        }
    );
</script>
