<div class="page-tab-content" id="annonces">

    <h3>Annonces actives</h3>
    <div class="annonce-blocks">
        <div class="annonce-block grid-gray">
            <div class="annonce-block-photo">
                <img src="//place-hold.it/120x120">
            </div>
            <div class="annonce-block-information">
                <h4>Appartement calme à Père-Lachaise</h4>
                <div class="information-more">
                    <div class="information-left">
                        <span>Appartement<span class="slash">|</span>Meublé</span>
                        <span>Paris 11e (75011)</span>
                        <span>45 m²</span>
                        <span>2e étage avec ascenceur</span>
                    </div>
                    <div class="information-right">
                        <span>disponibilité : immédiate</span>
                        <span>Cave<span class="slash">|</span>Balcon</span>
                        <span>&nbsp;</span>
                        <span class="blue">3 dates de visites</span>
                    </div>

                </div>
                <div class="information-links">
                    <a class="blue" href="#">Ajouter une date</a>
                    <a class="red" href="#">Modifier l’annonce</a>
                    <a class="black" href="#">Voir l’annonce</a>
                </div>
            </div>
            <div class="annonce-block-controlls">
                <div class="controlls-stats">
                    <span>Vue 87 fois</span>
                    <span>19 candidats</span>
                    <span>2 candidats sélectionnés</span>
                    <a class="btn btn-red" href="#">Mettre en valeur</a>
                </div>
                <div class="controlls-price">
                    <span class="price">
                        1200 €
                    </span>
                    <a class="btn btn-dark" href="#">
                        J’ai trouvé <br>mon locataire
                    </a>
                </div>
            </div>
        </div>

        <div class="annonce-block grid-gray">
            <div class="annonce-block-photo">
                <img src="//place-hold.it/120x120">
            </div>
            <div class="annonce-block-information">
                <h4>Appartement calme à Père-Lachaise</h4>
                <div class="information-more">
                    <div class="information-left">
                        <span>Appartement<span class="slash">|</span>Meublé</span>
                        <span>Paris 11e (75011)</span>
                        <span>45 m²</span>
                        <span>2e étage avec ascenceur</span>
                    </div>
                    <div class="information-right">
                        <span>disponibilité : immédiate</span>
                        <span>Cave<span class="slash">|</span>Balcon</span>
                        <span>&nbsp;</span>
                        <span class="blue">3 dates de visites</span>
                    </div>

                </div>
                <div class="information-links">
                    <a class="blue" href="#">Ajouter une date</a>
                    <a class="red" href="#">Modifier l’annonce</a>
                    <a class="black" href="#">Voir l’annonce</a>
                </div>
            </div>
            <div class="annonce-block-controlls">
                <div class="controlls-stats">
                    <span>Vue 87 fois</span>
                    <span>19 candidats</span>
                    <span>2 candidats sélectionnés</span>
                    <a class="btn btn-red" href="#">Mettre en valeur</a>
                </div>
                <div class="controlls-price">
                    <span class="price">
                        1200 €
                    </span>
                    <a class="btn btn-dark" href="#">
                        J’ai trouvé <br>mon locataire
                    </a>
                </div>
            </div>
        </div>
    </div>


    <!-- Неактивные блоки -->
    <h3 style="margin-top: 20px;">Annonces inactives</h3>
    <div class="annonce-blocks inactive-blocks">
        <div class="annonce-block grid-gray">
            <div class="annonce-block-photo">
                <img src="//place-hold.it/120x120">
            </div>
            <div class="annonce-block-information">
                <h4>Appartement calme à Père-Lachaise</h4>
                <div class="information-more">
                    <div class="information-left">
                        <span>Appartement<span class="slash">|</span>Meublé</span>
                        <span>Paris 11e (75011)</span>
                        <span>45 m²</span>
                        <span>2e étage avec ascenceur</span>
                    </div>
                    <div class="information-right">
                        <span>disponibilité : immédiate</span>
                        <span>Cave<span class="slash">|</span>Balcon</span>
                        <span>&nbsp;</span>
                        <span class="blue">3 dates de visites</span>
                    </div>

                </div>
                <div class="information-links">
                    <a class="blue" href="#">Ajouter une date</a>
                    <a class="red" href="#">Modifier l’annonce</a>
                    <a class="black" href="#">Voir l’annonce</a>
                </div>
            </div>
            <div class="annonce-block-controlls">
                <div class="controlls-stats">
                    <span>Vue 87 fois</span>
                    <span>19 candidats</span>
                    <span>2 candidats sélectionnés</span>
                    <a class="btn btn-red" href="#">Mettre en valeur</a>
                </div>
                <div class="controlls-price">
                    <span class="price">
                        1200 €
                    </span>
                    <a class="btn btn-dark" href="#">
                        J’ai trouvé <br>mon locataire
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>