<div id="publier" class="grid">
    <div class="left">
        <?= $this->partial('property/_partials/left-dashboard.phtml', $this->getVars()) ?>
    </div>
    <div class="right">
        <div id="content-step-0" class="progress-content">
            <div class="block-grid grid-light-blue">
                <h2>La location</h2>
                <p>Définissez les éléments essentiels de votre annonce.<br>Titre, montant du loyer, etc… tels qu’ils appaent aux candidats.</p>
                <span>1</span>
            </div>
            <div class="block-grid grid-light-blue">
                <h2>Décrire le bien</h2>
                <p>Décrivez les caractéristiques spécifiques de votre bien.<br>Le tout, en quelques clics.</p>
                <span>2</span>
            </div>
            <div class="block-grid grid-light-blue">
                <h2>Ajouter des photos</h2>
                <p>Les bonnes photos attirent les bons candidats.<br>Pensez-y.</p>
                <span>3</span>
            </div>
            <div class="block-grid grid-light-blue">
                <h2>Profil recherché</h2>
                <p>Vous préférez louer à un étudiant ? Un salarié ? Un indépendant ?<br>Donnez vos préférences, vos candi</p>
                <span>4</span>
            </div>
            <div class="block-grid grid-light-blue">
                <h2>Définir des visites</h2>
                <p>Sélectionnez les dates de visite qui vous conviennent.<br>Les candidats postuleront pour l’une d’entre</p>
                <span>5</span>
            </div>
            <div class="progress-buttons">
                <a class="btn btn-red btn-arrow-next right" href="<?=
                   $this->url(array(
                       'module' => 'user',
                       'controller' => 'property',
                       'action' => 'location'
                           ), null, false)
                   ?>"><?= $this->translate('begin') ?></a>
            </div>
        </div>
    </div>
</div>
