<table border="1" width="100%">
    <tr valign="top">
        <td width="33%">
            <!-- Left menu -->
            <table border="1" width="100%">
                <tr>
                    <td style="background-color:#3cbecc;"><?= $this->translate('status') ?>: 0%</td>
                </tr>
                <tr>
                    <td>Rental</td>
                </tr>
                <tr>
                    <td>Description</td>
                </tr>
                <tr>
                    <td>Photos</td>
                </tr>
                <tr>
                    <td>Hunted profile</td>
                </tr>
                <tr>
                    <td>Visit dates</td>
                </tr>
            </table>
            <!-- /Left menu -->
        </td>
        <td>
            <table border="1" width="100%">
                <tr>
                    <td style="background-color:#c0f2ef;">
                        <h1>1</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc a volutpat odio. 
                        Fusce nulla libero, convallis id nulla ut, rutrum consequat sapien. Curabitur vel malesuada diam, sed ullamcorper massa. 
                        Sed luctus at dolor nec imperdiet. In venenatis eleifend rhoncus. 
                        Nunc ligula lorem, sollicitudin vitae tortor ac, consequat facilisis lectus. 
                        Aliquam ornare placerat augue vitae pulvinar.
                        </p>
                    </td>
                </tr>
                <tr>
                    <td style="background-color:#c0f2ef;">
                        <h1>2</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc a volutpat odio. 
                        Fusce nulla libero, convallis id nulla ut, rutrum consequat sapien. Curabitur vel malesuada diam, sed ullamcorper massa. 
                        Sed luctus at dolor nec imperdiet. In venenatis eleifend rhoncus. 
                        Nunc ligula lorem, sollicitudin vitae tortor ac, consequat facilisis lectus. 
                        Aliquam ornare placerat augue vitae pulvinar.
                        </p>
                    </td>
                </tr>
                <tr>
                    <td style="background-color:#c0f2ef;">
                        <h1>3</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc a volutpat odio. 
                        Fusce nulla libero, convallis id nulla ut, rutrum consequat sapien. Curabitur vel malesuada diam, sed ullamcorper massa. 
                        Sed luctus at dolor nec imperdiet. In venenatis eleifend rhoncus. 
                        Nunc ligula lorem, sollicitudin vitae tortor ac, consequat facilisis lectus. 
                        Aliquam ornare placerat augue vitae pulvinar.
                        </p>
                    </td>
                </tr>
                <tr>
                    <td style="background-color:#c0f2ef;">
                        <h1>4</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc a volutpat odio. 
                        Fusce nulla libero, convallis id nulla ut, rutrum consequat sapien. Curabitur vel malesuada diam, sed ullamcorper massa. 
                        Sed luctus at dolor nec imperdiet. In venenatis eleifend rhoncus. 
                        Nunc ligula lorem, sollicitudin vitae tortor ac, consequat facilisis lectus. 
                        Aliquam ornare placerat augue vitae pulvinar.
                        </p>
                    </td>
                </tr>
                <tr>
                    <td style="background-color:#c0f2ef;">
                        <h1>5</h1>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc a volutpat odio. 
                        Fusce nulla libero, convallis id nulla ut, rutrum consequat sapien. Curabitur vel malesuada diam, sed ullamcorper massa. 
                        Sed luctus at dolor nec imperdiet. In venenatis eleifend rhoncus. 
                        Nunc ligula lorem, sollicitudin vitae tortor ac, consequat facilisis lectus. 
                        Aliquam ornare placerat augue vitae pulvinar.
                        </p>
                    </td>
                </tr>
            </table>
            <!-- Form -->
            <?= $this->form ?>
            <!-- /Form -->
        </td>
    </tr>
</table>
