<?php
$this->headLink()->appendStylesheet('/assets/css/property_form.css');
$this->headScript()->appendFile('/assets/js/property_form.js');
?>
<script type="text/javascript">
    $(document).ready(function() {

        var dropZone = document.getElementById('file-drope-zone');

        if (typeof(window.FileReader) == 'undefined') {
            $(dropZone).hide();
        }

        dropZone.ondrop = function(event) {
            event.preventDefault();

            $(dropZone).removeClass('hover');
            $(dropZone).css('opacity', 0.25);

            var file = event.dataTransfer.files[0];
            var fd = new FormData();
            var xhr = new XMLHttpRequest();
            xhr.open('POST', $('form#photos-form').attr('action'));

            xhr.onload = function() {
                updatePhotosList();
                $(dropZone).css('opacity', 1);
            };

            fd.append("image", file);
            fd.append("form", "upload");
            xhr.send(fd);
        };

        dropZone.ondragover = function() {
            $(dropZone).addClass('hover');
            return false;
        };

        dropZone.ondragleave = function() {
            $(dropZone).removeClass('hover');
            return false;
        };

    });
</script>
<div id="publier" class="grid">

    <div class="left">
        <?= $this->partial('property/_partials/left-dashboard.phtml', $this->getVars()) ?>
    </div>
    <div class="right">
        <div id="content-step-3" class="progress-content">
            <form id="photos-form" action="/user/property/photos/item/<?=$this->property->id?>" method="post" enctype="multipart/form-data">
                <div class="step-title">
                    <h1>Photos de l'annonce</h1>
                </div>
                <div class="block-grid grid-inset">
                    <fieldset class="image-form">
                        <?= $this->form_upload_photo->image ?>
                        <a id="upload-photo-file-btn" class="btn btn-red left btn-upload-photo" href="#"><div class="i-wrapper"><i class="icon-add-photo"></i></div><div class="text-wrapper">Sélectioner une photo sur mon ordinateur</div></a>
                        <div class="file-drope-zone" id="file-drope-zone">
                            <div class="i-wrapper"><i class="icon-drop-photo"></i></div>
                            <div class="text-wrapper">Glisser et deposer une photo ici pour la telecharger</div>
                        </div>
                    </fieldset>
                    <script type="text/javascript">
                        $('#upload-photo-file-btn').click(function() {
                            $('input#image').click();
                            return false;
                        });
                        $('input[type="file"]').change(function() {
                            if ($(this).val() != '') {
                                $('form#photos-form').submit();
                            }
                        });
                    </script>
                    <div class="upload-descr">
                        <p class="cyan">Les photos sont importantes sur OMMI.</p>
                        <p class="drk-gray">Elles aident  les bons candidats a se faire une meiluere idee de votre bien.<br />
                        Ne les chargez qu'une seules fois:<br />
                        pour votre confort, OMMI les garde en memoire pour de prochaines locations.</p>
                    </div>
                </div>
                <div class="block-grid grid-inset">
                    <?php if (!$this->photos): ?>
                        <fieldset id="photo-wrapper">
                            <p class="cyan">No photos</p>
                        </fieldset>
                    <?php else: ?>
                        <fieldset id="photo-wrapper">
                        <label>Choisir la photo principale de l'annonce</label>
                        <?php
                        $count = 1;
                        ?>
                        <?php foreach ($this->photos as $photo): ?>
                            <div data-action-url="/user/property/main-photo/item/<?=$this->property->id?>" data-photo-name="<?=$photo['name']?>" class="user-photo-item<?=($photo['link'] == $this->property->main_photo ? ' main' : ' setMainPhoto')?>" title="<?=($photo['link'] == $this->property->main_photo  ? '' : 'Assurez photo principale')?>" style="background: url('<?="/image/by/w/132/h/132/i/" . str_replace("/", '_', $photo['link'])?>');">
                                <div class="bottom-area">
                                    <?= $count++ ?>
                                    <i class="main-photo" title="Photo principale"></i>
                                    <a href="/user/property/remove-photo/item/<?=$this->property->id?>" class="del-photo" data-photo-name="<?=$photo['name']?>" onClick="return confirm('Effacer la photo, vous êtes shure?');"><i class="del-photo" title="Supprimer photo"></i></a>
                                </div>
                            </div>
                        <?php endforeach; ?>
                        </fieldset>
                    <?php endif; ?>
                </div>

                <div class="progress-buttons">
                    <input type="hidden" name="form" id="form-action" value="upload"/>
                    <a id="description-form-cancel" class="btn btn-gray btn-arrow-prev left" href="/user/property/description/item/<?=$this->property->id?>">Étape précédente</a>
                    <a id="description-form-next" class="btn btn-blue btn-arrow-next right" href="/user/property/hunted-profile/item/<?=$this->property->id?>">Enregistrer et continuer</a>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    function updatePhotosList() {
        $.get(window.location, function(htmlCode) {
            $('fieldset#photo-wrapper').html($(htmlCode).find('fieldset#photo-wrapper').html());
            $('fieldset#photo-wrapper').css('opacity', 1);
            $('a.del-photo').click(aDelClick);
            $('div.setMainPhoto').click(divSetMainClick);
        });
    }

    function aDelClick() {
        $('fieldset#photo-wrapper').css('opacity', 0.3);
        $.post($(this).attr('href'), {'photo': $(this).attr('data-photo-name')}, function(data) {
            updatePhotosList();
        });

        return false;
    }

    function divSetMainClick() {
        $('fieldset#photo-wrapper').css('opacity', 0.3);
        $.post($(this).attr('data-action-url'), {'photo': $(this).attr('data-photo-name')}, function(data) {
            updatePhotosList();
        });
    }

    $('a.del-photo').click(aDelClick);
    $('div.setMainPhoto').click(divSetMainClick);
</script>
