<?php if (!count($this->visits)): ?>
<p>It is't the selected dates for visits.</p>
<?php else: ?>
<table width="100%" border="1">
    <?php foreach($this->visits as $visit): ?>
        <tr>
            <td>Date: <?= $visit->availability ?></td>
            <td>Time: 
                <?php $time_list = $visit::getTimeList(); ?>
                <select name="at_time_<?= $visit->id ?>">
                <?php foreach($time_list as $value => $name): ?>
                    <?php if ($value == substr($visit->at_time, 0, 5)): ?>
                    <option value="<?= $value ?>" selected><?= $name ?></option>
                    <?php else: ?>
                    <option value="<?= $value ?>"><?= $name ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
                </select>
            </td>
            <td>Number of candidats:
                <?php $number_of_candidats_list = $visit::getNumberOfCandidats(); ?>
                <select name="visitors_<?= $visit->id ?>">
                <?php foreach($number_of_candidats_list as $value => $name): ?>
                    <?php if ($value == $visit->visitors): ?>
                    <option value="<?= $value ?>" selected><?= $name ?></option>
                    <?php else: ?>
                    <option value="<?= $value ?>"><?= $name ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
                </select>
            </td>
            <td><a href="#" class="update_visit_date" id="uVisitDate_<?= $visit->id ?>">[Seve]</a></td>
            <td><a href="#" class="remove_visit_date" id="rVisitDate_<?= $visit->id ?>">[Remove]</a></td>
        </tr>
    <?php endforeach; ?>
</table>
<?php endif; ?>

<?php if ($this->is_ajax): ?>
<script type="text/javascript">
    $(function() {
        $('.remove_visit_date').on('click', function(){
            var id = $(this).attr('id');
            $.ajax({
                type: 'POST',
                url: '/user/property/remove-visit-date/item/<?= $this->property->id ?>',
                data: {
                        id: id, 
                    },
                success: function(r) {
                    if (!r.error) {
                        $('#visits').empty().append(r.list);
                    }
                },
                dataType: 'json'
            });
            return false;
        });
    });
</script>
<?php else: ?>
<?php

    $function = "$(function() {
        $('.remove_visit_date').on('click', function(){
            var id = $(this).attr('id');

            $.ajax({
                type: 'POST',
                url: '/user/property/remove-visit-date/item/{$this->property->id}',
                data: {
                        id: id, 
                    },
                success: function(r) {
                    if (!r.error) {
                        $('#visits').empty().append(r.list);
                    }
                },
                dataType: 'json'
            });
            return false;
        });
    });";

    $this->jQuery()->addOnLoad($function); ?>
<?php endif; ?>
