<form id="processVisitDate">
            <div>
                <label for="phone">Phone:<br /> <input type="text" id="phone" name="phone" value="<?= htmlspecialchars($this->user->phone) ?>" /></label>
            </div>
            <div id="datepicker"></div>
            <hr />
                <table width="100%">
                    <tr>
                        <td width="33%">
                            <label for="availability">Date:<br />
                                <input type="text" id="availability" name="availability" value="" />
                            </label>
                        </td>
                        <td width="33%">
                            <label for="at_time">Time:<br />
                                <select id="at_time" name="at_time">
                                <?php foreach($this->time_list as $value => $name): ?>
                                    <option value="<?= $value ?>"><?= $name ?></option>
                                <?php endforeach; ?>
                                </select>
                            </label>
                        </td>
                        <td width="33%">
                            <label for="visitors">Number of candidats:<br />
                                <select id="visitors" name="visitors">
                                <?php foreach($this->number_of_candidats_list as $value => $name): ?>
                                    <option value="<?= $value ?>"><?= $this->translate($name) ?></option>
                                <?php endforeach; ?>
                                </select>
                            </label>
                        </td>
                    </tr>
                </table>
                <input type="submit" value="add" />
            </form>
            <hr />
            <div id="visits"><?= $this->visits ?></div>
            <hr />

            <?= $this->form ?>
