<?php

/**
 * Model_AdminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_AdminTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_AdminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Admin');
    }
}