<?php

/**
 * Model_Alert
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Alert extends Model_Base_Alert
{
const TYPE_INFO    = 'info';

    const TYPE_NOTICE = 'notice';
    const TYPE_SUCCESS = 'success';
    const TYPE_WARNING = 'warning';
    const TYPE_ERROR = 'error';

    static public function getTypes() 
    {
        return array(
            self::TYPE_INFO => 'Info Message',
            self::TYPE_NOTICE => 'Notice Message',
            self::TYPE_SUCCESS => 'Success Message',
            self::TYPE_WARNING => 'Warning Message',
            self::TYPE_ERROR => 'Error Message',
        );
    }
}