<?php

/**
 * Model_AlertTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_AlertTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_AlertTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Alert');
    }
    
    public function getAlertsByUserId($userId) 
    {
        return $this->createQuery('Alert')
                        ->andWhere('Alert.is_read != True')
                        ->andWhere('Alert.user_id = ?', array($userId))
                        ->orderBy('Alert.created_at DESC')
                        ->execute();
    }

    public function addAlert($alert_type, $user_id, $title, $body = '', $property_id = 0) {
        $user_id = intval($user_id);
        if ($user_id < 0) $user_id = 0;

        $property_id = intval($property_id);
        if ($property_id < 0) $property_id = 0;

        $alert              = $this->create();
        $alert->msg_type    = $alert_type;
        $alert->user_id     = $user_id;
        $alert->title       = trim($title);
        $alert->message     = trim($body);
        $alert->property_id = $property_id;

        $alert->save();
    }

    public function addAlertInfo($user_id, $title, $body = '', $property_id = 0) {
        $this->addAlert(Model_Alert::TYPE_INFO, $user_id, $title, $body, $property_id);
    }

    public function addAlertNotice($user_id, $title, $body = '', $property_id = 0) {
        $this->addAlert(Model_Alert::TYPE_NOTICE, $user_id, $title, $body, $property_id);
    }

    public function addAlertSuccess($user_id, $title, $body = '', $property_id = 0) {
        $this->addAlert(Model_Alert::TYPE_SUCCESS, $user_id, $title, $body, $property_id);
    }

    public function addAlertWarning($user_id, $title, $body = '', $property_id = 0) {
        $this->addAlert(Model_Alert::TYPE_WARNING, $user_id, $title, $body, $property_id);
    }

    public function addAlertError($user_id, $title, $body = '', $property_id = 0) {
        $this->addAlert(Model_Alert::TYPE_ERROR, $user_id, $title, $body, $property_id);
    }

}