<?php

/**
 * Model_FavoriteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_FavoriteTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_FavoriteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Favorite');
    }
    
    public function add($param){
	return true;
	$this->user_id = $param['user_id'];
	$this->property_id = $param['property_id'];
	return $this->save();

    }
}