<?php

/**
 * Model_FavoriteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_FavoriteTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_FavoriteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Favorite');
    }
    
    public function find($values = array())
    {   
        $query = $this->createQuery();
        foreach ($values as $key => $value) {
            $query->addWhere("{$key} = ?", $value);
        }
        $query->limit(1);
        return $query->fetchOne();
    }
}