<?php

/**
 * Model_MetroStationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_MetroStationTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_MetroStationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_MetroStation');
    }
}