<?php

/**
 * Model_MetroLineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_MetroLineTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_MetroLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_MetroLine');
    }
}