<?php

/**
 * Model_PageContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_PageContentTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_PageContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_PageContent');
    }
}