<?php

/**
 * Model_PropertyVisitDatesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_PropertyVisitDatesTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_PropertyVisitDatesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_PropertyVisitDates');
    }
}