<?php

/**
 * Model_PropertyXMetroStationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_PropertyXMetroStationTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_PropertyXMetroStationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_PropertyXMetroStation');
    }

}