<?php

/**
 * Model_PropertyApplicationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_PropertyApplicationTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_PropertyApplicationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_PropertyApplication');
    }

    protected function _queryWithDefaultJoins()
    {
        return $this->createQuery('PropertyApplication')
                    ->leftJoin("PropertyApplication.User User")
                    ->leftJoin("PropertyApplication.PropertyVisitDates PropertyVisitDates")
                    ->leftJoin("PropertyVisitDates.Property Property");
    }

    protected function _queryInitial()
    {
        return $this->_queryWithDefaultJoins()->andWhere('PropertyApplication.is_declined != True');
    }
    
    public function getListByOwnerId($ownerId)
    {
        return $this->_queryInitial()->andWhere('Property.owner_id = ?', $ownerId)
                                     ->orderBy('PropertyVisitDates.availability DESC')
                                     ->execute();
    }

    public function getOneByIdForPropOwner($applicationId, $propertyOwnerId)
    {
        return $this->_queryInitial()->andWhere('PropertyApplication.id = ?', $applicationId)
                                     ->andWhere('Property.owner_id = ?', $propertyOwnerId)
                                     ->fetchOne();
    }
}
