<?php

/**
 * Model_PropertyIssueSubjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_PropertyIssueSubjectTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_PropertyIssueSubjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_PropertyIssueSubject');
    }
}