<?php

/**
 * Model_PropertyVisitDates
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_PropertyVisitDates extends Model_Base_PropertyVisitDates
{
    public static function getTimeList()
    {
        return array(
            '08:00' => '08:00',
            '09:00' => '09:00',
            '10:00' => '10:00',
            '11:00' => '11:00',
            '12:00' => '12:00',
            '13:00' => '13:00',
            '14:00' => '14:00',
            '15:00' => '15:00',
            '16:00' => '16:00',
            '17:00' => '17:00',
            '18:00' => '18:00',
            '19:00' => '19:00',
            '20:00' => '20:00',
        );
    }

    public static function getNumberOfCandidats()
    {
        return array(
            0 => 'unlimited',
            1 => '1',
            2 => '2',
            3 => '3',
            4 => '4',
        );
    }
}