<?php

/**
 * Model_PropertyApplication
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_PropertyApplication extends Model_Base_PropertyApplication
{
    public function isAccepted()
    {
        return (bool) $this->is_accepted;
    }
    
    public function isDeclined()
    {
        return (bool) $this->is_declined;
    }
    
    public function isRead()
    {
        return (bool) $this->is_read;
    }
            
}