<?php

/**
 * Model_PropertyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_PropertyTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_PropertyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Property');
    }
}