<?php

/**
 * Model_Region
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Region extends Model_Base_Region
{
    public function getPath()
    {
        $value = $this->_get('path');
        if (!is_array($value)) {
            $value = json_decode($value, True);
            if ($value === False) {
                 throw new Zend_Exception("Error during decoding json field path with value {$this->_get('path')}, Error code: " . json_last_error());
            }
        }
        
        return $value;
    }
    
    public function setPath($value)
    {
        if (is_array($value)) {
            $value = json_encode($value);
            if ($value === False) {
                 throw new Zend_Exception('Error during encoding json field path: ' . json_last_error());
            }
        }
        
        return $this->_set('path', $value);
    }
}
