<?php

/**
 * Model_RegionBlockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_RegionBlockTable extends Model_RegionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_RegionBlockTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_RegionBlock');
    }
}