<?php

/**
 * Model_RegionDistrictTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_RegionDistrictTable extends Model_RegionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_RegionDistrictTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_RegionDistrict');
    }
}