<?php

/**
 * Model_RegionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_RegionTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_RegionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Region');
    }
}