<?php

/**
 * Model_RegionCityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_RegionCityTable extends Model_RegionTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_RegionCityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_RegionCity');
    }
}