<?php

/**
 * Model_SettingsOptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_SettingsOptionTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_SettingsOptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_SettingsOption');
    }
}