<?php

/**
 * Model_SubjectsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_SubjectsTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_SubjectsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Subjects');
    }
}