<?php

/**
 * Model_SubjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_SubjectTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_SubjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Subject');
    }
}