<?php

/**
 * Model_TransactionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_TransactionTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_TransactionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Transaction');
    }
}