<?php

/**
 * Model_UserResidentDocumentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_UserResidentDocumentTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_UserResidentDocumentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_UserResidentDocument');
    }

    public function removeAllUsersDocuments($userId)
    {
        $residentIds = array();
        $residents = Model_UserResidentTable::getInstance()->findByUserId($userId);
        foreach ($residents as $resident) {
            $residentIds[] = $resident->id;
        }
        $this->createQuery('doc')->delete()
                                 ->whereIn('doc.user_resident_id', $residentIds)
                                 ->execute();
    }
}
