<?php

/**
 * Model_UserPropertyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_UserPropertyTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_UserPropertyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_UserProperty');
    }
}