<?php

/**
 * Model_UserRequest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_UserRequest extends Model_Base_UserRequest
{
    static function getSpecialisationsList() {
        return array(
            '' => 'Selectionner une specialite',
            '1' => 'Plomberie',
        );
    }

    static function getRequestsTypeList($userType = 'resident') {
        if ($userType == 'owner') {
            return array(
                '1' => 'Dépanneur',
                '2' => 'Décorateur',
                '3' => 'Diagnostiqueur',
                '4' => 'Entrepreneur',
            );
        } else {
            return array(
                '1' => 'Dépanneur',
                '2' => 'Décorateur',
                /*'3' => 'Diagnostiqueur',*/
                '4' => 'Entrepreneur',
            );
        }
    }

}