<?php

/**
 * Model_UserResidentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_UserResidentTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_UserResidentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_UserResident');
    }
}