<?php

/**
 * Model_UserRequestTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_UserRequestTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_UserRequestTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_UserRequest');
    }
}