<?php

/**
 * Model_UserResidentGarantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_UserResidentGarantTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_UserResidentGarantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_UserResidentGarant');
    }
}