<?php

/**
 * Model_UserResidentGarant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_UserResidentGarant extends Model_Base_UserResidentGarant
{
    const FAMILY        = 'family';
    const FRIEND        = 'friend';
    const EMPLOYER      = 'employer';
    const BANK          = 'bank';
    const ORGANIZATION  = 'organization';
          
    static public function getTypes()
    {
        return array(
            'family'        => 'family',
            'friend'        => 'friend',
            'employer'      => 'employer',
            'bank'          => 'bank',
            'organization'  => 'organization'           
        );
    }
    
    public function getDocuments()
    {
        $table = Model_UserResidentDocumentTable::getInstance();
        return $table->createQuery()
                ->andWhere('user_resident_id = ?', $this->user_resident_id)
                ->andWhere('user_resident_garant_id = ?', $this->id)
                ->orderBy('id  DESC')
                ->execute();  
    }
}