<?php

/**
 * Model_UserResidentDocument
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_UserResidentDocument extends Model_Base_UserResidentDocument
{
    const TYPE_PASSPORT = 'passport';
    const TYPE_STUDENT_ID = 'student_id';
    const TYPE_INC_CERTIFICATE = 'inc_certificate';
    const TYPE_PAYSLIP = 'payslip';
    const TYPE_PAYCHECK1 = 'paycheck1';
    const TYPE_PAYCHECK2 = 'paycheck2';
    const TYPE_PAYCHECK3 = 'paycheck3';
    const TYPE_CONTRACT = 'contract';
    const TYPE_TAX_NOTICE = 'tax_notice';
    const TYPE_TAX_NOTICE_GUARANTEED = 'tax_notice_guaranteed';
    const TYPE_PAYSLIP_GUARANTEED = 'payslip_guaranteed';
    
    
    static public function getTypes()
    {
        $refl = new ReflectionClass('Model_UserResidentDocument');
        $result = array();
        
        foreach ($refl->getConstants() as $const => $val) {
            if (substr($const, 0, 5) == 'TYPE_') {
                $result[$const] = $val;
            }
        }
        return $result;
    }
}
