<?php

/**
 * Model_UserSettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_UserSettings extends Model_Base_UserSettings
{
    public static function getNotificationOptions()
    {
        return array(
            'visit_alerts' => array(
                'all'       => 'Acceptees et refusees',
                'accepted'  => 'Acceptees uniquement',
                'none'      => 'Aucune'                   
            ),
            'visit_alerts_period' => array(
                'immediately'   => 'Immediatement',
                'every_day'     => 'Chaque jour',
                'every_2_day'   => 'Tour les deux jours', 
                'never'         => 'Jamais'
            ),            
            'profile_alerts' => array(
                'immediately'   => 'Immediatement',
                'every_day'     => 'Chaque jour',
                'every_2_day'   => 'Tour les deux jours', 
                'never'         => 'Jamais'                
            ),
            'secondary_visit_alerts' => array(
                '5_hours'   => '5 heures avant',
                '1_day'     => '1 jour avant',
                '1_week'    => '1 semaine avant'
            ),
        );
    }
    
    public function getNotificationSettings()
    {
        $settings = unserialize($this->settings);
        if (!$settings) {
            $settings = array();
        }
        return $settings;
    }
}