<?php

/**
 * Model_Property_issueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Model_Property_issueTable extends Ext_Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Model_Property_issueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Model_Property_issue');
    }
}