<div class="grid">
	<div class="menu-annonce">
		<ul>
			<li><a href="" class="active">Description<i class="i-group-gray icon-list"></i></a></li>
			<li><a href="">Photos<i class="i-group-white icon-photo"></i></a></li>
			<li><a href="">Carte<i class="i-group-white icon-carte"></i></a></li>
			<li><a href="">Visites<i class="i-group-white icon-calendar"></i></a></li>
		</ul>
		<a href="#" class="btn btn-gray btn-gray-dark btn-left-flag">
			<i class="i-group-white icon-flag"></i>
		</a>
	</div>
	<div class="tab-annonce">
		<h2 class="black-txt">Description</h2>
		<div class="table-discription">
			<div class="cellsblock cellsblock-first">
				<div class="cellleft">
					<p>Localisation</p>
				</div>
				<div class="cellright">
					<p>75011 - Paris 11e</p>
				</div>
			</div>
			<div class="cellsblock">
				<div class="cellleft">
					<p>Loyer (charges comprises)</p>
				</div>
				<div class="cellright">
					<p>980 € </p>
				</div>
			</div>
			<div class="cellsblock">
				<div class="cellleft">
					<p>Charges</p>
				</div>
				<div class="cellright">
					<p>50 € </p>
				</div>
			</div>
			<div class="cellsblock">
				<div class="cellleft">
					<p>Durée du bail</p>
				</div>
				<div class="cellright">
					<p>Longue durée</p>
				</div>
			</div>
			<div class="cellsblock">
				<div class="cellleft">
					<p>Durée du bail</p>
				</div>
				<div class="cellright">
					<p>Longue durée</p>
				</div>
			</div>
			<div class="cellsblock">
				<div class="cellleft">
					<p>Durée du bail</p>
				</div>
				<div class="cellright">
					<p>Longue durée</p>
				</div>
			</div>
			<div class="cellsblock">
				<div class="cellleft">
					<p>Durée du bail</p>
				</div>
				<div class="cellright">
					<p>Longue durée</p>
				</div>
			</div>
			<div class="cellsblock">
				<div class="cellleft">
					<p>Durée du bail</p>
				</div>
				<div class="cellright">
					<p>Longue durée</p>
				</div>
			</div>
			<div class="cellsblock">
				<div class="cellleft">
					<p>Durée du bail</p>
				</div>
				<div class="cellright">
					<p>Longue durée</p>
				</div>
			</div>
			<div class="cellsblock">
				<div class="cellleft">
					<p>Durée du bail</p>
				</div>
				<div class="cellright">
					<p>Longue durée</p>
				</div>
			</div>
			<div class="cellsblock">
				<div class="cellleft">
					<p>Durée du bail</p>
				</div>
				<div class="cellright">
					<p>Longue durée</p>
				</div>
			</div>
			<div class="cellsblock">
				<div class="cellleft">
					<p>Durée du bail</p>
				</div>
				<div class="cellright">
					<p>Longue durée</p>
				</div>
			</div>
			<div class="cellsblock">
				<div class="cellleft">
					<p>Durée du bail</p>
				</div>
				<div class="cellright">
					<p>Longue durée</p>
				</div>
			</div>
			<div class="cellsblock">
				<div class="cellleft">
					<p>Durée du bail</p>
				</div>
				<div class="cellright">
					<p>Longue durée</p>
				</div>
			</div>
			<div class="cellsblock">
				<div class="cellleft">
					<p>Durée du bail</p>
				</div>
				<div class="cellright">
					<p>Longue durée</p>
				</div>
			</div>
			<div class="cellsblock">
				<div class="cellleft">
					<p>Durée du bail</p>
				</div>
				<div class="cellright">
					<p>Longue durée</p>
				</div>
			</div>


			<div class="cellsblock cellsblock-last">
				<div class="cellleft">
					<p>Durée du bail</p>
				</div>
				<div class="cellright">
					<p>Longue durée</p>
				</div>
			</div>
		</div>
		<div class="block-photo">
			<div class="photo-gallery">
				<div class="photo-img">
					<img src="/./assets/images/img-gallery.png">
				</div>
				<div class="control-btn">
					<a href="" class="btn-next"><i class="i-group-gray icon-chevron-left"></i></a>
					<span>Photo 1/3</span>
					<a href=""><i class="i-group-gray icon-chevron-right"></i></a>
				</div>
			</div>
			<div class="info-block-photo">
				<span class="blue">Cette annonce a été publiée par un professionnel.</span>
				<p>Honoraires (ttc) : 900 €</p>
						<span class="gray">Colocation non acceptee. Disponible immediatement.
						Bail longue duree.
						</span>
			</div>
			<div class="btn-nav-group">
				<a href="#" class="btn btn-red w220">
					<i class="i-group-white icon-heart"></i>
					Ajouter aux favoris
				</a>
				<a href="#" class="btn btn-blue w220">
					<i class="i-group-white icon-thumbs-up icon-partager"></i>
					Partager
				</a>
			</div>
		</div>
	</div>
</div>