<div class="grid" id="propertyTtabs">
	<div class="menu-annonce">
		<ul>
			<li><a href="#description">Description<i class="i-group-white icon-list"></i></a></li>
			<li><a href="#photos">Photos<i class="i-group-white icon-photo"></i></a></li>
			<li><a href="#map" class="active">Carte<i class="i-group-gray icon-carte"></i></a></li>
			<li><a href="#calendar">Visites<i class="i-group-white icon-calendar"></i></a></li>
		</ul>
		<a href="#" class="btn btn-gray btn-gray-dark btn-left-flag">
			<i class="i-group-white icon-flag"></i>
		</a>
	</div>
	<div class="tab-annonce" id="map">
		<h2 class="black-txt">Carte</h2>
		<div class="title-territory">
			<p class="blue">Avenu Ledru-Rollin, Paris 75011</p>
		</div>
		<div class="block-carte">
			<img src="/./assets/images/carte.png">
		</div>
		<div class="block-nav-carte block-text">
			<p>Le rond sur la carte correspond à la zone dans laquelle se trouve le bien à louer.</p>
			<p class="blue">
				L’adresse exacte vous sera fournie lorsque votre candidature sera acceptée.
			</p>
		</div>
		<div class="block-nav-carte block-link">
			<a href=""><i class="icon-link-carte"></i> Recentrer la carte</a>
		</div>
		<div class="block-nav-carte block-btn">
			<div class="btn-nav-group">
				<a href="#" class="btn btn-red icon-heart">
					Ajouter aux favoris
				</a>
				<a href="#" class="btn btn-blue icon-hand">
					Partager
				</a>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(function () {

		$('#propertyTtabs').tabs();
	});
</script>