<div class="grid">
	<div class="menu-annonce">
		<ul>
			<li><a href="">Description<i class="i-group-white icon-list"></i></a></li>
			<li><a href="" class="active">Photos<i class="i-group-gray icon-photo"></i></a></li>
			<li><a href="">Carte<i class="i-group-white icon-carte"></i></a></li>
			<li><a href="">Visites<i class="i-group-white icon-calendar"></i></a></li>
		</ul>
		<a href="#" class="btn btn-gray btn-gray-dark btn-left-flag">
			<i class="i-group-white icon-flag"></i>
		</a>
	</div>
	<div class="tab-annonce">
		<h2 class="black-txt">Photos</h2>
		<div class="table-photo">
			<a href="" class="nav-photo-left"><i class="icon-gal-prev"></i></a>
			<img src="/./assets/images/img-gallery-03.png">
			<a href="" class="nav-photo-right"><i class="icon-gal-next"></i></a>
		</div>
		<div class="block-photo">
			<div class="photo-gallery">
				<a href="" class="photo-mini"><img src="/./assets/images/img-gallery-04.png"></a>
				<a href="" class="photo-mini"><img src="/./assets/images/img-gallery-05.png"></a>
				<a href="" class="photo-mini"><img src="/./assets/images/img-gallery-06.png"></a>
				<a href="" class="photo-mini"><img src="/./assets/images/img-gallery-07.png"></a>
				<a href="" class="photo-mini"><img src="/./assets/images/img-gallery-08.png"></a>
				<a href="" class="photo-mini"><img src="/./assets/images/img-gallery-09.png"></a>
				<a href="" class="photo-mini"><img src="/./assets/images/img-gallery-10.png"></a>
				<a href="" class="photo-mini"><img src="/./assets/images/img-gallery-09.png"></a>
				<a href="" class="photo-mini"><img src="/./assets/images/img-gallery-08.png"></a>
				<a href="" class="photo-mini"><img src="/./assets/images/img-gallery-10.png"></a>
				<a href="" class="photo-mini"><img src="/./assets/images/img-gallery-05.png"></a>
				<a href="" class="photo-mini"><img src="/./assets/images/img-gallery-07.png"></a>
			</div>
			<div class="btn-nav-group">
				<a href="#" class="btn btn-red w220">
					<i class="i-group-white icon-heart"></i>
					Ajouter aux favoris
				</a>
				<a href="#" class="btn btn-blue w220">
					<i class="i-group-white icon-thumbs-up"></i>
					Partager
				</a>
			</div>
		</div>
	</div>
</div>