<div class="grid">
	<div class="menu-annonce">
		<ul>
			<li><a href="">Description<i class="i-group-white icon-list"></i></a></li>
			<li><a href="">Photos<i class="i-group-white icon-photo"></i></a></li>
			<li><a href="">Carte<i class="i-group-white icon-carte"></i></a></li>
			<li><a href="" class="active">Visites<i class="i-group-gray icon-calendar"></i></a></li>
		</ul>
		<a href="#" class="btn btn-gray btn-gray-dark btn-left-flag">
			<i class="i-group-white icon-flag"></i>
		</a>
	</div>
	<div class="tab-annonce">
		<h2 class="black-txt">Calendrier</h2>
		<p>
			<span class="gray"> Le propriétaire a défini des dates de visites
				pour ce bien (en bleu sur le calendrier).
			</span><br>
			En candidatant, vous serez invité à sélectionner une de ces dates.<br>
			<span class="blue"> Assurez-vous d’être disponible.</span>
		</p>
		<div class="block-calendar">
			<div class="calendar">
				<div class="name-month-calend">
					<h2>
						<a href="#" class="btn btn-gray btn-grayer-lite btn-cal-prev">
							<i class="i-group-gray icon-prev"></i>
						</a>
						Juillet
					</h2>
				</div>
				<div class="inner-cell cell-month">
					<div class="cell">Lun</div>
					<div class="cell">Mar</div>
					<div class="cell">Mer</div>
					<div class="cell">Jeu</div>
					<div class="cell">Ven</div>
					<div class="cell">Sa</div>
					<div class="cell">Dim</div>
				</div>
				<div class="inner-cell">
					<div class="cell cell-gray">1</div>
					<div class="cell cell-gray">2</div>
					<div class="cell cell-gray">3</div>
					<div class="cell cell-gray">4</div>
					<div class="cell cell-gray">5</div>
					<div class="cell cell-gray">6</div>
					<div class="cell cell-gray">7</div>
				</div>
				<div class="inner-cell">
					<div class="cell cell-gray">8</div>
					<div class="cell cell-gray">9</div>
					<div class="cell cell-gray">10</div>
					<div class="cell cell-gray">11</div>
					<div class="cell cell-black">12</div>
					<div class="cell">13</div>
					<div class="cell">14</div>
				</div>
				<div class="inner-cell">
					<div class="cell">15</div>
					<div class="cell">16</div>
					<div class="cell">17</div>
					<div class="cell">18</div>
					<div class="cell">19</div>
					<div class="cell">20</div>
					<div class="cell">21</div>
				</div>
				<div class="inner-cell">
					<div class="cell">22</div>
					<div class="cell cell-blue"><a href="#">23</a></div>
					<div class="cell cell-blue"><a href="#">24</a></div>
					<div class="cell">25</div>
					<div class="cell cell-blue"><a href="">26</a></div>
					<div class="cell">27</div>
					<div class="cell">28</div>
				</div>
				<div class="inner-cell cell-bottom">
					<div class="cell">29</div>
					<div class="cell">30</div>
					<div class="cell">31</div>
					<div class="cell cell-next-month">1</div>
					<div class="cell cell-next-month">2</div>
					<div class="cell cell-next-month">3</div>
					<div class="cell cell-next-month">4</div>
				</div>
			</div>
			<div class="calendar">
				<div class="name-month-calend">
					<h2>Août
						<a href="#" class="btn btn-gray btn-grayer-lite name-month-next">
							<i class="i-group-gray icon-next"></i>
						</a>
					</h2>
				</div>
				<div class="inner-cell cell-month">
					<div class="cell">Lun</div>
					<div class="cell">Mar</div>
					<div class="cell">Mer</div>
					<div class="cell">Jeu</div>
					<div class="cell">Ven</div>
					<div class="cell">Sa</div>
					<div class="cell">Dim</div>
				</div>
				<div class="inner-cell">
					<div class="cell cell-next-month">29</div>
					<div class="cell cell-next-month">30</div>
					<div class="cell cell-next-month">31</div>
					<div class="cell">1</div>
					<div class="cell">2</div>
					<div class="cell">3</div>
					<div class="cell">4</div>
				</div>
				<div class="inner-cell">
					<div class="cell">5</div>
					<div class="cell">3</div>
					<div class="cell">7</div>
					<div class="cell">8</div>
					<div class="cell">9</div>
					<div class="cell">10</div>
					<div class="cell">11</div>
				</div>
				<div class="inner-cell">
					<div class="cell">12</div>
					<div class="cell">13</div>
					<div class="cell">14</div>
					<div class="cell">15</div>
					<div class="cell">16</div>
					<div class="cell">17</div>
					<div class="cell">18</div>
				</div>
				<div class="inner-cell">
					<div class="cell">19</div>
					<div class="cell">20</div>
					<div class="cell">21</div>
					<div class="cell">22</div>
					<div class="cell">23</div>
					<div class="cell">24</div>
					<div class="cell">25</div>
				</div>
				<div class="inner-cell cell-bottom">
					<div class="cell">26</div>
					<div class="cell">27</div>
					<div class="cell">28</div>
					<div class="cell">29</div>
					<div class="cell">30</div>
					<div class="cell">31</div>
					<div class="cell cell-next-month">1</div>
				</div>
			</div>
		</div>
		<h2 class="black-txt">Visites</h2>
		<div class="block-btn-visites">
			<a href="#" class="btn btn-blue-lite blue-dark w220">Mardi 23 juillet 2013</a>
			<a href="#" class="btn btn-blue-lite blue-dark w220">Mercredi 24 juillet 2013</a>
			<a href="#" class="btn btn-blue-lite blue-dark w220">Vendredi 26 juillet 2013</a>
		</div>
		<div class="block-photo">
			<div class="btn-nav-group">
				<a href="#" class="btn btn-red icon-heart">
					Ajouter aux favoris
				</a>
				<a href="#" class="btn btn-blue icon-hand">
					Partager
				</a>
			</div>
		</div>
	</div>
</div>